### ISSUE TITLE
I want to do a payment with paramenters and confirm the payment

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#10]
## User Story
As Chris, I want to do a payment with paramenters and confirm the payment so that the payment cannot be done automatically.

**Comment by christianbrb** [comment]
@kelsos Is this included in #62 ?

**Comment by kelsos** [comment]
@christianbrb not yet, I started working on this yesterday but it will be included

**Comment by christianbrb** [comment]
Closing this as it is going to be included in #339
