### ISSUE TITLE
Can't open a channel 

### ISSUE THREAD

**Issue by Prajjwal-Arya** [raiden-network/light-client#1024]
## User Story
Can't open a channel as everytime i try to deposit TTT it shows " Your maximum usable amount is 0.0 TTT"

**Comment by kelsos** [comment]
Hey @Prajjwal-Arya did you mint also some tokens for the TTT token network?

**Comment by Prajjwal-Arya** [comment]
Yes, i have already mint some tokens and i have tried refreshing but still it was showing the same thing.

**Comment by taleldayekh** [comment]
@Prajjwal-Arya if you write to the mint function for this contract you will get the correct TTT tokens: https://goerli.etherscan.io/token/0x59105441977ecD9d805A4f5b060E34676F50F806#writeContract

**Comment by kelsos** [comment]
We updated the TTT token address that was wrong in the instructions #1041 

If you go to the previous screen when you selected the token does it show the minted amount?

**Comment by Prajjwal-Arya** [comment]
No, it still shows 0.0 .

**Comment by kelsos** [comment]
@Prajjwal-Arya that is weird at least after minting you should be able to see the amount there. any screenshots or more information you could provide?

**Comment by andrevmatos** [comment]
@Prajjwal-Arya we did a ton of minting & channel opening this week, and couldn't reproduce your issue. There's also some optimizations to minting and channel opening. Please, test current version, and reopen if your issue persists. Thanks for the interest and reporting.
