### ISSUE TITLE
Add context-aware information screens for various parts of the dApp main flow

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#1047]
## User Story
As Chris, I would like to click an information icon to get a brief explanation of the screen I'm currently at in the dApp.

## Acceptance criteria
Each screen in the main flow of the dApp should provide access to a brief summary of what the user is expected to do and the context of the action for that specific part of the flow. 

## Tasks
- [ ] Decide on design for the info button and for the context-aware information screen.
- [ ] Write copy for each information screen
- [ ] Consider illustrations

**Comment by christianbrb** [comment]
Duplicate of #698
