### ISSUE TITLE
Error validating migrated state version=0 

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1056]
I tried to launch the dapp with a state that's not versioned yet and the Raiden initialization fails. Not sure if that's an issue we have to take care of but reporting it nonetheless. Probably not relevant because new states will be created including the version, so removing olds states should work as a fix)

## Steps to Reproduce
1. Copy app state below
2. Go to https://lightclient.raiden.network
3. Replace state

## Expected Result
- State gets migrated so that it can be parsed (probably can't be validated because version is missing?)
- User can continue to use the dapp

## Actual Result
![Screenshot 2020-02-20 at 07 58 10](https://user-images.githubusercontent.com/3169205/74908656-c277b600-53b6-11ea-9105-c9cef0d43821.png)

## Additional Infos (Optional) 
```json 
raiden_goerli_0x9b0c8C8C75904CEf5B7a8dbF59c3459Ea85c6526_0x385dB1Ed9509FF184ff9E34a06b2D93daFdBAc0b:"{
  "address": "0x385dB1Ed9509FF184ff9E34a06b2D93daFdBAc0b",
  "chainId": 5,
  "registry": "0x9b0c8C8C75904CEf5B7a8dbF59c3459Ea85c6526",
  "blockNumber": 2129541,
  "config": {
    "pfsSafetyMargin": 1.1
  },
  "channels": {

  },
  "tokens": {

  },
  "transport": {
    "matrix": {
      "server": "https://transport04.raiden.network",
      "setup": {
        "userId": "@0x385db1ed9509ff184ff9e34a06b2d93dafdbac0b:transport04.raiden.network",
        "accessToken": "MDAyOGxvY2F0aW9uIHRyYW5zcG9ydDA0LnJhaWRlbi5uZXR3b3JrCjAwMTNpZGVudGlmaWVyIGtleQowMDEwY2lkIGdlbiA9IDEKMDA1OWNpZCB1c2VyX2lkID0gQDB4Mzg1ZGIxZWQ5NTA5ZmYxODRmZjllMzRhMDZiMmQ5M2RhZmRiYWMwYjp0cmFuc3BvcnQwNC5yYWlkZW4ubmV0d29yawowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IDprdzhCNlBiRTsjQ2VXI3YKMDAyZnNpZ25hdHVyZSDvo4L94YiKcCvgKw7OK1_0e0OmvvPajhP1XoOEFwpqJQo",
        "deviceId": "OLZHCMQKXZ",
        "displayName": "0xdfa161f090a566221f03641d52b7dd466078e3044d3ad9d7a52255a7c560aca958938bb3c040b489f81487efead4f9d1a7d3077f75a8ebcc6db83562dbacb1a31b"
      }
    }
  },
  "secrets": {

  },
  "sent": {

  },
  "path": {
    "iou": {

    }
  }
}"
```

**Comment by nephix** [comment]
@andrevmatos said it's due to the missing `pendingTxs` prop which was added before the migration got introduced. So the state above is "quite outdated"

**Comment by andrevmatos** [comment]
This specific state didn't contain the latest breaking change prior to the state migrations/upgrade. At the time, we didn't care, but now, every breaking change in state should be accompanied of a migration function. I'd say this issue should be closed, as we din't care yet, but if you wanna fix it locally by "migrating" it manually, just add a `"pendingTxs: []` prop to the state and try to connect ot the account in dApp again =)
