### ISSUE TITLE
Blurred dApp parts when opening a modal

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1057]
Currently, the blurred modal backdrop is inconsistently implemented across the dApp, mainly due absolute positioning it in the first parent with `position: relative;`

It should be discussed how to iron this out

## Steps to Reproduce
1. Go to https://lightclient.raiden.network
2. Connect
3. Click on "Deposit"
4. Check other modals as well, e.g. Minting dialog

## Expected Result
- Backdrop looks consistent

## Actual Result
![Screenshot 2020-02-20 at 08 02 28](https://user-images.githubusercontent.com/3169205/74909664-15eb0380-53b9-11ea-872d-a72e6ae9ddea.png)
<img width="1758" alt="Screenshot 2020-02-19 at 17 43 05" src="https://user-images.githubusercontent.com/3169205/74909682-1d121180-53b9-11ea-9755-44b7cc5901a6.png">

**Comment by kelsos** [comment]
@nephix what I got from our discussion with @taleldayekh is that we want the blur to cover the card area.

**Comment by nephix** [comment]
Decision from planning meeting: Cover the whole screen, as it's the simplest solution

**Comment by taleldayekh** [comment]
> Decision from planning meeting: Cover the whole screen, as it's the simplest solution

Genau
