### ISSUE TITLE
I want to have the support to mint the selected token, if I am on the "Select Hub" screen 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1071]
## User Story
As Chris I want to have the support to mint the selected token, if I am on the "Select Hub" screen so that I don't have to use etherscan for that.

**Comment by kelsos** [comment]
The mint function is already implemented on the SDK but we have to keep in mind that this works only for the `CustomToken` contract we deploy or for tokens with similar ABIs. This means that there is a chance that minting will fail if you deploy a different contract that does not conform to the same ABI. We should display an error message in this case.
