### ISSUE TITLE
Deploy only releases to ghpages

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1072]
## Description
Deploy only releases to ghhpages to avoid deploying changes, which might break the hosted dApp.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
I can take this over since I more familiar with the infrustracture part.

**Comment by nephix** [comment]
We could also just work in a `develop` branch and only merge to master if we're confident that nothing broke. Should be fairly easy once we have the integration tests in #348 and would not require that many (if any?) CI changes

**Comment by andrevmatos** [comment]
Done as part of the v0.4.0 release #1117
