### ISSUE TITLE
Some UI improvements in the mobile view

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1078]
## Description
There might be some UI improvements required in the mobile view. Attaching some screens from the workflow of opening channels.

![light_client_test25thfeb](https://user-images.githubusercontent.com/15123108/75240118-d1f96380-57e9-11ea-9802-96b3b5275455.png)

![light_client_direct_transfer_screen](https://user-images.githubusercontent.com/15123108/75240199-fb19f400-57e9-11ea-871b-1e8d246bfdda.png)

![light_client_direct_transfer_screen1](https://user-images.githubusercontent.com/15123108/75240213-010fd500-57ea-11ea-95ed-9048a0014041.png)

![light_client_transferring_tokens_screen](https://user-images.githubusercontent.com/15123108/75240266-138a0e80-57ea-11ea-88fb-c59844719b3d.png)

One doubt about the notification panel, is it a button and should it open some view

![light_client_pending_transfers](https://user-images.githubusercontent.com/15123108/75240404-4a602480-57ea-11ea-9f47-9c6b8f2b0669.png)

## Acceptance criteria
-  UI text errors might need to be corrected to be good user experience

## Tasks
Not really clear about the tasks hence havent mentioned them. Could be mentioned as they are identified.
- [ ]

**Comment by kelsos** [comment]
@agatsoh thanks for identifying some of the issues. Can you keep updating this issue with anything you find? We haven't been paying much attention to how the light client dApp appears on mobile but I think it is about time. Having a clear picture of what is needed would be really nice :)

**Comment by agatsoh** [comment]
@kelsos Yes I will keep updating this issue. I am also trying to install metamask and get it to work in a real mobile so I will try and update that as well.

**Comment by agatsoh** [comment]
![Screenshot_20200226-190413_MetaMask](https://user-images.githubusercontent.com/15123108/75549219-248a8800-5a55-11ea-9816-d04a5ec26718.jpg)

![Screenshot_20200226-190442_MetaMask](https://user-images.githubusercontent.com/15123108/75549236-2f451d00-5a55-11ea-813b-6feccb6505b1.jpg)

![Screenshot_20200226-190451_MetaMask](https://user-images.githubusercontent.com/15123108/75549257-3c620c00-5a55-11ea-96de-61fd032db9c8.jpg)
