### ISSUE TITLE
Balance not shown right on Transfer screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1082]
## Steps to Reproduce
1. Go to the transfer screen, if you are already connected to a hub
2. Check the token balance (<0.000001)

    ![grafik](https://user-images.githubusercontent.com/35398162/75354273-02ee9c80-58ad-11ea-841b-ccd729ba7072.png)
3. Navigate back to the transfer screen

## Expected Result
- I don't exactly remember how this has been implemented before
- It was ~0.0 or <0.0 and on hover over the exact amount has been shown (maybe look for a later commit how this has been done)

## Actual Result
- 0.0 is shown
- 0.0 is shown on hover over

    ![grafik](https://user-images.githubusercontent.com/35398162/75354582-7d1f2100-58ad-11ea-8721-f827561015d1.png)

## Additional Infos (Optional) 
- Firefox

**Comment by nephix** [comment]
I think the amount **<0.000001** is what you have in your wallet, while the **0.0 TTT** amount is the balance of your largest open channel.

**Comment by christianbrb** [comment]
Right, thanks :) This is a bug which occurred because of #1065 

Closing the issue
