### ISSUE TITLE
Channel is in a "stuck" state 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1084]
## Steps to Reproduce
1. Select a token
2. Go to the "Select Hub" screen
3. Add a new address
4. Click on "Select Hub"
5. Enter an amount to deposit
6. Click on "Open Channel"
7. Confirm one transaction in MetaMask to open a channel
8. Close the modal window or close the browser

## Expected Result
- I don't really know

## Actual Result
- Channel is in a "stuck" state (see screenshot)
- I cannot do anything with it

    ![grafik](https://user-images.githubusercontent.com/35398162/75356857-c886fe80-58b0-11ea-84fa-479dad6d1754.png)

## Additional Infos (Optional) 
- Firefox

**Comment by andrevmatos** [comment]
Logs? This state is expected, `Opening` happens while the transaction is being mined/confirmed, you should see it transition to `Open` state in a few seconds/minutes, if not, i need all logs from this session to try to understand what went wrong

**Comment by christianbrb** [comment]
I don't have the complete logs. I will try to reproduce it.

Trying to open a new channel to the same address leads to

![grafik](https://user-images.githubusercontent.com/35398162/75357800-3ed83080-58b2-11ea-8e01-220d2bb137ac.png)

MetaMask - RPC Error: gas required exceeds allowance (8000000) or always failing transaction 
Object { code: -32000, message: "gas required exceeds allowance (8000000) or always failing transaction" }

**Comment by christianbrb** [comment]
Now the channel is gone

![grafik](https://user-images.githubusercontent.com/35398162/75357979-7cd55480-58b2-11ea-80a9-605b96b00afc.png)

**Comment by andrevmatos** [comment]
Without logs (for channel opening, channel going away, etc), I can't tell what's happening. We should put in the bug template the requirement for logs to be copied and pasted here, it's just opening DevTools and copying everything in the Console there.

**Comment by christianbrb** [comment]
It's not reproducible. It must have been a timing issue closing the modal and reloading the dApp (which also clears the log) at a specific point in time.

If it helps, it must have been one of those transactions:
https://goerli.etherscan.io/tx/0x201df1316a61913a4430c8f434984f93c71e31253026e1b8446e7343edef186e
https://goerli.etherscan.io/tx/0xefc094f16c16fb97bf8cba4a4596a453c5ced3f66d018adbb9ec9f943a391e0e
https://goerli.etherscan.io/tx/0x179ef1339052cf0c334e5de9e74121d6ed98f7fc69e70a7cb467b5ca8bebbc06

Account:
https://goerli.etherscan.io/address/0xb808877b5ec745183bd60ce8c89aba83011d56f6

**Comment by nephix** [comment]
**Off-topic**

> We should put in the bug template the requirement for logs to be copied and pasted here, it's just opening DevTools and copying everything in the Console there.

We should find a way to keep logs in memory and show the user a "Report a bug" button. When clicked, it redirects to a URL like:

https://github.com/raiden-network/light-client/issues/new?assignees=&labels=&template=bug.md&body=BUGREPORT

With **BUGREPORT** being the log output and application state etc already pre filled in

**Comment by andrevmatos** [comment]
> It's not reproducible. It must have been a timing issue closing the modal and reloading the dApp (which also clears the log) at a specific point in time.

@christianbrb did it eventually show up? The events must not be missed and if the tx was mined (independently of reload, being offline when it got confirmed, whatever), the channel must show up in the `open` state.

**Comment by andrevmatos** [comment]
The first tx you posted is the channelOpen. Then `approve` & `setTotalDeposit`, all of them succeded, so the event should have come through and set the channel as open there, if not we need the logs to understand why it happened.

**Comment by christianbrb** [comment]
As we didn't store the logs at that point in time, I am closing the issue :)
