### ISSUE TITLE
I want to learn how to use the dApp if I open it for the first time

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#109]
## User Story
As Chris I want to learn how to use the dApp if I open it for the first time so that I can directly start using it without looking at a user guide.

## Remarks
- See [MyCrypto as an example](https://www.cryptoteardowns.com/mycrypto) 

CC @franzihei

**Comment by taleldayekh** [comment]
This has been address with the introduced [info overlays](https://github.com/raiden-network/light-client/issues/698). Closing.
