### ISSUE TITLE
dApp gets exceptions when a PFS error occurs

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#1116]
## Steps to Reproduce

1. in a fresh account, without SVT nor UDC deposit
2. try to make a mediated transfer, it'll ask you to deposit to UDC to pay for PFS
3. mint & deposit to UDC
4. right after the dialog completes, before 5 blocks have passed, you'll see the updated UDC balance, then proceed to request the route
5. light-client will have seen the transaction as mined, and doesn't wait for it to be confirmed, balance is updated; but PFS only considers it as valid after confirmationBlocks have passed, so will reject with that specific error I got, which will trigger the issue in the dApp

## Expected Result
- Error dialog is shown
- No unhandled exception in console
- Error dialog can be closed
- the user can go back and continue using the dapp

## Actual Result
- Error dialog is shown
- Unhandled exception in console
- dialgo gets stuck, user can't close it

![Screenshot_20200228_120141](https://user-images.githubusercontent.com/587021/75559609-854c9d00-5a22-11ea-97b0-2c95c0beef30.png)

Error in console:
```
{type: "path/find/failure", payload: RaidenError: Pathfinding Service request returned an error
    at _callee4$ (webpack-internal:///f4…, meta: {…}, error: true}
type: "path/find/failure"
payload: RaidenError: Pathfinding Service request returned an error at _callee4$ (webpack-internal:///f455:11995:27) at tryCatch (webpack-internal:///98b8:47:17) at Generator.invoke [as _invoke] (webpack-internal:///98b8:266:22) at Generator.prototype.<computed> [as next] (webpack-internal:///98b8:100:21) at Observable.eval [as _subscribe] (webpack-internal:///7b88:35:33) at Observable._trySubscribe (webpack-internal:///87af:105:25) at Observable.subscribe (webpack-internal:///87af:91:22) at subscribeToResult (webpack-internal:///6b36:17:23) at MergeMapSubscriber._innerSub (webpack-internal:///446c:83:122) at MergeMapSubscriber._tryNext (webpack-internal:///446c:77:14)
code: (...)
details: {errorCode: 2107, errors: "Not enough deposit in UserDeposit contract."}
name: "RaidenError"
_code: "PFS_ERROR_RESPONSE"
stack: "RaidenError: Pathfinding Service request returned an error↵    at _callee4$ (webpack-internal:///f455:11995:27)↵    at tryCatch (webpack-internal:///98b8:47:17)↵    at Generator.invoke [as _invoke] (webpack-internal:///98b8:266:22)↵    at Generator.prototype.<computed> [as next] (webpack-internal:///98b8:100:21)↵    at Observable.eval [as _subscribe] (webpack-internal:///7b88:35:33)↵    at Observable._trySubscribe (webpack-internal:///87af:105:25)↵    at Observable.subscribe (webpack-internal:///87af:91:22)↵    at subscribeToResult (webpack-internal:///6b36:17:23)↵    at MergeMapSubscriber._innerSub (webpack-internal:///446c:83:122)↵    at MergeMapSubscriber._tryNext (webpack-internal:///446c:77:14)"
message: "Pathfinding Service request returned an error"
__proto__: Wrapper
meta: {tokenNetwork: "0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df", target: "0x8550dA53D944906159FA385d8a28E07A74583BE4", value: BigNumber}
error: true

TypeError: Cannot read property 'toHexString' of undefined
    at new BigNumber (bignumber.js?5384:89)
    at Object.bigNumberify (bignumber.js?5384:182)
    at formatUnits (units.js?945a:99)
    at Function.toUnits (balance-utils.ts?d9e2:9)
    at Function.displayFormat (filters.ts?976b:34)
    at VueComponent.get (TransferSteps.vue?5430:293)
    at Watcher.get (vue.runtime.esm.js?2b0e:4479)
    at Watcher.evaluate (vue.runtime.esm.js?2b0e:4584)
    at VueComponent.computedGetter [as callToActionText] (vue.runtime.esm.js?2b0e:4836)
    at VueComponent.TransferStepsvue_type_template_id_a77fd7ec_scoped_true_render (TransferSteps.vue?3233:17)
```

**Comment by nephix** [comment]
![gif](https://user-images.githubusercontent.com/3169205/75574626-f14cf680-5a5e-11ea-896d-c8b1fd5e00b5.gif)

Works for me, can you please provide exact steps?

Also

> No unhandled exception in console

if by your definition of error handling impossible

**Comment by andrevmatos** [comment]
Just triggering an normal exception is not enough, read the traceback, it seems it tried in `TransferSteps.vue` to call some `displayFormat` on some property which was `undefined` on the specific error/data I got, so triggering another error won't necessarily trigger it.
Reproducing steps goes as:
- in a fresh account, without SVT nor UDC deposit
- try to make a mediated transfer, it'll ask you to deposit to UDC to pay for PFS
- mint & deposit to UDC
- right after the dialog completes, before 5 blocks have passed, you'll see the updated UDC balance, then proceed to request the route
- light-client will have seen the transaction as mined, and doesn't wait for it to be confirmed, balance is updated; but PFS only considers it as valid after confirmationBlocks have passed, so will reject with that specific error I got, which will trigger the issue in the dApp

**Comment by andrevmatos** [comment]
From the traceback, it seems it was this call which failed. 
It means this was called even over the error condition, and one of these two values were `undefined`:
https://github.com/raiden-network/light-client/blob/2cc6e33ac19b8711b9ae123036700bb8f0144db3/raiden-dapp/src/views/TransferSteps.vue#L293-L296

**Comment by nephix** [comment]
> Just triggering an normal exception is not enough

That's why I asked you for exact steps, I have updated your OP

**Comment by andrevmatos** [comment]
Yes, dApp don't and shouldn't wait explicitly for confirmation blocks, this is handled by SDK, but so far we've implemented it only for transactions which trigger specific actions, like `channelOpen`. A couple of SDK methods, like `depositToUDC`, don't touch the state machine, and are handled directly by the `Raiden` class, and for these (without actions) we didn't yet implement confirmation blocks, but should on these cases.
I'll work on fixing this, and sure, this should get also their respective notifications as per #357 
Thanks

**Comment by andrevmatos** [comment]
I'll create a fix for the confirmation blocks waiting on these other methods, which will cause this specific error to not be triggered by this specific reason, but errors could happen later even for some unknown reason, this issue is about the dApp handling it correctly even if it happens.
