### ISSUE TITLE
Make the last input field in every form handle pressing enter

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1160]
## Description

During the workshop, some attendees attempted to press enter to continue on the last input in each form.  Currently, this does absolutely nothing, but maybe we should consider handling enter as a special case that proceeds to the next screen (similar to pressing the button). 

## Acceptance criteria
- As Chris I do want to be able to just type an eg. .5 instead of a 0.5 so that I am faster entering the payment amount (from #300)

## Tasks
- [ ]

**Comment by nephix** [comment]
We should think of using actual forms and handling `onSubmit()` (or the vue equivalent ;))
