### ISSUE TITLE
Resolving an ens address the first time might not properly validate

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1161]
## Description

While trying to resolve a top-level ens domain `raidenhub.eth` on Goerli, the first time the address was resolved the input would enter in an invalid mode that would disable input. This should not happen.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
This may have to do with this change:
https://github.com/raiden-network/light-client/pull/1140/files#diff-cf3b8f641876dc6e42228a33dbadbf1eR6
It was a quick fix for that issue, but `v-model` may conflict with property reactivity, and the race on the validation, but we need to test which approach works better there.

**Comment by kelsos** [comment]
I have seen it only happen the first time to be honest. After that, it seems to work fine.
