### ISSUE TITLE
I want to top up a channel with an amount, which has been transferred as parameters

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#12]
## User Story
As Chris, I want to top up a channel with an amount, which have been transferred as parameters so that I can make new payments.

**Comment by kelsos** [comment]
@christianbrb I am not sure about the scope of this. If it is only for new channels it works. For existing channels, this won't work though.

The expected query parameter name is `deposit`:

https://github.com/raiden-network/light-client/blob/ceaf844700fe60e9d5505bd404cf84a22cd9e131/raiden-dapp/src/views/OpenChannel.vue#L170

**Comment by kelsos** [comment]
@christianbrb Ok I saw that what I described above was another issue, so I suggest we keep this issue open.

**Comment by christianbrb** [comment]
Closing as we need to check, if it is a valid use case in future
