### ISSUE TITLE
Introduce integration tests for all the supported functionality of the SDK

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1217]
## Description
As part of #348 we need to cover all the basic functionality of the SDK with integration tests

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Currently we are adding Cypress GUI tests to the integration image.

As we are also starting to run the scenarios nightly (see #1977) I am closing the issue until we think it is necessary again.
