### ISSUE TITLE
e2e image improvements

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1218]
## Description
This is for further improvements to the integration image especially to add support for upcoming features. The target of the issue is to keep track of what is needed to be done. We can create separate issues for each one of them when the need arises. The issue serves as a base to keep track of everything.
 
- Introduce Monitoring Service
- ~~Introduce `Coturn`~~
- Make node configuration genearation dynamic
- Replace hardcoded keys with dynamic build time key generation

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Monitoring service testing is going to be covered within the scenarios.

@weilbith Could you check if these are the improvements you are also talking about?

**Comment by weilbith** [comment]
I think there is general room for improvements. The build of the image feels incredibly huge and cumbresome. I feel like parts can be improved. Eventually we need to discuss if we need certain flexibilities in favor of a more simple setup. E.g. do we need the ability to get any commit of the Python client and always build it ourself with all dependencies etc or are we fine to just choose from their public releases and download the final binary?
Also the deployment of the test blockchain can be eventually heavily improved. Talking with Paul about this.

@kelsos what is your intention with introducing TURN? I must admit I only heard it, but have barely an idea how it works. What is the goal you want to reach or what do we can improve by using it?

**Comment by kelsos** [comment]
@weilbith At some point, we were discussing introducing tests for WebRTC based transfers, and this would help in this case. If this is not the case anymore please feel free to remove that.  

Btw the reason we initially went with building from commit, was because the public releases we could use where outdated. If I remember correctly during that period we also didn't have any nightly binaries we could use either. Also, following the master branch would introduce new breaking changes, or incompatibilities on protocol or service and it would interrupt work. 

Since we where already using a random commit for our test environment this approach made sense back then. If you think that there is no possibility of such scenario happening any more I don't any reason to not simplify the approach.

I also agree that the approach is rather complicated and cumbersome, initially I wanted to use docker compose and re-use parts of the setup, for example for the services and transport but I remember running into a lot problems.

**Comment by weilbith** [comment]
> @weilbith At some point, we were discussing introducing tests for WebRTC based transfers, and this would help in this case. If this is not the case anymore please feel free to remove that.

I'll ask Andre. Was just asking since I don't know much about it. Thanks for elaborating!

> Btw the reason we initially went with building from commit, was because the public releases we could use where outdated. If I remember correctly during that period we also didn't have any nightly binaries we could use either. Also, following the master branch would introduce new breaking changes, or incompatibilities on protocol or service and it would interrupt work.

As I said: we should analyze what the current state is, how has it evolved and do we still need it. I don't want to destroy things. Just as someone reading it the first time and asking questions. If there are good answers I'm fine. :smiley: 
PS: I never wanted to follow `master`. But always settle on a specific released version of the Python client. I barely see a good reason to work on an "intermediate" state they never published. :shrug: 

> I also agree that the approach is rather complicated and cumbersome, initially I wanted to use docker compose and re-use parts of the setup, for example for the services and transport but I remember running into a lot problems.

I'm so thankful of all your work. I wasn't aware of what is all done already. Having found your work provides already a great setup that is working and that we can build on top of. Thanks. :pray:

**Comment by kelsos** [comment]
If I can provide insight on anything let me know :)

**Comment by taleldayekh** [comment]
Closing, we have a working e2e image and there is not immediate need to improve on it.
