### ISSUE TITLE
Αdd eslint's no-else-return to dApp and SDK

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1220]
## Description

Based on the following comment:
https://github.com/raiden-network/light-client/pull/1210#discussion_r396956215

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@weilbith Is this issue still valid or has the change been already applied?

**Comment by weilbith** [comment]
This rule is still not set. So we would need to do it still. Having both, Kelsos and Thomas not here anymore, I would like to discuss this rule again. Should be a quick argumentation. Because I would be against it.

**Comment by christianbrb** [comment]
@weilbith Thanks for your feedback :)

@taleldayekh @andrevmatos Please reopen the issue if you would like to enforce it.
