### ISSUE TITLE
I want to upload the state

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1222]
## User Story
As Chris I want to upload the state so that I can use a state I have saved.

## Acceptance criteria
- On the same screen where I download the state
- It needs to be checked if the state is from the same Raiden account

**Comment by christianbrb** [comment]
@andrevmatos to write down the requirements

**Comment by andrevmatos** [comment]
Some of the things to consider when implementing this:
- Upload state is to be done for a **specific** account, although before it is started
- If there's a mismatch between that specific selected account and the state being uploaded, `Raiden.create` will reject with an error
- Account used can be set in different places, so we need to keep that in mind:
  - Metamask account selection (outside dApp)
  - Main vs Subkey selection (inside dApp, before Connect)
- The dApp **can not** be started to check address or anything before uploading the state, this needs to be done on the same operation to ensure the state won't get outdated
- So far, `General` screen contains details of the account being used, which would require it to be started, which would make it hard/impossible to include the State Upload functionality inside

My main proposal would be simply to let the user select a file to be uploaded before clicking on Connect Main or Subkey, and let it fail if they select the wrong account or wrong state file, showing the relevant error in this case. At least this way we ensure an atomic operation on it.

**Comment by taleldayekh** [comment]
Great, thanks @andrevmatos .

**Comment by taleldayekh** [comment]
## Proposal 1
Replaces our _*splash screen*_ with the dApp window.
- The user is **not** connected
  * Display the Raiden logo and disclaimer text
  * Display *Connect* button
  * Display dialog with option to connect using *Web3 Provider* or *Dedicated Raiden Account* when the user clicks the *Connect* button
  * Display a *person*-icon instead of identicon on upper right side (this icon gets replaced with the identicon once user is connected).
  * Display *General* screen when *person*-icon is clicked
    * General menu does *not* display accounts details (since the user is not yet connected)
    * General menu displays menu items that are actionable for a non-connected user (like uploading state)
![wireframes__splash_screen](https://user-images.githubusercontent.com/43838780/77528328-09f9d200-6e8e-11ea-81a7-e0ae66b988b2.jpg)

**Comment by kelsos** [comment]
My only comment is that we would have to educate the users on how they can restore the state somehow. If I didn't know the flow and it would not be obvious to me that I can go there and restore the state. But otherwise, it looks really nice :)

**Comment by taleldayekh** [comment]
## Proposal 2
Replaces or *splash screen* with the dApp *general screen modal*.
* The user is **not** connected
  * Display the *general screen modal* replacing the *General* heading with *Raiden dApp* and the identicon with the Raiden logo
  * Display *Connect* button
  * Display dialog with option to connect using *Web3 Provider* or *Dedicated Raiden Account* when the user clicks the *Connect* button
  * Display menu items that are actionable for a non-connected user (like uploading state)

![wireframes__splash_screen_2](https://user-images.githubusercontent.com/43838780/77542811-0cb4f100-6ea7-11ea-9c29-08d6f1679111.jpg)

**Comment by taleldayekh** [comment]
> My only comment is that we would have to educate the users on how they can restore the state somehow. If I didn't know the flow and it would not be obvious to me that I can go there and restore the state. But otherwise, it looks really nice :)

I agree. The way I see it is that uploading the state is not necessarily the default action a user would do when connecting to the dApp. For uploading/downloading state they are probably already familiar with what the state does.

My idea is to have an informative text describing the state in the *Backup state* menu. In this way, a user will get informed about the state and its purpose when exploring the dApp and encountering this menu.
<img width="669" alt="state-description" src="https://user-images.githubusercontent.com/43838780/77545998-89e26500-6eab-11ea-9ed7-fd868f04ed6f.png">

**Comment by christianbrb** [comment]
@taleldayekh Looks good, like this we could make a release :)

**Comment by taleldayekh** [comment]
Mockup

![splash-screen-mockup](https://user-images.githubusercontent.com/43838780/77738570-5f5dec80-7010-11ea-9605-c5b108137321.jpg)

**Comment by nephix** [comment]
Looks good, I like it

**Comment by kelsos** [comment]
@nephix maybe connected show the identicon instead of the human icon?

**Comment by nephix** [comment]
@kelsos yeah identicon + green border indicates online and human icon + gray border could indicate offline or something like that

**Comment by taleldayekh** [comment]
> @kelsos yeah identicon + green border indicates online and human icon + gray border could indicate offline or something like that

Yes, sounds good, let's do it like that.
