### ISSUE TITLE
Transfer screen inputs are full width on mobile

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1243]
## Steps to Reproduce
1. Serve dapp
2. Connect

## Expected Result
- On mobile, the address and amount inputs are `col-10-sm` wide

## Actual Result
- The inputs are full width

**Comment by kelsos** [comment]
Checking through the Vuetify grid and issue tracker the lowest size is `xs` which is less than 600px wide. `sm` is more than 600px so it doen's not cover mobile devices. Usually, the mobile viewports are translated to somewhere between 320-420px width. That would make them `xs`.

It seems though that for Vuetify 2.x `cols` actually equals `xs` so by setting `cols="12"` this made the fields full length.
