### ISSUE TITLE
Pull request change log reminder

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1248]
## User Story

As a dev I want to get reminded when I forget do add a change log entry to my pull request

## Acceptance criteria

* If there're SDK changes, remind to add CHANGELOG in raiden-ts
* If there're dApp changes, remind to add CHANGELOG in raiden-dapp
* Should not be enforced
* Maybe just a comment

**Comment by kelsos** [comment]
There is this simple bot -> https://github.com/pverkhovskyi/changelog-reminder but looking at the code making our own would not be that hard
