### ISSUE TITLE
Upgrade test environment and integration tests to work with latest commit before v0.37

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1254]
## Description
Upgrade
- [x] Update integration test image
- [x] Contracts (upgrade the submodule) - Revert
- [x] Update the hardcoded contract version in the SDK - Revert
- [ ] Test RSB (Raiden Service Bundle - PFS/MS/Matrix)
- [ ] Test Raiden Hub (through tower)
- [ ] Documentation of the process
- [x] Update documentation (eg. https://lightclient.raiden.network/docs/connecting/#raiden-light-client-test-environment)

## Acceptance criteria
- dApp is working with the test environment
- The integration test is working
- Other devs than Kelsos are able to execute it the next time

**Comment by kelsos** [comment]
A contract deployment is not required since we use the same deployment as the python client.

For the hub we need to update the `testenv001` tag on docker to the v0.200.0-rc3 commit.
Then redeploying should be easy. 

For the integration image we need to:
- Update Raiden (this will also help to deploy the newer version of raiden-contracts)
- Update PFS
- Check if synapse needs update (?)

**Comment by christianbrb** [comment]
The documentation also needs to be updated, at least https://lightclient.raiden.network/docs/connecting/#raiden-light-client-test-environment (Raiden version)

**Comment by nephix** [comment]
I made some adjustments in the hub (updated the TTT token address) which are already on https://hub.raiden.network. Whenever I ran the deployment in tower though, the same 4 week old raiden python image seems to be get started. Instead, the updated one from [yesterday](https://hub.docker.com/layers/raidennetwork/raiden/testenv001/images/sha256-d21bb2d004fff45501953b76a355065a9f418e395c35f2a8b82c79af93192090?context=explore) should be used. 

My attempts to stop and remove the related docker containers and images didn't succeed. I thought that removing them and doing a `docker pull raiden-network/raiden:testenv001` would fix the issue. 

Via `docker ps` I can also see that the python client keeps restarting over and over again.

Seems more like a DevOps problem to me

**Comment by christianbrb** [comment]
As the newest contracts are going to be deprecated, we should the latest version which support the contracts v0.36
- [ ] Commit for Raiden @andrevmatos 
- [ ] Commit for RSB @andrevmatos

**Comment by andrevmatos** [comment]
- Contracts version: `v0.36.2` (commit [e1b5e5b8a4d060998be504b19c5748c0994494c5](https://github.com/raiden-network/raiden-contracts/commit/e1b5e5b8a4d060998be504b19c5748c0994494c5), same deployment/addresses as of `v0.36.0`, but the one pinned to raiden before 0.37 bump, so we should go with it)
- Raiden version: `ea7025739b460f940c26616ca1fccdb739b218ed` (commit right before 0.37 bump)
- Services version: [100fecf0d8c21ee68d8afbea912b67167ec7aad3](https://github.com/raiden-network/raiden-services/commit/100fecf0d8c21ee68d8afbea912b67167ec7aad3) - this is the commit before bump to rc3/0.37, but please, give it a run on integration image, to make sure it'll play along

**Comment by nephix** [comment]
The contract versions in the light client have been changed in #1303 

Pointing the `testenv001` to the correct commit and downgrading the services is still in progress by @eorituz

**Comment by nephix** [comment]
Integration test image part of this ticket has been moved to #1307

**Comment by eorituz** [comment]
Updated the Docker image `raidennetwork/raiden:testenv001` as well as the raiden service bundle to be compliant with the versions Andre determined three comments above.
The Raiden Hub is also updated.

**Comment by nephix** [comment]
I have tested direct and mediated transfers with the latest `testenv001` tag and it mostly worked.
I wasn't able to mediate through the hub and created https://github.com/raiden-network/raiden-hub/issues/11 with the steps

The integration test image part of this ticket is here: https://github.com/raiden-network/light-client/issues/1307
And the documentation part here: https://github.com/raiden-network/light-client/issues/1316
