### ISSUE TITLE
I want to add a custom payment identifier to my transfer

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1255]
## User Story
As Chris, I want to add a custom payment identifier to my transfer so that the target can identify the payment.

## Acceptance criteria
- 

## Tasks

**Comment by kelsos** [comment]
I would argue that I would prefer to avoid adding a rarely used field to the UI.

Rather I would think it better to have it available as a query parameter in the URL.
e.g. 
```
http://localhost:8080/transfer/0x59105441977ecD9d805A4f5b060E34676F50F806?target=0x1F916ab5cf1B30B22f24Ebf435f53Ee665344Acf&amount=0.01&identifier=12345
```
This way the identifier is added to the URL and is passed through the payment. In this case, the page or environment requiring the identifier could just generate the URL containing the identifier.

Then the only thing the user needs to do it to click the link and get directed to the page.
