### ISSUE TITLE
Test walkthrough

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1268]
## Description
Test walkthrough and creating issues for technical debt in tests

## Acceptance criteria
- Test walkthrough has taken place by all devs (individually)
- Create issues for the most obvious test debt (where we have got already knowledge)
- At the end all devs are aligned (dedicated call)
- Research how to improve tests

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Feedback from @taleldayekh @nephix needed for **One fixture to rule 'em all** #1377

**Comment by andrevmatos** [comment]
The was done.
Feedback on #1377 , and possibly new suggestion on new issue
