### ISSUE TITLE
General dialog misaligned on larger screens

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#1296]
## Steps to Reproduce
Click to open the general dialog on a large resolution monitor.

## Expected Result
The general dialog to cover all of the underlying dApp window.

## Actual Result
A small misalignment at the bottom of the general dialog, resulting in a small section of the underlying dApp window showing.

## Additional Infos (Optional) 
![Screenshot 2020-04-06 at 09 56 57](https://user-images.githubusercontent.com/43838780/78536092-8d4fe780-77ed-11ea-9635-97bc99d9ede4.png)

**Comment by christianbrb** [comment]
Done @taleldayekh fixed it
