### ISSUE TITLE
Make the Raiden account the default account when connecting to the dApp

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1302]
## User Story
As Chris I want to understand how the Raiden account works before using it the first time so that I can trust the dApp.

## Acceptance criteria
- Toggle between Raiden account and Main Account on the General screen / Account screen
- The default account is the Raiden Account
- The toggle screen for the Main account details why someone would want to toggle on the Main account (as settings screen on the Raiden Account screen)
- User needs to know why they are not seeing their MetaMask account when connecting

## User flow
A: Using the Raiden account
1. User clicks on connect
2. If he hasn't used a Raiden account before (for this URL and net), "Generate Account and key" with a brief explanation + referral to the settings screen for the main account
3. If he has used a Raiden account before no pop-up

B: Using the Main account
1. User clicks on the Identicon
2. User clicks on Settings
3. Brief explanation of main and raiden account
a. Main Account -> "You need to sign up to 7 messages manually for each transfer."
b. Raiden Account -> "Messages are signed automatically. You need to move back the tokens to your main account when leaving a token network."
4. User toggles to Main Account
5. Main Account as default is getting stored locally
6. User goes back to the connect screen
7. User clicks on connect
8. No pop-up

**Comment by christianbrb** [comment]
Split from #1108

**Comment by christianbrb** [comment]
The user needs to know:
- He needs the Raiden Account address to receive transfers
- It is much more convenient (no pop-ups)
- The user needs to transfer tokens and ETH back manually to the main account

It should get explained here:
![grafik](https://user-images.githubusercontent.com/35398162/80218948-25e5c480-8642-11ea-8383-4fab8478a727.png)

**Comment by taleldayekh** [comment]
In accordance with the user flow outlined in the issue description.

![wireframe_main_account_toggle](https://user-images.githubusercontent.com/43838780/81060946-bf7b6480-8ed3-11ea-90c2-3b44d7d4d466.jpg)

**Comment by taleldayekh** [comment]
Mockups for the updated connect button:
https://xd.adobe.com/view/28299435-4e57-487f-4745-55d76b62b496-5e18/

Mockups for the settings menu:
https://xd.adobe.com/view/4fb866db-3093-41e1-5887-4d97d8bc4526-3989/

**Comment by christianbrb** [comment]
@taleldayekh Looks great thanks :)

instead of 
![grafik](https://user-images.githubusercontent.com/35398162/81081682-843c5e00-8ef2-11ea-8999-3b785fd0402c.png)
we should write `You can use your web3 account directly ...`

Maybe `Settings` upon `Report bugs`

**Comment by taleldayekh** [comment]
Good point @christianbrb, we'll put settings on the top. I'll change the wording as well.

**Comment by taleldayekh** [comment]
Mockup links have been updated.

**Comment by nephix** [comment]
What should happened if the user is already connected (e.g. via subkey) and then toggles to main account from the settings screen?

1. Nothing, setting will apply once the user connects next time to the raiden network
2. Dialog that tells the user that he will get disconnected and can reconnect then with the selected account
3. No dialog, just disconnect immediately after toggling and go back to home screen where user can press connect again

**Comment by taleldayekh** [comment]
Would it make sense to only display the toggle setting when a user is disconnected?

**Comment by nephix** [comment]
I thought about that, but then there would be an empty settings menu item..
We could hide it completely until there are more settings that should be displayed even while connected maybe?

**Comment by kelsos** [comment]
Out of the 3 suggestions above the one that seems more reasonable to me is the 2nd one.

**Comment by taleldayekh** [comment]
I would say we hide it completely until we have more settings. Why would you want to change the account once already connected?

**Comment by nephix** [comment]
Ok I'm just going to hide it then, it's also the simplest solution..
