### ISSUE TITLE
dApp doesn't go back to "connect" screen upon shutdown

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#1305]
## Steps to Reproduce
1. Trigger some unexpected error (e.g. by changing slightly the transport's `acess_token` on state when app is not connected)

## Expected Result
- `raidenShutdown` action goes through, and dApp shows "Connect" screen

## Actual Result
- dApp stays at "Transfer" screen, with all controls enabled, even though it can't be used anymore because SDK did shutdown by unexpected error

## Additional Infos (Optional) 
```
0.5.2
```
Probably related to #1168 or some other change related to making the general screen the landing page/connect screen of dApp

**Comment by christianbrb** [comment]
In the done column within the project, but not closed. Closing
