### ISSUE TITLE
Refreshing dApp from another screen (e.g. home aka transfer screen) doesn't go back to Connect

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#1306]
## Steps to Reproduce
1. After successfully connecting the dApp, you're directed to the e.g. Transfer screen (if you already have channels on chain), e.g. `/transfer/<token>` url
2. Refresh dApp

## Expected Result
- With dApp reloading, you should be redirected to baseUrl/root, to re-connect

## Actual Result
- You continue on the Transfer screen you just refreshed, but now with a bunch of "Error: Raiden instance was not initialized" errors on console due to trying to access this screen without initializing/connecting the SDK

## Additional Infos (Optional) 
```
0.5.2
```

Also probably due to the General screen becoming landing/connect screen.

**Comment by christianbrb** [comment]
In the done column within the project, but not closed. Closing
