### ISSUE TITLE
Integration image fails after setting contracts to 0.36.2

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1307]
## Steps to Reproduce
```
$ cd light-client/integration
$ docker build -t lightclient-integration .
```

## Expected Result
Image builds successfully

## Actual Result

> Deploying contracts 0.36.2 on behalf of 0x69a1768aAc612ca1EC6C5220F60C461A972A8aeA
> Traceback (most recent call last):
>   File "/usr/local/bin/deploy_contracts.py", line 161, in <module>
>     main()
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/bin/deploy_contracts.py", line 71, in main
>     contracts_version=contract_version,
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 49, in __init__
>     super(ContractDeployer, self).__init__(web3=web3, contracts_version=contracts_version)
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/deploy/contract_verifier.py", line 33, in __init__
>     self.contract_manager = ContractManager(self.precompiled_path)
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/contract_manager.py", line 62, in __init__
>     with path.open() as precompiled_file:
>   File "/usr/local/lib/python3.7/pathlib.py", line 1203, in open
>     opener=self._opener)
>   File "/usr/local/lib/python3.7/pathlib.py", line 1058, in _opener
>     return self._accessor.open(self, flags, mode)
> FileNotFoundError: [Errno 2] No such file or directory: '/opt/raiden/lib/python3.7/site-packages/raiden_contracts/data_0.36.2/contracts.json'
> chmod: cannot access '/etc/profile.d/smartcontracts.sh': No such file or directory
> INFO [04-08|07:38:49.427] Got interrupt, shutting down...
> INFO [04-08|07:38:49.428] HTTP endpoint closed                     url=http://127.0.0.1:8545
> INFO [04-08|07:38:49.430] IPC endpoint closed                      url=/opt/chain/geth.ipc
> INFO [04-08|07:38:49.430] Blockchain manager stopped
> INFO [04-08|07:38:49.431] Stopping Ethereum protocol
> INFO [04-08|07:38:49.432] Ethereum protocol stopped
> INFO [04-08|07:38:49.433] Transaction pool stopped
> cp: cannot stat '/opt/raiden/lib/python3.7/site-packages/raiden_contracts/data_0.36.2/deployment_private_net.json': No such file or directory
> The command '/bin/sh -c download_geth.sh && deploy.sh     && cp -R /opt/raiden/lib/python3.7/site-packages/raiden_contracts/data_${CONTRACTS_VERSION}/deployment_private_net.json /opt/deployment/     && cp -R /opt/raiden/lib/python3.7/site-packages/raiden_contracts/data_${CONTRACTS_VERSION}/deployment_services_private_net.json /opt/deployment/' returned a non-zero code: 1

**Comment by nephix** [comment]
Changing `CONTRACTS_VERSION=0.36.0` instead of `0.36.2` did not help:

> Deploying contracts 0.36.0 on behalf of 0x71561F07Be956Bffcf8b3780163502C237C75ccb
> Deploying Raiden contracts
> Traceback (most recent call last):
>   File "/usr/local/bin/deploy_contracts.py", line 161, in <module>
>     main()
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 764, in __call__
>     return self.main(*args, **kwargs)
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 717, in main
>     rv = self.invoke(ctx)
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 956, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/opt/raiden/lib/python3.7/site-packages/click/core.py", line 555, in invoke
>     return callback(*args, **kwargs)
>   File "/usr/local/bin/deploy_contracts.py", line 79, in main
>     reuse_secret_registry_from_deploy_file=None
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 180, in deploy_raiden_contracts
>     deployed_contracts=deployed_contracts,
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 202, in _deploy_and_remember
>     receipt = self.deploy(contract_name, arguments)
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/deploy/contract_deployer.py", line 90, in deploy
>     receipt, tx = check_successful_tx(web3=self.web3, txid=txhash, timeout=self.wait)
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/utils/transaction.py", line 15, in check_successful_tx
>     receipt = wait_for_transaction_receipt(web3=web3, txid=txid, timeout=timeout)
>   File "/opt/raiden/lib/python3.7/site-packages/raiden_contracts/utils/transaction.py", line 38, in wait_for_transaction_receipt
>     receipt = web3.eth.getTransactionReceipt(txid)
>   File "/opt/raiden/lib/python3.7/site-packages/web3/eth.py", line 343, in getTransactionReceipt
>     raise TransactionNotFound(f"Transaction with hash: {transaction_hash} not found.")
> web3.exceptions.TransactionNotFound: Transaction with hash: b'*\xd0\x92\x11Y\x9f\x7f\x9b\x94\xd1\xfcU\x1f[\x85\xc8{r\xf6\x94\x0f\xd5*\xb7\x9dE\x19\xb5\xbdt\xf4\xbe' not found.
> chmod: cannot access '/etc/profile.d/smartcontracts.sh': No such file or directory
> INFO [04-08|10:33:30.814] Got interrupt, shutting down...
> INFO [04-08|10:33:30.815] HTTP endpoint closed                     url=http://127.0.0.1:8545
> INFO [04-08|10:33:30.816] IPC endpoint closed                      url=/opt/chain/geth.ipc
> INFO [04-08|10:33:30.817] Blockchain manager stopped
> INFO [04-08|10:33:30.817] Stopping Ethereum protocol
> INFO [04-08|10:33:30.818] Ethereum protocol stopped
> INFO [04-08|10:33:30.818] Transaction pool stopped
> cp: cannot stat '/opt/raiden/lib/python3.7/site-packages/raiden_contracts/data_0.36.0/deployment_private_net.json': No such file or directory
> The command '/bin/sh -c download_geth.sh && deploy.sh     && cp -R /opt/raiden/lib/python3.7/site-packages/raiden_contracts/data_${CONTRACTS_VERSION}/deployment_private_net.json /opt/deployment/     && cp -R /opt/raiden/lib/python3.7/site-packages/raiden_contracts/data_${CONTRACTS_VERSION}/deployment_services_private_net.json /opt/deployment/' returned a non-zero code: 1

**Comment by andrevmatos** [comment]
The first error was because 0.36.2 uses the same deploymend as 0.36.0, so the former folder doesn't exist. The second one **may** be related to docker caching; please try `docker build` with `--force-rm --no-cache` options and check if the error persists

**Comment by nephix** [comment]
@andrevmatos feel free to take the issue

**Comment by kelsos** [comment]
`--no-cache` should help if the intermediate steps fail at some point
