### ISSUE TITLE
Downloading app state should not be possible while disconnected

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1310]
## Steps to Reproduce
1. Go to https://lightclient.raiden.network/
2. Click on identicon
3. Click on Back up state
4. Click on Download State

## Expected Result
Nothing happens, it should be disabled because there is no web3 provider
Maybe a hint/tooltip why downloading state is disabled

## Actual Result
Warning modal, which after confirm downloads a state file that contains `undefined`

**Comment by christianbrb** [comment]
Disable download button, if not connected

**Comment by taleldayekh** [comment]
I just want to add a reminder to also edit the description on the screen for downloading/uploading the state while working on this issue.
