### ISSUE TITLE
General screen icons not displayed

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1311]
## Steps to Reproduce

1. Go to https://lightclient.raiden.network/
2. Click on identicon

## Expected Result
Menu icons are displayed

## Actual Result
<img width="648" alt="Screenshot 2020-04-08 at 13 49 58" src="https://user-images.githubusercontent.com/3169205/78781042-dc3d7e80-799f-11ea-80ca-55ed3c6c09e6.png">

## Additional Infos (Optional) 
- Browser: Firefox

**Comment by christianbrb** [comment]
Compare the icons which are shown and the icons which are not shown. What's the difference?
