### ISSUE TITLE
Introduce TURN server in integration image for WebRTC tests

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1331]
## Description

The recommended matrix TURN server is `coturn`, and it provide full TURN capabilities, not only STUN (TURN is a superset of STUN which also supports relaying). [Here](https://github.com/matrix-org/synapse/blob/master/docs/turn-howto.md) is official guide for deployment, and when available, is always preferred over the fallback one.
The fallback also isn't hardcoded, it just defaults to Google's public server, but is exposed through the `fallbackIceServers` config option, therefore changeable through `create`'s config param or `Raiden.updateConfig` method, if one needs to change it to something else for the tests.

_Originally posted by @andrevmatos in https://github.com/raiden-network/light-client/issues/1211#issuecomment-613458262_

**Comment by christianbrb** [comment]
@andrevmatos Could we just use Matrix as TURN server and remove Google?

**Comment by kelsos** [comment]
@christianbrb if I recall correctly the plan at some point was to include the `coturn` thing in the RSB and use that instead.

**Comment by andrevmatos** [comment]
@christianbrb As Kelsos mentioned, this would require the servers to have `coturn` deployed together with the `synapse` server. It's not hard and there're guides available, just need to be done, but is not critical either. We could then remove Google's, but no communication go through it, it's just a facilitator of the p2p connection, not much different than a DNS server (and most people don't mind using Ǵoogle's or Cloudflare's for that).
The fallback TURN server is configurable though, and it's safe for clients to use any of the several public available ones, even if it's different from potential partners.

**Comment by taleldayekh** [comment]
Closing since we will most likely move away from Matrix.
