### ISSUE TITLE
Explain state to the user

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1334]
## User Story

Follow up for https://github.com/raiden-network/light-client/issues/1310#issuecomment-611430574

As Chris I want to know what the "state" is, what it means to me and my tokens and how I can back it up

## Acceptance criteria
- It is on the Backup state screen
- Smaller than the current text
- White
- Simple description in the dApp
- Link to a longer description in the Readme

**Comment by christianbrb** [comment]
Some description about what the purpose of downloading the state is and why the user only can/cannot download/upload the state at a certain point
