### ISSUE TITLE
I want to transfer ETH between Main and Raiden accounts

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1365]
## User Story
As Chris I want to transfer ETH between Main and Raiden accounts so that I can pay the gas to transfer tokens

## Acceptance criteria
- It's on the general screen 
- One button to send ETH to the Raiden Account
- One button to withdraw ETH from the Raiden Account
- Possibility to enter an amount in a modal window

**Comment by christianbrb** [comment]
Proposal https://github.com/raiden-network/light-client/issues/1380#issuecomment-617758328

**Comment by andrevmatos** [comment]
With default subkey config, to transfer ETH from main account to subkey:
```ts
await raiden.transferOnchainBalance(raiden.address, '0.001');
```
To transfer entire ETH balance from subkey to main account (with #1392):
```ts
await raiden.transferOnchainBalance(raiden.mainAddress, undefined, { subkey: true });
```
When user wants to transfer everything, one can also pass result from `getBalance` to `value` parameter directly, and it'll be capped at transferable value (balance minus transfer cost), or leave `undefined`, as this is a special case when SDK needs to calculate gas price & cost, but it's handled internally by above PR.

**Comment by nephix** [comment]
Quick and simple proposal: 
<img width="633" alt="Screenshot 2020-04-23 at 09 38 02" src="https://user-images.githubusercontent.com/3169205/80072189-2ef16b80-8546-11ea-9d12-d57e70ad06f0.png">

**Comment by taleldayekh** [comment]
![swap](https://user-images.githubusercontent.com/43838780/80072429-8394e680-8546-11ea-996c-bd4d22fb2154.png)

**Comment by nephix** [comment]
And the screen would be reached by a separate menu item in the general view?

<img width="532" alt="Screenshot 2020-04-23 at 09 48 43" src="https://user-images.githubusercontent.com/3169205/80073187-a5429d80-8547-11ea-950d-da8dc3da3d95.png">

**Comment by taleldayekh** [comment]
Exactly! I already illustrated the icon for it yesterday @nephix :)
