### ISSUE TITLE
I want to set a monitoring reward calculated based on my channel capacity

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1369]
## User Story
As Chris I want to set a monitoring reward calculated based on my channel capacity so that paying the monitoring service will be economically viable.

Split from #1352 

## Acceptance criteria
Decide on either (or both):
- Have a fixed reward, send only monitoring requests when the received amount of tokens are valued more than the amount being paid.
- Set a max threshold, set monitoring requests with smaller values, and hope a monitoring service will pick it up (you will never pay to much).
- Value proportion between a token and a monitoring token.

**Comment by christianbrb** [comment]
@karlb How do you calculate the `reward_amount` the Raiden Node is submitting via the [Monitor Request](https://raiden-network-specification.readthedocs.io/en/latest/monitoring_service.html#monitor-request)?

**Comment by karlb** [comment]
> @karlb How do you calculate the `reward_amount` the Raiden Node is submitting via the [Monitor Request](https://raiden-network-specification.readthedocs.io/en/latest/monitoring_service.html#monitor-request)?

Currently, the python client uses
```
MONITORING_REWARD = TokenAmount(5 * 10 ** 18)  # about 1$
```

There is no way to negotiate sensible rewards at the moment. So the current approach is "set it to a reasonably high value and trust that at least one MS will act". This is definitively something to be improved in the future. Limiting the reward to the user's channel balance makes sense, but will require conversion rates between RDN and the token used in the channel.

**Comment by christianbrb** [comment]
@karlb Thanks for the information :)

**Comment by christianbrb** [comment]
@andrevmatos @kelsos @nephix 
Whoever starts to implement this. Let me know, when you are starting to have a discussion about the solution. I would like to keep the complexity and effort of this issue as low as possible.

**Comment by christianbrb** [comment]
Configuration parameter
- Multiplier = Token / SVT ~ Exchange rate
