### ISSUE TITLE
I want to deposit service tokens into the UDC while connecting to the hub

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1371]
## User Story
As Chris, I want to deposit service tokens into the UDC while connecting to the hub so that I am able to pay for the monitoring.

3 from https://github.com/raiden-network/light-client/issues/1352#issuecomment-615241579

## Acceptance criteria
- Integrate the depositing process during the open channel part.
- Inform user that they don't have enough tokens to monitor a channel and let them decide how to proceed accordingly.
- The user is warned, that he is not able to receive tokens without the deposit.
- If the deposit is not high enough the "Select Button" is still enabled -> it is just a warning

## User flow
1. Click on connect new token
2. Select token
3. Enter a hub address
3a. Check, if the SVT balance deposited in the UDC is high enough (compare SVT tokens deposited in the UDC with MonitoringReward set in the config)
3b. If the SVT balance deposited in the UDC is not high enough show a message
4. Click on "Select Hub"
5. Enter a deposit amount
6. Click on "Open Channel"

## MonitoringReward

- `raiden.config.monitoringReward: BigNumber | null = null`
- `raiden.updateConfig({ monitoringReward: parseUnits('5', 18) })`

## Sketch

Replace Pathfinding Service with Monitoring service in the text.

![grafik](https://user-images.githubusercontent.com/35398162/81170589-40516380-8f9b-11ea-8f7e-e68320774a9f.png)

## Tasks
- [x] Figure out how to integrate it into the channel open process.

**Comment by christianbrb** [comment]
Added the current user flow to the issue description.

Assumptions:
- We want the users to use the dApp to receive tokens (default)
- We want the users to use the monitoring service to safeguard their tokens
- The user needs a certain amount of tokens per channel (+amount needed to pay the PFS)

@nephix Could you attach a video/GIF how the user flow for the service token aquisition for the PFS looks like?

**Comment by nephix** [comment]
Can be seen here: https://drive.google.com/file/d/1ZLgbTgHDUumSx97N_-9IpGqWrDWCCPjl/view

**Comment by christianbrb** [comment]
@nephix Cool, thanks :)

**Comment by christianbrb** [comment]
@andrevmatos Is the monitoring reward exposed through the API?

https://github.com/raiden-network/light-client/blob/1a315a634f8b1280897182bdab7a8ae0166e0567/raiden-ts/tests/unit/epics/monitor.spec.ts#L62

**Comment by andrevmatos** [comment]
- `raiden.config.monitoringReward: BigNumber`
- `raiden.updateConfig({ monitoringReward: parseUnits('5', 18) })`

**Comment by christianbrb** [comment]
Whoever implements this: As we have got mint and deposit in one dialog for the PFS I assume that it is easier to implement this issue together with https://github.com/raiden-network/light-client/issues/1372. Let me know, if it is ok for you.

**Comment by nephix** [comment]
I'll do this together w/ #1372

**Comment by christianbrb** [comment]
Great, thanks for the comment :)

**Comment by nephix** [comment]
> * `raiden.config.monitoringReward: BigNumber | null = null`
> * `raiden.updateConfig({ monitoringReward: parseUnits('5', 18) })`

@andrevmatos `raiden.updateConfig({ monitoringReward: parseUnits('5', 18) })` does not work

> Type 'BigNumber' is not assignable to type 'Branded<BigNumber, UIntB<32>>'.
>   Property '[_brand]' is missing in type 'BigNumber' but required in type 'Brand<UIntB<32>>'.

**Comment by andrevmatos** [comment]
`monitoringReward` now defaults to `5SVT`, no need to set it. This looks like a type only issue, doesn't happen at runtime, it'll be decoded/validated in method. You could @ts-ignore it or cast the result of parseUnits to any or to the branded type.
