### ISSUE TITLE
I want to see if a monitoring service has submitted my balance proof

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1374]
## User Story
As Chris I want to see if a monitoring service has submitted my balance proof so that I know, that a monitoring service has acted on my behalf.

Split from #1352 

- If possible show how much the user has paid the monitoring service to submit the balance proof. If not, split into a separate story.

## Tasks
- SDK monitors monitoring service contract and fire events if some channel of us got updated by a MS
- Display if balance proof has been submitted as a first notification in the notification panel #168 .

**Comment by christianbrb** [comment]
For the SDK part. There are events in the contract. We need to monitor them.

**Comment by andrevmatos** [comment]
@taleldayekh SDK part was done in above PR. dApp part is still missing, but as you're the writer of the notification area, maybe it'd be easier for you to look at the event and see how that event would fit with your pattern?
