### ISSUE TITLE
I want to transfer tokens back to the main account

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1380]
## User Story
As Chris I want to transfer tokens back to the main account so that I can use them in eg. MetaMask.

After discussion of https://github.com/raiden-network/light-client/issues/1301 and https://github.com/raiden-network/light-client/issues/1314

## Acceptance criteria
- I only have got the option to withdraw all tokens

## First Discussion
@taleldayekh @nephix and @christianbrb 

### User flow:
1. Channel is getting closed by the partner
2. Channel is getting settled by the partner
3. Tokens out of channel are transferred from channel to the Raiden account (subkey)
4. Transfer ETH to Raiden Account to pay for gas -> signed in MetaMask (#1365) 
5. Transfer tokens from Raiden Account to Main (ETH) Account -> signed in dApp (background)

### Proposed solution:
- Having a button on the general screen for "token balances"
- List of tokens are shown and each token balance can be withdrawn
- Tell the user before settling, that the token balance can be withdrawn on the Account Screen (new naming for General screen)

### Wireframe

![wireframes__withdrawal](https://user-images.githubusercontent.com/43838780/79979992-b6859e80-84a2-11ea-8a9d-338d56195a72.jpg)

### Design / Mockups
https://xd.adobe.com/view/c95c87f5-d595-4ef8-7b9e-5b57e4e51941-bf6d/

### Question:
- @andrevmatos How does the subkey works for the UDC (SVT tokens)?

**Comment by andrevmatos** [comment]
> * @andrevmatos How does the subkey works for the UDC (SVT tokens)?

Mostly the same as normal token deposits. By default, the tokens are held by the main account, and it deposits in bahalf of the subkey to the UDC directly. It stays there and can be used by the subkey to sign/pay for PFS IOUs and later MS rewards. I'm not sure about withdrawing these tokens, but would think it may end up on the subkey as settles from channels.

**Comment by taleldayekh** [comment]
![wireframes__withdrawal](https://user-images.githubusercontent.com/43838780/79979992-b6859e80-84a2-11ea-8a9d-338d56195a72.jpg)

**Comment by nephix** [comment]
I like it 👍 
Should #1365 be on that withdrawal screen as well or should they be in the account detail section?

**Comment by taleldayekh** [comment]
Perhaps it should have its own menu item and page, to separate the two since they are different tasks.

**Comment by andrevmatos** [comment]
I think having the list of tokens in yet another screen is undesirable. We already have a token list, with balances, we should find a way to integrate it there, maybe expose it a little bit better than only through the token dropdown/button.

**Comment by taleldayekh** [comment]
This list would display only tokens for channels that have been settled as I understand it.

**Comment by taleldayekh** [comment]
@nephix If it is possible the ETH transfer screen could have something similar to this, where the user easily shifts funds between the two accounts in one screen.

![eth_swap](https://user-images.githubusercontent.com/43838780/79983401-074bc600-84a8-11ea-9a86-01915a79cf20.jpg)

**Comment by taleldayekh** [comment]
I have prepared a clickable mockup for this issue. Have a look at https://xd.adobe.com/view/c95c87f5-d595-4ef8-7b9e-5b57e4e51941-bf6d/ and feel free to provide feedback, new ideas, discuss, etc. @kelsos @nephix @andrevmatos @christianbrb

**Comment by andrevmatos** [comment]
`s/Your/You are/`

**Comment by taleldayekh** [comment]
> `s/Your/You are/`

Haha yes. ```You are``` right.

**Comment by christianbrb** [comment]
Looks great :) 

Some remarks:
- Remove (Account Details)
- Do not show Withdrawel (or gray out) if connected with the main account
- I would say "Withdraw tokens from your account" OR "Move tokens to your main account"
- Reduce the sentence to "Transfer the token amount back to your main account"

**Comment by kelsos** [comment]
We decided that all the tokens will be transferred right? no input to select an amount? or not?

**Comment by taleldayekh** [comment]
> We decided that all the tokens will be transferred right? no input to select an amount? or not?

Yes, all tokens. At least for now.

**Comment by taleldayekh** [comment]
> * I would say "Withdraw tokens from your account" OR "Move tokens to your main account"

I'm thinking perhaps it is better to be more explicit and make it clear that the tokens are transferred back to the main account. I'm afraid just using the word account might cause confusion.

**Comment by taleldayekh** [comment]
Mockups, slight update:
https://xd.adobe.com/view/c95c87f5-d595-4ef8-7b9e-5b57e4e51941-bf6d/

**Comment by christianbrb** [comment]
One additional thought: 
- The button should be grayed out if the user is using the dApp with his Main Account
