### ISSUE TITLE
On hover over on `Transfer Amount` and `Total Amount` I want to see the exact value 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1381]
## Steps to Reproduce
1. Send a transfer
2. Look at the transfer summary

## Expected Result
- On hover over on `Transfer Amount` and `Total Amount` I want to see the exact value 
- Check also other places

## Actual Result
- I see nothing on hover over

![grafik](https://user-images.githubusercontent.com/35398162/79865062-d6ea2600-83da-11ea-8bea-f5f9003455ae.png)

**Comment by taleldayekh** [comment]
Should we really enable this for all amounts in the dApp?

**Comment by kelsos** [comment]
While I certainly see a use for this. And I have seen a lot of other crypto apps dealing with a lot of decimals do it. I can certainly feel that having the hover effect when you go over the amount can be annoying.

My suggestion would be to instead add some indicator (like an *) when there are digits hidden and only show the tooltip hovering the asterisk. this way it would be less cluttered by accidental tootlips.

**Comment by christianbrb** [comment]
@taleldayekh showed me his solution and it looks really nice. It is not a hover over anymore, but extending the figures at the same place on hover over.

**Comment by christianbrb** [comment]
We have decided to implement it at every place.
