### ISSUE TITLE
Minting tokens doesn't allow the user to input the amount

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1389]
## Description

The minting dialog in the for the service tokens allows the user to input the number of tokens to be minted. The mint dialog for normal tokens used in channels only mints 1 token automatically and doesn't provide any way to specify the amount.

![image](https://user-images.githubusercontent.com/2269732/79960476-baef8e80-8485-11ea-93e5-a882384722f5.png)

## Acceptance criteria
- Allow the user to input the amount of tokens to be minted

## Tasks
- [ ]

**Comment by christianbrb** [comment]
This is acceptable at the moment. Closing.
