### ISSUE TITLE
CLI bundling does not work

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1401]
## Description

Currently in the `cli` branch, running `npm run build:bundle` does not seem to work and makes testing for the demo train difficult. 

CC @eorituz 

## Acceptance criteria
- `npm run build:bundle` creates a single `bundle.js` that includes all dependencies

**Comment by christianbrb** [comment]
@andrevmatos Could you check that? Thanks :)

**Comment by andrevmatos** [comment]
This was expected, and caused by `wrtc` (provider of WebRTC for NodeJS) being a native module which isn't easily bundlabe (but very performant and compliant, which compensates).
I'm working on implementing this, although it may mean the bundle will need to be accompanied by the native `.node` lib
