### ISSUE TITLE
Use cypress (frontend UI testing) and integration image for e2e/integration testing off the dApp

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1404]
## Description
Use cypress (frontend UI testing) and integration image for e2e/integration testing off the dApp.

## Acceptance criteria
- We need to check if the wizard solution (raw private key) still works (it's merged in master)

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@nephix @kelsos Based on your feedback. Should we go ahead with cypress or should we implement #1511 first and check how this works?

Personally I like manual testing as it also gives useful feedback and preserves a feeling for the actual dApp.

**Comment by nephix** [comment]
> Personally I like manual testing as it also gives useful feedback and preserves a feeling for the actual dApp

I agree

**Comment by kelsos** [comment]
I agree we should fix the manual testing first. I don't see the automated tests as replacing manual testing but as complementing.

**Comment by christianbrb** [comment]
@nephix @kelsos Thanks for your feedback. I have been moving this a little bit down to tackle it in the next iteration (not in this one starting today)
