### ISSUE TITLE
Better clarity between design and implementation

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1405]
## Description
Better clarity between design and implementation
&
Design has been reviewed and is "good enough"
## Acceptance criteria
- Come up with and agree on design guidelines
- Add design discussion label (in the planning)
- Distinctions between discussions on current implementation vs future improvements

## Tasks
- [ ]

**Comment by christianbrb** [comment]
I have added Design has been reviewed and is "good enough" as it seems to be related

**Comment by andrevmatos** [comment]
We've discussed that in the retro, and we decided in something along:
- We need to do throughout discussions/feedback only on major features and design
- We should not let the process hold back development speed for smaller design decisions
- Therefore, for them, whoever is implementing the design has autonomy to push it for implementation [This can be notified with a github label, no need for separate issues]
- But, nonetheless, before or after this, they should remain open for discussion and suggestions by whoever passes by the issue or wants to share some thoughts
  - Sometimes, a short suggestions/feedback discussion on comments or chat is enough to decide on a better way to do something, avoiding wasting/duplicating development work or a new issue and longer discussion for something small
  - If this can't be decided, if any part think it's relevant enough, they can block it and request deeper discussions with the rest of the team e.g. in the daily, possibly with a voting, let's just be reasonable about nitpicking

Any comments or additions, @taleldayekh @nephix @kelsos @christianbrb 
Christian, please, evaluate if these points are relevant enough to be put in the playbook

**Comment by taleldayekh** [comment]
Thank you so much for summarizing this.

**Comment by kelsos** [comment]
My comments are: 
- We need again to distinguish between the design phase and the implementation phase.
- There should be a point where feedback can still be considered and a point where feedback goes to a new issue.

Also regarding the complete autonomy on design decisions I disagree.

I would rather delegate the design proposals to an actual designer and provide feedback on that. Design or user experience is not my area of expertise. And I can recognize my biases based on my knowledge of how things work.

Also, design changes left to the developer, without any design system or proper design guidelines in place can lead to a lot of inconsistencies in the user experience. And while at some points we try to unify the experience, there is a period where the inconsistencies live for a while.

**Comment by christianbrb** [comment]
### Understanding the problem
- There is no agreement on a solution
- Design Feedback which is late in the process is expensive and annoying
- The developers need guidance on the design
- Our refinement was quite weak within the last iterations

For each issue, there are pigs and chickens. The ones which are implementing and designing are responsible and on the driver's seat. The ones not implementing should give feedback. If the feedback is important to you commit to it, create an issue and convince me to get it prioritized.

![grafik](https://agileforall.com/wp-content/uploads/2015/03/agile-safari-pig-and-chicken-part1.png)

### What we have learned in the past
- Going small steps/issues with design works much better than big chunks of design (see our discussion in #571) 
- Simple designs can be developed & implemented by the developer (currently I see a pushback regarding that)
- We can always improve or fine-tune later if the first design/solution is simple
- It has got value if we separate design and development (especially with Roy this worked well as he was not developing and Talel gave him quick feedback).

There is always a trade-off between getting feedback for the released feature quickly and separating design and development strictly.

### Process and Tools
#### A - Understanding the Problem
1. Vision ✔️
2. Persona ✔️
3. Scenarios 
4. Interviews / User Research
5. Paper Prototyping / User flow / Sketches (✔️) - or after 8
6. User Stories ✔️
7. Acceptance Criteria ✔️
#### B - Developing a solution
8. Estimates (Planning Poker) ✔️
9. Design (✔️)
10. Implementation ✔️
11. Test ✔️
12. Demo ✔️
13. Release (sometimes before, sometimes after the demo) ✔️
14. Solution feedback on eg. workshops etc. (✔️)

For each step, feedback and collaboration are important. The delay between step 3 and 12 should not be too big.

![grafik](https://user-images.githubusercontent.com/35398162/81271637-a518c680-904c-11ea-8ec5-c351035c5413.png)

Steps 8 to 12 should fit in one iteration. Step 8 will be the most controversial part and we need to experiment on how to deal with it in our new set-up with @sashseurat. 

### Conclusion
- We split design and development
- We decide within the refinement which issue needs a pre-iteration design, in-iteration design, and no design
- We collect feedback early and often (for example in the first step with a cheap paper prototype/wireframe)
- We try hard to split issues to start simple and small
- The developer decides if he incorporates feedback during development
- The one giving feedback is opening a new issue if the developer is not able to incorporate the feedback

**Comment by christianbrb** [comment]
Worked in the first refinement.

We have got now pre-iteration and in-iteration design.

In addition, I have created a Ready-Label which indicates if the issue is ready.
