### ISSUE TITLE
Standardized tests pattern, uniform quality for tests

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1408]
## Description
Standardized tests pattern, uniform quality for tests (test quality)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
Mostly done as part of #1377 , remaining test suites to be converted to the new pattern are #1614 #1615 & #1616

**Comment by taleldayekh** [comment]
Closing due to the bigger test refactoring as an outcome from the Andrena feedback.
