### ISSUE TITLE
Compliance/integration tests with other clients (cli, raiden-py)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1410]
## Description
Compliance/integration tests with other clients (cli, raiden-py)
- All features
- Distributed simulated environment

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by palango** [comment]
Fixed, as we have:
- Unit tests that test message and signature matches between the implementations
- E2E tests with sirect/mediated transfers between LC and PC
- Scenario player
