### ISSUE TITLE
v0.6.0 navigation is buggy

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1415]
## Steps to Reproduce
1. Go to https://lightclient.raiden.network/
2. Click on channels
3. Click back button

## Expected Result
- I see my channels (2.)
- I go to the transfer screen (3.)

## Actual Result
- I don't see my channels
- I am routed to the "Connect new token" screen

## Additional Infos (Optional) 
```
Firefox
```

**Comment by christianbrb** [comment]
@kelsos Could you take a look at it? The release does not seem to be usable at the moment. Thanks for your support :)

**Comment by kelsos** [comment]
Sure, also evaluating routes seems broken I will take a look.

**Comment by christianbrb** [comment]
Maybe it is also an issue with the closed channels of the hub in combination with the local state.

I did not take a screenshot, but after I was clicking on connect, I was directed to the transfer screen, the TTT token was shown, but with amount of 0.0.

So, what happened above seemed to be fine (seeing no channels and being navigated to the connect token screen).

**Comment by kelsos** [comment]
A yes this thing happened to me too on a channel with the old state but after a couple of minutes, everything was ok. I will have a look anyway and we need to see if it is possible to handle this situation.

**Comment by christianbrb** [comment]
Do you think, that the navigation is buggy?

If not, we should close the issue and open a new on for the problem:
> after I was clicking on connect, I was directed to the transfer screen, the TTT token was shown, but with amount of 0.0 and the channel list was empty because there haven't been channels any more

**Comment by kelsos** [comment]
I have a navigation issue already open but it has to do with the link evaluation. 
The closed channels issue is tricky because we don't have an easy way to navigate to channels if there are settleable channels available.

**Comment by christianbrb** [comment]
@kelsos Thanks :) Closing this issue
