### ISSUE TITLE
Source map error for ../sourcemaps/inpage.js.map

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1416]
## Steps to Reproduce
1. Open a channel

## Expected Result
- No error when accessing ../sourcemaps/inpage.js.map

## Actual Result
- Error in console log when accessing ../sourcemaps/inpage.js.map

## Additional Infos (Optional) 
```
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: https://lightclient.raiden.network/
Source-Map-Adresse: ../sourcemaps/inpage.js.map
```

**Comment by christianbrb** [comment]
@christianbrb to reproduce

**Comment by christianbrb** [comment]
Not reproducible. Closing

**Comment by kelsos** [comment]
@christianbrb it seems that the option to disable production source maps actually worked :)
