### ISSUE TITLE
I want to withdraw tokens from the UDC contract

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1421]
## User Story
As Chris I want to withdraw tokens from the UDC contract so that I can sell them.

## Acceptance criteria
- Needs the notification area to be in place
- There is an event which helps
- There is a withdraw and deposit button (perhaps in the UDC screen)

## Tasks
- [ ] Design (Pre-Iteration design)

**Comment by christianbrb** [comment]
@karlb How do I withdraw my tokens from the UDC as a user? I have already checked https://raiden-network-specification.readthedocs.io/en/latest/service_contracts.html#userdeposit, but couldn't find an answer.

**Comment by karlb** [comment]
To withdraw, you have to call `planWithdraw(amount)`, wait 100 blocks and call `withdraw(amount)`. You can do this on etherscan. The Raiden client should provide a user friendly way to do that, but it currenlty doesn't. It's only [getting the capability to do that internally](https://github.com/raiden-network/raiden/pull/6091) just now.

**Comment by christianbrb** [comment]
@karlb Cool, thanks for the information :) We are planning to implement this in the Light Client.

**Comment by christianbrb** [comment]
@taleldayekh Please assign the "Ready" label after the design has been done, thanks :)

**Comment by taleldayekh** [comment]
Sure thing!

**Comment by taleldayekh** [comment]
One quick fix which also makes sense would be to add the withdrawal icon next to the balance. A user could then perform minting/depositing and withdrawal on the same screen.

<img width="591" alt="Screenshot 2020-06-02 at 10 01 59" src="https://user-images.githubusercontent.com/43838780/83495784-727db480-a4b8-11ea-962b-e45459fb0896.png">

**Comment by kelsos** [comment]
Sound like a good idea to include a withdraw button there

**Comment by taleldayekh** [comment]
Mockup ready. Pretty straight forward but it does the trick:
https://xd.adobe.com/view/6d1e5b87-796c-43d3-6dc0-4817716010fe-1b2f/

Not that the withdrawal icon should not be visible if there is no balance.
@kelsos @andrevmatos @weilbith

**Comment by taleldayekh** [comment]
Whoever picks this issue please also center the top text. Dunno why it is not centered as it is now.

**Comment by kelsos** [comment]
@taleldayekh do we have this icon already in the project?

**Comment by taleldayekh** [comment]
Sure, you should already have used it when you implemented the token withdrawal screen.
