### ISSUE TITLE
Improve sorting of tokens in token selection screen

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1424]
## Description
Currently, our token selection screen will display tokens in a specific order as it is returned by the SDK.
This sometimes might be inconvenient as the tokens where there are active balances might be hidden way bellow. This requires the user to scroll through the token list to locate the tokens with sufficient balance.

## Acceptance criteria
- Tokens with balance are sorted in a descending way from the token with the biggest balance to the token with the less balance.

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@kelsos That's a very good and easy approach, thanks 👍

**Comment by christianbrb** [comment]
Maybe
1st criteria: Sort by balance
2nd criteria (for tokens with 0 as the balance): Sort by token name
