### ISSUE TITLE
Introduce filtering for tokens

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1425]
## Description
If the token list contains a great number of tokens some times finding the token to open a channel might take some time of scrolling through the list to locate the token. It would be nice to be able to search for the tokens by symbol, name, or address.

## Acceptance criteria
- Type the symbol, name or address or part of it and get only the list of tokens matching the search parameters.

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Related (maybe a duplicate) #849

**Comment by kelsos** [comment]
Yes it seems that it is duplicate so I am closing
