### ISSUE TITLE
Last channel is partially hidden when there's many channels

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#1427]
On Channels list screen, when there's many channels and there's the need to scroll, the last channel is partially hidden. Looks like the effective bottom is the screen, instead of the panel/box it is in.
Not shown in the screenshot, but it also gets cut when the expando is collapsed.
![image](https://user-images.githubusercontent.com/587021/80380142-86107c80-8875-11ea-9880-c130051b9508.png)

## Steps to Reproduce
1. Have many channels
2. Try to close the bottom one

## Expected Result
- You can scroll and see the whole pannel for all channels, expanded or not.

## Actual Result
- Last channel panel gets cut

## Additional Infos (Optional) 
- Current staging

**Comment by nephix** [comment]
Seems to be caused by the custom scroll bar implementation
