### ISSUE TITLE
Deposit dialog input is has a color quite close to the dialog color background

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1428]
## Description

It's really hard to distinguish the input compared to the rest of the dialog.

![image](https://user-images.githubusercontent.com/2269732/80380431-def50a80-889f-11ea-8e59-a7a950528c52.png)

The dialog background color is set to `#1E1E1E`
The input background color is set to `#1E1E21`

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@taleldayekh Is it the same gray in the transfer screen?

**Comment by kelsos** [comment]
We could either change the dialog to have a different background, or modify the input to have a different background when displayed in dialog.

**Comment by christianbrb** [comment]
It's fixed

![grafik](https://user-images.githubusercontent.com/35398162/89276990-8e324200-d644-11ea-8714-56012975ebb0.png)
