### ISSUE TITLE
Add the monitoring service to the integration tests

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1429]
## Description

Add the monitoring service to the integration tests

We would need this for #1374 -> I think nothing else could be tested with it
@kelsos We would need to decide if this is worth the effort.

## Acceptance criteria
-

**Comment by kelsos** [comment]
Thanks for creating the issue. Yes let's evaluate if it makes sense to spend time including that in the image.

**Comment by christianbrb** [comment]
At the moment it doesn't add value. In addition, we are currently working on running the different scenarios. Closing.
