### ISSUE TITLE
dApp shows unnecessary 2nd scroll bar

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1439]
## Steps to Reproduce
1. Serve current dApp from master
2. Connect
3. To go transfer screen

## Expected Result
- One scroll bar is shown on medium width screens

## Actual Result
- Right now there are two:
<img width="1279" alt="Screenshot 2020-04-29 at 10 09 06" src="https://user-images.githubusercontent.com/3169205/80574121-88074680-8a01-11ea-9e6e-f108ce3816aa.png">

## Additional Infos (Optional) 

- Browser: GC

**Comment by kelsos** [comment]
But there should be no scrollbar there though, right?

**Comment by nephix** [comment]
I guess the inner one shouldnt be there
It also shows up e.g. in the token list:
<img width="697" alt="Screenshot 2020-04-29 at 11 47 04" src="https://user-images.githubusercontent.com/3169205/80582628-51d0c380-8a0f-11ea-8caf-a104408556c6.png">

**Comment by kelsos** [comment]
Yes it should not, did we change something regarding the high of the card area recently?

**Comment by nephix** [comment]
I can't recall. Maybe `LazyRoute` forces the area to expand?

**Comment by kelsos** [comment]
You are right, it could be. I added a `v-container` so that might be the case, we can replace it with a div as it was previously to see if this fixes the issue.
