### ISSUE TITLE
User feedback: Transfer between main & raiden account

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1443]
## User Story

During the demo and internally the feedback for the transfer ETH between main & raiden account was that the direction of the transfer is not very clear and should be iterated on

## Tasks
- [ ] Design (in-iteration)

**Comment by christianbrb** [comment]
If there is an easy solution I would pull this into the next iteration
> the product backlog is quite uncomfortable to maintain from my mobile ;)

**Comment by taleldayekh** [comment]
Suggested design improvements here:
https://xd.adobe.com/view/6ee945a2-b751-4cd7-4ad1-9bdd0bf9d959-18d8/
