### ISSUE TITLE
Mobile view for transaction history

### ISSUE THREAD

**Issue by sashseurat** [raiden-network/light-client#1451]
## Description
The transfer screen (for desktop) with new transaction history is being implemented as part of the current UX improvement iteration. We will also need to have a design for the mobile view.

## Tasks
- [ ] @sashseurat to design a solution draft

- [ ] Review with decision

- [ ] Implementation

**Comment by christianbrb** [comment]
@taleldayekh Isn't there a possibility to have some small adjustments for mobile as we have done them before? I would like to avoid having a separate screen design for mobile.

**Comment by taleldayekh** [comment]
@christianbrb, a quick fix could be to stack the input fields and button on top of each other on three rows if everyone is ok with that.

**Comment by christianbrb** [comment]
@taleldayekh Sounds good :) Let's do it like that
