### ISSUE TITLE
Can't connect at https://lightclient.raiden.network/

### ISSUE THREAD

**Issue by BOR4** [raiden-network/light-client#1456]
## Steps to Reproduce
1. click connect
2. it fails

## Additional Infos (Optional) 

Mozilla/Ubuntu ... I have been using https://lightclient.raiden.network/ previously. Might have something to do with cache although I tried killing the cache.

I think this is what kills it:
![image](https://user-images.githubusercontent.com/40821065/80917378-c339aa80-8d5e-11ea-90c5-802104c1faea.png)

Requests go to https://raidentransport.test001:
![image](https://user-images.githubusercontent.com/40821065/80917411-fed47480-8d5e-11ea-92ab-9badf23e0643.png)

Responses:
![image](https://user-images.githubusercontent.com/40821065/80917390-db112e80-8d5e-11ea-8437-4e7790bdaba6.png)

I can ping:
![image](https://user-images.githubusercontent.com/40821065/80917462-5246c280-8d5f-11ea-9d61-e82b1243ef2b.png)

If you need more info I will try and provide. This is all I thought you might need :)

**Comment by andrevmatos** [comment]
Hmm, this seem to be an authentication failure with matrix. May it be related to our previous update?
We need to handle it and retry, but you can workaround by editing and deleting the `transport.matrix` key on state

**Comment by christianbrb** [comment]
@BOR4 Thanks for testing and posting the issue!

Could you download and attach the logs? 
Identicon on the top right -> General Screen -> Report Bugs

Please also download your state -> Backup state (but don't attach it yet)

**Comment by BOR4** [comment]
[raiden_2020-05-03T15_20_48.890Z.log](https://github.com/raiden-network/light-client/files/4573051/raiden_2020-05-03T15_20_48.890Z.log)

@christianbrb this should be it I think

**Comment by BOR4** [comment]
I can't download state ... It says it is only possible when connected to dApp and I am not connected.

**Comment by kelsos** [comment]
@andrevmatos no it's not related to the update.

I encountered the same issue once, in an account that has not been used in a while. I think it was an account with state that pre-dated the test environment.

**Comment by christianbrb** [comment]
@BOR4 Cool, thanks, we'll have a look at it :)

**Comment by christianbrb** [comment]
@andrevmatos Can we provide a hotfix release for this? Like this @BOR4 would be able to test it at https://lightclient.raiden.network/ with his current state.

**Comment by BOR4** [comment]
I tried as soon as I saw this merged xD and bug was still present ... just ping me when it is ready for test and I try it!

**Comment by kelsos** [comment]
@BOR4 https://lightclient.raiden.network/ is tied to releases now instead of the latest master.

**Comment by christianbrb** [comment]
@BOR4 We have made a new release and it has been deployed. Could you try to connect again now?

**Comment by BOR4** [comment]
@christianbrb works like a charm. Managed to connect first try without any issues.

**Comment by christianbrb** [comment]
Great 😊👍🏻 Thanks for testing the Light Client & your feedback 🍀
