### ISSUE TITLE
dApp on staging does not seem to update

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1457]
## Steps to Reproduce
1. Navigate to https://lightclient.raiden.network/staging/
2. The message ` A new version is available. ` is shown
3. Click on update

## Expected Result
- The dApp updates and the message disappears

## Actual Result
- The message stays and the spinner keeps spinning

## Additional Infos (Optional) 
```

```

**Comment by christianbrb** [comment]
After hitting refresh the message is not shown any more

**Comment by nephix** [comment]
Can't reproduce, worked for me on Firefox and GC.

> After hitting refresh the message is not shown any more

I think the button simply waits 1s and refreshes the page, so it's the same as refreshing the page. Was probably a glitch on github pages or some slow DNS response

**Comment by christianbrb** [comment]
@nephix Thanks for looking into it. Closing. If it appears again I am going to reopen it.

**Comment by christianbrb** [comment]
It doesn't work or it doesn't get feedback -> spinner keeps spinning

**Comment by nephix** [comment]
Just checked it too, worked for me again in FF and GC.

If someone encounters this again it would be interesting to see if something popped up in the console

**Comment by christianbrb** [comment]
@christianbrb to attach logs

**Comment by nephix** [comment]
@christianbrb did you experience this again now after the release? If yes, would really helpful to see if there are errors in the console

**Comment by christianbrb** [comment]
It worked on https://lightclient.raiden.network/
It still not worked on staging. Closing.
