### ISSUE TITLE
SDK initialization failed is still shown on the connect modal after closing and reopening connect modal

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1461]
## Steps to Reproduce
1. Navigate to https://lightclient.raiden.network/
2. Click on Connect
3. Click on "dedicated Raiden account."
4. Click on Cancel in MetaMask
5. Error is shown on the Connect Modal
6. Close the Connect Modal
7. Click on Connect

## Expected Result
- Error is not shown any more on the connect modal

## Actual Result
- Error is still shown on the connect modal

## Possible solutions
- Reset state
- Outdated modal
 
![grafik](https://user-images.githubusercontent.com/35398162/80970506-91d2e480-8e1b-11ea-95d8-cf61b4da3a86.png)

**Comment by nephix** [comment]
Not reproducible anymore with the new dialog/subkey flow
