### ISSUE TITLE
Move route title metadata to resources

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1465]
## Description
Currently, we have hardcoded text for the route titles:
https://github.com/raiden-network/light-client/blob/c80000bee11300449cc11c577d0189f3e4348b93/raiden-dapp/src/router/index.ts#L18

We should move these header titles to the en.json file and replace the title content with the key in the json file.

## Acceptance criteria
- Routes are moved to `en.json`

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@taleldayekh Is this issue still valid?

**Comment by taleldayekh** [comment]
Yes, the issue is valid, the route names are still hardcoded.

**Comment by christianbrb** [comment]
We won't do that soon. Closing.
