### ISSUE TITLE
 I want to be able to select a hub when I am already connected to a token network

### ISSUE THREAD

**Issue by roy-castrillo** [raiden-network/light-client#148]
## User Story
As Chris I want to be able to select a hub when I am already connected to a token network so that I can connect to additional Raiden clients

## Acceptance criteria
- Selected Token needs to be visible
- Similar UI and logic to Open Channel
- There needs to be feedback for all stages (no address, wrong address, right address)
- When typing in ens name, a suggested address should appear

## Tasks
- [ ] Design
- [ ] Implementation

**Comment by christianbrb** [comment]
@roy-castrillo This is implemented with the payment screen, right?

**Comment by christianbrb** [comment]
Closing as outdated and out of context
