### ISSUE TITLE
Combine ETH Transfer and Withdraw screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1481]
## Description
As the user just needs the ETH to withdraw tokens from his Raiden Account I would combine the two screens. 

In addition the ETH transfer screen looks quite empty.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Could be combined with #1443

**Comment by taleldayekh** [comment]
I believe the consensus is to keep them separated because they are two different actions. Also the ETH transfer screen has been re-worked in #1573 .

Perhaps close this issue?

**Comment by kelsos** [comment]
I am ok with that. If the others also agree then we can proceed and close it.
