### ISSUE TITLE
Test WebRTC on the IoT demo

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1483]
## Description
Test WebRTC on our IoT demo

Please keep this issue updated with the progress.

## Acceptance criteria
- Feedback if the current solutions works for @eorituz 

## Tasks
- [x] Provide test instructions @andrevmatos 
- [x] Execute test and give feedback @eorituz

**Comment by eorituz** [comment]
Tested the WebRTC raiden-cli on the nanopi today.
Works as expected and transaction time is arround ~3s.

However, I'd need one additional feature in order to continue working on the demo train: https://github.com/raiden-network/light-client/issues/1484

**Comment by christianbrb** [comment]
Great :) Thanks for your feedback 👍
