### ISSUE TITLE
[Feature Request] Add identifier to raidencli API

### ISSUE THREAD

**Issue by eorituz** [raiden-network/light-client#1484]
## Description
The demo train rellies on specific identifiers to process the incoming transactions and differentiate between them.
It would be awesome if you could add the possibility to set an identifier in REST-requests to the raiden-cli.

Right now the API accepts the additional entry int he json but ignores it:
```
pi@NanoPi-Duo2:~$ curl -v -H 'Content-Type: application/json' http://localhost:5001/api/v1/payments/0x31aA9D3E2bd38d22CA3Ae9be7aae1D518fe46043/0x0087b32F69DB0b92cA5F268b499017DC5ca6EBFA -d '{ "amount": 2 , "identifier": 6 }'
```
succeeds but the receiver repots a different identifier:
```
oliver@bbpc:~$ curl localhost:5001/api/v1/payments
[{"identifier": "1588928930581", "amount": "2", "log_time": "2020-05-08T09:08:55.264000", "initiator": "0x00D384EF74575E97884215e9f39142228c7ACfa8", "event": "EventPaymentReceivedSuccess", "token_address": "0x31aA9D3E2bd38d22CA3Ae9be7aae1D518fe46043"}]
```

## Acceptance criteria
- Be able to set an identifier with the raiden-cli

## Tasks
- []

**Comment by nephix** [comment]
I can confirm that the CLI currently doesn't handle payment identifiers set in the request at the moment, but it's straight forward to add
