### ISSUE TITLE
I want mint and deposit UDC tokens on a separate screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1489]
## User Story
As Chris I want mint and deposit UDC tokens on a separate screen so that I can pay the PFS and Monitoring Service

## Acceptance criteria
- 

## Open Questions:
- @kelsos "Do we need a new screen for this? Checking the MintDepositDialog it seems that it is self-contained so we could reuse that instead" in https://github.com/raiden-network/light-client/issues/1473

**Comment by taleldayekh** [comment]
Possibly add an item to manage UDC in the `Account` screen.
![udc](https://user-images.githubusercontent.com/43838780/81700092-7fcef280-9468-11ea-9616-9247e5970d05.png)

**Comment by kelsos** [comment]
As I also wrote in the chat, we could make a base that re-uses the common functionality if we absolutely need this to be a new screen and re-use as much as possible

**Comment by taleldayekh** [comment]
Mockups for this one here:
https://xd.adobe.com/view/69780e89-762b-4fff-40cf-f788b49189ec-1f49/
