### ISSUE TITLE
Which 3rd party services are used in the dApp and SDK on runtime?

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1497]
## Description
Which 3rd party services are used in the dApp and SDK on runtime?

One example is STUN server for WebRTC. Anything else? I have seen eg. Google Fonts in the requests, but I am not sure if this is dApp related.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by nephix** [comment]
Yes Google fonts as well (we load the Material Icons and Roboto font)
We could easily pull them in and host them ourselves though

**Comment by christianbrb** [comment]
@nephix Thanks for your feedback. Created issue #1498 to resolve this.

**Comment by nephix** [comment]
I'm closing this as all 3rd party things have been mentioned
