### ISSUE TITLE
Host Google fonts on our own - Material Icons and Roboto font

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1498]
## Description
Pull in Material Icons and Roboto font from Google fonts and host them

## Acceptance criteria
- Don't access the google-hosted fonts any more

**Comment by kelsos** [comment]
For the icons we can use them as a local dependency https://vuetifyjs.com/en/customization/icons/#install-material-design-icons and for the font we can do this https://vuetifyjs.com/en/customization/icons/#install-material-icons
