### ISSUE TITLE
Create unreleased section when doing a new release

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1505]
## Description

Sometimes tickets get added in the change log to a release version that got already published.

Maybe it make sense to add the unreleased sections in 
* `raiden-ts/CHANGELOG.md`, and
* `raiden-dapp/CHANGELOG.md`

as a step in our `RELEASE.md` to avoid this in the future
## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
We have got already an unreleased section
