### ISSUE TITLE
I don't see the pop-up for the Raiden Account

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1508]
## Steps to Reproduce
1. Navigate to https://lightclient.raiden.network/staging/
2. Click on connect

## Expected Result
- I see the Raiden Account modal

## Actual Result
- I do not see the Raiden Account modal
- I am directly directed to the transfer screen

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by nephix** [comment]
The modal is only displayed on first connect to inform the user that they're using a Raiden account.

If it doesn't show up then you probably already connected before with your account have and have `isFirstTimeConnect: false` in `raiden_dapp_settings` local storage?

<img width="1064" alt="Screenshot 2020-05-13 at 15 47 29" src="https://user-images.githubusercontent.com/3169205/81820720-42826780-9531-11ea-99fb-72c305e46584.png">

**Comment by christianbrb** [comment]
Ok, cool, a good addition to the feature :) 👍
