### ISSUE TITLE
Rework the account menu

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1509]
## Description
Feedback within the demo
- Easier if the whole "button" would be clickable not just the small arrow

Personal remarks
- Show the new settings section also if connected but grayed out

Review
- Name of each action
- Description of each action

## Acceptance criteria
- Name of each action should be better
- Description of teach action should be better
- Group Raiden Account, Withdrawal and UDC
- Group Backup State and Report Bugs
- Make the whole button clickable

@sashseurat 

## Tasks
- [ ] Design @sashseurat 

## Current Screen

![grafik](https://user-images.githubusercontent.com/35398162/97856499-ac1f4980-1cfc-11eb-9f80-558b4e7dfccf.png)

**Comment by sashseurat** [comment]
@christianbrb @taleldayekh @weilbith 
The optimized menu is ready for review, also in the following click dummy:
https://www.figma.com/proto/5H8EOoC2SntoXZuTtUZsyY/LC-UDC-Screen-Optimisation?node-id=29%3A145&viewport=-257%2C502%2C0.3179304003715515&scaling=min-zoom

<img width="489" alt="Screenshot 2020-11-04 at 15 23 46" src="https://user-images.githubusercontent.com/32264127/98123134-c4849500-1eb1-11eb-97d5-731114cac1da.png">



I find the label changes an improvement, but I would love to have your ideas as well :)

**Comment by christianbrb** [comment]
@sashseurat Looks great :)

My remarks:
- I like the new buttons -> please align with @taleldayekh as we might need to change them at other places as well
- We still have got white as the primary color (see eg. the transfer screen) for text therefore I would make the button header white.
- The button border should be the same grey as we have got on the transfer screen.
- Is the font size for the explaining text 14 px?

As a reference
![grafik](https://user-images.githubusercontent.com/35398162/98132586-e2a3c280-1ebc-11eb-821e-327b826a1e29.png)

**Comment by sashseurat** [comment]
> @sashseurat Looks great :)
> 
> My remarks:
> 
> * I like the new buttons -> please align with @taleldayekh as we might need to change them at other places as well
@taleldayekh let me know when you have time today to have a call about this :)

> * We still have got white as the primary color (see eg. the transfer screen) for text therefore I would make the button header white.
It seems to be more clickable when its blue. This is something we can test very easily with real people via [Maze](https://maze.design/)

> * The button border should be the same grey as we have got on the transfer screen.

Which border? these are new components that have different meanings from the transfer screen. Consistency does not translate into All Buttons Should Have Same Styling. we need to make concious decisions for each specific context.

> * Is the font size for the explaining text 14 px?
no. there is no need to enlarge this text and have it compete with the shorter titles - this will only create confusion. Bigger is not always better. This text is not intended to be always read, it is intended to be there if user is looking for further information after reading the title. We cannot treat that text as the primary piece of information (enlarging it will do so - it is very long as it is), and we cannot treat it as if it needs to be read every single time User is on this screen.


>

> As a reference
> ![grafik](https://user-images.githubusercontent.com/35398162/98132586-e2a3c280-1ebc-11eb-821e-327b826a1e29.png)
