### ISSUE TITLE
Make testing a PR easier

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1511]
## Description
Currently we have got the problem, that it is difficult to get a branch/PR in a state where it can be tested by the reviewer.

We have discussed several solutions:
- Looking at CircleCI or https://vercel.com/features/deployment-previews to build and deploy a PR branch
- Alternative: Get it built by the CI, download and serve locally

Additional actions:
- Having a different account for testing
- Test steps more detailed (exclude bugs)

## Acceptance criteria
- Decide on an approach and estimate after discussion

## Tasks
- [ ]

**Comment by nephix** [comment]
Vercel makes it very easy but reusing the build artifacts makes sense as well since we already build the dapp+sdk on every branch push. Would only need to:
* deploy it somewhere
* make it unique per pull request
* remove deployment when pull request gets closed/merged

**Comment by christianbrb** [comment]
Seems to be ready for the iteration for me

@nephix @kelsos @andrevmatos Please remove the label if there is more refinement needed.

**Comment by kelsos** [comment]
The vercel flow seems reasonable to me, and easy.

**Comment by nephix** [comment]
Zeit/Vercel's Now doesn't seem to offer a lot of monorepo support yet so it probably makes sense to go with a different option

**Comment by nephix** [comment]
Another option would be to use [netlify](https://www.netlify.com/)/[vercel](https://vercel.com/) and tell it via CLI to deploy the build build artifacts that we build via CircleCI:
```
$ netlify deploy --dir raiden-dapp/dist --site 714de093-0a95-4dc4-a978-ff660e317d91 --auth NETLIFY_AUTH_TOKEN

Deploy path: /Users/nephix/Projects/light-client/raiden-dapp/dist
Deploying to draft URL...
✔ Finished hashing 99 files
✔ CDN requesting 0 files
✔ Finished uploading 0 assets
✔ Draft deploy is live!

Logs:              https://app.netlify.com/sites/light-client-preview/deploys/5ebe6e9533a1407f5c8c2435
Website Draft URL: https://5ebe6e9533a1407f5c8c2435--light-client-preview.netlify.app
```

And then in a second step comment the draft URL to the pull request (this orb might help? https://circleci.com/orbs/registry/orb/benjlevesque/pr-comment)

**Comment by christianbrb** [comment]
@kelsos Do we know how to move forward with this issue?

Two other options:
- https://devcenter.heroku.com/articles/github-integration-review-apps
- https://sanderknape.com/2020/05/deploy-pull-requests-github-actions-deployments/

**Comment by kelsos** [comment]
I already checked the review-apps but I am not sure about the cost of that.

The whole idea is to automate the deployment using CI, but where to deploy is a question. I had a discussion with Nils on that but I am still not sure about deploying new instances of anything on each PR.

**Comment by christianbrb** [comment]
@andrevmatos to create a server (docker image)

**Comment by christianbrb** [comment]
Briefly discussed with @kelsos to take out complexity.

If there is no objection we would just provide the tool @andrevmatos proposed that downloads the published artifacts from CircleCI, starts an express server, and serves the content on the dev/tester local machine **without publishing it on a remote server**.

**Comment by christianbrb** [comment]
Decided in the daily: We go with the simple local approach :)

**Comment by andrevmatos** [comment]
I'm not sure what `simple local approach` means... for me, a simple local approach is what we have currently: `checkout branch, build and serve`. Simpler local than that, could only be `download and serve`, but that's not less work than what we have. And beyond that, just do this automatically upon accessing a URL of a service hosted somewhere. I'm looking for options on how it could look like local or remote.
