### ISSUE TITLE
I want to disconnect the dApp

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1515]
## User Story

As a user I want to disconnect the dApp e.g. if I don't want to use it anymore or to access features that are only available while disconnected (e.g. state upload)

Currently it's not obvious that the only way to disconnect is to browser reload

**Comment by kelsos** [comment]
When I needed to test something that required logging out. I found it really annoying that I had to reload the page. It should be really easy to add something like a logout functionality. We already have a `disconnect()` method for the sdk and a `reset` mutation to clear the dApp state. 

I think that the Account page would be a good candidate to add the logout functionality.
