### ISSUE TITLE
I want to open a channel to a client which has got a high uptime

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#155]
## User Story

As Chris I want to open a channel to a client which has got a high uptime so that I can be sure, that it well usable.

## Tasks
- [ ] Implement methods for smart suggestion of hubs/partners, so both assisted and automated onboarding/token network joining can be performed
- [ ] Make clear/configurable strategy

**Comment by andrevmatos** [comment]
Uptime isn't the only parameter, but yes, I'll use this issue to track SDK feature to suggest good partners/hub for clients, so they can make best informed possible choice upon trying to join automatically a token network.

**Comment by andrevmatos** [comment]
Duplicated of #211
