### ISSUE TITLE
On first connect the dApp connects to an unsupported network

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1574]
## Steps to Reproduce
1. Select an unsupported network in your web3 provider
2. Go to staging
3. Click on connect

## Expected Result
- Error Message: The current network is unsupported 

## Actual Result
- Raiden Account is getting generated. Tokens are loaded.
- On the second try to connect the right error message is shown

## Additional Infos (Optional) 
```
- Status Mobile App
```

**Comment by nephix** [comment]
Can't reproduce if I set metamask to main net and try to connect on https://lightclient.raiden.network/staging

<img width="670" alt="Screenshot 2020-05-26 at 13 52 56" src="https://user-images.githubusercontent.com/3169205/82897692-49a96c80-9f58-11ea-95b8-bf63d81359b2.png">

Or is there another network that we don't support?

**Comment by nephix** [comment]
Can't reproduce, both kovan and main net display the unsupported network message
