### ISSUE TITLE
Don't mint (only deposit) to UDC when not on a test net

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1579]
## Steps to Reproduce
1. Serve dApp
2. Connect (not to a test net)
3. Click on a token
4. Acquire some SVT
5. Try to deposit in dApp

## Expected Result
- We already have SVT in the account and can deposit 

## Actual Result
- Currently it should fail because minting is only allowed on test nets
- Depositing may fail as well because minting failed

**Comment by nephix** [comment]
According to @kelsos this should not happen because we skip minting if we already have sufficient SVT

**Comment by kelsos** [comment]
@nephix while this is true we should also check if mainnet 
https://github.com/raiden-network/light-client/blob/842352ee3f8418d3b6eed71eab365a36dda43da3/raiden-dapp/src/components/dialogs/MintDepositDialog.vue#L129

I think this issue is valid :)

**Comment by nephix** [comment]
Ok lets keep it open then :)
