### ISSUE TITLE
Raiden => Main account arrow not shown

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1582]
## Steps to Reproduce
1. Go to https://lightclient.raiden.network/staging
2. Connect
3. Click identicon
4. Click on raiden account

## Expected Result

<img width="544" alt="Screenshot 2020-05-27 at 09 41 21" src="https://user-images.githubusercontent.com/3169205/82991665-51235100-9ffe-11ea-952a-43f230ad60b8.png">

## Actual Result

- Arrow not displayed
- Main account icon is cut off

<img width="558" alt="Screenshot 2020-05-27 at 09 42 06" src="https://user-images.githubusercontent.com/3169205/82991680-584a5f00-9ffe-11ea-95c5-e5b487c943d0.png">

## Additional Infos (Optional) 

- Browser: Firefox

**Comment by nephix** [comment]
Related, in Chrome when hovering the arrow there's a gray circle:

<img width="569" alt="Screenshot 2020-05-27 at 09 46 05" src="https://user-images.githubusercontent.com/3169205/82992123-fccca100-9ffe-11ea-81c1-fe7be292aaeb.png">

Not sure if it should not be shown or if it should cover the whole arrow

**Comment by andrevmatos** [comment]
Seems related to #1582. Couldn't reproduce. Could this be some caching issue?

**Comment by nephix** [comment]
I don't think so, service worker has been updated so all assets have been refetched
