### ISSUE TITLE
Service Token balance confusion

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#1583]
## User Story

During tests on non-test-nets @agatsoh mentioned that when opening a new channel, the service token balance on:
* Token list view, and
* Select hub view

is very confusing..

In the first view it says I have 20 RDN (in the account), while the 2nd one says I have 0 RDN (in the user deposit contract)

We may need a better solution to differentiate the two

![JB0zrXT](https://user-images.githubusercontent.com/3169205/83002595-897e5b80-a00d-11ea-9355-3e0c96ea89cb.png)
![W3sRHYn](https://user-images.githubusercontent.com/3169205/83002600-8b481f00-a00d-11ea-9f5e-918a01446da6.png)

## Expected Result
- RDN Token should not be shown in the list

## Remark
- Filter all the tokens we have against the tokens returned from the SDK

**Comment by christianbrb** [comment]
@andrevmatos to check if there is a RDN token network

**Comment by christianbrb** [comment]
Maybe it's a bug
