### ISSUE TITLE
Add E2E dApp tests to CI

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1585]
## Description

This issue is a followup to #1584
After getting a satisfying number of e2e tests for the dApp we should include the tests to our CI configuration. 

We can either have them run as nightly tests, or have them run on every PR.
We should evaluate the total run time of the e2e suite and see if the extra e2e run time can be absorbed by running the job in parallel with the other tests jobs, without increasing test suite runtime.

## Acceptance criteria
- E2E tests run on the CI infrastructure

## Tasks
- [ ]

**Comment by christianbrb** [comment]
We are already doing this within #1584
