### ISSUE TITLE
Wrong deploy block number for Ropsten Red Eyes Release

### ISSUE THREAD

**Issue by marcosmartinez7** [raiden-network/light-client#160]
Basically if you run the light client against Ropsten the registered token will not appear

Thats because the ´deployment_ropsten.json´ file has a block_number that is greater that the block number when TokenNetworkRegistry was deployed 

"TokenNetworkRegistry": {"address": "0x40a5D15fD98b9a351855D64daa9bc621F400cbc5", "transaction_hash": "0x368fb55258310a29194ffa13e98058a3f79da91583776d70d2e507940ee00203", "block_number": **4249345**, "gas_cost": 4950722, "constructor_arguments": ["0xd97b443B69307E771AD2dDaA4bA1458B84d7b60b", 3, 500, 555428]}

https://ropsten.etherscan.io/address/0x40a5D15fD98b9a351855D64daa9bc621F400cbc5

The deployment_ropsten.json must be changed to 4236264

**Comment by kelsos** [comment]
@marcosmartinez7 I am closing the issue since the PR has been merged. 
Thank you for your contribution. :)
