### ISSUE TITLE
Convert transfers unit tests to the new pattern

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#1615]
## Description
With #1377 / #1577 , there's a new standardized way to do epics unit async testing.
We should convert the transfers tests to use this new pattern. Check #1614 for the new flow.
New `ensure*` fixtures functions may be needed to ensure some common state.

## Acceptance criteria
- [send.spec.ts](https://github.com/raiden-network/light-client/blob/master/raiden-ts/tests/unit/epics/send.spec.ts) is converted to the new tests fixtures
- [receive.spec.ts](https://github.com/raiden-network/light-client/blob/master/raiden-ts/tests/unit/epics/receive.spec.ts) is converted to the new tests fixtures
- [mediate.spec.ts](https://github.com/raiden-network/light-client/blob/master/raiden-ts/tests/unit/epics/mediate.spec.ts) is converted to the new tests fixtures

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@andrevmatos is currently working on this :)
