### ISSUE TITLE
Implement missing API endpoints for the train demo

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1646]
## Description

From https://github.com/raiden-network/light-client/issues/173#issuecomment-640456211

> The CLI works perfectly fine, lightning-fast and provides almost every needed endpoint. It only misses the GET .../api/(version)/payments/:token/:partner_address.
This is currently a blocker for the demo train, as I need this endpoint to verify that the train sent a payment with a unique given identifier.

CC @eorituz 

## Acceptance criteria
- endpoint **PUT** `api/v1/channels` is implemented
- endpoint **POST** `api/v1/payments/:token/:receiver_address` is implemented
- endpoint **GET** `api/v1/payments/:token/:partner_address` is implemented

## Tasks
- [ ]

**Comment by christianbrb** [comment]
For testing the integration image could get used

**Comment by weilbith** [comment]
Finally the last PR was merged. Sorry for the delay.
Now, everything for the train demo should be there. Looking forward to get feedback. In this case would be no feedback the best, but... :wink:
