### ISSUE TITLE
Receiving transfers is disabled even if I have minted and deposited SVT to the UDC contract

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1653]
## Steps to Reproduce
1. Connect to the dApp at https://lightclient.raiden.network/staging/
2. A message `Receiving transfers is disabled` is shown
3. Mint and Deposit UDC tokens

## Expected Result
- I get a message `Receiving transfers is enabled`
- The message `Receiving transfers is disabled` is not shown after connecting to the dApp

## Actual Result
- Nothing happens
- When I reload the dApp it still shows `Receiving transfers is disabled`

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by kelsos** [comment]
@christianbrb 
The rate to SVT is also required for receiving. Currently we don't provide a mechanism that can be used to set that value.

**Comment by christianbrb** [comment]
@kelsos Thanks :) That's important. I have created issue https://github.com/raiden-network/light-client/issues/1654 and pushed it up in the product backlog. Closing this issue.

**Comment by christianbrb** [comment]
How do I set the SVT rate?

CC @agatsoh

**Comment by andrevmatos** [comment]
It's a little bit tricky now. One way is to go to browser's DevTools, Application, Local Storage, search for `raiden_mainnet_<registry_addr>_<account_addr>` key, edit it, go to the empty `config` object and add it there as a json, like:
```json
  ...
  "config": {
    "rateToSvt": {
      "0x<token_addr>": "5000000000000000000"
    }
  },
  ...
```
Setting it to `5 * 10^18`, like I did above, means every `1 * 10^18` wei of token (1 token, if token has 18 decimals, as default) is worth `5 SVT` (5e18 wei of SVT), so as the default `monitoringReward` is 5SVT, the SDK will start sending MS requests once the amount transferred to us in a channel surpasses 1 token, but receiving will be enabled for every token network from scratch.

**Comment by christianbrb** [comment]
We do not need to document this, because #1705 is currently being implemented.
