### ISSUE TITLE
Disclaimer

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1658]
## Description
We need a disclaimer in the SDK, dApp and CLI/API on startup, which the user needs to accept.

See https://github.com/raiden-network/raiden/blob/84eb30b7a5122a94d8ed01a31def7ff3b6c4f414/raiden/ui/cli.py#L567-L607 as a reference

## Acceptance criteria
- The disclaimer for the SDK is in the Readme
- For the CLI/API we make it like the Python implementation
- You are not able to accept the connect screen without accepting the Disclaimer (dApp)
- Persists the state when a user has already accepted the disclaimer

## Tasks
- [x] In-iteration design

## Design
Mockup here:
https://xd.adobe.com/view/af981f2a-9e04-4711-5404-ec1f5d8de631-d9a9/

![grafik](https://user-images.githubusercontent.com/35398162/86474116-75332a00-bd42-11ea-91ae-647a40256a46.png)

**Comment by christianbrb** [comment]
For the dApp
- Show on startup
- User needs to click on "Yes" to continue
- Have a tickmark to not show the disclaimer again (by default it is not activated)
- Add a section with the disclaimer to the Raiden Account menu (maybe in a submenu called About as it is typically done in applications)

**Comment by christianbrb** [comment]
Refinement:
- Adding it to the main readme

**Comment by taleldayekh** [comment]
A blurred out overlay (similar to when the user tries to use the dApp without internet connection) with a centered box where the disclaimer text is shown. Underneath are a checkbox and button for the user to consent. Let's make the dApp remember the user's consent and only show this on the very first use.

**Comment by christianbrb** [comment]
@taleldayekh I am moving it out of the iteration as it's still refinement.

**Comment by taleldayekh** [comment]
Mockup here:
https://xd.adobe.com/view/af981f2a-9e04-4711-5404-ec1f5d8de631-d9a9/

**Comment by weilbith** [comment]
Disclaimer has been introduced to all components of the light client. Acceptance criteria are met. :heavy_check_mark:
