### ISSUE TITLE
Support gas price estimation

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1659]
## Description
Gas prices are fluctuating a lot at the moment. This leads to situations where opening a channel takes 2 hours. We should support the user in setting a good gas price.

CC @agatsoh 

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
most onchain txs are done through the main (aka Metamask) account, and on its prompt, you can set your desired gas price, and the SDK will respect and use it. It would only need to be implemented on the SDK for onchain txs sent by the subkey, e.g. token and udc withdrawals.

**Comment by christianbrb** [comment]
Discussion about the gas price strategy within the wizard (maybe helpful): https://github.com/raiden-network/raiden-wizard/issues/195

**Comment by christianbrb** [comment]
Let's skip this for now. Closing
