### ISSUE TITLE
Heavy and stress testing with BF6

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1691]
## Description
Currently we have got the unit, e2e, integration and manuel tests. The scenario player tests (#1412) will not be ready soon.

To be confident we would like to add additional (semi-)manual tests how we have done them for Red Eyes (a lot of transfers / load, kill the dApp / SDK during transfers, etc.)

## Acceptance criteria
- Scenario Player runs BF6
- Fixes to run BF6 are implemented
- Documentation and code on how to run BF6 is done

## Tasks
- [ ] @andrevmatos Do research on the various parts needed to split this story

**Comment by christianbrb** [comment]
Maybe we could also use the integration test for this.

**Comment by christianbrb** [comment]
Discussion with @andrevmatos 

It is more important to build a set of scripts to test for Goerli:
- 10 Nodes
- With mediated transfers
- Include PFS delays
- Killing nodes
- CLI Nodes and Python Nodes

Maybe using the scenario player or integration test script to set-up a Raiden Network (just Python Clients).
- [ ] @andrevmatos is checking out the scenario player
     - Scenario Player https://github.com/raiden-network/scenario-player
     - Scenarios: https://github.com/raiden-network/raiden/tree/develop/raiden/tests/scenarios

**Comment by andrevmatos** [comment]
Scenario Player integration depends on extending the CLI compatibility, aka #1692 , so I'm pulling that

**Comment by christianbrb** [comment]
Related #1412
