### ISSUE TITLE
Complete Raiden API endpoint implementations

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1692]
## Description

This issue acts as extension to #173 and works in addition to #1646.
The target is to have the cli implementation to provide all endpoints the [Raiden API specification](https://raiden-network.readthedocs.io/en/latest/rest_api.html) defines. While all routes are already defined, the according implementations with the SDK are missing.

## Acceptance criteria
- [ ] cli implements all Raiden API endpoints that are missing to completion

## Tasks
- [ ] implement route logic

**Comment by andrevmatos** [comment]
Done in the several PRs above. REST API should be complete. We're doing CLI parameters compliance now.
