### ISSUE TITLE
Show Privacy Policy & Imprint if dApp is hosted on *.raiden.network

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1693]
## Description
Show `Privacy Policy, Disclaimer & Imprint` if dApp is hosted on *.raiden.network

## Idea
Making it a configurable

## Acceptance criteria
- The link to the privacy policy, etc. is configurable
- The description of the link is configurable
- If the configuration fields are empty nothing is shown
- The default configuration is empty
- If it is deployed at *.raiden.network the text shows `Privacy Policy & Imprint` and a link to https://raiden.network/privacy.html

![grafik](https://user-images.githubusercontent.com/35398162/98820492-84339280-242e-11eb-8316-317f4f79105e.png)

## Tasks
- [ ]

**Comment by kelsos** [comment]
Don't we already do that? or is this about hiding if it is not hosted on `*.raiden.network`?

**Comment by christianbrb** [comment]
It's about hiding if it is not hosted on `*.raiden.network`?

**Comment by christianbrb** [comment]
Still clarifying, if this is needed.

**Comment by christianbrb** [comment]
The link is not shown on staging, reopening.

**Comment by taleldayekh** [comment]
It needs to be defined in Circle CI @christianbrb .
