### ISSUE TITLE
Clearify Raiden API sync status with SDK reference implementation

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1697]
## Description

The Raiden API specification defines three different possible status for
a Raiden node: 
  - `ready`
  - `syncing`
  - `unavailable`

The current reverence implementation with the SDK (`cli`) supports only `ready` and `unavailable`. The node is considered to be ready if `raiden.started` is true. Since there is no `syncing` status yet, the second return property on `/api/v1/status` called `blocks_to_sync` is set to `unknown` permanently.

This should be resolved. Maybe the answer is that that there is no actual synchronization phase with the SDK. But if I remember it correctly there actually was a sync phase that is just pretty short. In this case it must be figured out if the SDK somehow exposes this state and possibly add this functionality.

The API specification also defines the global error status code `503` if the sever is not available. While the app gets never started without the Raiden instance already created, the only case it could be unavailable would be the `syncing` state. So this must be added if this becomes be added.

## Acceptance criteria
- Clear statement about the SDK and syncing
- Eventually an interface endpoint of the SDK to expose the sync status
- Eventually a global middleware in the API to response in case of
unavailability

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
The SDK `synced` status was implemented on #2417. Closing.
