### ISSUE TITLE
What happens if a Raiden Clients wants to mediate through a Light Client?

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1699]
## Description
Currently mediating is disabled for the Light Client. How are we dealing with a situation where a Raiden client tries to use a Light Client as a mediating node.

### Example:
LC = Light Client
PC = Python Client

A (LC) <- B (LC) <- C (PC)

C requests a route from the PFS and get's one through B.

B cannot mediate.

It now tries to send a transfer to A, which fails.

@Dominik1999 
Is the example correct? Would the Python Client try to send the transfer again?

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
> C requests a route from the PFS and get's one through B.

This does not happen. As B has mediation disabled (by default), it doesn't send `PFSFeeUpdate` messages to the `path_finding` global room, which is needed to get picked up by PFS for a route, even if such message is sent with zeroed values, like we do when mediation is enabled, before we support non-zero mediation fees (#1342 and friends).

> B cannot mediate.
> 
> It now tries to send a transfer to A, which fails.

Even if some node forces trying to send a mediated transfer through B (by setting the route explicitly, or using local routing somehow), B will do what's supposed to in this case: receive the transfer, even process/store it, but won't proceed with the protocol, therefore making the only way out for the sender to wait for the transfer to expire and then send `LockExpired`, canceling the failed transfer attempt.

To avoid the locked transfer, the LC publishes the `noMediate` capability, so partners can know they shouldn't bother trying to mediate, independently of PFS mechanisms. Of course, this capability is currently honored only by other LCs, which will fail early as a protocol optimization.

So, IMO, this is a non-issue, and the LC behaves per protocol.

**Comment by christianbrb** [comment]
> This does not happen. As B has mediation disabled (by default), it doesn't send PFSFeeUpdate messages to the path_finding global room, which is needed to be eligible by PFS for a route.

@andrevmatos That's clever, thanks :)

@dominik1999 Please see André's answer above. I am closing the issue.

CC @GataKamsky
