### ISSUE TITLE
Expose transfer secret on SDK

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1708]
## Description

The [Raiden API for payments](https://raiden-network.readthedocs.io/en/latest/rest_api.html) (be aware that SDK calls payments transfers) defines the output format with the `secret` property. This property is simply not exposed by the `RaidenTransfer` object at the SDK. Therefor the `cli` can not access.

## Acceptance criteria
- `RaidenTransfer`  has the `secret` property
- the `cli` adopts to access this value on transfer to payment formatting

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@weilbith Is this needed for the train demo?

**Comment by weilbith** [comment]
I don't think so.
This would mean that the user has the need parse the `secret` property of the returned objects to do something with in. For the moment it is simply empty.
^--- @eorituz ?

**Comment by eorituz** [comment]
Nope, I do not need the secret.
I can't really think of a scenario where someone who uses the cli will actually need the secret.
So I don't think we should put too much effort into it at all.

**Comment by weilbith** [comment]
Yeah. But is should be a small thing to do. I already discussed a quick solution with Andre.

The point is that if you do such decisions already now, you will never switch the mode to clean all that stuff up. You'll simply continue to do new stuff and always say I'll do this later. So I'm fine that we need to get a first "interpretation" of the API spec ready so you have everything for the demo. But in general I would recommend to slow down afterwards and clean up before we continue. Slow development moves products fast on a long term.
