### ISSUE TITLE
Raiden API

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#173]
## Description

API which mimics the [Raiden API](https://raiden-network.readthedocs.io/en/stable/rest_api.html) to enable an integration test with the scenario player.

## Acceptance criteria
- Offers same API endpoints as Raiden python
- Endpoints take the same parameters as Raiden Python

## Tasks
- [ ] 

## Story Points

**Comment by kelsos** [comment]
This would be a node.js app build on top of the SDK, using something like [Express](https://expressjs.com/)?

**Comment by andrevmatos** [comment]
I think yes, and therefore, it'd be a second app for the SDK, now a node.js daemon providing the functionality over an HTTP REST API. As Raiden API is quite large, we'd need to prioritize which APIs are essential for the scenario player and implement them first.

**Comment by eorituz** [comment]
That is basically the same that I tried to do during my last berlin trip @kelsos, right?
So An node+express app that mimics the raiden API functionality

**Comment by kelsos** [comment]
@eorituz pretty much yes.

**Comment by manuelwedler** [comment]
I created this private repo for the API express app that I am using for the demo train integration: https://github.com/raiden-network/light-client-rest-api
We can move it into the light-client repo once we added TypeScript and the existing functionality exactly mimics the Raiden API.

**Comment by kelsos** [comment]
@manuelwedler I would prefer to keep it as it's own repo and probably add a link on that instead.

**Comment by christianbrb** [comment]
Let's have a meeting with @manuelwedler to split the issue

**Comment by nephix** [comment]
Another option might be https://www.fastify.io which is an express alternative (but the API is very similar) with the goal of being faster and allowing more throughput

**Comment by weilbith** [comment]
Just throw in another biased opinion which framework to use: [KoaJS](https://koajs.com/) is a more modular and light weight version in comparison to Express and was developed by the same team. I developed with both frameworks already and _KoaJS_ was more pleasant to work with. :man_shrugging:

**Comment by weilbith** [comment]
I did a quick comparison for [light-client-rest-apiu](https://github.com/raiden-network/light-client-rest-api) its current state in comparison to the official [Raiden API](https://raiden-network.readthedocs.io/en/stable/rest_api.html). Stroked endpoints are already implemented. Also mark the light client exclusive endpoints. 


### Channels

- _GET_ `/api/(version)/channels`
- _GET_ `/api/(version)/channels/(token\_address`
- _GET_ `/api/(version)/channels/(token\_address)/(partner\_address)`
- ~~_PUT_ `/api/(version)/channels`~~
- ~~_PATCH_ `/api/(version)/channels/(token\_address)/(partner\_address)`~~

### Tokens

- _GET_ `/api/(version)/tokens`
- _GET_ `/api/(version)/tokens/(token\_address)`
- _GET_ `/api/(version)/tokens/(token\_address)/partners`
- _PUT_ `/api/(version)/tokens/(token\_address)`

### Pending Transfers

- _GET_ `/api/(version)/pending\_transfers`
- _GET_ `/api/(version)/pending\_transfers/(token\_address)`
- _GET_ `/api/(version)/pending\_transfers/(token\_address)/(partner\_address)`

### Connections

- _GET_ `/api/(version)/connections`
- _PUT_ `/api/(version)/connections/(token\_address)`
- _DELETE_ `/api/(version)/connections/(token\_address)`

### Payments

- _GET_ `/api/(version)/payments/(token\_address)/(target\_address)`
- ~~_POST_ `/api/(version)/payments/(token\_address)/(target\_address)`~~

### MISC

- _GET_ `/api/(version)/address`
- _GET_ `/api/(version)/version`
- _GET_ `/api/(version)/status`
- _POST_ `/api/(version)/\\_testing/tokens/(token\_address)/mint`

### Light Client API exclusive

- _GET_ `/api/(version)/balance`
- _GET_ `/api/(version)/balance/(token\_address)`

**Comment by christianbrb** [comment]
@weilbith Thanks for your valuable PR description (https://github.com/raiden-network/light-client/pull/1636) :)

For prioritization of the endpoints: 
1. Did you already get in contact with @eorituz to get his requirements? These endpoints should have 1st priority
2. We should also work out the first scenario to find out which endpoints we would need for that (examples see [here](https://github.com/raiden-network/light-client/pull/1636)) - related issue -> #1412 - These endpoints should have 2nd priority

**Comment by weilbith** [comment]
> Did you already get in contact with @eorituz to get his requirements? These endpoints should have 1st priority

Well, from his messages I would assume he needs everything that Manuel his implementation provides, plus being able to doing payments. But if I remember correctly does Manuel his implementation provide endpoints the Raiden API does not provide (e.g. balance). @eorituz could you provide us with a specific list of requirements you have for your project?

**Comment by eorituz** [comment]
@weilbith @christianbrb  I think there is a bit of a misunderstanding:
Manuel's code is outdated and replaced by the raiden-cli, isn't it?
At least I am using and referring to the [raiden-cli ](https://github.com/raiden-network/light-client/tree/master/raiden-cli).

The CLI works perfectly fine, lightning-fast and provides almost every needed endpoint. It only misses the `GET .../api/(version)/:token/:address`. 
This is currently a blocker for the demo train, as I need this endpoint to verify that a certain payment has been sent.

**Comment by christianbrb** [comment]
@eorituz Thanks for your feedback :)

@weilbith Is Oli still able to use the raiden-cli as he is doing it right now after you have implemented #1636 ?

**Comment by weilbith** [comment]
No. The missing endpoints are `/payments/:token/:target` (`POST`) and `/config`. They are both currently implemented, but not within the new PR. The rest is available.

**Comment by weilbith** [comment]
I created the second follow up issue #1692 that complements #1646. Therefore this issue here should be good to become closed.
