### ISSUE TITLE
Add link to imprint and privacy policy

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#174]
## Description

Add a link to the [imprint and privacy policy ](https://raiden.network/privacy.html )to the dApp

## Acceptance criteria
- The link is called "Privacy Policy, Disclaimer & Imprint"
- It needs to be accessible from every page
- We add it to the app component
- We add it at the bottom of the screen

## Tasks
- [x] Design
- [x] Implementation

**Comment by kelsos** [comment]
@christianbrb there is either one or two places at most where we have to add it for it to be available all across the dApp.
