### ISSUE TITLE
Extend the integration testing

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1750]
### Problem
As the scenario player will not be available for the Light Client soon, we have decided to do more thorough testing on our own (#1691).
 
### Potential Solution
As a first step into that direction I would propose to extend our [integration tests](https://github.com/raiden-network/light-client/blob/master/raiden-ts/tests/integration/integration.spec.ts).

@kelsos Do you see possibilities to extend the load and complexity of the network within the integration tests?

### Remark
We would still need to find a way to simulate the network latency which has led to a lot of synchronization errors within the Raiden Python client. Maybe something like [ToxiProxy](https://github.com/Shopify/toxiproxy) could do the job.

**Comment by kelsos** [comment]
I am not sure about the complexity since the integration image is already big and I am not sure how it would help to add for example more instances of Raiden in the image. But we could potentially include ToxiProxy directly in the tests in between the transport.

**Comment by christianbrb** [comment]
The scenario player is working :) Closing the issue
