### ISSUE TITLE
Invalid error message on open channel

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1756]
## Steps to Reproduce
1. Connect to hub
2. Open Channel
3. Reject MetaMask pop-up

## Expected Result
- A meaningful error message is shown

## Actual Result
![grafik](https://user-images.githubusercontent.com/35398162/85272578-a2e3bd80-b47c-11ea-8b47-b70d4c939877.png)

**Comment by andrevmatos** [comment]
Logs?
