### ISSUE TITLE
Channel disappeared before being settled

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1757]
## Steps to Reproduce
1. Close a channel on https://lightclient.raiden.network/staging/ with 0x1F916ab5cf1B30B22f24Ebf435f53Ee665344Acf (Goerli)

## Expected Result
- After a while the channels becomes settleable

## Actual Result
- The channel disappeared
   ![grafik](https://user-images.githubusercontent.com/35398162/85272032-e984e800-b47b-11ea-8a13-1177ed2555df.png)

## Additional Infos (Optional) 

[raiden_2020-06-22T09 31 22.380Z.log.txt](https://github.com/raiden-network/light-client/files/4812498/raiden_2020-06-22T09.31.22.380Z.log.txt)

**Comment by andrevmatos** [comment]
Partner/hub settled the channel.

**Comment by christianbrb** [comment]
@andrevmatos Cool, thanks for taking a look into it.
