### ISSUE TITLE
Some UI irregularities

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1758]
## Steps to Reproduce
1. Connect to the app
2. 

## Expected Result
- 

## Actual Result
- 

![connect_screen](https://user-images.githubusercontent.com/15123108/85278523-b144d000-b4a2-11ea-937f-b71e5e1abc9a.png)

![connect_token](https://user-images.githubusercontent.com/15123108/85278541-b9047480-b4a2-11ea-9efb-5bf5b23c944b.png)

![token_select](https://user-images.githubusercontent.com/15123108/85278565-befa5580-b4a2-11ea-92ba-f0b4cd8fbcbf.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by kelsos** [comment]
Will be fixed when #1648 is merged, was broken but the last major vuetify upgrade
