### ISSUE TITLE
Error handling during opening a channel

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1761]
## Steps to Reproduce
1. Connect to the app
2. Open a channel 

## Expected Result
- User should be informed that his transaction has failed and what are the next steps that he can take to complete the transaction or file a bug report 

## Actual Result
- 
While opening a channel the deposit failed with the following error
`MetaMask - RPC Error: gas required exceeds allowance (11958817) or always failing transaction`
`type: "channel/deposit/failure", payload: {…}, meta: {…}, error: true`

https://imgur.com/HgC7zfn.png

https://imgur.com/rR63Dqg.png

While deposit has failed in the background the user gets the message that
```
Transferring tokens to the network and deposit into the channel

Please do not close the browser and confirm two (2) transactions with MetaMask.
```

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by andrevmatos** [comment]
I'm not sure we should fail the whole thing. Open Channel tx did succeed, and it'd get confirmed and resolve the dialog soon. The deposit failed, but this doesn't mean the open transaction failed. The user would see the channel opened but with zero balance there. Maybe we should have the deposit failed as a notification.

**Comment by agatsoh** [comment]
@andrevmatos you are right we dont need to fail the whole transaction just that we need to give the user a proper message that `channel has opened but the deposit has failed and please go to this place to deposit in the channel`.
