### ISSUE TITLE
Identicon click gives error subsequently cannot download logs

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1762]
## Steps to Reproduce
1. connect to the app
2. click on the identicon

## Expected Result
- 

## Actual Result
- 
`TypeError: Cannot read property 'length' of undefined`

![indenticon_click_bug](https://user-images.githubusercontent.com/15123108/85296257-be6fb800-b4be-11ea-98ac-bd0c22e5f84a.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by kelsos** [comment]
@agatsoh Can you provide more information on what exactly you did? This error I remember doing a fix somewhere but it might just be on the PR I am currently working on.

**Comment by christianbrb** [comment]
@agatsoh Should be fixed. Could you retest?

**Comment by kelsos** [comment]
@agatsoh confirmed that this is not an issue anymore so I am closing.
