### ISSUE TITLE
Update UDC deposit dialog for testnet

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#1769]
## User Story
As Chris I want to mint and deposit the testnet utility token in the UDC screen. Split from issue #587 

## Acceptance criteria
- Dialog should display the standard input field for amount
- Dialog should mint and deposit 10 testnet utility tokens by default

## Tasks
- [ ] Needs mockup
- [ ] In-iteration design

**Comment by christianbrb** [comment]
After @taleldayekh's [comment](https://github.com/raiden-network/light-client/issues/587#issuecomment-648101164), I would add here
- The dialog should show a warning if the amount of available tokens is lower than the entered amount (see eg. transfer amount input field)

**Comment by christianbrb** [comment]
I wouldn't show the `Available ETH to pay for on-chain transaction`
It's within the responsibility of MetaMask and I don't know any way how much I have to pay. We also don't show it as other places where on-chain operations are getting triggered.

**Comment by andrevmatos** [comment]
> I wouldn't show the `Available ETH to pay for on-chain transaction`
> It's within the responsibility of MetaMask and I don't know any way how much I have to pay. We also don't show it as other places where on-chain operations are getting triggered.

Maybe it'd be worth to be kept only for on-chain txs to be sent from the subkey?

**Comment by taleldayekh** [comment]
@raiden-network/light-client 

![mainnet-deposit](https://user-images.githubusercontent.com/43838780/87922557-72dc0a00-ca7c-11ea-949b-02e1bf9b22dc.jpg)

**Comment by taleldayekh** [comment]
This one should be pretty straight forward. @raiden-network/light-client 
<img width="554" alt="Screenshot 2020-07-20 at 13 21 09" src="https://user-images.githubusercontent.com/43838780/87932528-f6512780-ca8b-11ea-8400-7633654c74aa.png">
