### ISSUE TITLE
On open channel spinner my fan is going crazy

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1773]
## Steps to Reproduce
1. Navigate to https://lightclient.raiden.network/staging/
2. Select a hub
3. Enter deposit
4. Click on "Open Channel"

## Expected Result
- My computer stays silent
- I see the Horizontal Progress Bar instead of the Spinner
- No block information (see #1798) 

## Actual Result
- My fan is running and GPU is at ~95%

![grafik](https://user-images.githubusercontent.com/35398162/85414339-4364db00-b56c-11ea-908c-be184a802847.png)

![grafik](https://user-images.githubusercontent.com/35398162/85414297-347e2880-b56c-11ea-8e68-4ffe7f1e8579.png)

- Maybe the spinner (Vue-Component?) is killing the GPU?

## Additional Infos (Optional) 
```
- Firefox
```

**Comment by nephix** [comment]
Definitely a thing :) #1434

**Comment by christianbrb** [comment]
Hey @nephix! Nice to see you being around ☘️

**Comment by kelsos** [comment]
Assuming that this is caused by the animation indeed, I don't see how we could fix it other than removing the progress spinner.

**Comment by christianbrb** [comment]
Would be fine for me to either delete or replace it.

**Comment by kelsos** [comment]
My experience so far is that animations of any kind will not perform properly on the web, depending on the combination of hardware and software. You can see a couple of people opening similar issues in Vuetify's repo. 

Deleting it would not make sense. we still have to show something to the user when they are waiting. But if we go with animated content there is an absolute certainty that they won't work properly everywhere.

One idea would be to use some kind of animated image with transparency instead. But rasterized animated content with transparency can be tricky to get right.

**Comment by christianbrb** [comment]
We could show the following

`Waiting for the transactions to be confirmed - Block Number: ####`

The Block Number would increment and would show the user that something is happening.

In the future we could do something like we did for the transactions.

**Comment by christianbrb** [comment]
As a quickfix we could use the bar, which we have on the transfer in progress modal
(I wasn't quick enough taking a screenshot)

![grafik](https://user-images.githubusercontent.com/35398162/85584635-99ef1980-b63f-11ea-98d2-259b7fdcf859.png)
