### ISSUE TITLE
Reenable Continuous Deployment of the dApp to github pages

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#178]
## Description
Reenable hosting of the dApp to github pages

## Acceptance criteria
- Privacy policy is there #174 
- We need a domain name (Proposal: demo, light-client, light, demo-light-client)
- It has got a CNAME

## Tasks
- [x] Comms for the domain name @franzihei 
- [ ] Get the domain

**Comment by franzihei** [comment]
As long as we haven't properly branded (found a name for) the dApp, I'd go for a domain like: 
`dapp.raiden.network` or `lightclient.raiden.network`.

Generally, the shorter and the more self-explanatory, the better.
