### ISSUE TITLE
Pop-up modal its background not blurry in Firefox

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1781]
## Steps to Reproduce
1. Open dApp in Firefox web-browser
2. Do an action like mint SVT/tokens, a transfer, .. to get a pop-up modal

## Expected Result
- blurry background as for example in Chromium

## Actual Result
- clear background with all details

## Additional Infos (Optional) 
```
- Browser & version: Mozilla Firefox 77.0.1
```

**Comment by kelsos** [comment]
At least up to a point the blur filter was not supported by default in Firefox, and it was only behind a flag that you had to explicitly enable. https://www.reddit.com/r/FirefoxCSS/comments/d7bfmt/is_this_blur_possible_in_firefox/

**Comment by weilbith** [comment]
![screenshot_1592985002](https://user-images.githubusercontent.com/12543647/85518200-48736a00-b600-11ea-9a63-ec606b14319f.png)

**Comment by weilbith** [comment]
Okay so not solvable for now?

**Comment by kelsos** [comment]
On 78b9 Firefox developer edition the flag is still disabled by default

![image](https://user-images.githubusercontent.com/2269732/85518538-9f793f00-b600-11ea-80e7-4e148cc96abe.png)

I would guess yes, unsolvable until Firefox enables the flag for blur by default.

**Comment by weilbith** [comment]
Okay. So how do you proceed with such issues that become relevant later again?

**Comment by christianbrb** [comment]
There are places in the dApp where it is blurry in Firefox

**Comment by christianbrb** [comment]
For example on the token withdrawal screen

![grafik](https://user-images.githubusercontent.com/35398162/85523632-89bb4800-b607-11ea-863e-b62e1d766687.png)

**Comment by kelsos** [comment]
@christianbrb it didn't look blurry to me.

 I am not sure if achieving the same effect as the backdrop-filter is possible or easy. There are other blur filters but they apply on the elements itself, not on the parent elements. I would say it does not make sense for me to try to work around a browser limitation at this point.

**Comment by christianbrb** [comment]
Deposit is also blurry in Firefox

I have withdrawn all my tokens :P

![grafik](https://user-images.githubusercontent.com/35398162/85524220-41505a00-b608-11ea-8e47-68750b8cbebd.png)

**Comment by kelsos** [comment]
Ok this is probably using the overlay instead of the backdrop and applies the blur filter on the overlay.

**Comment by weilbith** [comment]
So this are different components? :thinking:

**Comment by kelsos** [comment]
The dialogs should be based on the same component, but they might have some different flag/property. At some point we tried to apply the blur only to the card itself but that didn't really work due to the layout.

**Comment by christianbrb** [comment]
My tests have been executed with `layout.css.backdrop-filter.enabled = true`
