### ISSUE TITLE
Channel Opening not succesfull - event not returned by MetaMask

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1787]
## Steps to Reproduce
1. Open a channel 
2. Select a hub

## Expected Result
- Light client should Open a channel along with deposit

## Actual Result
- The channel opening is successful but deposit is not successful
- The light client also does not show the channel which has been opened, this is 
valid both when channel is opened from and to the light client.
- There are no errors on the console.

[raiden_2020-06-24T12_02_33.749Z.log](https://github.com/raiden-network/light-client/files/4825229/raiden_2020-06-24T12_02_33.749Z.log)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by christianbrb** [comment]
Reloading ChannelOpen from the TokenNetwork could be a solution.
