### ISSUE TITLE
Investigate the resilience of epic on web3 provider errors

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1790]
## Description

While there should not be many places where that happens, we have to ensure that there is no possibility of specific epics completing when a web3 error happens during contract interaction.

There is at least one instance of the UDC withdrawal code where this might happen.

If the issue should be retried we should ensure that we do that, and recover so that the epics keep working normally.

If the issue is not recoverable a shutdown should happen.

## Acceptance criteria
- All inner and outer observables handle the web3 smart contract errors 
- The user is getting informed if it is not recoverable in a dialogue

## Tasks
- [ ] Write down the tasks (every epic or topic - eg. channels)

**Comment by christianbrb** [comment]
Proposal: Disconnect from Wifi and check when the SDK is crashing
