### ISSUE TITLE
Configuring just a list of networks per network in the dApp

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1791]
## Description
Currently monitoring all token networks in one network puts a lot of load on the RPC client especially on Goerli.

- There is a list of pre-monitored tokens per testnet
- If a user selects a new token network it gets monitored (as discussed in the retro)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
So, I'm working on a rewrite of the channel events fetching code. This should make event fetching more reliable, as well as include ChannelOpened events on the events scanned every session startup. But it'll still depend on `monitorToken` calls.
I'd say we should go with calling `raiden.monitorToken` explicitly every time the user clicks on a new token network to connect (even before actually trying to open the channel). This method is cached.
Also, for the 'pre-monitored' token list, we can either explicitly call this method from the dApp on a couple of token networks of interest on first/every startup (to do it on dApp's side), or meddle with `makeInitialState` to create a pre-populated list of `tokens` on `state` (but it may require hardcoding not only the `token` address,  but also the respective `tokenNetwork`).

**Comment by christianbrb** [comment]
@andrevmatos Thanks for the update :)

Pre-populated list would be nice, but we should make it configurable per network and not hardcoded.

**Comment by andrevmatos** [comment]
Oh, and a small hint: it should be safe and actually better to call and await `raiden.monitorToken` before `raiden.start`. This way, you ensure the `state.tokens` mapping is populated before the epics are subscribed, which ensures it doesn't do the initial scanning if you already populated the mapping with the tokens of interest.

**Comment by andrevmatos** [comment]
I don't think a new screen is needed, it adds another detail for the user to know about and keep in mind. I'm keeping the initial token scan anyway, so I'd say just ensuring we monitor early for tokens the user clicks would be enough. I'd consider this an implementation detail.
