### ISSUE TITLE
MetaMask pop-up does not pop-up

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1804]
## Steps to Reproduce
1. Click on Connect

## Expected Result
- The MetaMask pop-up pops up

## Actual Result
- The MetaMask fox in the toolbar just gets a little 1
![grafik](https://user-images.githubusercontent.com/35398162/85693485-9490de00-b6d6-11ea-976f-4f517f1a71b9.png)

## Additional Infos (Optional) 
```
- Firefox 77.0.1 
- MetaMask 7.7.9
```
It has started happening in the last few weeks.

**Comment by kelsos** [comment]
I have also accidentally done that in the past and returned to normal but I don't remember how exactly. This is something with metamask itself and has nothing to do with the dApp itself though. It is some metamask option or behavior

**Comment by christianbrb** [comment]
@kelsos Thanks for looking into the issue :)

I have looked everywhere:
- MetaMask and Firefox preferences.
- MetaMask support site
- Googled

I have allowed pop-ups.
I have deleted my cache.

Nothing works :(

**Comment by kelsos** [comment]
It is not an active setting, more of a behavior. This has happened to me quite a few times and then it goes back to normal. Check for any forgotten popu that might have been behind some window. I think that sometimes that was the cause.

**Comment by christianbrb** [comment]
Works fine now after a computer restart

**Comment by kelsos** [comment]
Yes, that has been my experience so far, this is usually temporary and it is resolved afterward.
