### ISSUE TITLE
Create example data for LockedTransfer for spec

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#182]
## Description

Create example data for LockedTransfer message for the spec

## Acceptance criteria
- Having predefined inputs
- Having predefined outputs
- Show step by step how the message is formed
- The explanation for each step is there

## Tasks
- [ ]

**Comment by kelsos** [comment]
Here you can find an initial draft https://gist.github.com/kelsos/652ab38929166aa0dbb3910c22ec8431

**Comment by christianbrb** [comment]
Follow up issue #195 195
