### ISSUE TITLE
channelWithBiggestCapacity is undefined and channel is shown in closed status

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1825]
## Steps to Reproduce
1. Close the last channel in a token network
2. Go to the transfer screen on staging
3. Enter an amount to deposit

## Expected Result
- Deposit works

see comment from @kelsos 
> This a miss on the implementation of the getter. We need to fix it. It will only happen when you have a single closed channel in a Token.

## Actual Result
- The following error is shown `this.channelWithBiggestCapacity(...) is undefined`
- Channel is shown as closed

![grafik](https://user-images.githubusercontent.com/35398162/86002739-0d62a380-ba11-11ea-9683-1b9af17455bf.png)

![grafik](https://user-images.githubusercontent.com/35398162/86002868-413dc900-ba11-11ea-8f5e-2bf102a48c4f.png)

## Additional Infos (Optional) 

[2020_06_29_logs.txt](https://github.com/raiden-network/light-client/files/4845343/2020_06_29_logs.txt)

**Comment by christianbrb** [comment]
Now it's gone:

![grafik](https://user-images.githubusercontent.com/35398162/86101744-fc6e6c80-baba-11ea-9c12-aa2f849d7016.png)

**Comment by andrevmatos** [comment]
@christianbrb So you were on the Transfer screen, but the channel you had was `closed`. Eventually it got settled by the HUB. It's expected. The problem here is you didn't get the transfer controls disabled for not having `open` channels with capacity. I thought we had an issue about this already.

**Comment by kelsos** [comment]
This a miss on the implementation of the getter. We need to fix it. It will only happen when you have a single closed channel in a Token.

**Comment by christianbrb** [comment]
Maybe this is not an issue anymore after #1930 and #2031 are implemented.
