### ISSUE TITLE
SDK should autmatically check node availability for mediated transfers

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1835]
## Description

The CLI struggles to do a mediated transfers because the SDK always returns that the target node is offline. This is actually incorrect and means that the SDK does not know the presence state of the target, since it only monitors the presence of channel partners. The dApp does therefore a manual presence check to fix that issue. But this is not intuitive, the error leads to wasted hours of investigation and everyone new to use the transfer function will run into this issue. Therefore the SDK itself should check if the targets presence is already monitored, else doing so by itself. The latter case will by slightly slower, while the first case is as fast as usual. After all the SDK will become more easy to use.

**Note:** This is kinda urgent for the train demonstration project using the CLI.

## Acceptance criteria
- SDK can to a mediated transfer to a target which presence is not yet monitored without an error message

## Tasks
- [x] @andrevmatos creates the design for the enhancement
- [ ] @weilbith implementation
   - [ ] adopt SDK 
   - [ ] remove now useless/time wasting presence call in the dApp

**Comment by weilbith** [comment]
@eorituz here

**Comment by eorituz** [comment]
My error logs:

**Comment by weilbith** [comment]
> Direct transfers from the sender as well as direct transfers to the receiver work perfectly fine.

That's what I did for the manual tests. But no mediated stuff. :see_no_evil:
