### ISSUE TITLE
Investigate why upload coverage sometimes gets stuck for sdk e2e or unit test jobs

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1837]
## Description
The coverage upload step seems to get stuck for two minutes and then exit without any output.

When this happens the only a part of the SDK coverage is reported so the reported coverage is less than what is expected, which makes the PR non-mergeable.

The step exits with 0 status so the CI passes properly but since the coverage is decreased it stops the PR from being merged. 

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
Does not seem to be an issue anymore.
