### ISSUE TITLE
dApp on mobile has got a few issues

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1838]
## Steps to Reproduce
1. Enter the Status Mobile App
2. Use the dApp

## Expected Result
- I am able to read everything 
- Everything looks ok
- I am able to press every button and use the input fields
- Tooltip issue is not included (see #2100) 

## Actual Result
- I have just checked one screen by now

- [x] This has been taken care of.
![0ED4A31D-726F-477D-BA2A-5019B5FB84A1](https://user-images.githubusercontent.com/35398162/86209262-77468e80-bb72-11ea-8492-c84354663a50.jpeg)

## Additional Infos (Optional) 
```
- Status App
- 828 x 1792
```

## Remark
- We'll spent ~1 day

**Comment by christianbrb** [comment]
@agatsoh Could you spend some time and test the dApp on the mobile? Please document any issue in this issue. Thanks :)

**Comment by agatsoh** [comment]
![Screenshot_20200828-155423_MetaMask.jpg](https://user-images.githubusercontent.com/15123108/91551163-608ca000-e947-11ea-8492-2d86d8704827.jpg)


So I was using the metamask app and I don't get the check boxes  to check the conditions of the disclaimer

**Comment by christianbrb** [comment]
@agatsoh Thanks for the update 👍 

Is it scrollable? If not, this should be one of the issues, that you need to fix.

**Comment by taleldayekh** [comment]
<img width="366" alt="Screenshot 2020-08-31 at 13 35 08" src="https://user-images.githubusercontent.com/43838780/91715874-d9316d80-eb8e-11ea-95b9-41cdc2e43f95.png">

**Comment by taleldayekh** [comment]
<img width="427" alt="Screenshot 2020-08-31 at 13 36 14" src="https://user-images.githubusercontent.com/43838780/91715964-fe25e080-eb8e-11ea-9129-9732e8e9443b.png">

**Comment by taleldayekh** [comment]
@agatsoh Besides the disclaimer and the screen @christianbrb posted I found the two above also breaking on mobile. I can go ahead and fix them in a separate PR from yours.
