### ISSUE TITLE
Extract/unify snackbar content and NotificationCard content

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#1902]
The snackbar panel has a `Dismiss` button; the notification panel's card has a close button which instead of dismissing, clears it. If splitting this component into a shared one which would work for both, you'd need to have only one way to do it, possibly with the close button, but then you need to have an event emitted there, instead of hardcoded, because on snackbar, close shouldn't clear the notification from queue, but instead, just hide it.

_Originally posted by @andrevmatos in https://github.com/raiden-network/light-client/pull/1842/files/55ac766fa300958a3642aa66b4b62bef7db6028c_

**Comment by christianbrb** [comment]
I have never managed to take a screenshot, but we should also 
- [ ] Fix the placement of the notification panel
- [ ] Exchange the green color with the turquoise color

**Comment by christianbrb** [comment]
@taleldayekh What about using the snack bar as proposed by @sashseurat 

The user would need to navigate to the navigation panel to see the details. This would be cleaner from my perspective.

**Comment by christianbrb** [comment]
@taleldayekh Are you coviring this within #2112?

**Comment by taleldayekh** [comment]
Not sure what this issue is about. But the notification snackbar now looks like this:
![noti](https://user-images.githubusercontent.com/43838780/91562392-6da49180-e93d-11ea-9054-dc3e9d355bb0.png)

**Comment by taleldayekh** [comment]
It used to be overloaded with information that is impossible to grasp within the 5000 milliseconds the card is displayed. The title is all we need and then the user can access the notification panel for more information.

**Comment by taleldayekh** [comment]
The snackbar had:
* Title
* Very long description
* Icon
* Badge
* Dismiss button

**Comment by kelsos** [comment]
> Not sure what this issue is about. But the notification snack bar now looks like this:
> ![noti](https://user-images.githubusercontent.com/43838780/91562392-6da49180-e93d-11ea-9054-dc3e9d355bb0.png)

This was about using the same component in the notifications and snackbar since initially they had the same content but duplicated.

If the new approach now is to simplify the snackbar content then this issue doesn't make sense anymore, because they have different content so you should be able to close it.

**Comment by christianbrb** [comment]
Ok, thanks :) Closing this issue.
