### ISSUE TITLE
Transfer History, Transfer title and token box changes and alignment

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#1925]
## Description
Next step for the transfer screen redesign

## Acceptance criteria
- [x] The title `Transfer` color is white
- [x] The title `Transfer History` is changed to `History`
- [x] The title `History` color is white
- [x] A grey box around the history area is added to finish the overall look and alignment
- [x] The grey box background color for all boxes is set to `#1E1E1E` (same as eg. deposit dialogue) 
- [x] The font-weight of the token amount display is set to `300`
- [x] The font-size of the token amount display is set to '50px' - I am not 100% sure, if this isn't too big
- [ ] ~~The font-size of the token name is set to '12px' - This is one less than the proposed 13px~~
- [ ] ~~The three dots (menu) have got a smaller weight.~~
- [x] The border (space) within the token card is aligned with the design and consistent
- [x] The line below Change Token goes more to the left (see design)
   ![grafik](https://user-images.githubusercontent.com/35398162/88902079-ff8f8080-d251-11ea-86cb-aed9fa2c84da.png)

## Design
From: 
https://www.figma.com/proto/3UX5wudtGolsdh5QVyuoTS/LC-Header?node-id=1%3A3&scaling=min-zoom

![grafik](https://user-images.githubusercontent.com/35398162/88905730-e1784f00-d256-11ea-8e2a-763f0777167d.png)

**Comment by christianbrb** [comment]
@taleldayekh I have compared the design within figma with the current implemented design in the dApp. I have extended the acceptance criterias to include the token "card".

**Comment by taleldayekh** [comment]
> * The line below Change Token goes more to the left (see design)

@christianbrb They are equal, it is just the arrow icon that makes it appear as if it goes more to the left. If you look in the WebUI you'll find the same phenomena.

**Comment by taleldayekh** [comment]
> * The three dots (menu) have got a smaller weight.

This is not possible. The icons can only be set to either small, large, or x-large. The weight can not be adjusted. The only workaround would be to not use the material design icons and create our own. I don't think that it is worth the effort just to make the dots slightly thinner, they are designed like this by default and in my opinion, they look good.

**Comment by christianbrb** [comment]
@taleldayekh Ok, we shouldn't create our own.

**Comment by taleldayekh** [comment]
> * The font-size of the token name is set to '12px' - This is one less than the proposed 13px

@christianbrb I remember in earlier conversations you not wanting the token name to be displayed at all? I removed it, let me know if this is what you want.

**Comment by christianbrb** [comment]
@taleldayekh That's even better, thanks :)

**Comment by taleldayekh** [comment]
> * The border (space) within the token card is aligned with the design and consistent

@christianbrb Not sure what you are referring to here?
