### ISSUE TITLE
RaidenError: Could not find a user with a valid signature(Matrix failure action)

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#1940]
## Steps to Reproduce
1. Open a channel on mainnet
2. Transfer to a user

## Expected Result
- The target is online and should be detected properly.

## Actual Result
- 
```
{
  "type": "matrix/presence/failure",
  "payload": {
    "details": {
      "address": "0xF128A427DeFf3a4f792373f4BE38bEecD07d4ffE"
    },
    "name": "RaidenError"
  },
  "meta": {
    "address": "0xF128A427DeFf3a4f792373f4BE38bEecD07d4ffE"
  },
  "error": true
}
```

![light_client_matrix_presence_failure](https://user-images.githubusercontent.com/15123108/88264557-93f56280-cce9-11ea-885b-31038994402b.png)

![light_client_target_is_offline](https://user-images.githubusercontent.com/15123108/88264840-18e07c00-ccea-11ea-95fd-3a81845a477f.png)

logs:
[raiden_0x14efA2b271969A46A094A23e0d49E32C1B617f89_2020-07-23T08_02_32.109Z.log](https://github.com/raiden-network/light-client/files/4964576/raiden_0x14efA2b271969A46A094A23e0d49E32C1B617f89_2020-07-23T08_02_32.109Z.log)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by christianbrb** [comment]
@agatsoh Could you check to which server the clients have been connected to?

**Comment by agatsoh** [comment]
I understand the problem now the light client was connecting with a goerli matrix server 
```
https://transport.transport02.raiden.network
```
I used to start the light client like this 
```
pnpm run serve --filter raiden-dapp -- --mode mainnet
```
it used to work but seems like it doesnt work anymore.

**Comment by agatsoh** [comment]
This was due to one environment variable not being set hence closing.
