### ISSUE TITLE
Move spec to Raiden repo and integrate

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#195]
## Description

Move current [spec draft of LockedTransfer](https://gist.github.com/kelsos/652ab38929166aa0dbb3910c22ec8431) to Raiden spec and integrate with rewriting from @Dominik1999 

## Acceptance criteria
- A PR in the spec repo is created
- Draft is reviewed and rewritten by @Dominik1999 
- Abbreviations are there with a link

## Tasks
- [ ]

**Comment by kelsos** [comment]
This was integrated to the raiden spec https://github.com/raiden-network/spec/pull/242
