### ISSUE TITLE
Capability parsing is trying to handle quote marks using regex

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#1975]
https://github.com/raiden-network/light-client/blob/126f898409667c437c952a01a40713aad735ceb6/raiden-ts/src/transport/utils.ts#L58-L59

regular expressions can not properly handle balanced characters. This should be replaced with a parser that properly handles balanced quote marks.

Two other alternatives are just removing the feature altogether or using a negative lookbehind to ignore escaped commas `(?<!\\),`

Edit: The value parsing is also not handling edge cases properly:

- white space is not handled consistently:
  - All the prefix white space is ignored for the keys `\s*`, however no post-fix white space is ignored because `([^=]+)` is greedy
  - Values don't ignore either prefix nor post-fix white spaces inside quotes
  - Values allow for exactly one-or-zero white space as a prefix before the quotes, while keys allow for zero-or-more, and values ignore all white space after the quotes
- the value part of the regex is using the non-greedy operator `(.*?)` but at the same time it anchors the match at the end of the string `"?\s*)?$`, this just makes the regex more complicates the regex.

My suggestion here is to simply split by the first escaped equal sign which is not escaped.

Perhaps it would make sense to just use json for this data?

Edit2: The regex above is not handling escaping of the `\` character properly, it was just a suggestion, if this is implemented that should be taken care of.

**Comment by andrevmatos** [comment]
Good call. I just wanted a less wasteful way to encode these small flat JSON mappings. Right now, we only use the `true` usecase, but I'd like to have these `key=value`, with quotes, commas and escape sequences properly supported, since I can foresee some more advanced usages for the functionality in the near future (after LC's mainnet). Thank you very much for raising attention to this.

**Comment by andrevmatos** [comment]
> Perhaps it would make sense to just use json for this data?

JSON are too wasteful, our space here is limited. The leading and trailing `{}`, keys requiring double quotes... and our values default to strings (with use-case further parsing, if needed) or even to `true` if present without value. Maybe JSON5 with implicit `{}` would be a compromise, but maybe we can find some proper way to do this with regexes or some small library.
