### ISSUE TITLE
fetchSortedMatrixServers$ has a hand rolled parser for YAML

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#1976]
Just like the python client (https://github.com/raiden-network/raiden/issues/6424) the light client has a hand rolled parser:

https://github.com/raiden-network/light-client/blob/5b3bfb9b26f9f090f787d321b4b1214dfaa2dde7/raiden-ts/src/transport/epics/init.ts#L154-L164

The fix should be synchronized among both implementations.

**Comment by palango** [comment]
After the synapse update this information is now json encoded: https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers-production-v1.2.0.json

```json
{
    "active_servers": [
        "transport.mainnet.raiden.anyblock.tools"
    ],
    "all_servers": [
        "transport.mainnet.raiden.anyblock.tools",
        "transport.raiden.dappnode.io",
        "transport.raiden.badgateway.tech",
        "transport.raiden.overdoze.se"
    ]
}
```

@christianbrb Do we need to update some environment for those changes?
