### ISSUE TITLE
Add minting/wrapping and faucet links on testnets

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#198]
## Description

It would be easier for people that want to test the dAPP to have easy access to a faucet (via a link) and to a mint/wrap function to create tokens for TTT (goerli) and W-ETH (rinkeby, ropsten).

(re-evaluate if the tokens are stll the same in other networks)

## Acceptance criteria
- Faucet icon button
- Mint icon button 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Removing from product backlog in favor of #638 -> implementing it later

**Comment by christianbrb** [comment]
Minting is now available for tokens. Closing

**Comment by kelsos** [comment]
We still don't have any links to faucets though :smiley:
