### ISSUE TITLE
Look at replacing "getAccount", and "getMainAccount" in raiden-service.ts with getters

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#1983]
## Description
In discussions with @weilbith, it was proposed to replace these two async functions in ```raiden-service.ts``` with getters since they are only returning addresses.

```
  async getAccount(): Promise<string> {
    return this.raiden.address;
  }

  async getMainAccount(): Promise<string | undefined> {
    return this.raiden.mainAddress;
  }
``` 

## Tasks
- [ ] Investigate whether this is possible and why they are async in the first place.

**Comment by weilbith** [comment]
In first place they should not be asynchronous. At least there is no reason as far as I can see. The `RaidenService` is basically just forwarding the getters of the SDK. They are not asynchronous. So we don't need to be as well. And if we already need to forward that stuff we should also use getters. The names do already show that these are actual getters. Take advantage of what the languages gives you.
After all these two changes should simply the code everywhere where used.

**Comment by taleldayekh** [comment]
Closing, has been fixed already.
