### ISSUE TITLE
dApp title is not actually centered

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#1984]
## Steps to Reproduce
1. Open the dApp

## Expected Result
- Title is centered in all cases
     - Back button is shown / not shown
     - Account button is shown / not shown
     - Notification icon is shown / not shown
- Content is disabled (column stays)

## Actual Result
- ![grafik](https://user-images.githubusercontent.com/35398162/88921475-e648fd00-d26e-11ea-8dae-546fd7c62fec.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by weilbith** [comment]
I suppose this is somewhat about Vuetify its grid system and how we use columns

**Comment by christianbrb** [comment]
Also do #1717

**Comment by christianbrb** [comment]
As Thore is on vacation, we are just going to center it without the refactoring proposed by him.
