### ISSUE TITLE
Investigate compatibility of matrix signing with Ledger Wallet

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#200]
## Description
![image](https://user-images.githubusercontent.com/2269732/60352300-cf7b0b80-99c7-11e9-9d83-9c04e4e6ca94.png)

Matrix login fails with a 403 after signing the matrix messages using a Ledger Wallet connected to Metamask.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
@andrevmatos tested with Trezor hard wallet which worked, reopen if this is an issue big enough that requires our attention.
