### ISSUE TITLE
Channel events are not properly ordered when multiple occur in the same block

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2004]
The sortBy is only taking the `blockNumber` into account:

https://github.com/raiden-network/light-client/blob/72d575fb5d5e2c801e55f3c4f27c4f14f4d54932/raiden-ts/src/channels/epics.ts#L475-L484

This is a bug, since it is possible for two transactions to be mined in the same block for the same channel. In practice this will be unlikely, but not impossible, this will be more of an issue for testing, it can result in hard to debug flakiness. I have not considered which kind of failures, if any, could happen because of this, however, since that is spotted I'd recommend removing the possibility of an error happening to begin with.

My suggestion is to *not* fetch events out-of-order to begin with. Instead fetch all the events in a single query.

**Comment by andrevmatos** [comment]
Thank you for this. Indeed this can get events out of order if they happen in the same block. I don't want though to fetch all events, specially on past/historical data, as we expect a very sizeable response on mainnet, so being strict on server-side filter, even if it means more requests, as these are one-shot-per-session requests, is desirable for us. I'll therefore implement including the `transactionIndex` in the sorting criteria.
