### ISSUE TITLE
Off-by-one event filtering in channelEventsEpic

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2007]
https://github.com/raiden-network/light-client/blob/72d575fb5d5e2c801e55f3c4f27c4f14f4d54932/raiden-ts/src/channels/epics.ts#L560-L571

The `+1` is an off-by-one error, it is unlikely but possible for the deploy and call transaction to be mined in the same block. Here is a test to prove this is the case:

https://github.com/raiden-network/raiden/pull/6435/files

Note: This can also happen with two transactions, e.g. a `registerToken` and a `openChannel`. It has happened during testing of the python implementation.

**Comment by andrevmatos** [comment]
How could that be? Don't the contract's `address` get available only after deploy? And one would need the contract's address to interact with the contract? Just to understand how this could happen on real life.
Anyway, we can remove the `+ 1`, the events filtering should be reliable over duplicated events.

**Comment by hackaugusto** [comment]
> How could that be? Don't the contract's address get available only after deploy? And one would need the contract's address to interact with the contract? Just to understand how this could happen on real life.

Please, refer to the test I mentioned above. I wrote it to show that this is possible.
