### ISSUE TITLE
Fix PR hosting script for MacOS with the Docker set-up

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2024]
@talel Could you provide details?

**Comment by weilbith** [comment]
Details: For some reason the `grep` command that is used in the bash script works differently when used on MacOS. The script works fine on Linux. At least from the quickfix session with Talel and me it looked like there is an issue about the argument parameter. 
I just download an image for a virtual machine. There I'll try to reproduce this issue with a minimal setup to verify if this is actually a MacOS issue or a setup issue of Talel his PC.

**Comment by christianbrb** [comment]
Or use the docker set-up

**Comment by weilbith** [comment]
For the active reader: installing MacOS to the virtual machine isn't to easy. Therefore we stop investigating into the issues with MacOS and rather just let Talel use the Docker approach.

**Comment by taleldayekh** [comment]
@andrevmatos Running `docker-compose up` spins up something but when I try to access the URL I get nada.

**Comment by taleldayekh** [comment]
Tried this one again today and now I'm getting `Script error: No artifact found to download`.

**Comment by taleldayekh** [comment]
To clarify my attempt:
1. Navigated to the `serve_pr` dir.
2. Created an CircleCI token and saved it in a `.env` file.
3. Created a `app` dir with the correct permissions.
4. Have docke running on my machine.
5. Executed `docker-compose up`.
6. Only getting `Script error: No artifact found to download`.

**Comment by weilbith** [comment]
Stupid comment, but did you check on CircleCI that there was an Artifact built for the branch you are interested in?
