### ISSUE TITLE
Tooltips cluttering dApp

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2026]
## Description
There are tooltips in multiple locations of the dApp that clutters the interface and keeps popping up on the slightest movement of the mouse.

<img width="1574" alt="Screenshot 2020-08-03 at 14 41 19" src="https://user-images.githubusercontent.com/43838780/89183498-9d0eeb00-d597-11ea-816d-d669a801797d.png">

## Acceptance criteria
- Fewer tooltips that do not disturb

## Tasks
- [x] Go through dApp and decide which tooltips makes sense to keep
- [x] Remove the delay time on tooltips that are kept

**Comment by christianbrb** [comment]
Duplicate of #1926

**Comment by christianbrb** [comment]
I have closed #1926

**Comment by taleldayekh** [comment]
I simply removed the delay time which makes the tooltip disappear as soon as the mouse is not on top of it. I think this is a good solution, we get to keep the tooltips without them being persistent and cluttering the dApp.
