### ISSUE TITLE
Display transaction history per selected token only

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2033]
## Description
It seems like we are displaying a global transaction history for all tokens. I.e. in the screenshot below I can see all transactions made in TTT even when my currently selected token is ZZTop.

<img width="553" alt="Screenshot 2020-08-04 at 13 19 43" src="https://user-images.githubusercontent.com/43838780/89288118-68f9ff80-d655-11ea-9f12-bf0ca0e39f9f.png">

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
This looks like a bug
