### ISSUE TITLE
transferChannelClosedEpic should not be emit transfer failed just because the channel is closed. 

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2036]
The `transferChannelClosedEpic` will emit ` ErrorCodes.XFER_CHANNEL_CLOSED_PREMATURELY` for every transfer initiated by the light client if a channel is closed and the secret has not been revealed yet:

https://github.com/raiden-network/light-client/blob/3b175851df7f2fdb918136bbb97d62a608be28c4/raiden-ts/src/transfers/epics/close.ts#L59-L63

However, it seems the secret can still be revealed:

https://github.com/raiden-network/light-client/blob/1e0af28e9ccab805abdcb36926af7219efdf80b7/raiden-ts/src/transfers/epics/secret.ts#L101-L156

And unlocked on-chain.

Additionally, when mediation is implemented assumptions like this are harder to make, since a mediator can only wait for the lock to expire to know for sure it did fail. I'd suggest only using off-chain unlock, on-chain unlock, and expiration as signals for the result of a transfer.

**Comment by andrevmatos** [comment]
Thanks, @hackaugusto ! This is exactly the kind of thing I was expecting to start coming out of your review!
This is awesome, thank you very much for looking this through. This is quite edgy, since it only happens if a channel gets closed while transfers are pending, but definitely we must fix.

**Comment by andrevmatos** [comment]
`transferChannelClosedEpic` got removed as part of #2110 . Closing.
