### ISSUE TITLE
Fatal error: RaidenError: Could not contact any Matrix servers.

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2042]
## Steps to Reproduce
1. Metamask pointing to a new account
2. connecting and signing on metamask with that account

## Expected Result
- Finds atleast one matrix server to connect

## Actual Result
- 
![light_client_failure_matrix](https://user-images.githubusercontent.com/15123108/89304378-fe63b680-d68a-11ea-8119-965bb50bf7c9.png)

[raiden_0x38E382F62e2E08887031ee07FEA8E3acd5d70226_2020-08-04T14_09_23.517Z.log](https://github.com/raiden-network/light-client/files/5022601/raiden_0x38E382F62e2E08887031ee07FEA8E3acd5d70226_2020-08-04T14_09_23.517Z.log)

**Comment by christianbrb** [comment]
@agatsoh Thanks for opening the issue :)

Could you describe your set-up in more detail? Browser / address / Did you work with this account in another browser?

**Comment by agatsoh** [comment]
Closing the issue due to not loading the matrix server list
