### ISSUE TITLE
Consider requiring a higher expiration for new transfers.

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2057]
https://github.com/raiden-network/light-client/blob/27d308d6279ec7f8d797ea8fc5829738992d905c/raiden-ts/src/transfers/epics/locked.ts#L132

When `action.payload.expiration == state.blockNumber + revealTimeout` it is too late, at this point the recipient can not safely proceed with the off-chain transfer, for a new transfer that means the sender will have funds locked, but the transfer will not be mediated. A single block is probably too strict, without RTC transfers can take multiple seconds to complete, so a few blocks at least should be required.

In the python client an arbitrary value of `reveal_timeout` is used:

https://github.com/raiden-network/raiden/blob/9bd24b1ca72555e7594540a16438534a00f19620/raiden/transfer/channel.py#L166

Note: The change described above is in a best effort basis, the analysis above assumes the sender and the receiver have the same value for the `revealTimeout` setting, but that is the best that can be done ATM. This could only be fixed if the PFS knew the reveal timeout of all payees in a path, and would return the `max` of these reveal timeouts, which to be used as a *lower* bound for the check above.

**Comment by taleldayekh** [comment]
Closing, has been addressed in #2436.
