### ISSUE TITLE
Missing overflow check for lock.amount

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2058]
The code below is not using the decoder:

https://github.com/raiden-network/light-client/blob/27d308d6279ec7f8d797ea8fc5829738992d905c/raiden-ts/src/transfers/epics/locked.ts#L137

This may result in a overflow if the fee is high enough, unlikely, but it doesn't hurt to check

**Comment by andrevmatos** [comment]
#2063 and #2059 are similar issues; we must handle overflow on the few arithmetics operations we do on foreign messages. Closing those in favor of this one.
