### ISSUE TITLE
 Missing overflow check for locked_amount

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2059]
Like https://github.com/raiden-network/light-client/issues/2058 , in the code below a overflow check is missing:

https://github.com/raiden-network/light-client/blob/27d308d6279ec7f8d797ea8fc5829738992d905c/raiden-ts/src/transfers/epics/locked.ts#L167

**Comment by andrevmatos** [comment]
Closing in favor of #2058
