### ISSUE TITLE
Tighten check for sending an unlock

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2062]
Having a secret registered is not sufficient, since it may be registered *after the lock has expired*, the code below:

https://github.com/raiden-network/light-client/blob/60903231bc2bcebc366b8431061bb20610ca5579/raiden-ts/src/transfers/epics/locked.ts#L245

Should instead be:

```typescript
(
    state.sent[secrethash].secret![1].registerBlock > 0 &&
    state.sent[secrethash].secret![1].registerBlock < locked.lock.expiration
)
```

Or equivalent (I did not check the API of `lock.expiration`). Note that this may or may not be a bug, it depends if `transferUnlock.request` is emitted for that case or not, I did not check this. 

Edit: Here is the code that checks the lock.expiration against the block at which the secret was registered:

https://github.com/raiden-network/raiden-contracts/blob/93230caa554f6f29e55b4521aafd0af20b710b1f/raiden_contracts/data/source/raiden/TokenNetwork.sol#L1679-L1686

Use this to make sure there is not off-by-one errors

**Comment by andrevmatos** [comment]
Superseded by #2077 and #2085
