### ISSUE TITLE
Missing overflow check for transferred_amount

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2063]
Similar to #2058 and #2059 when a locked transfer is successful the transferred_amount will be increased, and that must not overflow. Because of this, when a locked transfer must only be create iff the code below would not overflow:

https://github.com/raiden-network/light-client/blob/60903231bc2bcebc366b8431061bb20610ca5579/raiden-ts/src/transfers/epics/locked.ts#L257-L259

To reinforce, the overflow must be checked when the locked transfer is created, and not at unlock time, that would be too late.

**Comment by andrevmatos** [comment]
Closing in favor of #2058
