### ISSUE TITLE
Payment identifier and Message identifier generation

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2064]
## Description
(`src/transfers/utils.tx:58`)

Both identifiers are only generated based on the current time with millisecond precision. This can be easily guessed, but could also easily collide on accident, for example if to message are generated fast within the same millisecond, etc. This should have another careful look if that is really good enough, or if not better some kind of randomness should be used. 

_Copied from the team repo_

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
These are absolutely non-secret, and non-critical for the security of the protocol. MessageId is used only by transport, to relate a confirmation with its message, and PaymentId is just a transfer metadata, not used for anything special. We could make a little bit more effort to make these true random though.

**Comment by taleldayekh** [comment]
Closing, no risk in keeping as is.
