### ISSUE TITLE
Ping, Pong messages not implemented

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2065]
## Description
The ping and pong message from the raiden python client are not  implemented. If they are not used anymore, maybe consider removing them from the python code base too. 

_Copied from the team repo_

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
Ping/Pong are from the raw UDC transport times. Not used anymore. Not sure why python-core keeps them, but it doesn't affect us.
