### ISSUE TITLE
Channels are not identified by chain id

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2068]
## Description
The canonical identifier for a channel was chosen to be `(chain_id, token_network_address, channel_id)`, but internally in the sdk only `(token_network_address, partner_address)` is used. Make sure that this is fine, for example the state is not shared when the sdk is used with different chains. 

_Copied from the team repo_

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
`chain_id` is set in state, and SDK shuts down if it changes during runtime, and also validate any message containing it to match our current value, so it shouldn't allow running with another state on a different network. The `tokenNetwork,  partner` choice was to facilitate matching a `channelOpen.request` (which doesn't know yet the id) with its `.success` response. We may look into reevaluating this though.

**Comment by weilbith** [comment]
What happens when I do the following:
- I run the SDK on chain `a` and produce data
- I stop the SDK
- I run the SDK on chain `b` but provide it the data of the last run on chain `a` during creation

**Comment by christianbrb** [comment]
@andrevmatos to provide details and close it

**Comment by andrevmatos** [comment]
So, the `RaidenState` contains the `chainId` and `registryAddress` for which it was initialized. If you try to launch SDK with different values for any of them, it'll fail to start. This is what you'll get if you try to do what you said. `chainId` and `tokenNetworkAddress` is also checked for any incoming message, and it'll be rejected if it doesn't match, therefore this is a non-issue.
