### ISSUE TITLE
Expiration is ignored

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2069]
## Description
The expiration of received transfers is on purpose ignored in (`src/transfers/epics/locked.ts`). If this is fine, you should consider updating the specs, as it is mentioned there to check the expiration. (see "Precondition for LockedTransfer)

_Copied from the team repo_

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
Yes, this is explicit due to the need to keep the states in sync even over long periods of time one or both clients could go offline. See #1514
