### ISSUE TITLE
Payment id not checked on secret request receive

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2070]
## Description
In the specs it says it be check if there is a payment with the same hash time lock and payment identifier, but only the hash time lock is checked in the sdk (`src/transfers/epics/secret.ts:67`. Update the specs, if this check is not necessary or check it.
_Copied from the team repo_

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
It is checked, 9 lines below:
https://github.com/raiden-network/light-client/blob/60903231bc2bcebc366b8431061bb20610ca5579/raiden-ts/src/transfers/epics/secret.ts#L67-L80
