### ISSUE TITLE
Not a common format for messages that get signed

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2071]
## Description
There seems not to be a common format for messages that get signed. There is at least 
 - contract messages like the balance proof starting with `contract address`, `chain_id`, `message_id`
 - protocol messages starting with `message_id`
 - pfs messages starting with `chain_identifier`, `token_network_address`, `channel_identifier`

It is not obviously clear why they can not be cross replayed. You should make sure that they can not, or better, make it more obvious, for example by starting the messages in a way that it is obvious that this can not happen. 
Maybe you are doing this simply by the length, which should work, but then it should be more clear that you do that.

_Copied from the team repo_

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
This is per protocol. We just comply with the format here. Not sure how to proceed. What's signed is actually the hash of these messages, they have different sizes, and the only one with variable size is PFS fee update, which isn't composed using any partner data, but instead simply internal config values. @christianbrb how would we audit this part of the protocol? If out of scope, we should close this issue.

**Comment by christianbrb** [comment]
@andrevmatos Thanks :)

This is not in scope. Closing

CC @Dominik1999 @karlb
