### ISSUE TITLE
registerBlock has to be verified

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2077]
A lot of the code assumes that `TransferState`s with a non-zero `registerBlock` had a valid on-chain registration.

Examples:

https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/close.ts#L49-L54

https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/locked.ts#L614

https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/expire.ts#L40-L41

https://github.com/raiden-network/light-client/blob/59e7662e643e5b0a17db8b46a44d29b471b0263d/raiden-ts/src/transfers/state.ts#L36-L40

However, that is not sufficient. Not only the secret has to be registered on-chain, but the block at which the secret was registered, must be smaller than the `lock.expiration`. All of the above sites and any other places that use `registerBlock` without comparing to the `lock.expiration` have to be fixed.

**Comment by andrevmatos** [comment]
@hackaugusto , the `registerBlock` is set by the `transferSecretRegister.success` action, which is only emitted for a transfer if the register block was before the expiration block:
https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/secret.ts#L327-L333
That's why, in all these places, we assume if `registerBlock` is set and not zero, it happened before expiration. Is this enough?

**Comment by andrevmatos** [comment]
We should add an additional check in the `reducer` too, to avoid a very edgy case where the registering gets detected inside the expiration period, reorged and confirmed on a block after expiration, which will make the above code not emit it, but it may get confirmed by `confirmationEpic`, which is the only case when the `registerBlock` can get set with a block after expiration.

**Comment by hackaugusto** [comment]
> Is this enough?

It looks like it is sufficient.

Ideally this information should somehow be encoded, maybe in the type or attribute name, I guess having an attribute `successfullyRegisteredOnChain` and a comment when the variable is set explaining the above would be sufficient to avoid confusion (at least for me). ATM the validation of a secret registration is split on multiple places, which makes it hard to understand if the code is correct.

I don't really understand the corner case you are talking about, maybe close this issue and open a new one with the corner case?

**Comment by andrevmatos** [comment]
Let's keep this one, as the title is appropriate. I'll try to explain better this variable in the `TransferState` too, so it's made more obvious. The secret registration is validated  and emitted in only one place (the one I linked), and from there on, this state property is informative of the on-chain secret registration took place or not (therefore the checks out there), but we could inform it better and maybe split these kind of checks on their own standalone functions to make it centralized.
