### ISSUE TITLE
Merge Select Hub & Open Channel Screens

### ISSUE THREAD

**Issue by roy-castrillo** [raiden-network/light-client#208]
## User Story
Select hub and open channel screens should be merged, as the former will rarely be changed. While users will be given the opportunity to edit the hub, the most common scenario is one where it has automatically been selected after choosing the token.

## Acceptance criteria
- Enter deposit amount should be the most prominent action
- Hub is no longer an input field, but editable info that users may change if needed

## Tasks
- [x] Design
- [ ] Implementation

**Comment by christianbrb** [comment]
This has been done

![grafik](https://user-images.githubusercontent.com/35398162/67478790-0c48cd80-f65d-11e9-85be-c87de6c8f0ab.png)
