### ISSUE TITLE
makeAndSignUnlock$ assert for channel state is too restrictive

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2080]
From my understanding, with interactive signing the code below will require user intervention, to give permission for the signing:

https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/locked.ts#L265

The amount of time it will take for the user to perform the action is unbounded. From what I understand from @andrevmatos explanation for https://github.com/raiden-network/light-client/issues/2061 , the signing process will happen in a separate thread which won't block the SDK, meaning the blockchain event listener will continue running and can fetch new events from the blockchain.

It is completely possible that by the time the code below is executed, the node learns about the channel being closed: 

https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/locked.ts#L268-L282

Leading to a failure in the assert. In that case, instead of an assert error, which I believe stops the SDK, a `transferUnlock.failure` should be returned.

**Comment by andrevmatos** [comment]
You're right on your thinking, indeed with interactive signing we can't know how long the user will take to sign a message. But no `assert` should ever shutdown the SDK. We'll give a second pass to make sure of that on #1790 . The asserts are not used in our codebase as _something that never happens_, but instead on the sense of TypeScript's _assertion functions_, which acts as type-guards.
Specifically on these transfers observables, all of them end with a `catchError`, which will emit the respective failure, in this case, `transferUnlock.failure`:
https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/locked.ts#L305-L309

**Comment by hackaugusto** [comment]
I didn't expect an `assert` to be used for type narrowing. I don't know if that is standard practice with TS, but maybe consider using `if` statements for type narrowing and `assert`s for stating assumptions that when broken represents a bug.

**Comment by andrevmatos** [comment]
https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions
This is not that common, but is supported by language syntax, used consistently through our codebase, and composes well with the error observables logic (errors skips all following operators until hitting ones made specifically to handle it, like `catchError` and `retryWhen`).
