### ISSUE TITLE
Clarify runtime characteristics of epics

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2081]
It is not clear when actions are interleaved with the `redux-epics` framework. The SDK has defensive code like the following:

https://github.com/raiden-network/light-client/blob/862c5d53f999549ba1a123837cb90e726ebe06c1/raiden-ts/src/raiden.ts#L898-L930

The first part of the `merge` is effectively registering a handler for the *new actions* emitted as a result of the epic execution, the actual action is only dispatched inside the `defer`. This pattern of registering *before* dispatching exists to prevent races, were dispatching the action would be immediately executed and the epic results would be pushed into `action$` before the handlers are installed.

However it is not clear if the pattern is necessary. `redux-observable` internally uses [a queue scheduler](https://github.com/redux-observable/redux-observable/blob/2b6c0ed700b78f86780ac5d2e6ba81d341249a0a/src/createEpicMiddleware.ts#L32-L34), this scheduler will [delay the propagation of the *new actions* generate by the epics](https://github.com/ReactiveX/rxjs/blob/40b32d8fadeb1c0ef752fa4281aff20fa3a2c18b/src/internal/scheduler/AsyncScheduler.ts#L31-L34) if an epic is currently running. In that case, the dispatch [happens right away](https://github.com/redux-observable/redux-observable/blob/2b6c0ed700b78f86780ac5d2e6ba81d341249a0a/src/createEpicMiddleware.ts#L88-L91), but [the propagation of the actions is queued](https://github.com/redux-observable/redux-observable/blob/2b6c0ed700b78f86780ac5d2e6ba81d341249a0a/src/createEpicMiddleware.ts#L93-L96)

**Comment by andrevmatos** [comment]
That's a good point, thank you for raising it. On preliminary tests, it seems that this event's queueing is relevant only at startup/subscription time, to avoid later epics losing events emitted at this point in time by previous epics. After that, it seems dispatch is synchronous until it hits some async function inside an epic.
In either case, the pattern currently used is suitable for both sync and async dispatch+handling of actions in the epics, being simply overcautious on the later.
We should indeed clarify and add a test to ensure this.
