### ISSUE TITLE
off-by-one on secret epic

### ISSUE THREAD

**Issue by hackaugusto** [raiden-network/light-client#2085]
Follow up to https://github.com/raiden-network/light-client/issues/2077 .

The code below is accepting the secret registration were `lock.expiration == registration_block` as valid.

https://github.com/raiden-network/light-client/blob/0abfd9ee9d4359b150048f7018dd13fe07175086/raiden-ts/src/transfers/epics/secret.ts#L326-L343

However the smart contract does not:

https://github.com/raiden-network/raiden-contracts/blob/93230caa554f6f29e55b4521aafd0af20b710b1f/raiden_contracts/data/source/raiden/TokenNetwork.sol#L1679-L1686

The code should be changed from `gte` to `gt`.

**Comment by andrevmatos** [comment]
I was about to ask you about it. Thanks!
