### ISSUE TITLE
Fix breaking MetaMask changes

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2089]
## Description
See the PR

see https://github.com/MetaMask/metamask-extension/issues/8077

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
I am not getting any console warnings from MetaMask. I've used MetaMask to connect, mint and open channels. Perhaps it is safe to close this issue?

**Comment by christianbrb** [comment]
Maybe this is helpful?

> We are going to remove our injected `window.web3`. See #7163 for why, and our [migration guide](https://docs.metamask.io/guide/provider-migration.html#replacing-window-web3) for replacement strategies.

See: https://github.com/raiden-network/light-client/search?q=window.web3

> We are also going to make _some_ breaking changes to our provider. These include:
> 
>     * Stop 0-padding `eth_chainId` return values
> 
>     * Stop emitting `chainIdChanged`, and instead emit `chainChanged`
> 
>     * Remove `ethereum.publicConfigStore`
> 
>     * Remove the following experimental methods:
>       
>       * `ethereum._metamask.isEnabled`
>       * `ethereum._metamask.isApproved`

See: https://github.com/raiden-network/light-client/search?q=window.ethereum

**Comment by taleldayekh** [comment]
As discussed in the daily, this issue can be closed.
