### ISSUE TITLE
Staging doesn't work

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2092]
## Steps to Reproduce
1. Enter https://lightclient.raiden.network/staging/

## Expected Result
- I see the connect screen

## Actual Result
- I see an empty page with the following output

![grafik](https://user-images.githubusercontent.com/35398162/90620065-47cb0e80-e212-11ea-9ae8-01a2e1a03b3a.png)

## Additional Infos (Optional) 
```
- Firefox
- Also tested with Edge
```

**Comment by taleldayekh** [comment]
@christianbrb Remove the last `/` in the URL and it will work. Try: https://lightclient.raiden.network/staging

**Comment by christianbrb** [comment]
It works : Thanks :)
