### ISSUE TITLE
Test UDC deposit and RDN on mainnet

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2099]
Test UDC deposit and RDN on mainnet

**Comment by agatsoh** [comment]
I have 10 RDN deposited in the UDC which is showing correctly.
I have 5 RDN in my main account which is also showing correctly in the dialog but I am not sure why the `deposit`  button is freezed even when `5.0 RDN` is correctly autopopulated in the input box.

![udc_deposit_dialog_test21Aug](https://user-images.githubusercontent.com/15123108/90862500-22253d00-e3ab-11ea-90eb-69bc57a3b073.png)

**Comment by agatsoh** [comment]
@taleldayekh FYI

**Comment by taleldayekh** [comment]
Oh, no :( Will look into it.

**Comment by taleldayekh** [comment]
I think I found the bug. Looks like the RegEx that is used `^[1-9]\d*$` only parses whole numbers, so `5` enables the button while `5.0` won't enable the button. I will update the RexEx.
