### ISSUE TITLE
Tooltips don't work on mobile

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2100]
## Description
Tooltips don't work on mobile

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
https://github.com/Akryum/v-tooltip#manual-trigger-example

**Comment by weilbith** [comment]
@taleldayekh cool feature. Eventually could be combined with a `onTapHold` or `onLongTap` touch action (e.g. use [vue2-touch-events](https://www.npmjs.com/package/vue2-touch-events).

**Comment by taleldayekh** [comment]
Closing, not really an issue since no complaints have been made about the tooltips lately.
