### ISSUE TITLE
Don't show the red line under the amount input field

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2108]
## Steps to Reproduce
1. Connect new token
2. Enter a hub address
3. Click on Select Hub

## Expected Result
- No red line on the amount input field

## Actual Result
- Red line on the amount input field
   ![grafik](https://user-images.githubusercontent.com/35398162/91169777-2ec1d200-e6d8-11ea-81e4-dd8f4c25afaa.png)

- There is also a blue line, if I have added an amount + the field is active    
    ![grafik](https://user-images.githubusercontent.com/35398162/91169895-60d33400-e6d8-11ea-8c58-d12f88eec355.png)

- ... and a grey line if the field is inactive
    ![grafik](https://user-images.githubusercontent.com/35398162/91170005-8c561e80-e6d8-11ea-90df-bd5b011c940d.png)

## Additional Infos (Optional) 
```
- Firefox
```

**Comment by christianbrb** [comment]
Same for the amount field on the transfer screen

![grafik](https://user-images.githubusercontent.com/35398162/91172871-33d55000-e6dd-11ea-8a3a-5d87eb4fa012.png)

**Comment by christianbrb** [comment]
It applies for all amount input fields.

**Comment by christianbrb** [comment]
Thomas once fixed that: https://github.com/raiden-network/light-client/pull/708

**Comment by taleldayekh** [comment]
This does not seem to be an issue anymore (latest master), I cannot reproduce it, neither on Firefox nor Chrome. @agatsoh could you take a look an see if you are experiencing these issues.

**Comment by agatsoh** [comment]
Yes i confirm that the red line is not shown either in chrome or in firefox. I think this issue can be safely closed.

**Comment by taleldayekh** [comment]
I'm reopening this issue. Apparently this is a problem on staging. I don't see any red line when serving the dApp locally (latest master) but for some reason, the red line happens on staging.

**Comment by weilbith** [comment]
Incredibly hard to debug since `staging` gets deployed in production mode. So eventually there is something broken about the `$route` query parameters. I don't know why this should happen, but the treatment of these parameters is not too stable...

**Comment by christianbrb** [comment]
If the channel is closed the line looks different (see screenshot below)

![grafik](https://user-images.githubusercontent.com/35398162/93869503-2905df00-fccc-11ea-864a-7666ffdc1aa5.png)
