### ISSUE TITLE
dApp keeps redirecting to connect view after connecting

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2114]
## Steps to Reproduce
1. Connect to the dApp on hosted, staging, or locally using Goerli.

## Expected Result
- To get redirected to the next view

## Actual Result
- Redirects back to the connect view and console showing a transport 500 error, something like this: `POST https://transport.demo001.env.raiden.network/_matrix/client/r0/join/%23raiden_goerli_monitoring%3Atransport.demo001.env.raiden.network? 500`

## Additional Infos (Optional) 
Logs:
[raiden_0xee0f8e9A79cC3789AEba5A6CE16b21275924A618_2020-08-28T14_07_17.190Z.log.zip](https://github.com/raiden-network/light-client/files/5142504/raiden_0xee0f8e9A79cC3789AEba5A6CE16b21275924A618_2020-08-28T14_07_17.190Z.log.zip)

**Comment by christianbrb** [comment]
The same is happening to me.

My logs: 
[raiden_0x8c8492280cB454F2753DBb9a3114F4DA80F66714_2020-08-28T14 14 33.854Z.log](https://github.com/raiden-network/light-client/files/5142541/raiden_0x8c8492280cB454F2753DBb9a3114F4DA80F66714_2020-08-28T14.14.33.854Z.log)

**Comment by christianbrb** [comment]
@andrevmatos 
> This doesn’t look like a LightClient issue, but a server one. [...] a join on global public room giving a 500 response is a server side issue

**Comment by ulope** [comment]
The postgres db on that server was crashlooping because it couldn't allocate enough shared memory.
I suspect memory fragmentation. I rebooted the server and now things seem to be back up.

I also reduced the worker count from 8 to 4 since the machine only has 4 cores and 8 GB RAM.

**Comment by taleldayekh** [comment]
@ulope It works, thank you, I'm back in business!
