### ISSUE TITLE
In channels list only a single channel should have an expanded menu

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#212]
## Description
Now that the channel list displays 3 different lists, each list has an independent expansion tracking. This means that you can have an expanded item for each list. This should change so that each time you expand an item on one of the lists, then any expanded area in the other lists collapses automatically.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
We are currently discussing alternatives to the current structure with channels and tokens
@kelsos Please reopen, if you think, that it is still important right now and should be fixed soon.

**Comment by kelsos** [comment]
Let's reevaluate it after the design update if it is still valid. But
closing it now makes sense to me.
