### ISSUE TITLE
Cant accept disclaimer in metamask mobile

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#2129]
## Steps to Reproduce
1. Install metamask app
2. Go to raiden light client

## Expected Result
- i can accept the disclaimer

## Actual Result

Checkboxes aren't visible

![Screenshot_20200905-221032_MetaMask.jpg](https://user-images.githubusercontent.com/3169205/92312833-13eb3980-efc5-11ea-8427-ca41c5b84de1.jpg)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by weilbith** [comment]
Hmm actually the text part should be `60vh` height. On your screenshot it looks like Metamask its UI is taking a lot of the screens height. But actually `vh` should refer to the size of the viewport. :thinking:

**Comment by christianbrb** [comment]
@nephix Thanks for raising the issue. Could you check if https://lightclient.raiden.network/staging works for you? We have done some changes (#1838) lately to fix issues on mobile.

**Comment by nephix** [comment]
I can accept the terms but the 2nd checkbox isnt clickable

![Screenshot_20200917-134156_MetaMask.jpg](https://user-images.githubusercontent.com/3169205/93465854-a061fa00-f8eb-11ea-8220-7bd33bd4a6fc.jpg)

![Screenshot_20200917-134201_MetaMask.jpg](https://user-images.githubusercontent.com/3169205/93465879-a8219e80-f8eb-11ea-9a55-5fe53d2c12d2.jpg)

**Comment by christianbrb** [comment]
Thanks for the quick test :) We'll fix it.
