### ISSUE TITLE
Address input should not be valid when resolving an ens domain

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#214]
## Description

Address input has a valid state while resolving an ENS domain. This allows the user to press the screen button breaking the flow.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by nephix** [comment]
@kelsos @christianbrb I worked on this and at some point you've mentioned that something will likely change about ENS handling so please check if this ticket is still valid

**Comment by christianbrb** [comment]
Yes, it should still be valid. On some networks, ENS is not available.

**Comment by kelsos** [comment]
So the other issue we mentioned is like @christianbrb mentioned about ens being or not being available. It should be a separate issue.

This issue is about when the ENS is supported, you type your address and wait for the promise of the asynchronous request. Currently, while the promise is still pending the status is valid and you can press the button to `Select`. You should not be able to do so until the promise completes.

Does this clarify what the issue is about?

**Comment by nephix** [comment]
I know what the issue is about, but stopped working on it since you told me to do so because of other related issues to this ticket.

**Comment by kelsos** [comment]
@nephix we should fix it regardless of the other issue.
