### ISSUE TITLE
dApp: Tidy up the RaidenService module and introduce some structure

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2147]
## Description
At the moment this module is a steadily growing. Functions get bigger and bigger. Nobody finds something, it is hard to read and hard to extend. Parts like the subscription to events for submitting notifications started small for a couple of events. Now it has become huge without any structure. But actually this procedure follows a pretty simple schema. This should be represented in the code. This will increase the readability of the code and new contributor can easily add/remove a notification.
Another example is the `connect()` function. It is at the moment of writing 167 (**!!!!!**) lines long. This is insane. Everybody add something somewhere. There is no structure of the code and no overview what happens during this stage of the application.
This story continues...
Although is the concept of separating concerns missing. This makes it incredibly hard to have good tests and especially an overview of how complete/good the test suite(s) is/are.

## Acceptance criteria
- The code is clean, readable and easy to extend

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
Closing, already an issue for this #2231
