### ISSUE TITLE
CodeClimate checks do not seem to work any more

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2148]
## Description
After reading #2147 I have checked CodeClimate and the code quality seemed [to get worse within the last 2 months](https://codeclimate.com/github/raiden-network/light-client/trends/technical_debt).

![grafik](https://user-images.githubusercontent.com/35398162/93756124-d7465180-fc04-11ea-91e6-a8a309f44185.png)

It does not seem to get checked any more within a PR (see eg. https://github.com/raiden-network/light-client/pull/2146).

## Acceptance criteria
- Every PR is checked

## Tasks
- [ ] Check the configuration (see https://docs.codeclimate.com/docs/workflow)

**Comment by christianbrb** [comment]
CodeClimate were stuck. Removed from the required checks. Maybe this was due to @kelsos leaving the team (token?).

**Comment by kelsos** [comment]
@christianbrb Was I the one that created the codeclimate configuration?

**Comment by kelsos** [comment]
At least from what I see, I cannot access the repo settings for the projects on code climate anymore as excepted. Maybe you can go to the site log in with the github account and check the repo settings tab.

https://docs.codeclimate.com/docs/github-pull-requests#pull-request-statuses

The screenshot is from one of my own projects that has codeclimate activated.
![image](https://user-images.githubusercontent.com/2269732/94273548-dbe07200-ff44-11ea-8181-24e4720ef894.png)

**Comment by christianbrb** [comment]
@kelsos Great :) Thanks for the quick feedback :)

**Comment by palango** [comment]
![Screenshot 2020-10-05 at 14 31 51](https://user-images.githubusercontent.com/90851/95079885-87dd4680-0717-11eb-9465-c467133e513f.png)

Looks like that for me now. However, I still don't see the according check in the GitHub settings. @kelsos Do you remember how you enabled that?

**Comment by palango** [comment]
It works in https://github.com/raiden-network/light-client/pull/2197

According to the requirements that's all to do. Is there anything more that used to be done @christianbrb ? The technical dept is still higher than in summer.

**Comment by kelsos** [comment]
Out of curiosity @palango any idea why it stopped working, was it because I left the organization?

**Comment by palango** [comment]
> Out of curiosity @palango any idea why it stopped working, was it because I left the organization?

No, I don't know. Andre removed the branch check at some point because it wasn't working, but maybe it really was disabled because you left the team.

**Comment by palango** [comment]
Done with the check marked as required for PRs to master.
