### ISSUE TITLE
dApp: introduce automatic propery type check

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2151]
## Description

At the moment we need to declare the type of a components property twice. Once for the type check of the component and another time for TypeScript itself. This looks like that:

```ts
@Prop({ type: String })
myProp!: string;
```

There is a nice library called [reflect-metadata](https://github.com/rbuckton/reflect-metadata) that allows decorators to extract metadata from TypeScript. This is [supported by](https://github.com/kaorun343/vue-property-decorator#if-youd-like-to-set-type-property-of-each-prop-value-from-its-type-definition-you-can-use-reflect-metadata) the `vue-property-decorator` library we are already using for our `vue-class-component`s. The resulting code would then look just like this:

```ts
@Prop
myProp!: string;
```

The feature that `reflect-metadata` provides is already discussed to be supported natively. 
This makes all properties type-safe per default and saves the developer annoying code to write and maintain. I use it already privately and it works fine. :upside_down_face:  

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
Vue3 gets advanced typechecking on all properties ootb, and with it I think it's good to also ditch our classes for composition API documents, which will make these decorators not needed. I think we should go on that direction when we need to touch this.
