### ISSUE TITLE
Feedback on Open Channel Progress

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2154]
## Description

@taleldayekh Thanks a lot for the implementation of #1941. It improved a lot the usability.

Some in-iteration feedback on the current implementation: 

- [x] 1. The grey text on the notifciation is hard to read. What do you think about switching to white? The date/time could stay grey. CC @sashseurat 

- [x] 2. Sorting of the notifications should be descending (latest on top). It is the other way around.

    ![grafik](https://user-images.githubusercontent.com/35398162/93888294-1a2d2580-fce8-11ea-8a71-cc4a19a6441c.png)

3. It says "Channel successfully opened" before the deposit has taken place. Is this by design? It might be better to create a new issue with the deposit progress. Would that work and make sense from your perspective?

- Created an issue: https://github.com/raiden-network/light-client/issues/2156

![grafik](https://user-images.githubusercontent.com/35398162/93888524-67a99280-fce8-11ea-93e4-98addd1cb541.png)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by sashseurat** [comment]
> 1. The grey text on the notifciation is hard to read. What do you think about switching to white? The date/time could stay grey. CC @sashseurat

How about this color:
#AFB8C0

**Comment by christianbrb** [comment]
@sashseurat `#AFB8C0` is a nice color and it would be a new color as far as I can see. Right now I would go with the white we are already using and deciding in a separate issue, if we want to change some or all of this white to `#AFB8C0`.

**Comment by taleldayekh** [comment]
> It says "Channel successfully opened" before the deposit has taken place.

@christianbrb The deposit is a separate event from the channel open. So the channel open notification is correct in the sense that it displays `Channel successfully open` before the deposit signing appears in MetaMask. A channel has been opened regardless of whether you choose to deposit or not. If you cancel the MetaMask signature the channel will still be opened.

**Comment by christianbrb** [comment]
Makes sense, that’s why I have opened https://github.com/raiden-network/light-client/issues/2156
