### ISSUE TITLE
Account screen routing not working when disconnected

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2159]
## Steps to Reproduce
1. Disconnect the dApp.
2. Click on the gray identicon to access the account screen.

## Expected Result
- The account screen to be accessible with a limited set of menu items.

## Actual Result
- Cannot access the account screen because the routing is blocking it.

**Comment by andrevmatos** [comment]
This issue is urgent. It seems lots (most? all?) of routes stopped working. I can't perform transfers because not even the `transfers-steps` routes are accessible.
