### ISSUE TITLE
Remove NotificationImportance property and notificationQueue getter

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2173]
## Description
There is no clear use case for the notification importance property. We should either decide on a use case or remove it from the code base.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by weilbith** [comment]
@christianbrb any opinion on that?

**Comment by taleldayekh** [comment]
Closing, the importance is used to determine whether a snacker is shown or not.
