### ISSUE TITLE
NavigationDuplicated: Avoided redundant navigation to current location

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2176]
## Steps to Reproduce
1. Navigate to https://lightclient.raiden.network/staging/
2. I don't know ;)

## Expected Result
- No console error/warning

## Actual Result
- The following console error is shown

`Uncaught (in promise) NavigationDuplicated: Avoided redundant navigation to current location: "/transfer/0x59105441977ecD9d805A4f5b060E34676F50F806".`

![grafik](https://user-images.githubusercontent.com/35398162/94400633-baac9b00-0169-11eb-91b7-66e6c0eddf29.png)

## Additional Infos (Optional) 
```
- Firefox 80.0.1
```

**Comment by taleldayekh** [comment]
To reproduce:
- Make a transfer
- After a transfer close the dialog before it closes itself

Timer redirecting to the same route you are already at.

**Comment by weilbith** [comment]
@christianbrb I fail to reproduce this issue. Can you please help me?
Here is what I do:
  - I have an open channel with the hub that is funded
  - I'm on the `/transfer/<token-of-channel>` route
  - I'm entering the hub as direct transfer target and any small amount
  - I follow the progress by clicking on transfer and then accept the "path" and fees
  - The transfer progresss dialog pops up and shows me the steps that have become completed
  - Before the transfer is done, I close the dialog (using the `X` button and/or just click outside of the dialog)
  - The console never shows an error, never mind how often I try

**Comment by christianbrb** [comment]
I am not able to reproduce it. Closing.
