### ISSUE TITLE
I would like to get reminded frequently to make a backup of my state

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2178]
## User Story
As Chris I would like to get reminded frequently to make a backup of my state so that I don't lose tokens.

## Acceptance criteria
- It is shown as a notification
- Show it once a day

**Comment by taleldayekh** [comment]
@sashseurat Design?

**Comment by christianbrb** [comment]
@taleldayekh Thanks for implementing this.

The notification get's easily missed.

As a quick-fix: 
- Could we make the notification sticking or at least staying there for a much longer time? I wasn't even able to take a screenshot)

And two additional changes to the notification card:
- Backup state to not risk loosing funds -> Backup your state to not risk loosing tokens
- Backup state menu -> Click here to go to the backup state menu
