### ISSUE TITLE
Check availability of target as soon as a valid address is inserted.

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#218]
## Description

Currently, the `getAvailability` is only checked as soon as the user presses transfer.
Check `getAvailability` as soon as the address is input, and require/validate that the available is true.

## Acceptance criteria
- Check availability as soon as a valid address is inserted.
- Show availability color-coded in the UI
- If it is available the border of the Identicon becomes green
- If it is offline
    - the border of the Identicon becomes gray
    - A validation message is shown "Target is offline"
    - The "Continue" button is disabled
- A channel cannot be opened if the channel partner is offline

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Is `getAvailability` checking the matrix presence?

If yes #150 could be closed?

**Comment by kelsos** [comment]
Yes this will be checking the presence in matrix.

**Comment by taleldayekh** [comment]
- Need to go through the user flow of the app and see at what steps the user inputs an address
- Need to decide what system or color-coding to use for distinguishing available targets from non-available ones

**Comment by andrevmatos** [comment]
Related to #600, #408: the same way I don't want to be bothered by paying PFS dialog & routes if there's just direct transfer, I don't want to be presented the PFS fees dialog if the target is offline, which can be done beforehand through this issue.

**Comment by christianbrb** [comment]
From @andrevmatos 
> How about 3-4s after last change in transfer in status, so if signatures keep being prompted (there’s activity) it’s delayed a little longer, and if it doesn’t change in 3-4s, may mean the transfer is getting stuck or slow, and then hide it
