### ISSUE TITLE
Token transfer unsuccessful after closing browser during withdraw

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2184]
## Steps to Reproduce
1. Crash the browser during withdraw (see #2184)
2. Wait a while (in my case it has been one night)
2. Navigate to https://lightclient.raiden.network/staging/#/transfer/0x59105441977ecD9d805A4f5b060E34676F50F806/0x1F916ab5cf1B30B22f24Ebf435f53Ee665344Acf?amount=0.0001
2. Make a transfer

## Expected Result
- Transfer successful

## Actual Result
- Transfer failed (Lock expired)
- [raiden.logs.txt](https://github.com/raiden-network/light-client/files/5298169/raiden.logs.txt)

## Additional Infos (Optional) 
- Maybe the originating problem is https://github.com/raiden-network/light-client/issues/2177

**Comment by andrevmatos** [comment]
Yes, this is a direct consequence of #2177 : got out of sync somehow and nothing will work after it.

**Comment by christianbrb** [comment]
@andrevmatos Thanks for looking into it.

Is this specific to withdraws?

**Comment by taleldayekh** [comment]
We'll tackle this in #2177 .
