### ISSUE TITLE
Due to WebRTC: BF6 encounters  lock expired  exception

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2195]
## Description
Running Scenario player with light client gives 
```
{
  "result": "scenario error",
  "message": "HTTP status code \"409\" while fetching http://127.0.0.1:58917/api/v1/payments/0xC563388e2e2fdD422166eD5E76971D11eD37A466/0xFa6Ab2E50c4e93037ABc86fB1E7e51b858f0Db23. Expected 200: {\"errors\": \"Payment couldn't be completed because: lock expired\"}",
  "event": "Run finished",
  "logger": "scenario_player.main",
  "level": "error",
  "timestamp": "2020-10-02 11:09:24.918355"
}
```
Many payments in many nodes have errored mostly from this task 
```
- parallel:
          name: "Every node sends 5 payment using Node 0 as hub"
```

[scenario-player-run_bf6_stress_hub_node_2020-10-02T15:57:32.log](https://github.com/raiden-network/light-client/files/5317666/scenario-player-run_bf6_stress_hub_node_2020-10-02T15.57.32.log)

individual node logs
https://drive.google.com/drive/folders/1w5iez-5vFM_6oPcbLzflkWSkXme_bZEw?usp=sharing

## Acceptance criteria
-  

## Tasks
- [ ]

**Comment by palango** [comment]
Was this with webRTC disabled?

**Comment by agatsoh** [comment]
Actually I did not enable or disable webrtc, I think default is enabled right ?

**Comment by andrevmatos** [comment]
There's some issue with sending messages while waiting for partners to join rooms, which triggers only on high-load scenarios like BF6. This may also affect WebRTC. I'm working on it.
