### ISSUE TITLE
Review SDK Documentation for onboarding

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#220]
## Description

Review of the [documentation create within the wiki](https://github.com/raiden-network/light-client/wiki) for onboarding.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb I went through the wiki twice. It seems really informative in regards to the design and decisions.

**Comment by nephix** [comment]
I went through it a couple of times and still do to look things up. It's well written and quite helpful to understand the overall architecture and how each used lib fits into the big picture.

What could be added (questions I still have at the moment):

1. How to debug SDK while running the light client?
2. A short paragraph about how and where to write tests
