### ISSUE TITLE
Cypress: Add test for mediated transfers

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2210]
## Description
We need to add tests for not only direct transfers but also mediated ones.

## Acceptance criteria
-

## Tasks
- [ ] Figure out how to set up the e2e tests so that mediated transfers can be done in the dApp via Cypress.
- [ ] Increase the lock timeout of the Python client

**Comment by taleldayekh** [comment]
We have a new issue that covers the remaining Cypress tests #2274 .

**Comment by palango** [comment]
Ran into a new problem now, but that should be easy to fix: `Path invalid because of too low reveal timeout ratio`
