### ISSUE TITLE
Specify if ETH is on main account or subkey account

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2216]
## Description
If a user tries to i.e. withdraw tokens without having any ETH on the subkey account the withdrawal will fail. This is easily missed because a user might confuse the main account ETH and subkey account ETH.

## Acceptance criteria
- Specify which account the ETH balance is on, i.e. `Subkey ETH` instead of just ETH.

<img width="595" alt="Screenshot 2020-10-09 at 13 42 16" src="https://user-images.githubusercontent.com/43838780/95579376-d2bbce80-0a35-11eb-98e6-13ed4651c2ef.png">

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
For me, it's clear that ETH belongs to that address. Maybe instead we should just replace the `Account` header with `Raiden Account` when subkey is enabled, or something like that. I remember @christianbrb was quite against showing mainnet ETH balance there, since the user can see it in Metamask popup.

**Comment by taleldayekh** [comment]
Ok, yes displaying `Raiden Account` would also be fine imo, but I don't think there is any harm in being explicit. Just an easy way to quickly make sense of things. After using the Raiden account all the time you'll stop even thinking that a main account even exists.

**Comment by christianbrb** [comment]
@taleldayekh to create bug issues for the ETH on the UDC screen. Please also check the Withdrawal screen.

**Comment by weilbith** [comment]
@taleldayekh this was "accidentically" resolved by the recent PR, wasn't it?

**Comment by taleldayekh** [comment]
@weilbith Yes, you fixed that so it makes sense closing this issue.
