### ISSUE TITLE
Ensure that the dApp works on wallets with dApp browser

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#223]
## Description

Out of curiosity yesterday I tried to check how the dApp runs in status.im. Apparently, it doesn't after spending a bit investigating I found out that a `raidenShutdown` is fired immediately after `raidenInit`.

```
{
  meta: undefined
  payload: {reason: Error: The method eth_sign does not exist/is not available at Object.eval [as   callback] (webpac…}
  type: "raidenShutdown"
}
```

https://medium.com/metamask/the-new-secure-way-to-sign-data-in-your-browser-6af9dd2a1527

## Acceptance criteria
- Works in Status and imToken
- Needs to be tested with https

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
To clarify, we actually use the `personal_sign` proposal from EIP191. There're some inconsistencies between clients exposing this EIP signature format through `eth_sign` additionally or exclusivelly, which led to this issue. We expected [ethers.Signer.signMessage](https://docs.ethers.io/ethers.js/html/api-wallet.html#signing) to do the right choice, as it complies with that format, but seems we'll need some workaround for status for it to do the right thing.

**Comment by nephix** [comment]
I'm going to look into this, there seems to be a workaround as explained on https://github.com/ethers-io/ethers.js/issues/491

**Comment by andrevmatos** [comment]
Seems ethers special-case Metamask [here](https://github.com/ethers-io/ethers.js/blob/d7190646280af9bb36352fc502ba7f6e84559026/src.ts/providers/web3-provider.ts#L63), if the `AsyncSendable.isMetaMask` is truthy. We just need to do the same for these wallets which doesn't support `eth_sign`. I'd rather detect and set earlier than catch, to avoid the erroring overhead when possible.
