### ISSUE TITLE
UDC withdrawal transfers to the Raiden Account and not to the Main Account

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2233]
## Steps to Reproduce
1. Deposit tokens to the UDC
2. Withdraw 10 tokens from the UDC
3. Wait for the transaction to be confirmed (https://goerli.etherscan.io/tx/0x8ab3af27d017b67b607b95c474c02ed31a760ce59d594dad628e0d4cd4d0996a)
4. Wait another 100 blocks

## Expected Result
- I see the tokens within my main account (https://goerli.etherscan.io/address/0xB808877b5Ec745183bd60Ce8c89aBa83011D56f6)

## Actual Result
- I see the tokens in my Raiden account (https://goerli.etherscan.io/token/0x5fc523e13fbac2140f056ad7a96de2cc0c4cc63a?a=0x8c8492280cB454F2753DBb9a3114F4DA80F66714)

![grafik](https://user-images.githubusercontent.com/35398162/95844706-7fa18e80-0d49-11eb-9e7a-29fe4f6473a9.png)

**Comment by andrevmatos** [comment]
I think UDC withdraw doesn't support a beneficiary account, so the tokens can only go to the holder (subkey) account, and need to be withdrawn from there.

**Comment by palango** [comment]
> I think UDC withdraw doesn't support a beneficiary account, so the tokens can only go to the holder (subkey) account, and need to be withdrawn from there. Changing this would require changing the UDC smartcontract.

That's true. We can create an issue, but for mainnet this cannot be changed.

**Comment by christianbrb** [comment]
Misunderstanding
