### ISSUE TITLE
RDN tokens not shown on the token withdrawal screen on mainnet

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2237]
## Thanks for filing a bug report :-)

Reported by @jjjseee

## Steps to Reproduce
1. Deposit RDN to the UDC
2. Withdraw tokens from the UDC
3. Wait 100 blocks
4. Check etherscan if the withdraw-transaction has been completed for the Raiden Account (in this case: https://etherscan.io/tx/0x9aa881340667f0d81c9e1b5c25e963c38b30e4be5b58aa500a42471957b95a66)

## Expected Result
- I see the RDN tokens on the Withdrawal Screen and can withdraw them to the main account.

## Actual Result
- I don't see the tokens on the withdrawal screen and cannot withdraw the tokens.

   ![grafik](https://user-images.githubusercontent.com/35398162/95880553-ec338200-0d77-11eb-83ac-5423d14b094b.png)

**Comment by agatsoh** [comment]
The withdraw tokens screen after withdraw


![withdraw_tokens_screen](https://user-images.githubusercontent.com/15123108/95977772-e05ac500-0e36-11eb-965e-0b092569252d.png)

![withdraw_function_call_etherscan](https://user-images.githubusercontent.com/15123108/95978083-52cba500-0e37-11eb-81a0-dfeefb60cb29.png)

![rdn_balance_raiden_account](https://user-images.githubusercontent.com/15123108/95978100-57905900-0e37-11eb-9665-4079f3cabb61.png)

**Comment by agatsoh** [comment]
On the mainnet RDN still does not appear on the withdrawal screen

![rdn_withdrawal_screen](https://user-images.githubusercontent.com/15123108/96116700-81648100-0f06-11eb-9225-10ad46f5bd79.png)

**Comment by agatsoh** [comment]
latest test 
![Uploading withdraw_tokens_screen_latestg.png…]()

**Comment by christianbrb** [comment]
It does not seem to work on mainnet. Reopening.

@taleldayekh Could you please have a look, thanks :)

**Comment by weilbith** [comment]
Sorry. I linked my PR to the wrong issue. :see_no_evil:
