### ISSUE TITLE
Raiden-CLI doesn't return transaction request

### ISSUE THREAD

**Issue by eorituz** [raiden-network/light-client#2238]
## Steps to Reproduce
1. Using master at commit `758f7e4dc0024ff0410289ef418b66c87ba5df00`
2. Send payment 
```
http POST localhost:5001/api/v1/payments/0x3ed0DaEDC3217615bde34FEDd023bC81ae49251B/0x5358D52F4a4728d34676454Bdbafd129f0095831 identifier=999 amount=1
```
3. Payment request should never return

##Raiden Sender Logs
[raiden.log](https://github.com/raiden-network/light-client/files/5372592/raiden.log)

## Proof of successful payment
```
(demoenv001) oliver@bbpc:~/Arbeit/github/raiden_sensor_paywall/imx_buyer$ http localhost:5001/api/v1/payments
HTTP/1.1 200 OK
Access-Control-Allow-Origin: http://localhost:*/*
Connection: keep-alive
Content-Length: 2272
Content-Type: application/json; charset=utf-8
Date: Tue, 13 Oct 2020 16:01:31 GMT
ETag: W/"8e0-7U+HDWYAzK9rbq9XddmR/spepg4"
Vary: Origin
X-Powered-By: Express

[
   ...,
    {
        "amount": "1",
        "event": "EventPaymentSentSuccess",
        "identifier": "999",
        "initiator_address": "0xbD4B4C7155F55F6051A732772589C38480E58F71",
        "log_time": "2020-10-13T15:52:10.760Z",
        "secret": "0x71c888457ad07421391220cdbf6fbba111fde24bd59d59c0ed2a17e31bcc4459",
        "secret_hash": "0xd06e57b84653144a0a645dec3498da102b9d75672a45c447840143071cc48eb0",
        "target_address": "0x5358D52F4a4728d34676454Bdbafd129f0095831",
        "token_address": "0x3ed0DaEDC3217615bde34FEDd023bC81ae49251B"
    },
   ...
]
```

## Expected Result
- Payment request returns after successful payment

## Actual Result
- Payment seems to be completed but the request doesn't return

**Comment by andrevmatos** [comment]
Just tested here, and it _works for me™_. Please, make sure your clients are all at latest master commit (your linked commit comes before the capabilities adjustments, so you may have been gotten with incompatible versions there), and don't forget to:
1. update dependencies
2. build sdk (it's not built automatically on `pnpm install` anymore)
3. build cli

**Comment by eorituz** [comment]
Mhh Updated both clients to commit `c666432af0ba53e9aa3972b17351048ec91b4d8c`.
Unfortunately, I still have the issue of not returning payment requests.
```
http POST localhost:5001/api/v1/payments/0x3ed0DaEDC3217615bde34FEDd023bC81ae49251B/0x5358D52F4a4728d34676454Bdbafd129f0095831 identifier=222 amount=1
```
Sender logs:
[sender.log](https://github.com/raiden-network/light-client/files/5376924/sender.log)
Receiver logs:
[receiver.log](https://github.com/raiden-network/light-client/files/5376931/receiver.log)


Both clients indicate that the transfer was successful. I can also confirm that by calling 
```
http localhost:5001/api/v1/payments

**Comment by eorituz** [comment]
@andrevmatos thank you for having a look at it.

Reinstalled the light-client on both machines using the latest master and the Tx work as expected.
