### ISSUE TITLE
Check for compatibility with the Raiden client and contracts it is running with

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#226]
## Description

@eorituz was running into [an issue](#224 ), that the light client SDK can only send token transfers to a Red Eyes client. The user needs to get a good error message or warning if the clients are not compatible. 

Related Raiden issue https://github.com/raiden-network/raiden/issues/3283

CC @hackaugusto 

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by eorituz** [comment]
I'd like to add that not only the clients need to have the same version but they also need to refer to the same smart contract! 
(So the python RedEyes client e.g. talks to different smartcontracts when started in `--environment-type production` or with `--environment-type development`)

**Comment by christianbrb** [comment]
@eorituz Thanks a lot for opening this issue. It is an issue we definitively need to solve. There is a duplicate issue #786 

Closing this one in favor of #786 

CC @karlb @Dominik1999
