### ISSUE TITLE
Use correct server list for mainnet

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2263]
## Description

Currently the list of available matrix servers is hard coded to the list of goerli testnet servers.
https://github.com/raiden-network/light-client/blob/c79d70f93b71d9d11c83c1c7403615d43811df7f/raiden-ts/src/config.ts#L116-L117

Depending on the network the list should be adapted.

## Acceptance criteria
- Use the correct server lists for at least goerli and mainnet

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
It was dynamic before, but it got removed when we disabled mainnet support. It's on a `makeDefaultConfig` which receives the current `network`, so it's just a matter of changing the list URL on a per-network basis.
