### ISSUE TITLE
Add Cypress tests for closing/settling channel

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2274]
## Description
Currently, we are lacking one test in our Cypress e2e setup, closing/settling channel.

## Acceptance criteria
- We want to have a shorter default settlement timeout (as low as 20) to reduce the run time of the tests.
- The settlement and reveal timeout is set to 20 blocks.
- We do not implement the direct mining of a given block

**Comment by palango** [comment]
@taleldayekh I opened a bug for the issue we found in the python client yesterday: https://github.com/raiden-network/raiden/issues/6632
