### ISSUE TITLE
MetaMask - RPC Error: execution reverted: deposit not increasing

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2275]
## Steps to Reproduce
1. Deposit tokens to the UDC 
![udc_deposit_screen](https://user-images.githubusercontent.com/15123108/96572378-60c36f00-12ea-11eb-9bf3-51c9d91ee8cb.png)

2. Withdraw tokens from the UDC. They would get withdrawn to the raiden account. These tokens are kept as it is in the raiden account.

3. Again deposit to the UDC. The UDC has 0 SVT token balance(because we just withdrew in the previous step).
 
![execution_reverted_deposit_not_increasing](https://user-images.githubusercontent.com/15123108/96573000-2c9c7e00-12eb-11eb-98ec-0d7ef071ec78.png)

## Expected Result
- Ideally the user should be able to deposit and withdraw tokens as he wishes.

## Actual Result
 ```
inpage.js:1 MetaMask - RPC Error: execution reverted: deposit not increasing {code: -32603, message: "execution reverted: deposit not increasing", data: {…}}
```

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by andrevmatos** [comment]
Thank you, Sohan, for this report. This is something simple which slipped through our eyes.
On https://github.com/raiden-network/light-client/blob/aa524a2f0ab4a5c30ba1e20163ad5b0a6d65796d/raiden-ts/src/raiden.ts#L1202 we're fetching UDC balance as seen by `latest$`, which is the `effectiveBalance`. For the deposit, we must instead calculate the new total deposit based on the UDC's `total_deposit` method.
This is a fairly simple task. Anyone up for it?
