### ISSUE TITLE
Ditch demo001 and use raiden test servers

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#2278]
## Problem
We introduced demo001 in order to be compatible with Raiden-py on a time where we were running behind and it was moving too fast. Now, we're already compatible, and their infra allows better testing, is more up-to-date, contains multiple-servers federation and allows testing with other raiden-py nodes.

## Solution
We should shut down our demo001/testenv001 servers and default to using their transport/pfs/ms servers.
Our hub should also be moved to it.

## Acceptance criteria
- The standard Raiden test environment is used
- Demo001 should stay (to coordinate with @eorituz) 

## Tasks
- [ ] Coordinate with @eorituz -> @christianbrb

**Comment by christianbrb** [comment]
Makes sense from my perspective :)

**Comment by christianbrb** [comment]
Currently, the following tools are using the demo001 env:
- Raiden Goerli Wizard
- try.raiden.network
- workshops.raiden.network
- lightclient.raiden.network
- hub.raiden.network

If we are moving away from demo001 to the Raiden test server all of them (except workshops) would need to move to them.

This would need more frequent updates of the solutions to stay in sync with the Raiden test servers and might has in impact on their stability.

@eorituz @manuelwedler @ezdac What is your opinion?

**Comment by ezdac** [comment]
This should be a simple configuration parameter that has no effects on the persistence layer?
From my perspective there are no concerns, but I'm also not responsible for any of the services mentioned above.

**Comment by eorituz** [comment]
Mhhh the light client "default" can use the latest transport/pfs/ms servers of the python team without affecting anything else. (As long as there is the possibility to also configure the demo env servers - But AFAIK that can be done via the config file).
The Demo env is meant to stay and only be updated if there are major changes. Right now I don't see the need to bump the demo env and therefore I'd keep all raiden solutions running with demo001.

**Comment by christianbrb** [comment]
Note to myself. We have to make a decision about the Raiden hub

**Comment by manuelwedler** [comment]
In my opinion it would be easier to stick to one environment if we can be sure that it is stable. For example Jacob had a problem at the last workshop where someone was not able to connect a manually started Raiden client with one started with the Wizard, because they run on different environments. But this could also be solved by documenting the demo environment. 

I feel like the Wizard should be on the same environment as the hub, because they can be used in combination to quickly try out Raiden and send some payments without having to run a second node.

**Comment by christianbrb** [comment]
@manuelwedler @eorituz @ezdac Thanks for your input.

@palango This is the comment, which needs to be considered: https://github.com/raiden-network/team/issues/666#issuecomment-551632187

**Comment by palango** [comment]
I discussed this with different people and try to summarize here.

My understanding is that the consensus is that the demo env makes sense and should be kept. The main reason is to decouple enduser-focusing activities from development-related tasks.

### Pros
- Development can happen without fear of interfering with demos/workshops

### Cons
- Additional maintenance
- Unclear environments for users that start their own node without the wizard (see https://github.com/raiden-network/light-client/issues/2278#issuecomment-721748071)

### Open Questions
- Should the demo env be updated to the latest RSB version?
- Does the demo env need a hosted version of the light client?
- Adjust hosted light client (lightclient.raiden.network) to use demo env?

**Comment by ezdac** [comment]
> Does the demo env need a hosted version of the light client?

Definitely - when we plan to continue using the demo env as stable deployment environment for the Demos, this should also stay the default for testnet.

> Adjust hosted light client (lightclient.raiden.network) to use demo env?

The hosted version currently already uses the demo env when used with a Goerli metamask account.

**Comment by palango** [comment]
Thanks @ezdac . I missed that `staging` runs on the demo env.

So from my side what needs to be done is:
- Add another staging deployment running on the test servers (goerli)
- Add a hub to the test environment

Alternatively we help @eorituz setting up the light client for the demo env and move staging to the test env.

@christianbrb Opinions?

**Comment by ezdac** [comment]
>  I missed that staging runs on the demo env.

Maybe I'm missing something here, but when I use `lightclient.raiden.network` (not only `/staging`),
the config shows me e.g. `"matrixServer": "https://transport.demo001.env.raiden.network"`.

The initial issue description asks wether moving the default demo env to the default py-raiden env makes sense:
> .. default to using their transport/pfs/ms servers. ...

**Comment by christianbrb** [comment]
Proposal:
https://lightclient.raiden.network/ -> Demo001 + official release
https://lightclient.raiden.network/pre-release -> test001 + pre-release
https://lightclient.raiden.network/staging -> test001 + master

**Comment by palango** [comment]
Discussed with @eorituz 
We will add a demo env deployment of the stable lightclient to lightclient.raiden.network/demo

This allows us to handle the other deployments like we want while having a stable light client for the demo env.

**Comment by manuelwedler** [comment]
Does this make any changes necessary to our other tools?
Will the demo environment get updated?

**Comment by eorituz** [comment]
@manuelwedler I will update the demo env every once in a while (As soon as there is a major improvement to the current demo env)

Changes to the raiden solution bundle will only be needed once the demo env is actually upgraded. But I don't see that happening in the next two months.

**Comment by andrevmatos** [comment]
Ok, how about this compromise:
- We leave `demo001` transport and services online and connected to each other, as they are, but add them to the transport federation whitelist.

Rationale: the main motivation for this issue is that the goerli nodes use the same registry and TokenNetworks (therefore seem like a single network) but they can't talk on transport level, leading to several problems. If we just allow them to talk, the stable environment will continue to use the configured, outdated but stable transport and PFSs,  but shouldn't be negatively affected by the transport networks talking to each other. At the same time, if it happens that nodes are purposefully connected to each other from the different transport servers, we won't see this weird behavior when they think they're in the same TN but not quite since they can't see each other as online. No need to add the demo001 transport to the available servers list, just to the federation whitelist.

Same demo stability when only using clients connected to the stable transport and services, but no more bugs due to disjoint federation network. This should be fairly easy. cc @ulope

**Comment by taleldayekh** [comment]
Closing, we have issue #2514 about tackling this.
