### ISSUE TITLE
Add information on how to use the Light Client with a private network or unlimited Red Eyes contracts.

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#228]
## Description

During initialization of the Light Client [raiden.create](https://github.com/raiden-network/light-client/blob/master/raiden/src/raiden.ts#L241) the deployment information of the smart contracts, which the receiving Raiden Full Client is using needs to be provided.
Searching the deployment information manually is a pain in the ass atm :D

CC @eorituz @pirapira 

Related to #226 and https://github.com/raiden-network/raiden-contracts/issues/1000

## Solution
- Add information on how to use the Light Client with a private network or unlimited Red Eyes contracts.
- Add this information to a new wiki page
- Link the new page to the readme

## Tasks
- [ ]

**Comment by christianbrb** [comment]
A first solution might be to tie an SDK release to specific smart contracts as it is done with raiden-libs and the smart contracts (as far as I have understood it)

**Comment by kelsos** [comment]
I have created a [draft](https://hackmd.io/@kelsos/HyXl8JuVr)

**Comment by kelsos** [comment]
The draft has been added to the wiki https://github.com/raiden-network/light-client/wiki/Using-the-SDK-in-a-private-chain-or-a-development-environment
