### ISSUE TITLE
PFS2 Error performing REST-API call: open_channel

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2293]
## Steps to Reproduce
1. 
2. 

The logs will be updated shortly
Scenario pfs2_simple_no_path Failed
## Expected Result
- 

## Actual Result
- 

## Tasks
- [ ] Giving the whole light client team access to the logs @palango

**Comment by christianbrb** [comment]
Might be related to the retry async solution

@palango to attach the logs

**Comment by palango** [comment]
We had to adjust some server settings and during re-deployment the logs were lost. Nothing we can do here now.
