### ISSUE TITLE
BF1,2,4,6,7  PF6,9 gets Insufficient balance (0.23356111006324348 Eth) in account

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2296]
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 

`Insufficient balance (0.23356111006324348 Eth) in account 0x8f5EA3Bb3E99C317b8745918F6973f7AfBF659c3 on chain “5” - it needs additional 0.2664388899367565 Eth (that is 266438889936756531 Wei).`
Likely all the failures have a common cause
## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by palango** [comment]
This means that the SP account had to few Eth to run the scenarios. We filled the account.
