### ISSUE TITLE
Make unsafe (remaining lock timeout < reveal_timeout) transfers traceable

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2297]
In #2210 we had some problems because the python client didn't continue a payment that it deemed unsafe (remaining lock timeout < reveal_timeout) and didn't show that information.

We have the same check and don't log a potential error either.

https://github.com/raiden-network/light-client/blob/d65362c267857d1643194d47915948760d4beedd/raiden-ts/src/transfers/epics/locked.ts#L494-L510

## Tasks
- [x] Log a message describing the problem

**Comment by christianbrb** [comment]
Logging isn't working
