### ISSUE TITLE
Don't handle reveals when 'receive' capability is off

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2299]
## Description

Currently the `RECEIVE` capability stops the client from asking for the secret:
https://github.com/raiden-network/light-client/blob/d65362c267857d1643194d47915948760d4beedd/raiden-ts/src/transfers/epics/locked.ts#L494-L510

If a `SecretReveal` was received (shouldn't happen) the client would handle it.

## Acceptance criteria
- 

## Tasks
- [x] Add the same capability check to the `transferSecretRevealEpic`
- [x] Expand and adjust tests

**Comment by christianbrb** [comment]
@palango Thanks for opening the issue :)

What is the problem here?

**Comment by andrevmatos** [comment]
@christianbrb I tried to describe it in the body of the PR. It's a very edgy case, and not a "risk", just consistency
