### ISSUE TITLE
BF1 gets No route between nodes found

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2303]
## Thanks for filing a bug report :-)
Failure dates 31st Oct and 01, 02 November 2020
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
`HTTP status code “409” while fetching http://127.0.0.1:39243/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x66E7d2dC38f884024Ba8B8F95D9d7a4E8a8566ff. Expected 2..: {“message”:”No route between nodes found.”,”details”:””}`

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by andrevmatos** [comment]
This is a PFS presence issue. @palango any chance of we ensuring our scenario runs are in a different time than raiden-py's?

**Comment by agatsoh** [comment]
Same issue today just writing down for book keeping
[scenario-player-run_bf1_basic_functionality_2020-11-02T21:14:14.log](https://github.com/raiden-network/light-client/files/5481582/scenario-player-run_bf1_basic_functionality_2020-11-02T21.14.14.log)

**Comment by andrevmatos** [comment]
@agatsoh scenario player logs aren't useful here, we need the node's logs.
Anyway, this error is definitely a presence issue on PFS, nothing to do on our side, so I'm closing it.

**Comment by agatsoh** [comment]
We encountered this error again today in PFS4
```
{
  "task": "<TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200, 'identifier': 160420145141000001}>",
  "event": "Task errored",
  "logger": "scenario_player.tasks.base",
  "level": "error",
  "greenlet_name": "orchestration",
  "timestamp": "2020-12-08 01:39:51.224464",
  "exception": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__\n    return_val = self._run(*args, **kwargs)\n  File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run\n    f'HTTP status code \"{resp.status_code}\" while fetching {url}. '\nscenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:40671/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x82b0301892eDA8DA0341Cb2fCC00F7016Cdd5C76. Expected 200: {\"message\":\"No route between nodes found.\",\"details\":\"\"}"
}
```


Failed at:
```
TransferTask: {'from': 0, 'to': 3, 'amount': 1000000000000000, 'expected_http_status': 200, 'identifier': 160420145141000001}
```

**No route between nodes found**

Traceback (most recent call last):
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/base.py\", line 140, in __call__
return_val = self._run(*args, **kwargs)
File \"/usr/local/lib/python3.7/site-packages/scenario_player/tasks/api_base.py\", line 59, in _run
f'HTTP status code \"{resp.status_code}\" while fetching {url}. '
scenario_player.exceptions.RESTAPIStatusMismatchError: HTTP status code \"409\" while fetching http://127.0.0.1:40671/api/v1/payments/0x59105441977ecD9d805A4f5b060E34676F50F806/0x82b0301892eDA8DA0341Cb2fCC00F7016Cdd5C76. Expected 200: {\"message\":\"No route between nodes found.\",\"details\":\"\"}


Node0 logs
```
2020-12-08T01:39:51.219Z [info] %c action     color: #03A9F4; font-weight: bold {
  type: 'path/find/failure',
  payload: RaidenError: No route between nodes found.
      at /lc/index.js:249342:23
      at Generator.next (<anonymous>)
      at Observable._subscribe (/lc/index.js:209078:29)
      at Observable._trySubscribe (/lc/index.js:198183:25)
      at Observable.subscribe (/lc/index.js:198169:22)
      at Object.innerSubscribe (/lc/index.js:199250:23)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._innerSub (/lc/index.js:204040:50)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._tryNext (/lc/index.js:204034:14)
      at MergeMapSubscriber.module.exports.__webpack_modules__.42713.MergeMapSubscriber._next (/lc/index.js:204017:18)
      at MergeMapSubscriber.module.exports.__webpack_modules__.65183.Subscriber.next (/lc/index.js:198786:18) {
    details: {}
  },
  meta: {
    tokenNetwork: '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3',
    target: '0x82b0301892eDA8DA0341Cb2fCC00F7016Cdd5C76',
    value: BigNumber { _hex: '0x038d7ea4c68000', _isBigNumber: true }
  },
  error: true
}
```
SP logs 
[scenario-player-run_pfs4_use_best_path_2020-12-08T01:33:42.log](https://github.com/raiden-network/light-client/files/5658648/scenario-player-run_pfs4_use_best_path_2020-12-08T01.33.42.log)


Node logs:
[pfs4_node0_node3_8thDec2020.tar.gz](https://github.com/raiden-network/light-client/files/5658650/pfs4_node0_node3_8thDec2020.tar.gz)

**Comment by agatsoh** [comment]
Same error on PFS5
[scenario-player-run_pfs5_too_low_capacity_2020-12-08T01:40:00.log](https://github.com/raiden-network/light-client/files/5658748/scenario-player-run_pfs5_too_low_capacity_2020-12-08T01.40.00.log)

**Comment by agatsoh** [comment]
https://github.com/raiden-network/light-client/issues/2433 is a duplicate of this issue

**Comment by agatsoh** [comment]
Same error observed on PFS6 on 6thDec 2020

[pfs6_node3_node0_6thDec2020.tar.gz](https://github.com/raiden-network/light-client/files/5659156/pfs6_node3_node0_6thDec2020.tar.gz)
[scenario-player-run_pfs6_simple_path_rewards_2020-12-06T00:24:40.log](https://github.com/raiden-network/light-client/files/5659157/scenario-player-run_pfs6_simple_path_rewards_2020-12-06T00.24.40.log)

**Comment by agatsoh** [comment]
Occured again on 1st Jan 2021 logs are attached as follows

[scenario-player-run_pfs6_simple_path_rewards_2021-01-01T04:00:46.log](https://github.com/raiden-network/light-client/files/5758919/scenario-player-run_pfs6_simple_path_rewards_2021-01-01T04.00.46.log)
[pfs6_node3_node0_1stJan2021.tar.gz](https://github.com/raiden-network/light-client/files/5758921/pfs6_node3_node0_1stJan2021.tar.gz)

**Comment by agatsoh** [comment]
4th Jan 2021 Failure logs are attached

[scenario-player-run_bf1_basic_functionality_2021-01-03T21:02:13.log](https://github.com/raiden-network/light-client/files/5763356/scenario-player-run_bf1_basic_functionality_2021-01-03T21.02.13.log)
[bf1_node3_node0_4thJan2021.tar.gz](https://github.com/raiden-network/light-client/files/5763359/bf1_node3_node0_4thJan2021.tar.gz)

**Comment by agatsoh** [comment]
3rdJan 2021 failure logs are attached for PFS5

[scenario-player-run_pfs5_too_low_capacity_2021-01-03T00:09:51.log](https://github.com/raiden-network/light-client/files/5763376/scenario-player-run_pfs5_too_low_capacity_2021-01-03T00.09.51.log)


[pfs5_node0_node3_4thJan2021.tar.gz](https://github.com/raiden-network/light-client/files/5763395/pfs5_node0_node3_4thJan2021.tar.gz)
