### ISSUE TITLE
PFS9, 6, 3, 1. MS3. BF6, 7, 4, 3, 2 get Insufficient balance in account error

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2304]
## Steps to Reproduce
1. 
2. 

## Expected Result
- 

## Actual Result
- 
`Insufficient balance (0.3269447117662875 Eth) in account 0x8f5EA3Bb3E99C317b8745918F6973f7AfBF659c3 on chain “5” - it needs additional 0.1730552882337125 Eth (that is 173055288233712503 Wei).`

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by palango** [comment]
@Dominik1999 [filled the account again](https://goerli.etherscan.io/tx/0xaf88c068a77deef511b9f5a563f0835033ec013907ad5289592b39b237e4cc96) and I'm going to adjust the reclaim interval to something shorter.
