### ISSUE TITLE
I want to be informed that I have to withdraw my RDN / SVT tokens on the UDC screen first

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2307]
## Description
As Chris I want to be informed that I have to withdraw my RDN / SVT tokens on the UDC screen first so that I can withdraw them afterwards on the withdrawal screen.

## Acceptance criteria
- Link to the UDC screen
- Show the information area
- Existing color variables
- Smallest text font 12px

## Tasks
- [x] Design @sashseurat 

## Design
[The click-dummy](https://www.figma.com/proto/5H8EOoC2SntoXZuTtUZsyY/LC-UDC-Screen-Optimisation?node-id=29%3A145&viewport=-1797%2C-97%2C1&scaling=min-zoom)

<img width="506" alt="Screenshot 2020-11-05 at 09 51 11" src="https://user-images.githubusercontent.com/32264127/98218858-8e482380-1f4c-11eb-91f5-5d76e317946c.png">

**Comment by sashseurat** [comment]
@taleldayekh @christianbrb @weilbith 
Link to Figma click-dummy containing the Withdrawal screen with link to UDC, ready for review:

https://www.figma.com/proto/5H8EOoC2SntoXZuTtUZsyY/LC-UDC-Screen-Optimisation?node-id=29%3A145&viewport=-257%2C502%2C0.3179304003715515&scaling=min-zoom

Here is a screenshot:
<img width="504" alt="Screenshot 2020-11-04 at 15 00 22" src="https://user-images.githubusercontent.com/32264127/98120699-9487c280-1eae-11eb-8740-5e8c210ab9ae.png">

**Comment by christianbrb** [comment]
@sashseurat Thanks a lot :) 

My remarks:
- I would use a lighter grey for the explaining text -> more towards white as this one is hard to read
- Explaining text at least 12px
- Button -> White text on turqoise as we do for the other buttons
- The screen might benefit from a grey area for the tokens as you did it for the explainatory text and on the transfer screen.

**Comment by weilbith** [comment]
> I would use a lighter grey for the explaining text -> more towards white as this one is hard to read

According to her design explanation this is intended. And I think she has a point there. The user should not get distracted by this text. He should not first read this notice. He first gets an independent impression of the screen structure and when he starts to interact and go into details he will read this message. And at least for me this is pretty easy to read.

**Comment by sashseurat** [comment]
> @sashseurat Thanks a lot :)
> 
> My remarks:
> 
> * I would use a lighter grey for the explaining text -> more towards white as this one is hard to read

Thore's explanation is correct. This can also be tested very easily.

> * Explaining text at least 12px
it is

> * Button -> White text on turqoise as we do for the other buttons

The explenation I gave for choosing to style these buttons differently than in the transfer screen is here again true.
"I made a conscious decision to not have the same styling to the buttons as in the transfer screen. This screen is similar to a settings screen, and its functions should not seem to User as primary in the dApp. This is common."

> * The screen might benefit from a grey area for the tokens as you did it for the explainatory text and on the transfer screen.
I can do this quickly and ping you when the click-dummy is ready

**Comment by sashseurat** [comment]
@christianbrb [click-dummy is ready](https://www.figma.com/proto/5H8EOoC2SntoXZuTtUZsyY/LC-UDC-Screen-Optimisation?node-id=29%3A145&viewport=-1797%2C-97%2C1&scaling=min-zoom) with the gray area for the ready token items, here is a screenshot:
<img width="506" alt="Screenshot 2020-11-05 at 09 51 11" src="https://user-images.githubusercontent.com/32264127/98218858-8e482380-1f4c-11eb-91f5-5d76e317946c.png">

**Comment by weilbith** [comment]
This issue is blocked until the two related issues with their PRs are done.
The problem is that we now have ended up with a horrible design hybrid. Partially we use the components from Vuetify and custom ones. So we have now two versions of the "action"-button design. 
Anyway we have already two "implementations" of this new button in two complete different setups (main account menu using a Vuetify list with all its special sub-components and the other version at the UDC screen with pure HTML and CSS). These two differ heavily and therefore were kinda acceptable up to this moment. Now we need the basic implementation again here. So we must export this as a new custom component of us. There we should attempt to make this also working for the account menu.
After all this will cause merge-conflicts with the open PRs as this will refactor them. Since we have already two dependent PRs that need a rebase, I will not open another one yet.

**Comment by weilbith** [comment]
Quick note:
I contacted Talel and the info section that is shown here should not be integrated into his new feature of #698 as we did (plan) for the UDC screen before.
