### ISSUE TITLE
I want to know how much blocks are left until I can withdraw my RDN / SVT from the main account

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2308]
## User Story
As Chris I want to know how much blocks are left until I can withdraw my RDN / SVT from the main account so that I can get them.

## Acceptance criteria
- It is shown on the UDC screen
- I want to see the number of remaining blocks until the planned withdraw is complete
- I want to see the amount of RDN / SVT on the planned withdrawal
- We use our existing colors
- There is another issue for the rest of the screen https://github.com/raiden-network/light-client/issues/2220
- A refactoring to split the stores is done

## Design
[The click-dummy](https://www.figma.com/proto/5H8EOoC2SntoXZuTtUZsyY/LC-UDC-Screen-Optimisation?node-id=14%3A27&viewport=-1799%2C1629%2C1&scaling=min-zoom)
- Click on the Withdraw button to see the complete design

One part:
![grafik](https://user-images.githubusercontent.com/35398162/98555538-59b4ce80-22a2-11eb-8bf4-dad3e40a46a5.png)

## Remark
- Are several planned withdrawals possible at a time? -> No it is not.

## Tasks
- [x] Design @sashseurat (can be done together with #2220)
- [ ] Write down the software design @weilbith

**Comment by weilbith** [comment]
This requires a small new function in the interface of the SDK. This should work pretty much similar to how we get token balances. This means it does not use the state machine and doesn't dispatch any action or event. It simply provides an easy method to query the user deposit contract for planned withdraws for the SDK user. This then simply gets queried on the account UDC screen of the dApp. Similar to the account withdrawal screen this will require to show a loading state while the SDK reads data from the blockchain. This will be just a `mounted` hook of the Vue component as use already there.
After all this is a pretty simple solution with a high impact. It should be very simple to add.

**Comment by weilbith** [comment]
@christianbrb do you want any end-to-end tests for this feature?

**Comment by christianbrb** [comment]
@weilbith No, I don't think so.
