### ISSUE TITLE
Upgrade infrastructure to Node 14

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2311]
Upgrade infrastructure to Node 14

**Comment by andrevmatos** [comment]
[Yarn is already installed on `circleci/node` images](https://circleci.com/docs/2.0/yarn/), gladly one less Docker image for us to maintain

**Comment by andrevmatos** [comment]
A reference of good options for TypeScript + NodeJS v14:
https://stackoverflow.com/questions/61305578/what-typescript-configuration-produces-output-closest-to-node-js-14-capabilities/61305579#61305579
Our ESM build isn't fully compatible with Node's restrictions yet, there're some things which would need to be made, including adding `.js` extension to all of our local imports, but we can look at it in the future.
