### ISSUE TITLE
Scenarios failed due to geth nodes unreachable

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2313]
## Description

`HTTPConnectionPool(host='geth.goerli.ethnodes.brainbot.com', port=8545): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72f204606710>: Failed to establish a new connection: [Errno 111] Connection refused'))"}`

Possibly caused by geth nodes not responsing
## Acceptance criteria
- [ ] Healthcheck of the geth nodes which the SP raiden nodes rely upon 

[scenario-player-run_pfs9_partial_withdraw_2020-11-03T01:14:12.log](https://github.com/raiden-network/light-client/files/5480822/scenario-player-run_pfs9_partial_withdraw_2020-11-03T01.14.12.log)

## Tasks
- [ ]

**Comment by palango** [comment]
There's nothing the LC can do if the client is not reachable.
