### ISSUE TITLE
Inform user about metamask crash while using the application and come out

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2321]
## Steps to Reproduce
1. Accept disclaimer 
2. Connect
3. Crash metamask (eg. on Firefox enter `about:performance` and end the MetaMask-Task)

## Expected Result
- Dapp should inform that metamask has crashed and he needs to reload it. Come out of it to the Disclaimer or Connect screen

## Actual Result
- Blockchain related interactions are not giving feedback (eg. spinner is spinning forever on deposit)

**Comment by taleldayekh** [comment]
Do you have any more details about the "weird" errors? 😀

**Comment by agatsoh** [comment]
@taleldayekh  I will once more test it out and post examples or errors here.

**Comment by agatsoh** [comment]
One scenario for example once the metamask crashes can be seen, 
I dont know why I am not getting the UI errors but just as an example,
you are on the transfer screen and metamask crashes. 
You are still not aware that metamask just crashed.
![metanask_crash_issue](https://user-images.githubusercontent.com/15123108/98249431-3afdc180-1f9c-11eb-9ba8-89b116da1256.png)
You enter the Address of the user and the amount and click `Continue`
and the spinner keeps spinning without you getting an idea that metamask has crashed. 
This is one scenario i faced, in each screen depending on when metamask crashes there 
can be different errors.

**Comment by christianbrb** [comment]
@christianbrb to reproduce it

**Comment by christianbrb** [comment]
It is reproducible. The dApp doesn't realize, that MetaMask is not working.
The logs don't show an error.

**Comment by christianbrb** [comment]
See https://github.com/raiden-network/light-client/issues/2375 for more information
