### ISSUE TITLE
sdk - add interface method to get planned UDC withdrawals

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2322]
## Description

Related to #2308 we need more access to the data of the UDC contract. I.e. entries of the planned withdrawals mapping with the users address(s). This is hard to do in the dApp itself. But the SDK has everything needed already there. The idea is to offer a simple method like we have already to get token balances. There is no need to extend the whole state machine in any kind. It is only about reading some information from a contract via the connected Ethereum node

## Acceptance criteria
- SKD has method to get a list of planned withdrawals for the account the SDK got instantiated with

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
There may only be one planned withdraw at a time. A new one while there's a pending will replace the previous. It's exposed mostly as an amount and a blockNumber. If blockNumber is in the future, it's pending; if it's in the past, it's available and ready to be performed; I think it resets to `0` after the withdraw is performed.

**Comment by weilbith** [comment]
Thanks Andre! :pray:

**Comment by weilbith** [comment]
I should have consulted you earlier. My plan was just do add 2 lines of code to the Raiden class. I'll look into your hints. Sounds very good and we should re-use that.

**Comment by weilbith** [comment]
I think this issue has no point. I did a bad research. Everything is already there.

**Comment by andrevmatos** [comment]
The action has a `payload.block` property which can inform you on when is the current/next planning expiration block. It's also emitted on startup (for past plannings). You can rely on it, if you can keep track of latest emit. If you don't want to keep track of it, and ask SDK explicitly, then yes, you'd need a new method on the `Raiden` class.

**Comment by weilbith** [comment]
Can I safely remove planned withdrawls after the `withdrawn` event?

**Comment by andrevmatos** [comment]
Yes. Just bear in mind the workflow here:
```
plan ->100 blocks -> +confirmation blocks -> withdraw -> +confirmation blocks -> withdrawn (confirmed)
```

**Comment by weilbith** [comment]
Yes. So after plan, I see a successful withdraw action with the block when the final withdraw is possible. Special feature is now that the SDK is doing this then automatically. If this transactions succeeds, we get a withdrawn action.
We should consider to rename at least the first action. withdraw and withdrawn are not really well distinguishable.

**Comment by andrevmatos** [comment]
Yes, maybe.. the issue here is that `withdraw` is an async action, so it has `udc/withdraw/request`, `udc/withdraw/success` and `udc/withdraw/failure`; the confusion is between `udc/withdraw/success` (which represents when a withdraw was successfully planned/queued) and `udc/withdrawn`, which represents when it got completed (i.e. made effective by 2nd tx). Since async actions can only have one respective success, we had to rename the _success success_ action to `withdrawn`; maybe a better name would be `udc/withdraw/complete`. Feel free to rename it ;)

**Comment by weilbith** [comment]
Haha, but humans are those who read and maintain the code. :stuck_out_tongue_winking_eye: 
I'll see if I'm motivated enough to rename it. But actually I had more in mind to actually bring the word `plan` into the game.  Because having successful and completed together is also not really helpful.
But this is definitely not part of this issue (or its parent).
