### ISSUE TITLE
sdk-integration-tests: runtime regression

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2324]
Recently runtime of the `sdk-integration-tests` went from 6mins to 12mins. We should investigate if we can recover some/all of those losses.

@andrevmatos noted that https://github.com/raiden-network/light-client/pull/2289 might be the culprit:
> A nice and easy way to optimize that by a lot would be to make our integration tests use-case based, instead of testing each function separately
> e.g. a happy case test: channel open -> deposit -> transfer -> withdraw -> close -> settle -> unlock
> than failure cases for individual steps, possibly making better use of the snapshoting feature of ganache (we already have utils for it)
> This way, we could decrease the number of integration tests by a lot, and allow finer-granularity tests to depend on a given previous state (e.g. sneaking in a get channels$ test after channel got opened on the happy case test
> Most of the time is spent on setting up and resetting these integration tests
> I know “mixing” tests isn’t very good, but since the setup times here are so long, and we already have extensive unit tests, maybe we could consider this refactoring..pretty sure we could get it down to a couple of minutes at most
> The subkey integration test is an example of a more extensive test which works very well, and is fast despite testing maybe half of what the other tests does (but here using the subkey)

**Comment by andrevmatos** [comment]
#2417 improved a lot on this, integration tests there are taking 7min, but we should still refactor this at some point in the future
