### ISSUE TITLE
dapp: handle blockchain event related notifications properly according to confirmation property

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2334]
## Description

Talel and I introduced the cool feature that notifications can have the optional properties of a target block number when this event becomes done/ready/finished/... This allowed us to introduce automatically a block counter in the notification card. When the counter reached zero, it was shown as successful. In the meantime, the rest of the whole notification remained the same.

This has some things we forgot here. We correctly handle that there could a `success` or `failure` variant of the event we see form the SDK. When we see success event and it is blockchain related the confirmation state is always undefined for the first time. Depending on the confirmation blocks this remains like that (events gets emitted for each new block again) until the confirmation property changes to a boolean value. This can be either `true` if the associated transaction got confirmed or `false` if there was a reorg of the blockchain. 
There are now two issues. First we never handle the case that the transaction could get reorged. Second we never care about the confirmation state itself. As soon as the counter reaches zero, we made it a confirmed notification. 

So we need to evaluate the confirmation property of an event. This should not be handled by the "stupid" notification card which shows the counter if required (i.e. it is a blockchain related notification). But the module which commits the notification object to the store need to do. We have introduced the option to update already existing notifications. This will allows to replace the "pending" notification with a counter with a different notification object that is a success or informs about an reorg issue. This issue differs from the error notification caused by a `failure` event. Thereby the notification card can remains simple, showing the counter if there is a given target block number in relation tot he current block number. The event listener is then responsible to watch out for the confirmation state and then replace the notification (as we do always, also for continuous unconfirmed events, just that they replace the object with itself [kinda stateless here]) with a success of reorg one.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by weilbith** [comment]
This kinda acts as preparation for #2308
Talel and I have evaluated that we should correct this first.

**Comment by christianbrb** [comment]
@weilbith is going to submit the PR for review and creates a new issue for further improvements

**Comment by weilbith** [comment]
I opened the issue that was asked for. I now rebase the PR to include the fixup commits. When the CI runs through successfully, I'll merge it afterwards.
