### ISSUE TITLE
Document how to debug the SDK while running the light client

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#234]
## Description

Follow up of #220 
Document how to debug the SDK while running the light client

## Acceptance criteria
- Description how to debug with Unit Tests in Jest
- How to check Matrix is included
- Describe how to call the public methods
- Redux Logger output is described

## Tasks
- [ ] Debugging session @andrevmatos @nephix 
- [x] Documenting it

**Comment by andrevmatos** [comment]
Added docs in https://github.com/raiden-network/light-client/wiki/SDK-Development/de9dd07fb5e1e1fe12566e1904c824bd8c4bb3e3

**Comment by nephix** [comment]
Perfect, thank you. Closing this one
