### ISSUE TITLE
Add to wiki how to add what kind of tests

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#235]
### Description
Follow up of #220 
A short paragraph about how to add what kind of tests

### Acceptance Criteria
- I know what kind of tests we have after reading it
- I know how to add new tests
- It is aligned with the contributing guide
- No end-to-end tests
- Just documenting what we have right now
- No specification

**Comment by andrevmatos** [comment]
Done in https://github.com/raiden-network/light-client/wiki/SDK-Development/c0e3493fc201df5fad83209c630fd37e42b84647

**Comment by nephix** [comment]
Looks good to me, thanks! I'm closing this one
