### ISSUE TITLE
SecretRequest never arrives at py-raiden node

### ISSUE THREAD

**Issue by ezdac** [raiden-network/light-client#2352]
Not sure wether this is light-client related, py-raiden or protocol related.
This seemed to work before the latest update at `lightclient.raiden.network`

## Steps to Reproduce
1. Open funded direct channel from py-raiden-sender node (on goerli, demo env) with current `lightclient.raiden.network` node
2. Send transfer to lightclient node 
```
partner='0x1308501A72870E541D963fB8D5D58e953b03d475', token='0xC563388e2e2fdD422166eD5E76971D11eD37A466',identifier=1112222, amount=111
```

## Expected Result
- py-raiden receives SecretRequest, answers with appropriate messages
- lightclient receives secret, transfer is successful

## Actual Result
- transfer stays pending in lightclient until the Lock expires
- py-raiden keeps on retrying sending the transfer, which is ignored by the lightclient (since it knows it already)
- py-raiden never receives the SecretRequest at [_handle_sync_messages()](https://github.com/raiden-network/raiden/blob/b150d634d23218172bc635e864e4676d4689c75d/raiden/network/transport/matrix/transport.py#L1131)

Additionally, py-raiden seems to keep on retrying transfers, that the lightclient recognizes as already expired.

## Additional Infos (Optional) 
```
- py-raiden `1.1.1` as the sender of the transfer
- Chrome 86.0.
- MacOS 10.15.7
```
[raiden_0x1308501A72870E541D963fB8D5D58e953b03d475_2020-11-11T14_04_33.162Z.log](https://github.com/raiden-network/light-client/files/5524500/raiden_0x1308501A72870E541D963fB8D5D58e953b03d475_2020-11-11T14_04_33.162Z.log)
[raiden-debug_2020-11-11T14:03:07.968206.log](https://github.com/raiden-network/light-client/files/5524502/raiden-debug_2020-11-11T14.03.07.968206.log)

**Comment by christianbrb** [comment]
According to @andrevmatos it might be a presence issue

**Comment by christianbrb** [comment]
### Solution

Let's first do:
1. Ignore presence for messages, which are reactions to our messages

If the presence bug is still present afterward to go with:
2. Use to-device queuing

**Comment by christianbrb** [comment]
Maybe related: https://github.com/raiden-network/raiden/pull/6708
