### ISSUE TITLE
dApp does not connect after deleting all local data

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2360]
## Steps to Reproduce
1. Open a channel on https://lightclient.raiden.network/
2. Make transfers
3. Delete Cache, Cookies, IndexedDB, LocalStorage and Session Storage
4. Go to https://lightclient.raiden.network/
5. Accept the disclaimer
6. Generate Raiden Account

## Expected Result
- I am on the transfer screen and see my full deposit as capacity

## Actual Result
- The spinner on the connect button is spinning

[raiden_2020-11-13T09 00 37.777Z.log](https://github.com/raiden-network/light-client/files/5535801/raiden_2020-11-13T09.00.37.777Z.log)

This web console error is not stored in the logs:

![grafik](https://user-images.githubusercontent.com/35398162/99049877-a5fc5900-2597-11eb-9a55-45029e846bee.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by christianbrb** [comment]
@andrevmatos This is the output, which I have shown in the daily:

![grafik](https://user-images.githubusercontent.com/35398162/99082099-00131380-25c4-11eb-8e67-48021ea64c1f.png)

**Comment by palango** [comment]
@christianbrb Is it possible that you used an really old local database? I found [this,](https://github.com/pouchdb/pouchdb/pull/7618) which indicates that pouchdb has two adapters for index DB which are incompatible.

However, the update was already done 2 month ago in  10eff40

**Comment by christianbrb** [comment]
@palango I have deleted all databases. The SDK has reinstated the databases and now it does not work.

Are you able to reproduce the issue?

**Comment by palango** [comment]
Yes, I can reproduce it.

@andrevmatos I see this place when I add a breakpoint when the exeption is thrown:
```js
function openDatabase(openDatabases, api, opts, resolve, reject) {
  var openReq = opts.versionchanged ?
    indexedDB.open(opts.name) :
    indexedDB.open(opts.name, createIdbVersion());

  openReq.onupgradeneeded = function (e) {
    if (e.oldVersion > 0 && e.oldVersion < versionMultiplier) {
      // This DB was created with the "idb" adapter, **not** this one.
      // For now we're going to just error out here: users must manually
      // migrate between the two. In the future, dependent on performance tests,
      // we might silently migrate
      throw new Error('Incorrect adapter: you should specify the "idb" adapter to open this DB');
    }

    var db = e.target.result;

    var pouchdbVersion = getPouchDbVersion(e.oldVersion);
    upgradePouchDbSchema(db, pouchdbVersion);
    maintainNativeIndexes(openReq, reject);
  };
```

**Comment by palango** [comment]
One additional thing I noticed.

After deleting all storage from the dApp I got the problem Christian describes. After deleting the storage again and an reload, the problem is usually fixed. So maybe the database is not deleted completely...

**Comment by andrevmatos** [comment]
Ok, I managed to reproduce this on Firefox only, and only in a very specific condition: the user cleared data **while** the dApp was connected.
Looks like, on Firefox at least, when we have an open DB connection and DB is deleted, next "write" call will create an empty database with `version=1` to store that write, which will then fail on pouchDB checks on next start.
It's hard to detect when database is cleared mid-runtime, and I don't think this is a usecase we should support. It's also hard to detect this and stop the SDK, since no error is thrown.
We could handle this error at startup, and clear the database if we get it, but no one should ever clear their state, and if they do, they should do it while the dApp is disconnected.
I'll try to improve a little bit the handling of this very edgy and unsupported case though.

**Comment by christianbrb** [comment]
@palango @andrevmatos Thanks a lot for your investigation.

The workaround deleting the 2nd database while being disconnected worked for me.

I am reducing the criticality to "minor". 

@andrevmatos No need for a fix from my perspective.

**Comment by christianbrb** [comment]
@andrevmatos is fixing it upstream
