### ISSUE TITLE
Multiple scenario failures because of "node did not stop cleanly"

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2361]
BF2, MS1, MS2, MS3 and PFS8 failed tonight with the message `Exception: Node X did not stop cleanly`

I could not find any obvious problems in the logs.

What's a bit strange is that the scenario runs (especially the MS ones) take little more than 5 mins, but that error should only be thrown after 10mins:
```py
    def stop(self, timeout=600):  # 10 mins
        assert self._process is not None, "Can't call .stop() before .start()"
        self._process.send_signal(signal.SIGINT)
        if self._process.wait(timeout):
            raise Exception(f"Node {self._index} did not stop cleanly: ")
```

### Logs
- [MS2.zip](https://github.com/raiden-network/light-client/files/5536150/MS2.zip)
- [MS3.zip](https://github.com/raiden-network/light-client/files/5536152/MS3.zip)

**Comment by andrevmatos** [comment]
This may happen because some or all of the nodes isn't exiting cleanly. This usually happens when a segfault crashes it on stop. I've seen that be caused only by `wrtc` (issues on native modules have higher chance of segfaults) on node12, node14 should have fixed it, but maybe some issue brought it back. We need to investigate.

**Comment by palango** [comment]
Reverting the change https://github.com/raiden-network/light-client/commit/e44f9e69026a7b989b7bef183f5bf494c92f97df#diff-60a5943f2bab4aca20494c51597bf22b7a680a4e58e2355e879d1f96b1295416L415-L416 makes it work for me again.

**Comment by andrevmatos** [comment]
Minimally reproduce example: `$ node index.js`
```js
const wrtc = require('wrtc');
const pc = new wrtc.RTCPeerConnection();
setTimeout(() => pc.close(), 5000);
```
