### ISSUE TITLE
Assess auto vs interactive request for delayed actions

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#237]
## Description

In Raiden, some operations become only available after some (considerable amount of) time after the action which triggered them, currently:
- `channelSettle` (on-chain): it becomes available only `settleTimeout` (default=`500` ~= 2h) blocks after `channelClosed`, actually retrieve the left tokens back to user's account
- `transferExpire` (off-chain): a **lock**ed transfer may only be expired (sending a new set of messages starting with `LockExpired`),  effectivelly retrieves the tokens which were locked to first try the transfer, `expiration` (default = `DEFAULT_REVEAL_TIMEOUT * 2 = 100` ~= 22min) blocks after transfer creation, retrieve tokens locked in a failed transfer, returning them to capacity

These actions have a minimum point in time after which they can be requested, but they aren't required to be performed immediately (actually not even required by protocol to be performed at all), but they're usually interesting for the user to be performed (i.e. users have an incentive to do that).

Despite that, from a UX perspective, it may be quite confusing for the user to see unrequested prompts popping up in their screen minutes, hours or even days (e.g. when they come back online) after the state changes that first caused them.

### Current state is:
- settleChannel is done only on-demand (interactively), through [Raiden.settleChannel](https://github.com/raiden-network/light-client/blob/dfac0ca77f0e86a483a59e61547c89b0d53d34a5/raiden/src/raiden.ts#L592) public method. dApp is expected to notify users somehow when they have **settleable** channels, so they can perform the settling
- transferExpire (as per #232) is done automatically, as its timeout is shorter (possibly customizable in the future) and the transfer status overlay should stay on-screen while transfer is still pending. Notice this will only take that long on the full unhappy case, which requires signing the `LockExpired` message after the lock expires.

### Proposal is to make it configurable:
- `autoSettle`: automatically calls `channelSettle` when a channel becomes settleable, or else through `settleChannel` method (interactively).
- `autoExpire`: automatically performs `transferExpire` when a pending transfer lock expires, or else through a `expireTransfer` method (interactively).

### Where we can envision a few environments and its expected defaults/best values:
1. **m2m/nodeJS/local account/privatekey** (like scripts and non-interactive systems built on top of the SDK): both autoSettle and autoExpire set, auto-managed case
2. **browser/Metamask with subkey** (#172) for signing, ETH/tokens transferred to the subkey account: same as local account case
3. **browser/Metamask with subkey** (#172) for signing, ETH/tokens kept on the main account: autoSettle=false (as it'll always trigger a prompt for the on-chain tx), autoExpire=true as off-chain messages are always signed by the subkey and therefore isn't interactive
4. **browser/main Metamask/full interactive account**: both autoSettle and autoExpire set to false, with buttons/actions on dApp to allow users to call them, as well as persistent notifications warning them when there're pending actions on channels/transfers
    * alternatively/configurable? (may apply to the subkey cases as well): either/both autoSettle/autoExpire set to true, but watch events to raise overlays/popup dialogs to the user when the **auto**-actions happen, informing them why they're being prompted to sign messages [unexpectedly]
      * alternative to this alternative: both set to false (interactive), but these popups are still raised, and the user may/must accept/dismiss them

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
For Milestone 1: receiving a transfer also may happen without notice, and requires signing some messages (e.g. `SecretRequest`). Therefore, it may also be a candidate for the auto vs interactive setting, and interactive may even allow a user to be informed about an incoming mediated transfers and possibly reject it by not requesting/revealing the secret and letting the last hop transfer lock expire.
Related: https://github.com/raiden-network/raiden/issues/3184

**Comment by taleldayekh** [comment]
Have been implemented in #2020 and #2629.
