### ISSUE TITLE
dApp: udc withdrawal plan and automatic final withdrawal user flow improvement

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2372]
## Description

During the design of showing the progress of planned UDC withdrawals we did one mistake: the last final transaction that get done automatically.

This is what happens in the SDK:
- user triggers withdrawal
- SDK does withdrawal plan transaction
- plan gets written to contract, period where services can claim IOUs starts
- period ends and user is able to claim finally the tokens
- SDK automatically detects end of period and pushes second transaction to claim remaining tokens

What do we show:
- before: no withdrawal in progress
- after trigger: withdrawal in progress in pending with block counter for period
- after period: withdrawal in progress in ready state with link to withdrawal (claim screen)
- after final withdrawal tx: no withdrawal in progress

The issue:
There is a short period in which the SDK detects that the period is over and does the transaction until seeing the mined claim transaction. In this period we show the user the ready state and the navigation link. If he follows the link he will see no tokens to transfer from Raiden to main account, since the tokens are not yet claimed from contract. But when the tokens are automatically claimed by the SDK the link to the withdrawal screen disappears (e.g. when the user closes the screen/app while the period is running).

Decided on solution:
- the ready state does not show a link but a information that the token get claimed now.
- the notification for the final token claim from the contract includes link to navigate to withdrawal/transfer screen (this also shows/works when the user was offline/away for a while)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@weilbith Nice catch :) It is important, that we implement this.
