### ISSUE TITLE
I don't see my tokens other than SVT / RDN on the withdrawal screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2376]
## Steps to Reproduce
1. Move TTT to the Raiden Account (Within this case the tokens are from a closed channel, but this might be related to #https://github.com/raiden-network/light-client/issues/2377)
2. Move SVT to the Raiden Account

## Expected Result
- I see TTT and SVT on the withdrawal screen

## Actual Result
- I just see SVT on the withdrawal screen

Raiden Account:
https://goerli.etherscan.io/address/0x8c8492280cB454F2753DBb9a3114F4DA80F66714

![grafik](https://user-images.githubusercontent.com/35398162/99794865-1de3f980-2b2b-11eb-8050-fbb7b13077c7.png)

Withdrawal screen:
![grafik](https://user-images.githubusercontent.com/35398162/99794824-0c025680-2b2b-11eb-82a6-3f15fa254a40.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by andrevmatos** [comment]
I wouldn't qualify this as `critical`, this doesn't put user's funds at risk, just hide them on the Withdrawal screen, and even before the fixup, the user can trigger it to show up by going to the Select Token screen (which refreshes tokens data and balances) and then going to the Withdrawal screen.

**Comment by christianbrb** [comment]
@andrevmatos Thanks for providing this workaround and fix. I wasn't aware of this. I am classifying it as `medium`
