### ISSUE TITLE
After closing and settling the tokens are not on my Raiden Account

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2377]
## Thanks for filing a bug report :-)

I have got a weird issue, that I do not understand

## Steps to Reproduce
1. See https://docs.google.com/document/d/1_aT0Vgf9Cd6JuQuA01Kacc94mJB-rHELNttL13UAvs0/edit because I had the intention to test something else
    - Create a channel
    - Make a transfer
    - Delete the state, while the dApp is disconnected
    - Connect to the dApp (a new state is getting created) 
2. Close the channel: https://goerli.etherscan.io/tx/0xbeac9f3cedcdc830d2e1ae1ddd3219c6832011023fe1cbc954125b7a3669724a
3. The partner settles: https://goerli.etherscan.io/tx/0xaade96109721c4f5148df1c69cc0dd7265dca448edf2f7434507a3ba65fdbd5d

## Expected Result
- The TTT tokens are on my Raiden Account

## Actual Result
- The TTT tokens are not on my Raiden Account

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by palango** [comment]
So both of those nodes deposited:
- Node 1: 100TTT: https://goerli.etherscan.io/tx/0x9a4007cbae49535c8b9d5700ad51d17ddf11d67219f0678fd516f72be37d6cf2
- Node 2: 0,05 TTT: https://goerli.etherscan.io/tx/0x9a599cd6e17d8c770a5e7d6a60f6a5c5e5979cf525dded2653183c89c9671629

I see those two deposits on the chain
```
(Pdb++) event1
AttributeDict({
    'args': AttributeDict({
    'channel_identifier': 9732, 
    'participant': '0x1F916ab5cf1B30B22f24Ebf435f53Ee665344Acf', 
    'total_deposit': 100 000 000 000 000 000 000}), 
    'event': 'ChannelNewDeposit', 
    'logIndex': 0, 
    'transactionIndex': 1, 
    'transactionHash': HexBytes('0x9a4007cbae49535c8b9d5700ad51d17ddf11d67219f0678fd516f72be37d6cf2'), 
    'address': '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3', 
    'blockHash': HexBytes('0x8d8bd86521ae45f0dcfcbdf1268bfa3e47f363e21225b47f088ebd8a57c3607b'), 
    'blockNumber': 3695455
})

(Pdb++) event2
AttributeDict({
    'args': AttributeDict({
        'channel_identifier': 9732, 
        'participant': '0x8c8492280cB454F2753DBb9a3114F4DA80F66714', 
        'total_deposit': 50 000 000 000 000 000
    }), 
    'event': 'ChannelNewDeposit', 
    'logIndex': 6, 
    'transactionIndex': 9, 
    'transactionHash': HexBytes('0x9a599cd6e17d8c770a5e7d6a60f6a5c5e5979cf525dded2653183c89c9671629'), 
    'address': '0x3EA2a1fED7FdEf300DA19E97092Ce8FdF8bf66A3', 
    'blockHash': HexBytes('0xe636c463ef316d76e2370472d32ae8682bb79fd8d510904c3d77e21b4a13d7cf'), 
    'blockNumber': 3695492})
})
```

Then node 2 sends all its tokens (0,05TTT) to node 1. That means node 1 has a balance proof for that transfer.

Now node 2 deletes the state, and doesn't display any sent transfers anymore (this is correct behavior).

Now one node closes the channel, the other sends the balance proof and the node 1 receives all tokens. Looks fine for me.

**Comment by christianbrb** [comment]
@palango Thanks a lot :) 
I was not able to get any tokens as I have transferred them. I need to rebuild my test set-up.
