### ISSUE TITLE
Defaults for mainnet (dApp, CLI, SDK)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2378]
## Description
Define and set the default options for mainnet

## Acceptance criteria
- All configurable options are documented here: https://github.com/raiden-network/team/issues/881
- All options depending on the chain id (=mainnet) are documented here: https://github.com/raiden-network/team/issues/881

## Tasks
- [x] Add the reason to the configurable options
- [x] Add the options depending on the chain id

**Comment by taleldayekh** [comment]
@christianbrb to sign off the values in @palango

**Comment by taleldayekh** [comment]
@palango Do what's needed to be able to implement and close this.

**Comment by palango** [comment]
All defaults have been set and enabled.
