### ISSUE TITLE
dApp: Illustrate and implement the dApp screens in the info overlay

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2379]
## User Story
As Chris I want to see illustrations as a compliment to the descriptions when I view any info overlay.

## Acceptance criteria
All screens with an info overlay should have an illustration and all illustrations should be in the same style.

## Tasks
- [ ] Illustrations for:
  - Select Hub
  - Open Channel
  - Transfer
  - Transfer (steps)
  - Channels
  - Raiden Account
  - Withdrawal
  - UDC
  - Backup State

- [ ] Add illustrations to dApp

**Comment by MariaNono** [comment]
@taleldayekh Illustrations are done and I will upload the svgs here shortly
![Screenshot 2020-12-01 at 11 53 14](https://user-images.githubusercontent.com/16062579/100731635-ed724a00-33cb-11eb-9a41-ab4c4d286541.png)

**Comment by MariaNono** [comment]
Here are the SVGs @taleldayekh 
[LC Info illustrations.zip](https://github.com/raiden-network/light-client/files/5623541/LC.Info.illustrations.zip)
Let me know if there are any problems
