### ISSUE TITLE
I want to enter an address in a non-checksummed format 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#238]
## User Story

As Chris, I want to enter an address in a non-checksummed format so that I don't have to convert my non-checksummed address to a checksummed address

see: https://web3js.readthedocs.io/en/v1.2.0/web3-utils.html#tochecksumaddress

**Comment by andrevmatos** [comment]
I think that may be a problem. Checksummed addresses were introduced in https://github.com/ethereum/EIPs/issues/55 to avoid users commiting typos or partial paste errors for addresses on UIs. They can always go to the given address in e.g. etherscan.io to check the account and from there copy the checksummed address they've verified as the intended one.

If we really want to support non-checksummed addresses, I'd say to only support all-lower or all-uppercase addresses, and with a small warning under the input box that this address is not checksummed and a link to the EIP with the importante of prefering checksummed source addresses.

**Comment by christianbrb** [comment]
According to the feedback, I'll close the issue

Thanks @ulope and @andrevmatos :)
