### ISSUE TITLE
Uncaught (in promise) Error: Redirected when going from "/?redirectTo=%2Ftransfer" to "/transfer" via a navigation guard

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2383]
## Steps to Reproduce
1. I don't know

## Expected Result
- No error is shown

## Actual Result
- Error is shown in the console

`Uncaught (in promise) Error: Redirected when going from "/?redirectTo=%2Ftransfer" to "/transfer" via a navigation guard`

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by weilbith** [comment]
I would argue that this is stupid error by Vue (they kinda state this in their docs). It is kind of intended behavior. But the noise in the console and the warning are very annoying. Let's see how to resolve this.
