### ISSUE TITLE
`--environment` in CLI

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2389]
## Expected Result
The LC CLI doesn't implement the `--environment` argument the python client has.

It is used to:
- Stop the node from starting in development mode on mainnet -> we don't have that
- Creating new token networks on mainnet -> we don't support that
- Make the node check the validity of registration of PFS' on mainnet only -> we always check that

We need to decide if we need to implement this.

**Comment by christianbrb** [comment]
Isn't it also used to pull the Matrix servers https://github.com/raiden-network/raiden-service-bundle/tree/master/known_servers

**Comment by christianbrb** [comment]
@christianbrb We have got that for the mainnet servers

We have decided to not implement the --environment parameter
