### ISSUE TITLE
Add Raiden CLI readme to the auto-generated documentation

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2397]
## Description

Add Raiden CLI to the auto-generated documentation

## Acceptance criteria
- 

## Tasks
- [x] Check, if this is included as I have just seen this in the demo @andrevmatos 
- [ ] Add the CLI docs

**Comment by andrevmatos** [comment]
There's some very simple dApp docs, and no CLI, but it can accept any new page in the `.md` format. It's just a matter of creating the docs and organizing it there

**Comment by christianbrb** [comment]
Ok, thanks, let's add the CLI docs
