### ISSUE TITLE
I would like to see the time until a transaction is complete instead of blocks

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2398]
## User Story
As Chris, I would like to see the time until a transaction is complete instead of blocks so that I don't have to calculate blocks x seconds.

CC @GataKamsky

**Comment by taleldayekh** [comment]
Since this is an enhancement I'll pull it to the post-mainnet backlog.

**Comment by taleldayekh** [comment]
Closing, we can open this again if we get user feedback about implementing counting in time.
