### ISSUE TITLE
Mobile Testing on MetaMask Mobile

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2400]
## Description
Mobile Testing on MetaMask Mobile

## Acceptance criteria
- Doing the full lifecycle
- Using a fresh ETH account

## Tasks
- [ ] Test on staging
- [ ] Document the test

**Comment by agatsoh** [comment]
- [ ] Disclaimer 
- [ ] Connect
- [ ] Connect a token

**Comment by agatsoh** [comment]
![light_client_mobile_channel_screen](https://user-images.githubusercontent.com/15123108/100361486-38810b80-3020-11eb-8725-dba58e2b0bd7.jpeg)

**Comment by weilbith** [comment]
@agatsoh so **it is** about those buttons. :grimacing:

**Comment by agatsoh** [comment]
The account screen looks a bit ugly.


![raiden_lc_account_screen](https://user-images.githubusercontent.com/15123108/100446793-6e33fc00-30d5-11eb-9b56-e9e3be0238ac.gif)

**Comment by agatsoh** [comment]
Transfer eth screen the amount is not visible when editing it. Its gets white out due to the background.
![transfer_eth_screen](https://user-images.githubusercontent.com/15123108/100453094-62016c00-30e0-11eb-9997-a8ca36337c1a.jpeg)

**Comment by taleldayekh** [comment]
Separate issues exist for this, closing.
