### ISSUE TITLE
Test deleting the database

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2401]
## Description

Please execute and document (Screenshots, Etherscan transactions) the following test:

1. Go to staging
2. Open a channel with 0.5 TTT
3. Make a transfer of 0.25 TTT
4. Delete the local data (PouchDB, etc.)
5. Reopen the browser
6. Wait until the dApp has resynched
7. Close the channel
8. Settle the channel (or wait for the partner to settle)
9. Check tokens on the withdrawal screen

## Expected result
- There are 0.25 TTT on the withdrawal screen

## Actual result
- 

## Tasks
- [ ] Run the test
- [ ] Open a new issue, if it doesn't work

**Comment by agatsoh** [comment]
On settling the channel I get this error, unfortunately I did not take take each and every screenshot, but i will put whatever i have here and also perform a retest.

![error_settle](https://user-images.githubusercontent.com/15123108/100322291-0d7bc500-2fea-11eb-9ede-f2fb1d2fa8ab.png)

**Comment by agatsoh** [comment]
Accounts:
Account 1
Main: `0x911E8066cf7Ce063D70D43a3cD0c2CA67CdDB8c0`
Subkey: `0xe523679c4e94c06b0D62BAf996E5D451C831e343`

Account 2.
Main: `0xF87568e93F1437FD9Da14Da547234f0870e125A4`
subkey: `0x7532311B8baa45fbe4A9f596a2Fb75f5b3A625AB`


Etherscan transactions:
For: Account 1

Account Opening:
https://goerli.etherscan.io/tx/0x539c15f0c979e7bacc8e6027ea2345db6a2d6037cb55ee5f83c065b68c36b7b2

Account Closing:
https://goerli.etherscan.io/tx/0x3f171c36921b6e1fcd71792a55037f2cf671837378610b0b5b3e3a6c5f949d0c

**Comment by agatsoh** [comment]
Local Storage and Indexed DB was completely deleted from the browser associated with Account1 and then on re-opening it was re-generated.
![indexeddb](https://user-images.githubusercontent.com/15123108/100324181-e1ae0e80-2fec-11eb-9e03-56bee68dbf0c.png)

Downloaded logs after deleting the indexed db and closing the channel generated from Account1
[raiden_0xe523679c4e94c06b0D62BAf996E5D451C831e343_2020-11-26T08_05_39.761Z.log](https://github.com/raiden-network/light-client/files/5601314/raiden_0xe523679c4e94c06b0D62BAf996E5D451C831e343_2020-11-26T08_05_39.761Z.log)

**Comment by taleldayekh** [comment]
Closing for now, please reopen if still relevant.

**Comment by christianbrb** [comment]
@agatsoh Cool, thanks for testing :)
