### ISSUE TITLE
GitHub PR check for CHANGELOG entries if making a PR from forked repositories

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2405]
GitHub PR check for CHANGELOG entries is flake if making a PR from forked repositories.

**Comment by kelsos** [comment]
The problem with this is that the PR check action uses the GH_TOKEN. When working from a forked repo, the GH_TOKEN is the forked repository's token so the comment can't work since the forked repo's token doesn't give write access to the main repo. This is purely for security reasons.

**Comment by weilbith** [comment]
I think this isn't an issue. I'm working on a fork ever since and the check works perfectly fine for me. It detects missing entries, but also recognized it when I have added one. 
Therefore I'm closing it. If I should be wrong, please re-open the issue.
