### ISSUE TITLE
Lower transfer expiration for dApp

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2409]
In https://github.com/raiden-network/team/issues/894 and https://github.com/raiden-network/team/issues/891 we made the case for a shorter time between receiving a secret and the on-chain transaction in case we don't receive an unlock.

A decision has been made, and we need to implement it for the dApp (and possibly the CLI).

- SDK
  - [x] Make lock expiration configurable
  - [x] Add test for the minimal expiration
- dApp
  - [x] Use lower expiration by default
- CLI
  - [x] Decide if lower expirations should be used

**Comment by taleldayekh** [comment]
@palango to implement Python client part.

**Comment by palango** [comment]
I read the code and tested it manually: The PC accepts mediations up until the reveal timeout, so no action on the python side is necessary.
