### ISSUE TITLE
To few items from transfer history loaded

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2410]
## Steps to Reproduce
1. Create some transfer history
2. Reload the dApp

## Expected Result
- All space should be used to display the history

## Actual Result
- Some empty space that get's filled after a first scroll event

After load:
![Screenshot 2020-11-26 at 17 10 07](https://user-images.githubusercontent.com/90851/100373075-7bd07f80-300a-11eb-9ca6-6e856bcc76df.png)

After scroll event:

![Screenshot 2020-11-26 at 17 10 12](https://user-images.githubusercontent.com/90851/100373082-7d9a4300-300a-11eb-9e1b-4c01ae03328e.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by weilbith** [comment]
Hmm. We could try to increase the threshold value for the intersection observer. But actually it looks like `0.7` are fine. :thinking:

**Comment by palango** [comment]
@weilbith This still seems to be an issue. On the left is Brave, still not loading the third item. Right is Firefox, where all is as expected.

![Screenshot 2020-12-03 at 16 13 50](https://user-images.githubusercontent.com/90851/101048089-a67a8500-3582-11eb-8b05-e3582376ba2e.png)

**Comment by weilbith** [comment]
Could you eventually try to play with the threshold yourself. But actually the space looks like it should be big enough. Does Brave follow the most recent spec of the API?

**Comment by palango** [comment]
You mean this one: https://caniuse.com/mdn-api_intersectionobserver_thresholds ?

**Comment by weilbith** [comment]
Yes. Wait Brave uses the chromium engine, right?

**Comment by palango** [comment]
I think so

**Comment by weilbith** [comment]
@palango I'm sorry, but I tested it now with Brave, Chromium and Firefox (this is the order in the screenshot). For all of them it works fine on my side. The only awkward thing is that in Chromium the application is larger...
I don't know what is going wrong for you. Please make sure to test it again on latest master. I the meantime I'll close this issue until we can replicate it.

![test](https://user-images.githubusercontent.com/12543647/103291738-b7d17880-49ec-11eb-8c01-c3212e4e6641.jpg)
