### ISSUE TITLE
dApp: extend service worker to allow offline usage

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2414]
## Description
The dApp should be usable even if the server is down. Furthermore it should only request the server for updates and else just use the cached version of the application.
While our service worker claims to do this, it is clearly not working. Finally this is the result of the Chrome PWA test.
This is a big step into the direction of make this app used as PWA by Chrome and Firefox mobile (and more...).

Related to: #2382

## Acceptance criteria
- service handler caches all resources
- service handler serves app and only fetches resources if there was an update
- offline section for PWA checks run through

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Closing it in favor of #2440
