### ISSUE TITLE
Bad transfer history ordering

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2415]
## Steps to Reproduce
1. Send some transfers
2. Look at the transfer history

## Expected Result
- Latest transfer shown first, as I'm potentially more interested in those

## Actual Result
- Latest transfer shown last, making it necessary to scroll

## Additional Infos (Optional) 
![Screenshot 2020-11-27 at 12 22 25](https://user-images.githubusercontent.com/90851/100444232-68292580-30ab-11eb-899a-8f5ec1f152f9.png)

**Comment by taleldayekh** [comment]
Is it a bug or a feature. :) You are right, the latest transfer should be displayed on top.
