### ISSUE TITLE
Channel close button incorrectly inactivated

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2418]
## Steps to Reproduce
1. Open two channels for the same token
2. Go to the channels page
3. Close one channel

## Expected Result
- I can directly close the other channel as well

## Actual Result
- The other channels "Close" button is greyed out
  - Seems like it's re-activated as soon as the "close" transaction is confirmed. see screenshots

## Screenshots

![Screenshot 2020-11-30 at 17 00 35](https://user-images.githubusercontent.com/90851/100633231-1fcd6a00-332e-11eb-840c-ae7720242077.png)
![Screenshot 2020-11-30 at 17 02 30](https://user-images.githubusercontent.com/90851/100633240-222fc400-332e-11eb-8e90-9ed1951f514b.png)

## Additional Infos (Optional) 
```
- Firefox 83, macOS 10.15.7
```

**Comment by palango** [comment]
This also happens when one channel is settled:
![Screenshot 2020-12-01 at 17 15 30](https://user-images.githubusercontent.com/90851/100766394-e44ba200-33f8-11eb-9769-75c5ef08a0e3.png)

**Comment by taleldayekh** [comment]
Was implemented like this to not switch busy state when clicking another channel. Can be fixed by giving each button unique tags.
