### ISSUE TITLE
Copy to clipboard does not work in LC mobile

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2423]
## Steps to Reproduce
https://github.com/raiden-network/light-client/issues/2400#issuecomment-734294170

## Expected Result
- Copy to clipboard should copy the particular address to the clipboard in case of using the LC on mobile.

## Actual Result
- Copy to clipboard functionality which exists usually on addresses of accounts which get copied immediately when you click them on the web app does not work on the mobile app.

**Comment by weilbith** [comment]
@agatsoh I tried this and it works for me. I used the MetaMask mobile app with the built-in browser. I visited directly lightclient.raiden.network (no local test version). I can accept the disclaimer, connect (and create a sub-key), then go to my account and click on my address. I get the message that it was copied. If I then enter for example the address bar of the web-browser and copy from clipboard I have my address.
So I would argue in general this works fine. It just depends on the App you are using and if it properly supports the system clipboard.
Should we close this issue?

**Comment by agatsoh** [comment]
Yes if it works for you then its absolutely fine, I also used the metamask mobile app but didnt somehow work for me. It showed notification that it copied but then when i went ahead to paste the stuff then nothing happened. But this may be just a case for my mobile. So we can close this and if somebody complains then we could re-open it.
