### ISSUE TITLE
Lower block confirmation number for testnet/staging

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2432]
When testing we spend a lot of time waiting for block confirmations.

I suggest lowering the block confirmation to a lower number (e.g. 2) on the staging and test environments.

## Acceptance criteria
- [ ] Make this easier to configure on our side, as advanced settings.

**Comment by taleldayekh** [comment]
Could changing values get us out of sync or introduce other issues?. @palango look up potential pitfalls, coordinate default values with the Python team.
