### ISSUE TITLE
Return informative errors on CLI if user request API while node is still syncing

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#2434]
## Description
Follow up of #2417 
On this PR, the notion of `synced` state was introduced on SDK, and on CLI we update properly the value of the `/status` endpoint. Also, some sensible endpoints (like channels) are made available only once the SDK finishes syncing. Before that, the CLI may currently return some not very informative errors, like 500 or 404. We should add proper error messages there, so the user is infomed they need to wait for the SDK to finish syncing before requesting those endpoints.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
Closing, user is not expected to make api calls while syncing other than to the status endpoint.
