### ISSUE TITLE
Provide a way to locally regenerate a subkey for a different domain

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#2446]
## Description
Subkey (Raiden Account, #172) is a unique private key used in the Light Client, deterministically generated as the `sha256` of the main key `personal_sign` (EIP-191)  signature of a message containing the current network name, dApp's domain and a warning that this message should not be signed outside of a trusted app, or a different domain, or else it'd give the webapp access to its funds and Raiden channels.

We need to make it more secure, and also make it easier for a user to regenerate this key for another domain, to control the channels and funds from a standalone, locally served instance of the dApp, in case that domain goes offline.

This should be done before mainnet release, as it's a breaking change.
Two proposals:
1. Read an environment variable to allow the user to specify the domain/origin/referer to be used in the subkey message to be signed
2. Investigate if EIP-712 standard provide more security for our usecase, by embedding the domain in the payload, and having Metamask enforce it. This may only be feasible if there're advanced options allowing 1. above to still be possible, although with the proper safeguards on Metamask's side.

## Acceptance criteria
- We do not use EIP-712
- The user can set an environment variable
- If the environment variable is defined it is overriding the URL
- The workaround is documented

## Tasks
- [ ]

**Comment by weilbith** [comment]
For the moment I just read into the details of EIP-712 to see if it fits our needs.
