### ISSUE TITLE
Images for user docs

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2449]
![disclaimer](https://user-images.githubusercontent.com/15123108/102077147-db15f880-3e2e-11eb-8b39-1b5e6b7e25eb.png)

**Comment by agatsoh** [comment]
![connect_screen](https://user-images.githubusercontent.com/15123108/102077692-b66e5080-3e2f-11eb-9533-dd7f3e76e30a.png)

**Comment by agatsoh** [comment]
![connect-to-select-hub-screen](https://user-images.githubusercontent.com/15123108/102077805-e0277780-3e2f-11eb-86ab-cdbf060aba6b.gif)

**Comment by agatsoh** [comment]
![select_hub](https://user-images.githubusercontent.com/15123108/102077868-faf9ec00-3e2f-11eb-8a5d-a5df28c4f860.png)

**Comment by agatsoh** [comment]
![mint_udc_ttt_combined](https://user-images.githubusercontent.com/15123108/102077942-15cc6080-3e30-11eb-964b-90e0441fa6e7.png)

**Comment by agatsoh** [comment]
![after_minting_select_hub](https://user-images.githubusercontent.com/15123108/102078028-41e7e180-3e30-11eb-90bf-9c5b7df8ed2c.png)

**Comment by agatsoh** [comment]
![select-button-click](https://user-images.githubusercontent.com/15123108/102078097-5b892900-3e30-11eb-9061-10205ee6fd78.gif)

**Comment by agatsoh** [comment]
![transfer_screen_after_select_hub](https://user-images.githubusercontent.com/15123108/102078186-7eb3d880-3e30-11eb-87d3-ab342f062a9e.png)

**Comment by agatsoh** [comment]
![channels_screen](https://user-images.githubusercontent.com/15123108/102078250-9ee39780-3e30-11eb-975b-ecaeb6a8e2c7.png)

**Comment by agatsoh** [comment]
![network_visualisation](https://user-images.githubusercontent.com/15123108/102085833-2d5e1600-3e3d-11eb-917b-eb5311fa118a.png)

**Comment by agatsoh** [comment]
![direct_transfer](https://user-images.githubusercontent.com/15123108/102086318-e9b7dc00-3e3d-11eb-8a1b-cbb4f64034f8.png)

**Comment by agatsoh** [comment]
![direct_transfer_confirm](https://user-images.githubusercontent.com/15123108/102086680-782c5d80-3e3e-11eb-82a9-b3b7de65a82e.png)

**Comment by agatsoh** [comment]
![after_transfer_history](https://user-images.githubusercontent.com/15123108/102087290-541d4c00-3e3f-11eb-9719-397f51e95645.png)

**Comment by agatsoh** [comment]
![mediated_transfer](https://user-images.githubusercontent.com/15123108/102088064-65b32380-3e40-11eb-8523-06501ea783a4.png)

**Comment by agatsoh** [comment]
![request_route_pfs](https://user-images.githubusercontent.com/15123108/102089472-44533700-3e42-11eb-8491-6535b700faf3.png)

**Comment by agatsoh** [comment]
![select_route](https://user-images.githubusercontent.com/15123108/102181893-57611800-3ed1-11eb-976a-1cbe361cef38.png)

**Comment by agatsoh** [comment]
![confirm_transfer](https://user-images.githubusercontent.com/15123108/102183697-3cdc6e00-3ed4-11eb-85cd-bb95c787a48d.png)

**Comment by agatsoh** [comment]
![after_mediated_transfer](https://user-images.githubusercontent.com/15123108/102209131-52fb2600-3ef6-11eb-939e-3e4554c637fd.png)

**Comment by christianbrb** [comment]
@agatsoh Are you using the images within the documentation?

I have once discussed with @taleldayekh, that it is better to publish the documentation without screenshots as they might get outdated quite quickly.

**Comment by taleldayekh** [comment]
Oh, I missed that. I also pushed for using images as a being a good idea :D

**Comment by agatsoh** [comment]
@christianbrb yes I am using these images in the documentation.
@christianbrb  could we make the documentation for now with the screenshots and remove them in a later iterations ?

**Comment by agatsoh** [comment]
![acount_screen](https://user-images.githubusercontent.com/15123108/102340538-ac2d8d00-3fbc-11eb-83bd-b5624a3c574f.png)

**Comment by agatsoh** [comment]
![transfer_eth_account](https://user-images.githubusercontent.com/15123108/102342273-0596bb80-3fbf-11eb-952c-c65b61a9d47a.png)

**Comment by agatsoh** [comment]
![manage_udc_tokens](https://user-images.githubusercontent.com/15123108/102347600-9fae3200-3fc6-11eb-9815-212095be0b96.png)

**Comment by agatsoh** [comment]
![backup_state](https://user-images.githubusercontent.com/15123108/102349148-e866ea80-3fc8-11eb-99c1-d78b8ae6a6ba.png)

**Comment by agatsoh** [comment]
![withdraw_token](https://user-images.githubusercontent.com/15123108/102354467-9de96c00-3fd0-11eb-8f3e-27a473abe335.png)

**Comment by agatsoh** [comment]
![mint_udc_ttt_combined_new](https://user-images.githubusercontent.com/15123108/103345560-b6b94d80-4ab7-11eb-847a-d8f08bc96c23.png)

**Comment by agatsoh** [comment]
![select_hub_without_tokens](https://user-images.githubusercontent.com/15123108/103347552-4e6d6a80-4abd-11eb-869f-2d98e65caf2a.png)

**Comment by agatsoh** [comment]
![select_hub_with_tokens](https://user-images.githubusercontent.com/15123108/103347569-59c09600-4abd-11eb-9197-5d9a7e628267.png)

**Comment by agatsoh** [comment]
https://user-images.githubusercontent.com/15123108/103350123-ec186800-4ac4-11eb-8943-585665a924d5.mp4

**Comment by agatsoh** [comment]
![select-hub-navigate-new](https://user-images.githubusercontent.com/15123108/103350295-824c8e00-4ac5-11eb-86e5-99aec9533d8e.gif)

**Comment by agatsoh** [comment]
![select-hub-open-channel-new-cut](https://user-images.githubusercontent.com/15123108/103350414-e66f5200-4ac5-11eb-8339-5e3ecb564d5f.gif)

**Comment by weilbith** [comment]
@agatsoh can this be closed? 🤔

**Comment by taleldayekh** [comment]
Yes, let's close this.
