### ISSUE TITLE
I want to send payments to any Raiden client reachable free of charge in the network

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#245]
## User Story
As Chris I want to send payments to any Raiden client reachable free of charge (without paying mediation fees) in the network so that I can safe tokens.

## Acceptance criteria
- PFS is set in a configuration file or/and at the start of the dApp
- Getting the route from a free PFS server
- Only use routes free of charge (see `fee_penalty` in [the Raiden spec](https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#routing-preferences))
- Clients without a free path won't be reachable
- SDK accepting a configuration object
- We have got a default configuration for each testnet
- We implement a setting screen later
- Default configuration for testnets is available

## Tasks
- [ ] Splitting the issue into separate tasks/issues @andrevmatos 

## Prerequisite
- We need a testnet client with testnet services (we need services working with v0.100.5a0 - Antifragile Crocodile)

CC @Dominik1999 @palango

**Comment by christianbrb** [comment]
> We need a testnet client with testnet services (we need services working with v0.100.5a0 - Antifragile Crocodile)

@Dominik1999 @palango as discussed

**Comment by andrevmatos** [comment]
Done in #330
