### ISSUE TITLE
Proposed hubs list cannot be fetched - CORS issue

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2454]
## Steps to Reproduce
1. Go to https://lightclient.raiden.network/staging
2. Select the TTT token

## Expected Result
- I get a list of proposed hubs

## Actual Result
- Hub is online
- No suggested hubs are returned

![grafik](https://user-images.githubusercontent.com/35398162/102329302-88505400-3f88-11eb-9b6b-405d11079e32.png)

![grafik](https://user-images.githubusercontent.com/35398162/102329499-c6e60e80-3f88-11eb-91d3-0a5f339b7a22.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by palango** [comment]
The PFS address looks really wrong: pfs-goerli-with-fee.services-.raiden.network

**Comment by christianbrb** [comment]
We could try different PFSs
