### ISSUE TITLE
Notification window is not centered and clicking on it does not open the notification panel

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2458]
## Steps to Reproduce
1. Access https://lightclient.raiden.network/staging/
2. Connect

## Expected Result
- The notification "Backup your state" is centered
- If you click on the notification the notification window opens

## Actual Result
- It is not centered
- It cannot be clicked

![grafik](https://user-images.githubusercontent.com/35398162/102620281-102b8f00-413e-11eb-8ea8-26c04fac9c3f.png)

## Additional Infos (Optional) 
```
- Browser & version
- Browser console errors
- Device / OS
```

**Comment by weilbith** [comment]
@christianbrb what do you mean with centered? Could you specify this? Should it be centered on x **and** y axis? :thinking:

**Comment by christianbrb** [comment]
Just centered vertically. It looks like it isn't, but correct me if I am wrong.

**Comment by weilbith** [comment]
Sorry to do it this way, but to avoid any kind of misunderstanding I add this image. So the notification snackbar  (like all of our snackbars) has a center alignment on the horizontal x-axis. On the vertical y-axis it is aligned "bottom" with a small margin to the bottom window edge.

![image](https://user-images.githubusercontent.com/12543647/103525378-665b3a80-4e7f-11eb-9784-5fd250380bdc.png)

**Comment by christianbrb** [comment]
Sorry, I have meant horizontally
