### ISSUE TITLE
Review and update the private chain guide

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#2487]
## Description
Review and update if necessary https://github.com/raiden-network/light-client/blob/master/raiden-ts/docs-source/private-chain.md

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by agatsoh** [comment]
Installing geth guide link is broken we should update it.
https://raiden-network.readthedocs.io/en/latest/custom-setups/private_net_tutorial.html#installing-geth

**Comment by agatsoh** [comment]
There is problem in deploying the `TokenNetworkRegistry` on the current configuration of geth 
https://raiden-network.readthedocs.io/en/latest/custom-setups/private_net_tutorial.html#deploy-contracts
The transaction gets a `status = 0` which means the EVM has reverted the transaction. 
`TO DO: `
Post some logs

**Comment by agatsoh** [comment]
![raiden_contracts_submodule_edited](https://user-images.githubusercontent.com/15123108/127455881-16d61132-1ded-4299-99ee-6a87298408be.png)

**Comment by agatsoh** [comment]
![raiden_contracts_setuppy_edited](https://user-images.githubusercontent.com/15123108/127465142-032fc99c-9ee5-4650-af7c-08d132684e49.png)

**Comment by agatsoh** [comment]
![gitblame_flowchart](https://user-images.githubusercontent.com/15123108/127465197-785cd17b-fae6-4066-a31b-cf3121678df0.png)

**Comment by agatsoh** [comment]
![tag_version_raiden_contracts](https://user-images.githubusercontent.com/15123108/127996083-95ab8794-44d7-4588-ae11-18e0e99dac7f.png)
