### ISSUE TITLE
I want to withdraw tokens out of a channel

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#249]
## User Story
As Chris I want to withdraw tokens out of a channel so that I can get liquidity out of it.

## Acceptance criteria
- The design of the modal window looks similar to deposit
- Withdraw works for the partner
- I am getting a notification if my partner withdraw
- Withdraw can be executed by Chris

## Tasks
- [x] Design (in-iteration)

## Design
![buttons](https://user-images.githubusercontent.com/43838780/85297360-f0732100-b4a2-11ea-91be-08ac2801ca7d.jpg)

## Documentation
- ADR: https://raiden-network.readthedocs.io/en/latest/adr/0005-withdraw-expiry.html
- Messages: https://raiden-network-specification.readthedocs.io/en/latest/messaging.html#withdraw-request-message

## Remarks
- The user needs ETH on the Raiden Account to withdraw and the modal for withdraw needs to include that (see modal on the Withdrawal Screen)

**Comment by christianbrb** [comment]
Removed from the product backlog as it is a rare use case, if the user just sends tokens and adds a lot of complexity

**Comment by kelsos** [comment]
@christianbrb yes this will make more sense after we implement receiving

**Comment by christianbrb** [comment]
Design: Looks like deposit

**Comment by christianbrb** [comment]
Part of it is already getting implemented here #1514

**Comment by taleldayekh** [comment]
Clickable mockup:
https://xd.adobe.com/view/9d7680d1-ec16-4299-6246-10cba7e6ee86-eb47/

@kelsos @andrevmatos @christianbrb @weilbith

**Comment by christianbrb** [comment]
@taleldayekh Thanks, looks like a bigger change.

1. Where is the settle button?
2. Where do we put the message "Please wait until your channel is settleable. this may take some time."

**Comment by taleldayekh** [comment]
User clicks `close channel` icon and confirms in dialog. `Deposit/withdrawal` icons are disabled and small spinner is displayed while the closing is in progress. Once the channel has been closed an icon for settling appears from which the user can settle the channel. Not sure how the settle icon should look.

![close_loading](https://user-images.githubusercontent.com/43838780/85294906-7b521c80-b49f-11ea-8ced-ddddfbb12230.jpg)

**Comment by taleldayekh** [comment]
An alternative would be to move the buttons instead of using icons for the close and settle. The flow would look something like this:
![buttons](https://user-images.githubusercontent.com/43838780/85297360-f0732100-b4a2-11ea-91be-08ac2801ca7d.jpg)
