### ISSUE TITLE
Update demo env

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2514]
## Description
This needs to be done for the PFS suggested partners to work. @eorituz can you help here? Is it important to have this feature in the demo env for now?

Needs more discussions and not only in the LC team.

We are not ditching it. Split it by contracts or link by transport servers are the alternatives.
Will the RSB be released?

## Acceptance criteria
- Conceptualise the problem

## Tasks
- [ ] Bump PFS to latest version
- [ ] Wait for @fredo PFS changes to be done before this upgrade

**Comment by taleldayekh** [comment]
@eorituz, would you be ok with Andrés last comment in the "ditch demo env" issue? #2278

**Comment by eorituz** [comment]
Sounds like a good idea to me. 
@ezdac and the TransCore team took over the maintenance of the demoenvs. @ezdac What do you think?

**Comment by palango** [comment]
We now have a separated demo environment. The usage is documented here: https://hackmd.io/q5oULgo6Qzuj5jBTC_E5zw

The LC by default uses the test environment.
- https://lightclient.raiden.network/staging/ uses the test environment
- https://lightclient.raiden.network/ uses the demo environment

**Comment by manuelwedler** [comment]
So we have a second deployment of the contracts on goerli, is this correct? This makes it necessary to update the Explorer and maybe the Wizard.

Is the PFS of the demo environment updated?

**Comment by palango** [comment]
> Is the PFS of the demo environment updated?

No, the demo env kept the current version. But there is a [new issue](https://github.com/raiden-network/raiden/issues/6964) for updating the versions used in the demo env.
