### ISSUE TITLE
Make a first Light Client Red Eyes Testnet release

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#252]
## Description

After having implemented #26 the SDK is feature complete for milestone 0 for Red Eyes. This issue keeps track of making a first test net release and to decide how to maintain it afterward.

## Acceptance criteria
- Manual release
- Include #14 
- Release Notes
- No state backup
- v0.1.0

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Some collected links for the release notes
- [Easy Release Note Template](https://github.com/palantir/plottable/wiki/Release-Notes-Template)
- [How to write great release notes](https://www.prodpad.com/blog/writing-release-notes/)
- [5 excellent product release note examples and how to write your own](https://www.appcues.com/blog/release-notes-examples)
- [Keep a changelog](https://keepachangelog.com/en/1.1.0/)

Maybe using in future:
- [Chronicler - Service to ensure that your release notes are always up to date](https://chronicler.starchartlabs.org/)
- [Release drafter - GitHub Action](https://github.com/toolmantim/release-drafter)

**Comment by andrevmatos** [comment]
Done: https://github.com/raiden-network/light-client/releases/tag/v0.1
