### ISSUE TITLE
Receiving Transfers disabled on a balance of 8 SVT tokens

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2529]
## Steps to Reproduce
1. Withdraw 2SVT tokens from the `Manage UDC tokens` screen after having deposited 10 SVT tokens in the UDC contract
2. After a few mins Receiving transfers disabled notification will come as a snackbar, also saved in the notification panel.

## Expected Result
- Atleast upto the decided 5 SVT balance receiving should work.

## Actual Result
- 
Notification of `receiving` being  disabled is received on UDC balance of 8 SVT tokens, though I guess decided was 5 SVT
![withdraw_udc_screen_8SVT](https://user-images.githubusercontent.com/15123108/105710307-ed5e7880-5f3c-11eb-9ebd-871d3a1da178.png)

![notification_panel_receiving_disabled](https://user-images.githubusercontent.com/15123108/105710323-f3545980-5f3c-11eb-9afc-c6d68e8d59db.png)

**Comment by andrevmatos** [comment]
@agatsoh the latest logs seem to indicate both clients have receiving enabled. Could you please try again and post the new logs in case this persists?

**Comment by agatsoh** [comment]
fixed  with this pull request https://github.com/raiden-network/light-client/pull/2526
