### ISSUE TITLE
I want to get a list of PFS services from the service registry 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#253]
## User Story

As Chris I want to get a list of PFS services from the service registry so that I can use any PFS service in the network
See [Raiden Client implementation](https://github.com/raiden-network/raiden/commit/bce57dad6c8d183387d658065b7c0838544a8bfa)

## Acceptance criteria
- At start-up, the service registry is queried
- The first one is stored in the config
- It is an asynchronous operation
- The whole config is stored in the state (#399)

**Comment by Dominik1999** [comment]
It is not complicated at all.

There are 2 non-tech related problems though:
- If there is one free pfs in the ServiceRegistry, then everybody is using this free PFS. So we will destroy the merely existing market for the other PFS
- BBLE will not operate a PFS on their own on mainnet. So we would need to find someone offering this service for free but stake the min. nec. 500 RDN

**Comment by christianbrb** [comment]
@Dominik1999 We have changed this to request any PFS service from the registry

**Comment by nephix** [comment]
If the user gets a list of available PFS servers presented, what's the criteria for him to select one?

**Comment by christianbrb** [comment]
At the moment the one with the fastest response time.

In #386 it would be the cheapest one or a combination of both.
