### ISSUE TITLE
raiden-ts isnt' bundled/packaged for use without complicated babel plugins (eg it doesn't work in create-react-app)

### ISSUE THREAD

**Issue by JasoonS** [raiden-network/light-client#2540]
## Steps to Reproduce
```bash
git clone git@github.com:avolabs-io/flows-monorepo.git
git reset --hard fc722d5
cd flows-monorepo/dApp/user
yarn
yarn re:build
yarn start
```

after `yarn start` has run you should see the following error:
```
Failed to compile.

./node_modules/raiden-ts/dist/config.js 110:26
Module parse failed: Unexpected token (110:26)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|   const matrixServerInfos = network.chainId === 1 ? 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers-production-v1.2.0.json' : 'https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers-development-v1.2.0.json'; // merge caps independently
|
>   const caps = overwrites?.caps === null ? null : {
|     [Capabilities.DELIVERY]: 0,
|     [Capabilities.MEDIATE]: 0,
```

## Expected Result
Code should compile, and babel+webpack should be able to bundle it.

## Actual Result
Unable to bundle app that uses `raiden-ts@0.15`

## Additional Infos (Optional) 
I have tried adding all the babel plugins present in this repo, maybe I'm still missing some. However, I believe it would be best that the package is built so it doesn't require the end user to fiddle with babel plugins etc.

I have used these tutorials as a reference for adding babble plugins, however, I have added various babel plugins to other applications so I don't think I'm at error in how I am adding them.
https://medium.com/@adostes/enabling-optional-chaining-in-a-create-react-app-a9f626a515d9
https://devinschulz.com/modify-create-react-apps-babel-configuration-without-ejecting/

**Comment by taleldayekh** [comment]
Thank you for bringing this to our attention @JasoonS. We will take a closer look at it.

**Comment by taleldayekh** [comment]
Patch has been provided that solves the issue, please re-open if future problems occurs.

**Comment by JasoonS** [comment]
Amazing, thank you @andrevmatos ! :blush:

**Comment by JasoonS** [comment]
@andrevmatos just btw, I needed to install `pouchdb-adapter-memory` to get it to work, I didn't dig into why, just letting you know. Other than that it is working great now.

**Comment by andrevmatos** [comment]
@JasoonS this is stated in my patch. The requirement for it is that it's a devDependency from `raiden-ts` (therefore not automatically installed), used only in tests, but in src there's an adapter file which detects if it's a test environment and dynamically loads it. Looks like CRA can't detect it's used only in tests, and fails if there's some dynamic imported lib it can't provide. I may try to fix this later, by removing the automatic usage of it on tests and passing it explicitly, but the patch I provided should fix it for now.
