### ISSUE TITLE
Only join discovery room

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2571]
Part of issues for the LC side of raiden-network/raiden#6809

Raiden Nodes only need to join discovery rooms once to_device messaging to the services is implemented

### Acceptance Criteria
- Not join the ms and pf rooms
- Ensure that state and events from the global rooms are not being fetch and don't join the rooms

**Comment by andrevmatos** [comment]
I'm closing this since the feature branch got merged to `next`. Eventually that will get merged back to `master`, but until then we can consider this feature as implemented.
