### ISSUE TITLE
Implement paste functionality on address input

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#258]
## Description
 Implement and enable paste functionality for the address input.

## Acceptance criteria
- User presses the paste button approves clipboard permissions and the content of the clipboard is automatically transferred to the input.

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@kelsos This sounds nice, but we will not implement it soon. I have been reading it already 20 times ;) Closing.

**Comment by kelsos** [comment]
@christianbrb I remember that being tricky to implement. I did try once, and this was a follow-up issue from another issue I was working on (based on some designs Roy provided back in the day). I would say the effort required to make it work doesn't justify this. And also the designs moved one, so closing it is absolutely reasonable.

**Comment by christianbrb** [comment]
@kelsos Great, thanks 👍
