### ISSUE TITLE
LC queries PFS for direct transfer on the mainnet

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2587]
## Thanks for filing a bug report :-)
~Please treat this is as a provisional issue. I am re-verifying everything again so that i reproduce this reliably~
Scenario:
LC browser node
`0x9307b1EE0f1299547F8F46A268efbd6089Ce81B2`
subkey account: 
`0x07d036DbC602F0191a4bC8e217fe48d34cD4a230`

LC CLI node
`0x5d3c715dfec88ee0C1a14C2B6ed3b0878612581c`

```
node build/index.js --eth-rpc-endpoint http://10.104.6.7:8545 --api-address "http://localhost:5010" --keystore-path /home/devaki/.ethereum/keystore/ --address 0x5d3c715dfec88ee0C1a14C2B6ed3b0878612581c --log-file node-5d3c71-mainnet-24thFeb2021.log --password-file password_file.txt --accept-disclaimer --enable-monitoring
```

## Steps to Reproduce
1. yarn build 
2. npx serve -l 8080 ./dist 

`.env.production`
```
VUE_APP_MATRIX_LIST_URL=https://raw.githubusercontent.com/raiden-network/raiden-service-bundle/master/known_servers/known_servers-production-v1.2.0.json
VUE_APP_ALLOW_MAINNET=true
VUE_APP_HUB=hub.raiden.eth
VUE_APP_IMPRINT=https://raiden.network/privacy.html
VUE_APP_TERMS=https://github.com/raiden-network/light-client/blob/master/TERMS.md
```

## Expected Result
- LC should directly proceed to transfer

## Actual Result

![light_client_direct_mint_error_full_screen](https://user-images.githubusercontent.com/15123108/109007288-fd9b7c00-76d1-11eb-92cd-395be4dac052.png)

## Additional Infos (Optional) 
LC browser logs
[raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-24T13_18_23.400Z.log](https://github.com/raiden-network/light-client/files/6036295/raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-02-24T13_18_23.400Z.log)

LC CLI logs
[node-5d3c71-mainnet-24thFeb2021.log](https://github.com/raiden-network/light-client/files/6036303/node-5d3c71-mainnet-24thFeb2021.log)

**Comment by andrevmatos** [comment]
There's one case where LC can and should try to request PFS for direct transfers: your partner is online, you don't have enough capacity on the direct channel with them, but you may have enough capacity on a channel with another peer; the rationale is that, even though the direct route isn't suitable, maybe PFS could give you an indirect route which is.
Please, check if this is the case, try to balance or deposit on the channel to ensure there's enough capacity for the transfer, and check if this is still the case.

**Comment by andrevmatos** [comment]
The error shown has nothing to do with this "issue": it's caused by the auto-pfs code trying to contact and validate the registered PFSs, but some of them isn't responding properly, so it gets skipped, but the working ones are there, as they should.

**Comment by agatsoh** [comment]
I have 10 DAI in deposited in the channel and I am transferring 1 DAI. But I am building everything again and trying to run it so that I reliably reproduce this.

**Comment by agatsoh** [comment]
After a long time the channel has started showing on the CLI node,
```
$ curl -i http://localhost:5010/api/v1/channels/0x6B175474E89094C44Da98b954EedeAC495271d0F/0x07d036DbC602F0191a4bC8e217fe48d34cD4a230
HTTP/1.1 200 OK
X-Powered-By: Express
Access-Control-Allow-Origin: http://localhost:*/*
Vary: Origin
Content-Type: application/json; charset=utf-8
Content-Length: 337
ETag: W/"151-1H/RcWvDgozLTmm1N0GnQoc8g/0"
Date: Wed, 24 Feb 2021 15:59:36 GMT
Connection: keep-alive
Keep-Alive: timeout=5

{"channel_identifier":"66","token_network_address":"0xEA92bD481e54BBB9Bb6C927970a54E82eE26c6B4","partner_address":"0x07d036DbC602F0191a4bC8e217fe48d34cD4a230","token_address":"0x6B175474E89094C44Da98b954EedeAC495271d0F","balance":"0","total_deposit":"0","total_withdraw":"0","state":"opened","settle_timeout":"500","reveal_timeout":"50"}
```

**Comment by agatsoh** [comment]
I have tested this and satisfied myself again on the latest master it gives the same error on LC browser. if someone wants i could also also upload the state and then the keystore file and they can also try to reproduce this.
