### ISSUE TITLE
dApp: cannot navigate back from account screen when not connected

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2590]
## Steps to Reproduce
1. On the dApp connect screen click the identicon to access the account menu. 
2. Try to navigate back to the connect screen.

## Expected Result
- Possible to navigate back to the connect screen.

## Actual Result
- Not possible to navigate back to the connect screen without reloading the dApp (back arrow missing).

## Additional Infos (Optional)
<img width="628" alt="Screenshot 2021-02-25 at 13 50 08" src="https://user-images.githubusercontent.com/43838780/109156067-b31d0c80-7770-11eb-8d6d-a355de63d88a.png">

**Comment by weilbith** [comment]
I can confirm that it works once you are connected. :grimacing:
