### ISSUE TITLE
Receiving LC node registers secret on-chain

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2596]
## Steps to Reproduce
1. Perform a direct transfer between 2 nodes
The way I serve the dapp
`yarn workspace raiden-dapp run serve`
## Expected Result
- Instantaneous Transfer between the nodes 

## Actual Result
- 

Logs
* Sender
[sender_0xd4e2fedb3F823BB39210976B1317Ab32F43CCa01_2021-02-26T15_16_18.691Z.log](https://github.com/raiden-network/light-client/files/6050566/sender_0xd4e2fedb3F823BB39210976B1317Ab32F43CCa01_2021-02-26T15_16_18.691Z.log)

* Reciever
[receiver_0xf99d67202512dfB1b316bBB6C44cD6457527bc43_2021-02-26T15 16 51.653Z.log](https://github.com/raiden-network/light-client/files/6050604/receiver_0xf99d67202512dfB1b316bBB6C44cD6457527bc43_2021-02-26T15.16.51.653Z.log)

**Comment by taleldayekh** [comment]
@andrevmatos log file from the Cypress e2e test run

[logs-cypress-run.zip](https://github.com/raiden-network/light-client/files/6077430/logs-cypress-run.zip)

**Comment by agatsoh** [comment]
these are logs of LC nodes I just created from fresh accounts and absolutely no changes to the `env`s

[sender_fresh_0xc8c4E7abdf241008dbEa7927509872fC68DF0F4A_2021-03-03T16_28_22.543Z.log](https://github.com/raiden-network/light-client/files/6077500/sender_fresh_0xc8c4E7abdf241008dbEa7927509872fC68DF0F4A_2021-03-03T16_28_22.543Z.log)


[receiver_fresh_0x0648f636C8994Ee32c7e64B8B692DE908BC4919E_2021-03-03T16 29 10.519Z.log](https://github.com/raiden-network/light-client/files/6077505/receiver_fresh_0x0648f636C8994Ee32c7e64B8B692DE908BC4919E_2021-03-03T16.29.10.519Z.log)

**Comment by andrevmatos** [comment]
@agatsoh I identified the root cause of your issue: your sender node has receiving disabled, because it doesn't have UDC deposit, and a small bug is causing that the handling of the `RevealSecret` for the `Unlock` to be missed due to that. I'll be a PR ready shortly.

**Comment by agatsoh** [comment]
@andrevmatos  I did make a UDC deposit before a I received though, so receiving should be enabled. There is no notification for that, so may be should have a notification for that otherwise first time user would be confused whether receiving is enabled. He only gets one notification of receiving being disabled.

**Comment by agatsoh** [comment]
@andrevmatos Yes I so ideally for direct transfers UDC deposit should not be required right ? But my receiver has a UDC deposit because I got notification that receiving has been disabled, ofcourse due to not having UDC deposit which is pre-requisite for Monitoring services.

**Comment by andrevmatos** [comment]
@taleldayekh your logs only contain dApp's. It seems to be behaving as expected, but the PC node isn't replying, so I need its logs to check what's happening.

**Comment by taleldayekh** [comment]
Those would be in the docker container right?

**Comment by andrevmatos** [comment]
Yes, it should be there. If it was in a volatile folder, it's gone, and we may need to set the container to mount the folder in a persistent volume.
