### ISSUE TITLE
Mobile dApp: Introduce the SQL lite plugin

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2601]
## User Story

As Chris I want to be able to rely on IndexdDB and local storage working as intended on iOS and Android.

## Acceptance criteria

Saving to IndexedDB or local storage should never be an issue on mobile and behave as in the current dApp.

## Tasks (split each task into separate issues)

- [x] Do a deeper research on why we should not rely on it working in its current state.
- [ ] Introduce the SQL lite plugin.

**Comment by taleldayekh** [comment]
@taleldayekh Split as above.

**Comment by palango** [comment]
So this all seems a bit more complicated than anticipated.

First of all we need a PouchDB adapter to get unlimited storage on the capacitor build: [Adapters](https://pouchdb.com/adapters.html#pouchdb_in_the_browser).
The recommendation seems to be [GitHub - pouchdb-community/pouchdb-adapter-cordova-sqlite: PouchDB adapter for Cordova SQLite. Designed for PouchDB 6+.](https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite), which is written for Cordova, but my understanding is that Cordova stuff should be compatible with capacitor in general, so we need to test.

With this in place, we need an Cordova SQLite plugin, that manages the interaction with the native iOS/Android components. Of the three mentioned ones, there is only one which has seen commits in the last year: https://github.com/storesafe/cordova-sqlite-storage

(The capacitor community sqlite plugin doesn’t seem compatible on a first look: [GitHub - capacitor-community/sqlite: Community plugin for native & electron SQLite databases](https://github.com/capacitor-community/sqlite))

This all seems quite a bit fiddly, but I’ll try to set it up until someone has more links to share.

**Comment by weilbith** [comment]
> but my understanding is that Cordova stuff should be compatible with capacitor in general, so we need to test.

Capacitor uses Cordova under the hood. So yes.

> With this in place, we need an Cordova SQLite plugin, that manages the interaction with the native iOS/Android components. Of the three mentioned ones, there is only one which has seen commits in the last year: https://github.com/storesafe/cordova-sqlite-storage

It also has plenty of stars on GH. Not the ultimate indicator, but a good sign. I saw many of those plugins which had no attention at

> (The capacitor community sqlite plugin doesn’t seem compatible on a first look: GitHub - capacitor-community/sqlite: Community plugin for native & electron SQLite databases)

We need the Cordova stuff **plus** this as well? I actually thought only one of them. 🤔 

> This all seems quite a bit fiddly, but I’ll try to set it up until someone has more links to share.

Actually you basically just described what we had in mind when we created the issue. So nothing too new. Except the part with Capacitor **and** Cordova plugin.

**Comment by weilbith** [comment]
Please remember that the DB adapter must be added as dependency and imported by the dApp. But then just set the adapter parameter for the SDK settings and it should do the work. Don't instantiate anything or similar.

**Comment by palango** [comment]
Thanks for the quick reply.

> We need the Cordova stuff plus this as well? I actually thought only one of them. 🤔

No, just one. My expectation was just that a dedicated capacitor plagin should be better/tighter integrated that a cordova plugin.

**Comment by weilbith** [comment]
Okay. Well, as I said the one you proposed seems to have a lot of attention and is frequently used. So let's give that one a first try. 👍🏾

**Comment by weilbith** [comment]
The hard question is to tell if it works. Should mean not just that the app runs, but takes the correct database. Maybe it is not possible to still take the old one. Not 100% sure how this looks in detail.

**Comment by palango** [comment]
Fixed in https://github.com/raiden-network/light-client/pull/2666
