### ISSUE TITLE
dApp mobile: Raiden Wizard integration research

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2602]
## User Story

As Chris I want to get started making payments right away by using a similar onboarding wizard as the Python client.

## Acceptance criteria

Clear idea of the desired outcome of integrating the Wizard and a good estimation of the efforts required.

## Tasks
- [ ] @taleldayekh Get a better understanding of what is expected with having the wizard integrated in the LC.

**Comment by weilbith** [comment]
Quick chat with Talel: it probably makes no sense to invest any time here as it should not be possible to find any easy integration here. He will have a final word on this with Kamal tomorrow and then probably close the issue then.

**Comment by taleldayekh** [comment]
The Raiden Wizard is not really relevant for the Light Client since the Light Client already have an onboarding process for acquiring most of the necessary tokens to get started making transfers. A user cannot acquire ETH and DAI but this could be solved by i.e. Ramp Network integration.
