### ISSUE TITLE
Optimize for mobile

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#261]
## User Story
As Chris I want to be able to understand the light client UI on mobile devices.
![Screenshot 2019-08-15 at 13 11 22](https://user-images.githubusercontent.com/3169205/63091654-54fa5100-bf5f-11e9-8c44-19d5c468976c.png)

## Acceptance criteria
* UI elements should adjust to screen size of user

## Tasks
- [ ] Check placeholders for e.g. address inputs
- [ ] Check display of token addresses

**Comment by christianbrb** [comment]
Split into
- Pragmatic Part
- Really optimize for mobile

**Comment by christianbrb** [comment]
@nephix Could this be closed after the fixes we have done for ETHCC?
