### ISSUE TITLE
Mobile dApp: Research Fastlane

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2648]
## Description

Get a better understanding on how Fastlane is used.

## Acceptance criteria
- Ground work necessary before tackling #2605 

## Tasks
- [ ] Read docs
- [ ] Talk with Daniel

**Comment by weilbith** [comment]
We have enough follow up issue for this one. More will come with time. As we still have the parent tracking issue, this issue here is good to close as the initial research phase is done. Some of the results which where "special" are mentioned in the associated issues.
