### ISSUE TITLE
dapp: make beta releases the Google Play Store via Fastlane in the staging CI workflow

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2665]
## Description

The title is pretty expressive. Note that this requires #2656 which is blocked due to app store permission issues.
Production releases are out of target for this issue as this whole process is not well defined yet. The most critical part here will be the secret handling as not all of them can be done via environment variables as usual.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by weilbith** [comment]
As we should take the Trustlines setup as template I took a look how they get their keystore files etc into the CI environment. How they do it is to encode the files with base64, store them into environment variables and then during runtime decode them again into a file.

**Comment by weilbith** [comment]
One of the major issues now is that the base executor image does not have Ruby available. But we remember the issue that using different executors for different jobs which build on top of each other does not work well.

**Comment by weilbith** [comment]
It looks like the `cimg/ruby:3.0.1-browsers` image provides everything we need. I'll give it a try.

**Comment by weilbith** [comment]
The image works for all jobs in the default workflow as we had them before. 👍🏾 
I already put all the secrets encoded into environment variables.

**Comment by taleldayekh** [comment]
We will most likely not proceed with a "native" mobile dApp and we have a working Fastlane deployment for internal test versions on Google Play.
