### ISSUE TITLE
Optimize capacitor build pipeline

### ISSUE THREAD

**Issue by palango** [raiden-network/light-client#2678]
## Description

We have special build tasks for the capacitor build. They use the capacitor build system and set the capacitor build [mode](https://cli.vuejs.org/guide/mode-and-env.html#modes), so set the correct environment variables.

However,. it seems like the build modes like `dev` or `production` have other (implicit) effects like code optimization/minimalization. This means that the capacitor builds are not optimized, which shows itself in a 10x artifact file size as shown below.

We should investigate this further and find a way to avoid this, so that the capacitor builds are optimized as well.

#### Not optimized
```
➜  raiden-dapp git:(sqlite-plugin) ✗ du -h dist
868K	dist/css
3.4M	dist/js
 35M	dist/bundled/js
 60K	dist/bundled/img/icons
280K	dist/bundled/img
3.4M	dist/bundled/fonts
 38M	dist/bundled
 60K	dist/img/icons
280K	dist/img
3.4M	dist/fonts
 47M	dist
```

#### Optimized
```
➜  raiden-dapp git:(sqlite-plugin) ✗ du -h dist
868K	dist/css
3.4M	dist/js
868K	dist/bundled/css
3.4M	dist/bundled/js
 60K	dist/bundled/img/icons
280K	dist/bundled/img
3.4M	dist/bundled/fonts
8.1M	dist/bundled
 60K	dist/img/icons
280K	dist/img
3.4M	dist/fonts
 16M	dist
```

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by weilbith** [comment]
Closed in #2788
