### ISSUE TITLE
Updating the SDK documentation from a developer perspective using the SDK

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#273]
## Description
The [payments endpoint is missing in the SDK documentation](https://github.com/raiden-network/light-client/tree/master/raiden#paying-through-a-channel). 

It needs to be checked if the SDK documentation is up to date from a developer perspective

## Acceptance criteria
- SDK documentation is up to date with the codebase
- The Readme is updated
- What do I need to do with the SDK to send a payment?
- Kelsos would be happy
- Scenarios are defined

## User
- I don't know Raiden at all
- I just know Ethereum

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
Partly done in #288, still needs to improve, so should stay open

**Comment by taleldayekh** [comment]
This needs to wait until we have a working package of raiden-ts on npm. It will be difficult to work on this if there is no way to try out the examples in the docs to start with.

Hopefully this can be tackled starting the next iteration.

**Comment by christianbrb** [comment]
Refinement whiteboard picture

![grafik](https://user-images.githubusercontent.com/35398162/70316172-6374bd00-181b-11ea-9458-d7e58efa13a0.png)

@taleldayekh Could you break this down into actionable issues?

**Comment by andrevmatos** [comment]
`npm` package is working and can be used on es5, esNext & TS projects as far as I could test.

**Comment by christianbrb** [comment]
Splitting in 2 or 3 issues

**Comment by taleldayekh** [comment]
I wrote down some suggestions for restructuring/improving the docs in issue #709 which could be used when splitting into new issues.

**Comment by christianbrb** [comment]
Dedicated docs issues have been created and some have been already implemented:
https://github.com/raiden-network/light-client/issues?q=is%3Aissue+is%3Aopen+label%3A%22docs+%F0%9F%93%96%22
