### ISSUE TITLE
Text of invalid address warning gets cut in half

### ISSUE THREAD

**Issue by BOR4** [raiden-network/light-client#274]
Probably due to long warning text gets cut in half

![image](https://user-images.githubusercontent.com/40821065/63424848-92ebef00-c40f-11e9-8f1a-618069cda579.png)

### Acceptance criteria
- The text is left-aligned
- The input box should be bigger

**Comment by BOR4** [comment]
browser used: mozilla,
OS: linux

**Comment by kelsos** [comment]
@BOR4 thanks for reporting we will have a look :)
