### ISSUE TITLE
Agree on protocol for breaking changes

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2753]
## Description

To improve the communication between the Python Client and the Light Client team we should discuss to introduce some sort of protocol regarding breaking changes that both teams would have to comply too. The idea is that we in the future work more closely together whenever changes are necessary that breaks compatibility.

## Acceptance criteria
- We want to add a new scenario to the scenario player and both teams need to maintain their clients so that that scenario does not fail. The scenario runs clients of different versions on the same network.
- Discuss remote function calls for breaking changes.
- Something similar to versioning for encodings.
- Decide on shared strategy and derive future tasks based on that.

## Tasks
- [ ] Propose ideas for PC team
- [ ] @taleldayekh setup call with PC team (smaller group for initial discussions, @andrevmatos @weilbith from lc team, maybe @fredo @karlb from pc team.

**Comment by taleldayekh** [comment]
@weilbith please close when the others have created the issues.

**Comment by ulope** [comment]
SP multi client support: https://github.com/raiden-network/scenario-player/issues/686
