### ISSUE TITLE
Download Log downloads empty log file with zero size

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2754]
## Steps to Reproduce
Start raiden dapp on the ~~`next`~~  `next_address_metadata` branch
1. Click on the identicon
2. Click of `Download logs`

## Expected Result
- A file with the logs would be downloaded 

## Actual Result
- Empty file is downloaded

**Comment by taleldayekh** [comment]
@agatsoh Try on testnet and see if the same problems occur there.

**Comment by agatsoh** [comment]
This is the first time I got to the logs on mainnet but there is a difference.
Mainnet logs only capture exceptions(that too only some exceptions not all) while goerli logs capture all the logs. I dont know if this is by design.

Mainnet logs 
[raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-05-27T11_45_43.050Z.log](https://github.com/raiden-network/light-client/files/6554270/raiden_0x07d036DbC602F0191a4bC8e217fe48d34cD4a230_2021-05-27T11_45_43.050Z.log)

Goerli logs

[raiden_0xc8c4E7abdf241008dbEa7927509872fC68DF0F4A_2021-05-27T12_48_54.701Z.log](https://github.com/raiden-network/light-client/files/6554273/raiden_0xc8c4E7abdf241008dbEa7927509872fC68DF0F4A_2021-05-27T12_48_54.701Z.log)

**Comment by agatsoh** [comment]
@palango OK I was actually wrong here I am not testing on the latest next I am testing on  latest branch opened by @andrevmatos `next_address_metadata` since that is likely to be merged to `next`, it just happened to forget mentioning it. Could you test this on `next_address_metadata` please ?

**Comment by agatsoh** [comment]
One more thing that I did differently is I built the `raiden-dapp` and did not serve directly like this. You first need to be inside the `raiden-dapp` folder for this 
```
yarn build --mode production
npx serve -l 8080 ./dist
```

**Comment by palango** [comment]
> @palango One more thing that I did differently is I built the `raiden-dapp` and did not serve directly like this. You first need to be inside the `raiden-dapp` folder for this
> 
> ```
> yarn build --mode production
> npx serve -l 8080 ./dist
> ```

Thanks. I'll try that as well. Is there reason you're doing this?

**Comment by agatsoh** [comment]
@palango Mostly to closely mimic production dapp deployment and also to get the service worker, working for me. 
Though I rarely use `yarn workspace raiden-dapp serve` I observed earlier that on doing this service worker does not become active. For service worker we need build and then deploy.

**Comment by palango** [comment]
Just using the `next_address_metadata` branch I also can download logs. But when building for production I see the following error in the console. @agatsoh did you see that as well?

```
Uncaught (in promise) DOMException: IDBDatabase.transaction: 'logs' is not a known object store name
```

**Comment by agatsoh** [comment]
@palango  Yes I see the same exception but somehow it does not affect the operation of the dapp. I am not very sure whether that could be related to the logs getting stored or not.

**Comment by weilbith** [comment]
The origin of this issue is are the code optimization tools which are part of the buid-chain for production mode. One feature of them is to remove all functions `.name` property to save a lot of bytes in the final bundle. Unfortunately this property is used in the SDK to filter logging factory methods. The origin for this filter is to prevent Matrix monkeypatching to overwrite the logging factory.

Once this filtering got resolved to work also for production, there was another minor issue where `loglevel` had an undefined `this` context. While not being sure why this happens in detail, it can be easily resolved by binding their default factory method to an empty context.
