### ISSUE TITLE
PR check for missing CHANGELOG entries broken

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2776]
It fails to push comments for forks (see [this log](https://pipelines.actions.githubusercontent.com/sfNS90Um6EluR49RnGLZTKIUWB7uGmYI066dNW4AP5Ft6vFzkd/_apis/pipelines/1/runs/2112/signedlogcontent/3?urlExpires=2021-06-03T10%3A10%3A50.5681951Z&urlSigningMethod=HMACV1&urlSignature=EJAhjEMHMifNTkO37ewplxUZrlfw2LM9WM7CkjQd6Vo%3D)).

**Comment by taleldayekh** [comment]
Atm, not possible to fix this on public repositories due to GitHub. Reopen if/when GitHub makes this possible.

**Comment by weilbith** [comment]
I'll try to subscribe to the changes by GitHub and fix is when possible.
