### ISSUE TITLE
Create an issue template for bugs

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#279]
## Description
Create an issue template for bugs

## Acceptance criteria
- The right balance between details and not scaring the user from opening issues has been found

## Tasks
- [ ]

**Comment by nephix** [comment]
We did really well by keeping it limited to:

# Steps to reproduce
1. Do this
2. Click here

# Expected result
* Button is blue

# Actual result
* Button is green

Besides that, Mozilla has a really solid [guide](https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines).
