### ISSUE TITLE
SDK: fix navigation bugs in deployed docs

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2792]
[See this comment](https://github.com/raiden-network/light-client/issues/2792#issuecomment-857804849)

### Todo

- [ ] Investigate and fix the problem

**Comment by andrevmatos** [comment]
It does work, but some links in the Readme and/or when navigating from one page to another inside the deployed docs, you end up getting redirected to the dApp due to the router fallback guards

**Comment by taleldayekh** [comment]
@andrevmatos I updated the issue title and description.

**Comment by agatsoh** [comment]
@andrevmatos Could you pinpoint atleast one link which gets redirected wrongly ?

**Comment by andrevmatos** [comment]
In the docs homepage, `Architecture > Vertical`, there's a `Raiden` link, which should lead to the `Raiden` class documentation, but redirects to the dApp.

**Comment by agatsoh** [comment]
@andrevmatos @taleldayekh The `abi` and `deployment` now dont exist, what do we want those bullet points to be replaced with ?

> - [`abi`](https://github.com/raiden-network/light-client/tree/master/raiden-ts/src/abi) and [`deployment`](https://github.com/raiden-network/light-client/tree/master/raiden-ts/src/deployment) are data directories and don't contain any logic.
 
>- `abi` is the output of the [TypeChain](https://github.com/ethereum-ts/TypeChain) contracts interfaces used for type safety.
>- `deployment` contains information about the deployed Raiden contracts for the Ethereum test networks.
