### ISSUE TITLE
Implement gas price scaling in order to ensure transactions are mined in due time

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#2795]
## Description
Some onchain transactions in SDK need to be guaranteed to be mined before a given block. With scenarios of high gas price fluctuations, like mainnet and goerli currently, transactions may take several hours to get mined with the _naive_ approach currently set if simply using return of `eth_gasPrice` RPC method (default strategy of `ethers` when no gas price is specified). In dApp with e.g. Metamask, this is not a big problem, as the user needs to interactively confirm the transaction prompt, and therefore is in charge of guaranteeing a reasonable gas price, but CLI needs to perform this on its own.

Currently, the main transactions which have a "deadline" are:
- channel withdraw (withdrawal expiration block)
- channel update ( settleable block)
- secret register (lock expiration)

The proposed strategy is to start with the value returned by `eth_gasPrice`, and bump it by a given multiplier (e.g. 50%) when achieving **half way** through the deadline.
To do this from a central place, we should have contracts transactions requests be emitted as actions, and then a central epic to serialise and submit them, controlling `nonce` and `gasPrice` given strategy above.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
This got fixed with a simpler approach in #2804, I'm reopening so we can address this in the proper manner after mainnet

**Comment by taleldayekh** [comment]
Not relevant after the ERC1559.
