### ISSUE TITLE
dApp - remove allow mainnet flag 

### ISSUE THREAD

**Issue by weilbith** [raiden-network/light-client#2815]
## Description

After the mainnet release, no environment disabled mainnet anymore. Therefore this flag has no point anymore. To keep the code clean, we should remove this "feature".

**Comment by palango** [comment]
We might still wan't to disable mainnet on staging, right?

**Comment by weilbith** [comment]
Why should we?

**Comment by taleldayekh** [comment]
Closing, we will not enable mainnet on staging.
