### ISSUE TITLE
Add yarn global path while installing the raiden-cli, fix raiden-cli error

### ISSUE THREAD

**Issue by agatsoh** [raiden-network/light-client#2834]
## Steps to Reproduce
1. `yarn global add @raiden_network/raiden-cli`
2. `raiden-cli ` is not available on the commandline so user cannot do `raiden-cli --help`

## Expected Result
- `raiden-cli` should be available to me on the commandline

## Actual Result
- `raiden-cli ` is not available on the commandline so user cannot do `raiden-cli --help`
This is because the yarn global path needs to be on the `PATH ` variable

After we export the yarn global path on the PATH variable only then does the `raiden-cli` become available 
`export PATH=$PATH:$HOME/.config/yarn/global/node_modules/.bin`

But after adding this we get an error
```
$ raiden-cli --help
/home/pi/.config/yarn/global/node_modules/.bin/raiden-cli: 5: /home/pi/.config/yarn/global/node_modules/.bin/raiden-cli: Syntax error: "(" unexpected
```

## Tasks
- [ ] Add yarn global path to the `PATH` variable
- [ ] fix `raiden-cli` error

**Comment by taleldayekh** [comment]
Not relevant.
