### ISSUE TITLE
Get logs showing all Raiden operations performed on the NanoPi

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2841]
## Description

We need to get the logs from the same NanoPi used in the train demo that shows all Raiden operations being performed, e.g. opening channel, direct transfer, mediated transfer, receiving transfers, closing and settling.

## Acceptance criteria
- The NanoPi should run the latest Light Client release.
- The Light Client does **not** have to be build on the NanoPi, running it is sufficient.
- The logs should contain all Raiden operations detailed in the Raiden protocol and relevant for expected Light Client usage.

## Tasks
- [x] Figure out how to get the Light Client running on the NanoPi again.

**Comment by eorituz** [comment]
Here are the Logs:

Actions with timestamps:
1) Direct Transfer at 11:09 UTC
2) Mediated Transfer at 11:10 UTC
3) Open Channel at 11:13 UTC
4) Withdrawal from Channel at 11:18 UTC
5) Close Channel at 11:21 UTC
6) Receive direct Transfer at 11:24 UTC
7) Receive mediated Transfer at 11:25

[nanopi_raiden.txt](https://github.com/raiden-network/light-client/files/6763879/nanopi_raiden.txt)

**Comment by taleldayekh** [comment]
That is great! Thanks a lot for the effort @eorituz
