### ISSUE TITLE
dApp: Add "popup" with randomised message after successful transfer

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2845]
## User Story

As a visitor on EthCC participating in the UX/UI survey I want to see a popup that randomly displays whether I get a t-shirt or a beer after I've completed a transfer.

**This will be throwaway code** and should therefore be kept simple and a minimum viable effort is sufficient. Should not be considered as a long term addition to the code base.

@DinaBB feel free to add any more details.

## Acceptance criteria

dApp should display a popup message with either a t-shirt or a beer.

## Tasks

- [ ] Could be implemented in a temporary EthCC branch that gets deleted after the conference?

**Comment by DinaBB** [comment]
Pop up example:

**Comment by palango** [comment]
@weilbith This can be closed, right?
