### ISSUE TITLE
Bring up offline hub

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2858]
@palango fill in details

## PRs
- https://github.com/raiden-network/ansible-role-raiden-hub/pull/5
- https://github.com/raiden-network/hub.raiden.network/pull/5

**Comment by weilbith** [comment]
The related PRs (raiden-network/hub.raiden.network#6 and raiden-network/ansible-role-raiden-hub/pull#5) have been merged. The new hub is up and available. I already opened a channel to it and now see if I can do a transfer. As soon as that passed I'll close the issue.

**Comment by weilbith** [comment]
Transfer visible at https://hub.raiden.network . Done ✔️
