### ISSUE TITLE
Two times settling a channel leads to non-clickable token

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#286]
## Steps to reproduce
1. Connect to Kovan
2. Open the dApp at lightclient.raiden.network
3. Settle only available channel (has not been a valid address)
3. Settle the channel a 2nd time
4. Going back to the token screen
5. Click on the WETH token

## Expected result

* Menu to pay, etc. opens

## Actual result

* Nothing happens (see 
[lightclient.raiden.network-1566887702277.log](https://github.com/raiden-network/light-client/files/3544629/lightclient.raiden.network-1566887702277.log)

* Warning:
`Adding default global override for .m.rule.tombstone`

* Errors:
`MetaMask - RPC Error: The execution failed due to an exception`
`Error: No seed provided`

## Actual result (after restart)

* Empty token list

**Comment by christianbrb** [comment]
After a restart and reconnection the token list is empty

**Comment by nephix** [comment]
@christianbrb I wasn't able to reproduce this

**Comment by nephix** [comment]
I'm closing this one, as I can't reproduce it. I assume it got fixed within another bug fix
