### ISSUE TITLE
Fix CI publish staging workflow

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2877]
The CI pipeline works for the default workflow. But it fails for the `publish_staging` workflow when executing the dApp end-to-end tests. The only obvious difference for the tests between both pipelines is that one runs with an `e2e` mode build of the dApp, while the other uses the `staging` mode. That might have an impact. But a first analysis reveals an issue that pops up way earlier in the test flow. In fact Cypress fails to load the dApp at all. It can't even access the very landing page.
This is especially awkward for two reasons. First does Cypress initially check if there is a server running under the configured URL. If there is no process listening, Cypress will fail even earlier and reports this specific error. Second, I re-run the job in CI with an SSH connection to the machine. I turned on the logging (`set -x`) for the `run-cypress.sh` script. Everything looks fine. And if I `curl` the dApp while the Cypress tests are running, I successfully get the `index.html` file. So after all the web-server is working and it serves the build `staging` version of the dApp. Though something in the setup phase of the VueJS application loaded in the `index.html` does not seem to work. Unfortunately we are still unable to see the `console` of the dApp within the videos of the tests. Therefore we need to check if we can reproduce the issue locally with a `staging` build and then debug it. We might need to add some missing environment variables to the mode.

**Comment by weilbith** [comment]
I filled the details into the issue body.

**Comment by weilbith** [comment]
Okay, the issue is simple: the staging build gets build to working under the sub-path `/staging/...`. The end-to-end test server serves everything under root `/`. This means the production pipeline should not be affected.
The question is a little tricky. We somehow need to know for which mode the dApp was build then source their build environment variables to then adopt the server asset path.
