### ISSUE TITLE
Deploy Arbitrum node

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2908]
## Description

Deploy a company wide Arbitrum node connected to Rinkeby.

## Acceptance criteria
- 

## Tasks
- [ ] @weilbith Sets up server

**Comment by weilbith** [comment]
Just for the matter of documentation: the server was provided last Friday and Andre got access to iit.

**Comment by taleldayekh** [comment]
Thank you @weilbith.

**Comment by andrevmatos** [comment]
I've got an Arbitrum node running with the command below, which can be easily turned into a `docker-compose.yml` file:
```sh
podman run --rm -it --name arb-node \
  -p 8547:8547 -p 8548:8548 \
  -v /mnt/data/arbitrum-rinkeby:/arbitrum \
  offchainlabs/arb-node:v1.0.0-beta19-38e1600 \
  --l1.url=http://10.88.0.1:8745 \
  --persistent.global-config=/arbitrum
```

This will bring up a `forwarder node`, which can be used to query the state of the L2 chain and just forwards the transactions one by one from the user. A more useful node, called an `aggregator node`, can be run by appending these parameters:
```sh
--node.type=aggregator --wallet.local.pathname=/path/to/wallet.json --wallet.password=pass
```

An aggregator node needs to have a wallet with native tokens (ETH on each L1) to pay for transactions (so it _costs  money_ to be run), but can collect fees and makes transactions cheaper by being able to aggregate several L2 txs and compress them in a single L1 commit. Of course, it can only batch txs from its own users, so it's not very useful to run an aggregator node which will submit just a handful txs per time unit.

That said, the most useful node in arbitrum is called a `sequencer node`; for now, it is centralised, only one on each chain can be run, and the ones from the main deployments (rinkeby and mainnet) are run by OffchainLabs. The sequencer node offers the best batching possible, and instant finality, as it controls the sequence of the priority tx queue. In case it'd censor user's txs, the longer path through a normal node could always be taken, so it's only a convenience improvement. The company is working on decentralising it, but for now, this is how everyone is using Arbitrum, and is the recommended way.

Currently, the L2 data is still syncing, but as soon as it's complete, I can consider this issue as closed, and the above details are documentation on how to do it, if it becomes needed at some point.
