### ISSUE TITLE
Move ERC20 tokens from Rinkeby to Arbitrum

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2910]
## Description

Understand how to get ERC20 tokens from the testiest to Arbitrum and describe the process in comments that can later be extended to a documentation.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by palango** [comment]
Is this about test tokens or proper mainnet tokens?

We deployed mintable token contracts on the arbitrum testnet, so no tokens need to be moved for this.

If we want to integrate this further, we have to create a special L2 token contract, like this example here: https://github.com/OffchainLabs/arbitrum/blob/master/packages/arb-bridge-peripherals/contracts/tokenbridge/test/TestArbCustomToken.sol

This then need to be registered in the Arbitrum token gateway: https://developer.offchainlabs.com/docs/bridging_assets#the-arbitrum-generic-custom-gateway

**Comment by taleldayekh** [comment]
This has been done manually, because we decided against adding an interface for it.
