### ISSUE TITLE
Start Matrix and PFS servers with the Arbitrum provider

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#2911]
## Description

We need to make sure that working Matrix and PFS servers are used.

Lacking Python support makes the registration difficult and we need to find workaround. Alternative would be to rewrite the script for registering the services in the service registry.

Should be easy to rewrite to JS.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by palango** [comment]
PFS and Matrix are running now:  https://pfs.arbitrum.env.raiden.network/api/v2/info

**Comment by andrevmatos** [comment]
Thank you, @palango . It's up and running thanks to you! I'll put the instructions for the client on #2913 , we can consider this one done.
