### ISSUE TITLE
this.channelWithBiggestCapacity is undefined

### ISSUE THREAD

**Issue by BOR4** [raiden-network/light-client#297]
I've been playing with https://lightclient.raiden.network and encountered this error.

How I reproduced:

1. had old address I used to play with lightclient before
2. clicked disconnect token (WETH)
3. accepted and signed all transactions (all channels are in closed)
4. clicked on WETH again and then pay
5. selected deposit
6. typed in an amount
7. got error

Screen shot:
![image](https://user-images.githubusercontent.com/40821065/64062451-ac96ee80-cbe6-11e9-8770-9aeeb6ae4ead.png)

I assume problem is it is searching for OPEN channel with biggest capacity however since all are closed it throws an exception.

If you need more info let me know.

**Comment by kelsos** [comment]
Yes, it is searching for an open channel with the biggest capacity. The information you provided should be sufficient. Thank you for reporting.

**Comment by christianbrb** [comment]
Should be fixed
