### ISSUE TITLE
User Facing Light Client Issues

### ISSUE THREAD

**Issue by MrCleanerPickerUpper** [raiden-network/light-client#298]
Issues found while using light client:

After connecting to Hub (0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6) it doesnt show how much WETH I have available to open a channel, it only shows available WETH once ive typed in a number.

After typing in a number I have to put a whole number (1,2,3,4...) before it allows me to put a decimal place. I.e. I cannot just put .5, i have to put 3.5 then delete the 3.

When opening a channel, there is a step guy on top showing the stages. The image is obscured, each process has a strange diamond/square on top to make the steps not readable. 

![raidengraphic](https://user-images.githubusercontent.com/54746230/64066367-41e1b500-cbde-11e9-8572-97ccbeb7a976.png)

Unable to open channel: Set total Deposit Failed 

![error](https://user-images.githubusercontent.com/54746230/64066370-4d34e080-cbde-11e9-8f26-2bce609d1cfd.png)

When retrying it goes straight to "oops something went wrong, channel open failed"

**Comment by christianbrb** [comment]
@MrCleanerPickerUpper Thanks for testing the light client :-)

For the first two paragraphs, I have created separate issues (see #299 and #300).

Could you provide us information
- which browser you are using
- the error shown in the browser console logs (if you are familiar with it)

**Comment by kelsos** [comment]
@MrCleanerPickerUpper The current version uses the Red Eyes contracts. The Red Eyes contracts unfortunately only allow up to 0.15 as a deposit and everything bigger will actually fail. We will start a discussion to integrate the limit checking in the newer version.

In regards to the stepper, I have seen this in a few browsers and we should probably remove it temporarily until we find a cross-browser compatible way to implement that doesn't break. @roy-castrillo.

**Comment by roy-castrillo** [comment]
@kelsos remove the stepper completely or leave it, but remove the shapes behind them? See the example:

![Screenshot 2019-09-03 at 13 57 29](https://user-images.githubusercontent.com/47739420/64171385-d2283000-ce52-11e9-8587-db1612f3b757.png)

**Comment by kelsos** [comment]
Just remove the shapes, yes that looks great :D

**Comment by christianbrb** [comment]
Approach
- First try to fix the current solution.
- If this is not doable implement the new approach

**Comment by christianbrb** [comment]
@MrCleanerPickerUpper Thanks again for your feedback

We have created two additional issues regarding your feedback:
- #302 
- #313
