### ISSUE TITLE
PUT `api/v1/channels/` for existing channel crashes node

### ISSUE THREAD

**Issue by ezdac** [raiden-network/light-client#2998]
When doing a `PUT` (instead of a `PATCH`) to a channel that already exists (e.g. because partner opened it),
a `409 - conflict` is received. Unexpectedly, the [error](https://github.com/raiden-network/light-client/blob/b51dff44e492e757992ce72171ef76cab7621984/raiden-ts/src/channels/epics/open.ts#L119) is not caught in the running node and will make it crash:

```
node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

RaidenError: Invalid channel state.
    at /Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:255996:65
    at doInnerSub (/Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:212905:31)
    at outerNext (/Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:212900:70)
    at OperatorSubscriber._this._next (/Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:211157:21)
    at OperatorSubscriber.__webpack_modules__.85607.Subscriber.next (/Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:209261:18)
    at /Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:215184:28
    at OperatorSubscriber._this._next (/Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:211157:21)
    at OperatorSubscriber.__webpack_modules__.85607.Subscriber.next (/Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:209261:18)
    at /Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:212742:24
    at OperatorSubscriber._this._next (/Users/ezdac/bbot/light-client/mainnet-testing/bundle/index.js:211157:21) {
  details: { state: 'open' }
}
```

## Steps to Reproduce
1. open channel from node1 to node0
2. on node0, try to open channel to node1 with same arguments 

## Expected Result
- An error should be returned
- The node should continue to work

## Actual Result
- The error is returned
- The node crashes

**Comment by andrevmatos** [comment]
There's something weird here: the error (that you linked) is specifically not thrown, but instead returned; it means it can't shutdown the state machine, and is how the SDK is expected to behave. But returned promises, on the `Raiden` class/public API, do convert these errors and reject the returned promises. This is usually fine and doesn't affect the state machine runtime, unless something else in the cli isn't handling this error properly and instead shutting down the node.
Do you have the complete logs for this issue?

**Comment by andrevmatos** [comment]
There's something weird here: the error (that you linked) is specifically not thrown, but instead returned; it means it can't shutdown the state machine, and is how the SDK is expected to behave. But returned promises, on the `Raiden` class/public API, do convert these errors and reject the returned promises. This is usually fine and doesn't affect the state machine runtime, unless something else in the cli isn't handling this error properly and instead shutting down the node.
Do you have the complete logs for this issue?

**Comment by andrevmatos** [comment]
I reproduced it locally. The issue actually only happens on NodeJS v15+, as since then, node started to exit when a promise rejected without being handled. The fix (in PR) is to ensure the `openChannel` dangling promises are parallelly awaited (with `Promise.all`), and to ensure CLI doesn't shut down on unhandled rejections (as those only happen on public API methods and don't affect state machine)

**Comment by ezdac** [comment]
> Do you have the complete logs for this issue?

Sorry, I do not have it on hand. I could dig for it though if this is important, but since you found the issue I assume not anymore?

>  on NodeJS v15+

Indeed, I was using Node 16
