### ISSUE TITLE
I do want to be able to type an eg. .5 instead of a 0.5 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#300]
## User Story
As Chris I do want to be able to just type an eg. .5 instead of a 0.5 so that I am faster entering the payment amount

> After typing in a number I have to put a whole number (1,2,3,4...) before it allows me to put a decimal place. I.e. I cannot just put .5, i have to put 3.5 then delete the 3.

## Tasks

cc @MrCleanerPickerUpper

**Comment by nephix** [comment]
Built-in in `<input type="number" />`, only need to switch to that in `AmountInput` component

**Comment by kelsos** [comment]
@nephix Basically the reason the field is not a number, is that Firefox has an issue handling more than 16 decimal points on the `type="number"`, and people were complaining about that on the WebUI so I decided to avoid the issue here. :)

**Comment by nephix** [comment]
I didn't know that, how ugly! Thanks for noticing and mentioning

**Comment by christianbrb** [comment]
Considering this would the implementation be more complex than 1 story point?

**Comment by nephix** [comment]
No, max 2. But I will need to address this within #1160 because they are related
