### ISSUE TITLE
Better inform user about deposit limits in the contract

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#302]
## Description

Currently, if the user tries to deposit a bigger amount than the limit. The deposit transaction will fail and a really unhelpful will be displayed. In the newer contracts, the limits are set during the deployment. 

If we can actually read a TokenNetwork's deposit limit then it would be better to check before calling deposit. This way we can stop a failing onchain transaction and also provide a more user-friendly message.

This should be done after upgrading to the Alderaan contracts.

## Acceptance criteria
- Fail before calling the deposit function
- Show a more meaningful message

## Tasks
- [ ]

**Comment by christianbrb** [comment]
CC @MrCleanerPickerUpper This is a follow-up issue on your reported issue #298

**Comment by taleldayekh** [comment]
It is very unlikely that a user runs into this.
