### ISSUE TITLE
Check pre-releases of critical dependencies it poses any future risks for the LC on proof of stake migration

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#3099]
To catch any potential issues early on.

**Comment by andrevmatos** [comment]
I just checked, the only lib which could suffer some impact from the merge would be [ethers.js](https://github.com/ethers-io/ethers.js), our web3 library, but the merge is expected to be transparent for the JSON RPC API (which we interact through this library), so they don't have any pre-release tagged nor planned, afaik. There's some work in a v6 major update, but it's feature-driven, and not strictly related nor timed for any time before the Merge itself.
We'll keep an eye and update as needed.
