### ISSUE TITLE
Identify inconsistencies between design and implementation

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#311]
## Description
Compare design and already implemented screens and define changes that must be made; if possible, implement them as well.

## Acceptance criteria
- Both design and implementation must be syncrhonised.
- When design and implementation look different, it must be decided whether we want to fine-tune them (bring them to 100%-100%) or whether we leave them as they are.

## Tasks
- [x] @nephix and @roy-castrillo hold meeting to compare design vs implementation
- [x] @nephix and @roy-castrillo make list of inconsistencies and prioritize them in order of importance and feasibility to implement during next iteration.

**Comment by christianbrb** [comment]
@roy-castrillo Do you still work on this issue or can we close it?

**Comment by roy-castrillo** [comment]
@christianbrb it's still something I'd like to do before leaving. Maybe I could arrange a meeting with @nephix?

**Comment by nephix** [comment]
@roy-castrillo sure, how about next Thursday?

**Comment by nephix** [comment]
Meeting notes:
* Connected tokens:
  * Wrong letter spacing on buttons in dropdown
* Replace start screen with transfer screen (#519)
* Find meaningful app header label (e.g. currently **Raiden dApp** or **Send** on transfer screen)
* Token overlay
  * Wrong icon spacing
* Transfer screen
  * Missing `>` arrow in call to action button
* Transfer stepper
  * Missing `>` arrow in call to action button
  * PFS selection
    * Maybe not pre-select a route?
    * Show amount to be transfered in continue button, after PFS got selected
    * Remove separating header line from PFS selection table
    * Add more spacing between rows in PFS table
  * Select Route
    * Remove separating header line from PFS selection table
    * Add more spacing between rows in PFS table
  * Confirmation screen
    * Proposal TBD by @roy-castrillo & @taleldayekh 
* Route payment overlay (implemented as part of #463)

**Comment by christianbrb** [comment]
@nephix Thanks :)

Could you split the comment into separate issues? Maybe summarizing the very small changes into one issue.

**Comment by nephix** [comment]
@christianbrb I have created the following tickets:
#542 
#543 
#544 

I'm closing this ticket, because we've identified the inconsistencies
