### ISSUE TITLE
Simplify and fix open channel stepper

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#313]
## Description
The stepper shown in the dApp when opening a channel seems to be broken on at least one browser. We decided to simplify the stepper.

Split from #298 

First proposal:

![Screenshot 2019-09-03 at 13 57 29](https://user-images.githubusercontent.com/47739420/64171385-d2283000-ce52-11e9-8587-db1612f3b757.png)

## Acceptance criteria
- The best simple solution is implemented

## Tasks
- [x] Call between @nephix and @roy-castrillo

**Comment by nephix** [comment]
Decision by @roy-castrillo and @nephix:

* Proposed simplified channel step view won't be implemented
* @nephix will fix the current channel step view as it is less effort
