### ISSUE TITLE
Multi-Hop?

### ISSUE THREAD

**Issue by MrCleanerPickerUpper** [raiden-network/light-client#314]
## Steps to Reproduce
1. Connect to node1.mat7ias.eth
2. Attempt to pay node2.mat7ias.eth
3. Error: Target not available/not online

![image](https://user-images.githubusercontent.com/54746230/64395474-09980780-d020-11e9-8458-8b80738d69d3.png)

## Expected Result
- Payment to go through node1 to pay node 2

## Actual Result
- target not available/not online

## Additional Infos (Optional) 
```
- Browser & version: Chrome 
Version 76.0.3809.132
- Browser console errors
- Device / OS: Windows 10, MSi
```

**Comment by andrevmatos** [comment]
Hi, @MrCleanerPickerUpper , thank you for getting involved and your report about this issue.
The error you pointed is registered here: https://github.com/raiden-network/light-client/blob/bbfd1842be66067c5739ef83a47bb05964307814/raiden-ts/src/transfers/epics.ts#L98-L99
Do you see any errors in browser console (dev tools)? It seems a user on transport server matching your target was found (the monitored check above), but it was not online or could be reached in Matrix. Please, paste the whole logs (from browser's console) in a pastebin and post here, if possible. Is there any chance the target node was not online (or on the same chain) at the time of the tried transfer?
Thank you

**Comment by MrCleanerPickerUpper** [comment]
> Hi, @MrCleanerPickerUpper , thank you for getting involved and your report about this issue.
> The error you pointed is registered here:
> 
> https://github.com/raiden-network/light-client/blob/bbfd1842be66067c5739ef83a47bb05964307814/raiden-ts/src/transfers/epics.ts#L98-L99
> 
> 
> Do you see any errors in browser console (dev tools)? It seems a user on transport server matching your target was found (the monitored check above), but it was not online or could be reached in Matrix. Please, paste the whole logs (from browser's console) in a pastebin and post here, if possible. Is there any chance the target node was not online (or on the same chain) at the time of the tried transfer?
> Thank you

@mat7ias had mentioned that his nodes indeed were not online. So it was a correct error. 

Hard to get an image of which hubs and full nodes are online or offline.
