### ISSUE TITLE
Usability: List of Reliable Nodes for Light Client Testing

### ISSUE THREAD

**Issue by MrCleanerPickerUpper** [raiden-network/light-client#315]
1. List of nodes/hubs that are available to open a channel with
2. Rank based on reliability score of % up time and fewest open channels (possible path finding service testing mechanism)?
3. Test addresses to send too from this open channel (other smaller hubs)?

**Comment by mat7ias** [comment]
The issue follows unaddressed point 4 in awesome-raiden, [here](https://github.com/raiden-network/awesome-raiden/issues/6). Also to point out that on testnet, ENS "mat7ias.eth" and its subdomains (mentioned in #314) currently are not reliable testing hubs/nodes for light clients. Saying that I'm happy to run multiple testnet nodes on-demand (for short periods) to help your testing @MrCleanerPickerUpper if you contact me directly through [community channels](https://github.com/raiden-network/awesome-raiden#community-channels).

**Comment by christianbrb** [comment]
@MrCleanerPickerUpper The [following guide](https://github.com/raiden-network/light-client#try-out-the-raiden-demo-dapp) has been created, which includes the address of @mat7ias testnode.

In addition, the following issues have been created to (partly) address the problem:
- Autopilot -> #211 (with a reference to an issue in the Pathfinding Repo)
- Show node status in the Raiden Explorer -> https://github.com/raiden-network/explorer/issues/74

I'll therefore close the issue. @MrCleanerPickerUpper Please go ahead and reopen the issue with a comment, if any of your proposals haven't been addressed.
