### ISSUE TITLE
 I want to know when the Light Client is connecting

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#318]
## User Story
When clicking **Connect** on the starting screen of the light client, the connection process can sometimes take quite a bit of time. As of now, user doesn't receive any feedback from the UI and the UI remains active while waiting:

![light-client-starting-screen-unresponsive](https://user-images.githubusercontent.com/3169205/64422853-583bb500-d0a5-11e9-928b-18819e6b7997.gif)

In that case connecting the light client took roughly 20secs (MetaMask & Goerli test network)

## Acceptance criteria
* TBD
* Replace button with loading spinner?
* Disable button and show loading spinner inside of the button?

## Tasks
- [ ] Design
- [ ] Implementation

**Comment by andrevmatos** [comment]
Done in #339
