### ISSUE TITLE
Disconnect token fails without user feedback

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#331]
## Prerequisites
* Connected to a Token
* Token only has channels in state `settleable` or `settling`

## Steps to Reproduce
1. Go to http://lightclient.raiden.network
2. Click Connect
3. Click on Token
4. Click Disconnect Token
5. Click Confirm

## Expected Result
- Token is disconnected and I receive a confirmation
- If disconnecting from Token did not work, I receive feedback why it failed

## Actual Result
- No feedback in UI

## Additional Infos (Optional) 
Console error `action channelCloseFailed`:

> Error: channel for "0x67b0Dd5217dA3F7028e0c9463FdaFBF0181e1E0A" and "0xbdb4a827588A292354EA4e6C67492e34eEB98bB7" not found or not in 'open' or 'closing' state
>     at MergeMapSubscriber.eval [as project] (webpack-internal:///../raiden-ts/dist/channels/epics.js:673:19)
>     at MergeMapSubscriber._tryNext (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/mergeMap.js:71:27)
>     at MergeMapSubscriber._next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/mergeMap.js:61:18)
>     at MergeMapSubscriber.Subscriber.next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subscriber.js:63:18)
>     at WithLatestFromSubscriber._next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/withLatestFrom.js:71:34)
>     at WithLatestFromSubscriber.Subscriber.next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subscriber.js:63:18)
>     at FilterSubscriber._next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/filter.js:42:30)
>     at FilterSubscriber.Subscriber.next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subscriber.js:63:18)
>     at TakeWhileSubscriber.nextOrComplete (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/takeWhile.js:50:25)
>     at TakeWhileSubscriber._next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/takeWhile.js:45:14)
>     at TakeWhileSubscriber.Subscriber.next (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Subscriber.js:63:18)
>     at Notification.observe (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/Notification.js:27:50)
>     at QueueAction.ObserveOnSubscriber.dispatch (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/operators/observeOn.js:48:22)
>     at QueueAction.AsyncAction._execute (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/scheduler/AsyncAction.js:68:18)
>     at QueueAction.execute (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/scheduler/QueueAction.js:31:18)
>     at QueueScheduler.AsyncScheduler.flush (webpack-internal:///../raiden-ts/node_modules/rxjs/_esm5/internal/scheduler/AsyncScheduler.js:47:32)
>

**Comment by christianbrb** [comment]
Channel Close is now gracefully handled

![grafik](https://user-images.githubusercontent.com/35398162/67262938-c64a0900-f4a6-11e9-824f-3f041feeccf1.png)
