### ISSUE TITLE
Does the light client support payment?

### ISSUE THREAD

**Issue by mnxzyw** [raiden-network/light-client#333]
## Description
>I have two accounts, one is the light client, the other is the raiden node. I found that the account where the light client is located can transfer to the account of the raiden node, but the account where the raiden node is located could not transfer to the account of the light client
- What I want to know is whether the light client can only transfer coin to others, but cannot be transferred

**Comment by christianbrb** [comment]
@mnxzyw Thanks for your question :-)

The Light Client is only able to send payments at the moment. It is not able to receive them. 

After we have adapted the Light Client to the newest Raiden Client Release Alderaan we are going to start implementing receiving payments. 

Let me know if you have got additional questions :-)

**Comment by mnxzyw** [comment]
@christianbrb Thank you very much for your answer.
