### ISSUE TITLE
Add "Status of Transfer" function

### ISSUE THREAD

**Issue by eorituz** [raiden-network/light-client#355]
## Description
We should add a function that returns the status of a particular transfer.
I am thinking about something like a function that takes a particular Transfer and returns something like "unlocked/successfull" or "locked/pending" or "secret registry called by intermediate /problem"

## Acceptance criteria
- Implement a function that returns a status for a given transfer

**Comment by andrevmatos** [comment]
We already expose this, but it's not a function, it's an observable you can subscribe to, which emits a bunch of information about each transaction as the state changes. It includes all these information you asked for. Specially, look into the `status`, `success` & `completed` properties
https://github.com/raiden-network/light-client/blob/ca9cfb8e44e0a0fe6a68ec1f2a341a01c9cb6b0d/raiden-ts/src/raiden.ts#L91-L96
https://github.com/raiden-network/light-client/blob/ca9cfb8e44e0a0fe6a68ec1f2a341a01c9cb6b0d/raiden-ts/src/transfers/state.ts#L81-L124
https://github.com/raiden-network/light-client/blob/ca9cfb8e44e0a0fe6a68ec1f2a341a01c9cb6b0d/raiden-ts/src/transfers/utils.ts#L63-L113
Please, reopen if anything else is needed.

**Comment by nephix** [comment]
In SDK API docs:

- https://lightclient.raiden.network/docs/classes/raiden.html#transfers
- https://lightclient.raiden.network/docs/interfaces/raidensenttransfer.html#properties
- https://lightclient.raiden.network/docs/enums/raidensenttransferstatus.html#enumeration-members
