### ISSUE TITLE
Provide feedback to PFS for routes

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#358]
## Description

Follow up ticket for https://github.com/raiden-network/light-client/pull/330#discussion_r328995823

As a PFS maintainer I want to collect feedback on the routes that PFS provides

## Acceptance criteria
- When processing payments, send the `feedback_token` to PFS' `/feedback` route as explained [here](https://raiden-network-specification.readthedocs.io/en/latest/pathfinding_service.html#post-api-v1-token-network-address-feedback)

**Comment by christianbrb** [comment]
@karlb Are you already using the PFS route feedback within the PFS?

**Comment by nephix** [comment]
I talked to @palango about this a while ago and back then he said it's not used

**Comment by christianbrb** [comment]
@nephix Thanks :)

I am doing issue housekeeping to reduce our inventory. I am looking at the least recently updated issues.

It is a nice to have. If the request is going to be raised by a user or the services team we'll reopen the issue.

**Comment by karlb** [comment]
> @karlb Are you already using the PFS route feedback within the PFS?

Still not in use. We wanted to have it in place so that we can start incorporating route feedback without having to change the clients. Updating a PFS is much easier than updating all clients.

**Comment by christianbrb** [comment]
Ok, make sense :) Thanks for your feedback

**Comment by christianbrb** [comment]
Closing this issue and wait for it to be implemented in the PFS.
