### ISSUE TITLE
Capacity can be missleading in payment screen

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#364]
## Steps to Reproduce
1. Have two open channels, one without capacity but online and one with capacity 1.0 TKN but offline
2. Attempt to send payment
3. Payment fails despite capacity being reported as 1.0 TKN

## Expected Result
- Capacity should be 0 since the online open channel with the biggest capacity has no capacity left.

## Actual Result
- The capacity of the biggest channel is reported as 1.0 TKN instead of 0 since only the `open` status of the channel is taken into consideration and not the presence of the node.

**Comment by christianbrb** [comment]
We could add this to the find path screen (see #350)

**Comment by christianbrb** [comment]
This is interesting and we should take this into account for #571 and #586 

The capacity needs to take the route into consideration and could be validated only after I have entered a target.

**Comment by christianbrb** [comment]
Yes, it would make sense to only show it after a target has been definined?

![grafik](https://user-images.githubusercontent.com/35398162/69854660-ef21a300-1289-11ea-822e-5bbbb34be1e8.png)

**Comment by christianbrb** [comment]
Dependant on #571

**Comment by christianbrb** [comment]
This seems to be complicated to achieve. T
