### ISSUE TITLE
Update onboarding guide after the switch to Alderaan

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#368]
## Description
We have switched from the Red Eyes to the Alderaan contracts. 
Therefore the current onboarding guide (https://github.com/raiden-network/light-client#try-out-the-raiden-demo-dapp) is not working anymore.

CC @taleldayekh 

## Acceptance criteria
- A Goerli test node is provided
- The guide is updated to work with Goerli

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
This has been fixed so I will close the issue.
