### ISSUE TITLE
Automatically create release notes

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#369]
## Description
There should be a way and process how to automatically maintain the release notes in regards to 
- Bugs
- Enhancements/Features

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb I am not aware of a good automated way to do it.

I would suggest following the same process we do in the WebUI by keeping a ChangeLog, which is similar to the one done in the Raiden client. 

In the WebUI, the format of the ChangeLog is following [this](https://keepachangelog.com/en/1.0.0/).

After that, each developer should be responsible for updating the ChangeLog as part of their PRs. 

Then we could include the ChangeLog in the releases as release notes.

**Comment by christianbrb** [comment]
Duplicate of #643
