### ISSUE TITLE
Automated releases of SDK to NPM upon GH release

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#370]
## Description
Automated releases of SDK to NPM upon GH release

Related to #38

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@kelsos Is this a duplicate of https://github.com/raiden-network/light-client/issues/38 ? If yes, please go ahead and close it. Thanks :)

**Comment by kelsos** [comment]
I would say that #38 contains this issue so yes I am closing this one.
