### ISSUE TITLE
I want to get a warning if I try to open a channel with 0.0 tokens

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#371]
## User Story
As Chris, I want to get a warning if I try to open a channel with 0.0 tokens so that I am able to use the channel when I have opened it.

**Comment by kelsos** [comment]
@christianbrb what does this mean technically, that you are still allowed to open a channel without deposit but you get a warning that the channels will be unusable until you deposit?

**Comment by christianbrb** [comment]
Yes :-)

**Comment by christianbrb** [comment]
Closed via #647
