### ISSUE TITLE
I want to be able to cancel a payment

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#374]
## User Story
As Chris I want to be able to cancel a payment so that I can continue using the app or retry the payment, if the payment hangs (see #373).

**Comment by andrevmatos** [comment]
I'd say we shouldn't work yet on canceling payments. My idea here is, instead, that the payments will be non-blocking, and go to a "pending transfers" badge/counter/dropdown in some corner, and free the user to continue using the dApp to do other things, as well as inspect the status of any of the pending and past/completed transfers from this dropdown. To "cancel" payments can only be done before revealing the secret, and consists of just deleting the secret (so we can't reveal it anymore) and still need to let it expire, so it'll at least continue as pending/non-completed until it expires.

**Comment by christianbrb** [comment]
Ok, we need to decide on a way how to deal with it

**Comment by kelsos** [comment]
I also agree that implementing a non-blocking design and having a list of pending transfers, is the best approach. However it would be even better if you don't have to interactively sign all the messages in the protocol.

**Comment by christianbrb** [comment]
Closing in favor of
#168 
#172 
#426
