### ISSUE TITLE
Show payment screen only after status = "completed"

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#375]
## Steps to Reproduce
1. Make a payment to 0x456e2459b6E01FF30375D59f24d359655bEB6754
2. Sign 5 transactions in MetaMask

### Workaround
See https://github.com/raiden-network/light-client/issues/375#issuecomment-546352727

### Final
- After signing the last transaction with MetaMask the updated payment screen is shown
        - Payment in process window (spinner) closes on [completed](https://github.com/raiden-network/light-client/issues/375#issuecomment-539488652)

## Actual Result
- After the payment screen is shown I have to sign two additional messages
       - Payment in process window (spinner) closes on [success](https://github.com/raiden-network/light-client/issues/375#issuecomment-539488652)

    ![grafik](https://user-images.githubusercontent.com/35398162/66390421-f1bef500-e9ca-11e9-96e8-3c8e967c0487.png)

**Comment by andrevmatos** [comment]
This is kind of by design: a transfer is considered `successful` before the last signature. It's successful as soon as the secret was revealed, since from that point on, the inititor can already consider it "lost" the sent amount. `success=false` otoh is set upon `RefundTransfer` or lock expiration.
Beyond `success`, what you're looking for is for the screen to persist until `completed` is set, which marks the point when no other signature/action may be needed for this transfer.

**Comment by nephix** [comment]
> Beyond `success`, what you're looking for is for the screen to persist until `completed` is set, which marks the point when no other signature/action may be needed for this transfer.

I think we already wait for `completed` [here](https://github.com/raiden-network/light-client/blob/master/raiden-dapp/src/services/raiden-service.ts#L282) or are we talking about different things?

I also received random meta mask transaction requests in the last couple of days and thought that they might be related to Matrix' current flakiness

**Comment by christianbrb** [comment]
#401 is related

@andrevmatos You where mentioning in the demo, that the messages to be signed are `delivered` messages?

**Comment by kelsos** [comment]
@christianbrb Did we decide on what exactly would the message be?

**Comment by christianbrb** [comment]
@kelsos No, but I would propose.

```
After the payment has been succesfull you need to sign additional messages:
1. To update the pathfinding server
2. To acknowledge delivered messages from the target
```

Does it make sense? If not, take this just as a proposal or we talk about it in the daily.
