### ISSUE TITLE
Warning: Could not decode message:

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#378]
## Steps to Reproduce
1. I don't know ;-)

## Expected Result
- No warnings are shown

## Actual Result
- The following warning is consistently shown

```json
epics.js:546 Could not decode message:
{
   "locked_amount":0,
   "recipient":"0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A",
   "message_identifier":"7374245717309372864",
   "chain_id":"5",
   "signature":"0x24016a4273db4971a86be3d86b8837cc21b0b490ca5d90c27b1b8d464951c15027d3bdbd6bbbcd26e26ebece64aebf83fad68e8bd3faacac72e5ade85a5dbc2f1c",
   "transferred_amount":0,
   "locksroot":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
   "channel_identifier":"36",
   "secrethash":"0x0015932eefc5e501cd87572c1d78d923fe51d20182360c3daabdb9634823bca5",
   "nonce":"4",
   "token_network_address":"0xE36995596D456aaEcD226a303250Bf99cf16b2A0",
   "type":"LockExpired"
}
: Error: Signature mismatch: sender=0x456e2459b6E01FF30375D59f24d359655bEB6754 != signer=0x1fCc46401119A12A5a90eeB81A91AD09eb2bfD1C
```

## Additional Infos (Optional) 
Log:
[lightclient.raiden.network-1570538510339.log](https://github.com/raiden-network/light-client/files/3702379/lightclient.raiden.network-1570538510339.log)

**Comment by andrevmatos** [comment]
Whoah, seems like someone tried to transfer to/mediate through your light client. This is not fatal, but shouldn't mismatch and just be replied with `Processed`. We'll check why the mismatch, maybe something changed on this message schema which we aren't aware of.

**Comment by andrevmatos** [comment]
This isn't fatal though, it keeps showing up because whoever is sending you this is retrying the message, but otherwise can be safely ignored as we don't act on this side of the channel. The useful side of the channels should still be consistent and working.

**Comment by nephix** [comment]
@christianbrb asked me to send him some tokens to `0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A`, which I had sent from `0x456e2459b6E01FF30375D59f24d359655bEB6754` thinking that `0xB84C6bFBA1108543Ea47e8B9a669CB39ffc70f6A` is a full client.

**Comment by christianbrb** [comment]
We still need to create an issue within the Raiden client. Does anybody has got the logs?
