### ISSUE TITLE
Appearance of modal windows

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#379]
## Description

Currently, the modal windows have got different sizes.

Example (Deposit Window)

![grafik](https://user-images.githubusercontent.com/35398162/66549055-c3fcbc00-eb42-11e9-8e90-97105b0553a8.png)

![grafik](https://user-images.githubusercontent.com/35398162/66548904-741df500-eb42-11e9-8cc2-0cc2ca6f2297.png)

## Acceptance criteria
- All modal windows should have the same width
- All modal windows should have the same design

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb @nephix 

Just a small comment to keep in mind that these two modal dialogs are not exactly equivalent. 

The dialog when depositing from the payment screen is a normal modal and it should appear in the center of the viewport. 

The dialog in the expanded area on the other hand while it looks like a modal it should always appear directly above the expanded area that initiated the dialog and it should always have the same size as the expanded area.

**Comment by nephix** [comment]
Thanks for the heads up @kelsos  👍 
It was mostly about the width of the modals though. Their position didn't change

**Comment by kelsos** [comment]
Yes I already checked it :D I just mentioned it because I was not sure if
that design decision was clear or not.
