### ISSUE TITLE
Automate release flow through github

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#38]
## Description

Automate release flow through github as a follow up to #14 

## Acceptance criteria
- Whenever a new release of the SDK is made on GitHub releases it should also be published on npm.

## Tasks
- Mostly DevOps work, perhaps Ask Nils for assistance.

**Comment by kelsos** [comment]
https://circleci.com/blog/publishing-npm-packages-using-circleci-2-0/ guide on publishing from CircleCI

**Comment by andrevmatos** [comment]
I'm in contact with npmjs.org's support to move the package to the Org. Then we can proceed to add the contributor's accounts and possibly a bot for CI publishing.

**Comment by kelsos** [comment]
@andrevmatos great Thanks for taking care of it :)

**Comment by kelsos** [comment]
So I tested the dry run and it seems to work successfully build the package. 
The account is ready and the environment variable is set in place (special thanks too @nlsdfnbch for his support).

The only thing remaining is that the bot to the organization, and then try a release to make sure that everything works as expected.

**Comment by andrevmatos** [comment]
The bot account is added to the organization and is already available as maintainer of the package! Everything ready, let's try a new release at sprint's end.
