### ISSUE TITLE
I want to deposit tokens to the UDC

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#388]
## User Story
As Chris, I want to deposit tokens to the UDC so that I am able to pay for getting routes.

## Acceptance criteria
- I see the amount of SVT / RDN that I am going to mint & deposit
- I am going to deposit the amount of tokens I have minted
- I see a button to mint & deposit to the UDC
- Minting and depositing is done in a single step
- The SDK exposes a function deposit to the UDC
- The UDC deposit is stored in an observable

![grafik](https://user-images.githubusercontent.com/35398162/67953273-16377700-fbef-11e9-85a4-0f83b4ddbb62.png)

**Comment by christianbrb** [comment]
Refinement:
- We need a design for it
- Put it where the user needs to use a paid PFS
- Check, if the UDC deposit is made per PFS services or globally ? @palango

**Comment by taleldayekh** [comment]
The UDC deposit is made once and the amout deposited can be used with however many PFS (and monitoring) services you wish until the UDC is "drained". @christianbrb

**Comment by kelsos** [comment]
Taking care of the SDK part: https://github.com/raiden-network/light-client/issues/389#issuecomment-555083544

**Comment by kelsos** [comment]
All PRs related to this issue have been merged to master and this issue is considered complete so I am closing.
