### ISSUE TITLE
I want to mint RDN tokens on the testnet

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#389]
## User Story
As Chris, I want to mint RDN tokens on the testnet so that I can use a paid PFS service.

## Acceptance criteria
- I see my ETH balance
- I have got a field to enter the amount of SVT / RDN to mint
- 1 SVT / RDN as default value
- I access this screen from the Select PFS screen with a button called Deposit
- Minting functionality is exposed from the SDK
- SDK function should be able to mint any token

![grafik](https://user-images.githubusercontent.com/35398162/67951925-bcce4880-fbec-11e9-94c5-82c7990087bb.png)

**Comment by taleldayekh** [comment]
RDN test tokens are used on the testnet it is only one token but it changes whenever new contracts are deployed.

**Comment by nephix** [comment]
I'm looking into how to mint RDN and exposing a function from the SDK

**Comment by nephix** [comment]
SDK function `mint()` has been implemented

**Comment by nephix** [comment]
The rest should be implemented when #402 is ready

**Comment by kelsos** [comment]
The minting part of this issue was already done by Thomas. I am will create a PR to finalize the SDK part of the issue by exposing a deposit API. 

After getting the SDK part merged I will continue on the dApp integration part.

**Comment by kelsos** [comment]
All the PRs related to this issue have been merged to master so I am closing this issue as it is considered done.
