### ISSUE TITLE
Update Try out Raiden for Alderaan

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#393]
## Description

Currently, try out Raiden is not working as a Red Eyes Raiden node is mentioned and https://lightclient.raiden.network is on Alderaan.

The [guide ](https://github.com/raiden-network/light-client#try-out-the-raiden-demo-dapp) needs to get updated to work for any potential tester.

## Acceptance criteria
- Should work with the "real" Wizard
- Needs to be on Goerli

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
Done!
