### ISSUE TITLE
Prevent users from navigating away from important views

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#394]
## User Story
When opening a channel, paying someone or depositing into a channel we're blocking the UI and wait for meta mask transactions to be confirmed. In those processes we tell the user to not close the browser:
![Screenshot 2019-10-16 at 10 17 07](https://user-images.githubusercontent.com/3169205/66901120-5814ca80-effe-11e9-8c32-30cf5efeecdd.png)

If the user navigates away from these screens we can get illegal states, e.g. payments getting "stuck" etc.

This could be prevented by showing an additional dialog through the `beforeunload` [event](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload)

Browsers have a built in dialog for this, but we could also implement our own if necessary.

## Acceptance criteria
- [ ] `beforeunload` event listener is added when a critical screen begins
- [ ] `beforeunload` event listener is removed when a critical screen ends
- [ ] User has to confirm a dialog when moving away from critical screens

**Comment by andrevmatos** [comment]
No _illegal state_ can be triggered by apps using the SDK, everything there is stateful, atomic and incremental. The SDK should support even reloading mid-transfer or alike, and catch up when messages/events are retried/received/etc. Signature prompts are done directly with Metamask and doesn't depend on dApp intermediation, so they're going to pop up even if the dApp was reloaded and don't know about the previous transient state it was on.
But for UX, it is userful to have these guards in place, so the user knows they shouldn't walk away when something is happening, they may not come back on time and expect it to have worked.
[Pending] transfers [history] dropdown/counter can be related to it.

**Comment by nephix** [comment]
If I leave a page and 10mins later a random meta mask transaction pops up asking me to sign stuff I don't know then it's pretty weird. 

Also declining/ignoring transactions left me in the last couple of days in a state where I was not able to do new transactions anymore without waiting for them to expire which is pretty bad for users and developers alike IMO

**Comment by andrevmatos** [comment]
I know it's bad for UX and I agree. #237 is all about avoiding this. My point is that, hopefully, SDK doesn't get on actually **invalid** state, or else this can led to costs to the user or bigger problems. So far, by your description, the state didn't become invalid, but the bad UX is related to communication issues and the long delays associated with locks & timeouts we can't do much to avoid as per protocol. We must implement this issue, but also investigate on how to avoid these roadbumps even if the user ignores and e.g. reload or exits the app.

**Comment by taleldayekh** [comment]
Make sure user cannot leave browser/tab or leave route:
* When opening a channel
* When there is a pending transfer
* Deposit
* When pfs has been payed for

**Comment by christianbrb** [comment]
Looks like this has been implemented now. At least I often get the message to not close the tab / window.

**Comment by andrevmatos** [comment]
No, it wasn't. That message is just a warning, it won't try to prevent you from not doing this. This issue is about actually a browser feature to show an `alert` if the user **do try** to close window/tab anyway. This was not implemented yet, AFAIK

**Comment by christianbrb** [comment]
The alert is shown:

![grafik](https://user-images.githubusercontent.com/35398162/89205085-6fd23500-d5b7-11ea-9fa6-b677755e20dd.png)
