### ISSUE TITLE
Signing update message for PFS is not transparent for the user (EIP712)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#401]
## Summary
After a new channel has been opened an additional message pops up (Update message to the global PFS matrix room). As a user, I do not know, what I am signing.

## Steps to Reproduce
1. Connect to the light client on Goerli
2. Push "Connect new token"
3. Select TTT
4. Enter 0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6 to the hub field
5. Enter an amount and click "Select hub"
6. Sign the messages in the open channel stepper
7. Channel is opened and tokens are deposited

## Expected Result
- No further action

## Actual Result
- The following MetaMask message is popping up
  
![grafik](https://user-images.githubusercontent.com/35398162/67074391-4a3f8080-f189-11e9-8548-d4d26c651628.png)

- The console output is showing

![grafik](https://user-images.githubusercontent.com/35398162/67074491-8246c380-f189-11e9-85b1-f7864253f63c.png)

- After signing the message

![grafik](https://user-images.githubusercontent.com/35398162/67074580-b28e6200-f189-11e9-9a10-681d7c68a8a7.png)

- The sdk has been sending an update to the global message room for the PFS

**Comment by kelsos** [comment]
So I was looking into some stuff and I came across the following EIP https://github.com/ethereum/EIPs/blob/master/EIPS/eip-712.md

I need to read through and see what it's current status is and if we can actually use it somehow.
There was an example on how it would look here: 

https://medium.com/metamask/eip712-is-coming-what-to-expect-and-how-to-use-it-bb92fd1a7a26

**Comment by christianbrb** [comment]
@kelsos This is great :) (but just for MetaMask)

There is some additional information in Reddit: https://www.reddit.com/r/ethereum/comments/absnnx/eip712_and_state_channels/

Let's check if we still need it after #617

**Comment by kelsos** [comment]
@christianbrb the just for metamask is valid until the EIP gets merged. Then it becomes a standard for Ethereum as far as I am aware.

**Comment by christianbrb** [comment]
With #650 it shouldn't be an issue any more. Closing :)

**Comment by andrevmatos** [comment]
EIP712 itself would be a nice improvement to the standard (non-subkey) UX, but requires a lot of changes in contracts & core as well. We should keep an eye on it, but yes, the problem is minimized with the subkey feature.
