### ISSUE TITLE
Extend the payment stepper to select PFS and path

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#402]
## Description
After #386 and #392 we have got two modal dialogs before the payment stepper. 

Extend the payment stepper to include the PFS and route selection instead of the two modal dialogs.

## Acceptance criteria
- Show the most important piece of information in every step
- I see a list of the PFS
- I have a stepper on top

## Tasks
- [ ] 

CC @roy-castrillo @taleldayekh

**Comment by taleldayekh** [comment]
Brainstorming w/ Roy

![IMG_4459](https://user-images.githubusercontent.com/43838780/68203044-41421200-ffc5-11e9-9b22-9e71bfdd7e65.jpeg)

**Comment by nephix** [comment]
As the designs for this are done, I'm going ahead and implement the dapp part of it

**Comment by christianbrb** [comment]
Looks like it is done and can be closed
