### ISSUE TITLE
Switching from Goerli to Kovan crashes the browser & very high RAM usage

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#407]
While trying to reproduce #282 

## Steps to Reproduce
1. Connect to Goerli
2. Token screen
3. Switch in MetaMask to Kovan

## Expected Result
- Landing screen and I am able to click on connect

## Actual Result
- Landing screen and the screen is frozen
- Console shows
```
action raidenShutdown @ 08:35:39.930
client.js:4247 stopping MatrixClient
sync.js:89 SyncApi.stop
sync.js:89 Sync no longer running: exiting
```
- Reloading the page is taking a long time `waiting for transport04.raiden.network`
- Not able to close the browser
- Task Manager was showing Chrome using 6.128,2 MB of Memory
- Chrome crashed
- Killed Chrome in the task manager
- After restarting chrome it worked

**Comment by kelsos** [comment]
@christianbrb 

I don't think this is related to matrix. I have seen this issue in the past, even before the transport/matrix was implemented.

**Comment by christianbrb** [comment]
Maybe looking into memory leaks on RaidenShutdown?
https://developers.google.com/web/tools/chrome-devtools/memory-problems/

Related how we store data?
https://stackoverflow.com/questions/39943762/can-a-redux-store-lead-to-a-memory-leak

**Comment by nephix** [comment]
I can reproduce it with the following steps:

1. Go to https://lightclient.raiden.network/
2. Connect
3. Change to Rinkeby
4. Change to Kovan
5. Change to Goerli
6. Connect
7. Change to Ropsten

At some point you're on stuck on the connect screen. Running a profiler showed that this originates from `ether.js`'s [base-provider.js](https://github.com/ethers-io/ethers.js/blob/master/providers/base-provider.js#L454)
