### ISSUE TITLE
I don't want to be bothered by routes if I am just doing direct payments

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#408]
## User Story
As Chris I don't want to be bothered by routes if I am just doing direct payments so that the dApp is easier and cheaper to use.

## Acceptance criteria
- The Fee dialogue is skipped
- The Select PFS dialogue is skipped
- The Select Route dialogue is skipped
- The user is informed, that direct payment is possible (How is the user is informed)
- The overlay doesn't rely on the component
- Do the SDK communication on the host component
- Out of scope: Availability of the node (#218)

**Comment by andrevmatos** [comment]
Fixed by #600
