### ISSUE TITLE
I want to see the RDN balance when opening the app

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#415]
## User Story
As Chris I want to see the RDN balance when opening the app so that I know how much token I own.

**Comment by christianbrb** [comment]
I am doing issue housekeeping looking at least recently updated issues.

It is a nice to have. If the request is going to be raised by a user we'll reopen the issue.

**Comment by kelsos** [comment]
@christianbrb I believe we can close this issue as it is not needed anymore. We display the RDN/SVT on the PFS route selection flow when it is required, in any other case you don't really need to know the amount and it is redundant information. 

I still believe the consensus was we only show numbers/amounts when it is absolutely needed and we don't clutter the UI with unnecessary information. @taleldayekh @nephix @andrevmatos correct me if you have a different understanding of this.

**Comment by christianbrb** [comment]
@kelsos Thanks :) Closing :)
