### ISSUE TITLE
I want to be able to continue using the dApp while sending a long running transfer 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#426]
## User Story
As Chris,I want to be able to continue using the dApp while sending a long running transfer so that I don't have to wait hours until the dApp is reusable.

Known drawbacks: 
- Signing messages, which come up after the payment progress window is closed.
- It might lock more tokens, than needed

## Acceptance criteria
- Just the hide button + the text
- The user does not get notified if a transfer fails or succeeds

## Wireframe

 ![grafik](https://user-images.githubusercontent.com/35398162/69031244-ea333880-09d9-11ea-93a1-a55545a40d59.png)

**Comment by taleldayekh** [comment]
**Proposed Solution**
Have some sort of list displaying the users transfer history and queue the pending transfer on the very top. For the UX/UI this would need some more detailed discussions which might be related to channel management as well.

**First Step**
As a very first step I would propose some brainstorming about possible implementations.

**Comment by christianbrb** [comment]
@taleldayekh Thanks for the summary :)
This sound quite big as a solution and is covered within #168 
I would still push for a small solution (Being able to close the payment in-progress window). 
As a workaround I have to close the browser/tab manually and reconnect, which is ugly at the moment.
Might sound ugly from a dev perspective, but for me, as a user, it is very helpful and does what I would do anyway with closing the tab/browser.

**Comment by taleldayekh** [comment]
The simplest of solutions is to just add a close-button while letting the user know that it is ok to close the window and that the transfer will carry on in the backend while the user continues to use the dApp.

**Comment by taleldayekh** [comment]
Made some inital drawings that outlines possible solutions for this issue:

![wireframe_transaction_history_proposal](https://user-images.githubusercontent.com/43838780/68865900-d941a900-06f3-11ea-8d64-eb82a9fd36c4.jpg)

**Comment by andrevmatos** [comment]
Could this `Pending transfer...` become a counter to the top right corner, or something like this? This information is interesting to the user in the sense of how many transfers are pending and preventing the user from leaving cleanly.

**Comment by taleldayekh** [comment]
The idea is for the user to be able to access a list of all pending transfers as well as all completed transfers (complete transaction history). Wheter the solution is to have a counter or simply a text displayed is yet to be refined.

**Comment by christianbrb** [comment]
@taleldayekh Thanks the drawings

Let's split this from simple to more complicated / more effort

1. This story:
    ![grafik](https://user-images.githubusercontent.com/35398162/69031244-ea333880-09d9-11ea-93a1-a55545a40d59.png)

2. A new story ([Pending transfers](https://github.com/raiden-network/light-client/issues/426#issuecomment-554561805))

3. The transaction history / notification area -> see https://github.com/raiden-network/light-client/issues/168

**Comment by christianbrb** [comment]
@taleldayekh @christianbrb 

- We give the user the possibility to hide the "Sending tokens" screen (see drawing)
- We focus our energy on the implementation of pending transfers / history

**Comment by christianbrb** [comment]
New story for the counter: https://github.com/raiden-network/light-client/issues/585

**Comment by taleldayekh** [comment]
I'm gonna play with the idea of removing this stepper completely and integrating it in the current app window as an overlay of some sort. Now it appears as something separated from the rest of the app interface.

![stepper](https://user-images.githubusercontent.com/43838780/69945129-36599f00-14e9-11ea-8413-a1174f18e2a4.png)

**Comment by christianbrb** [comment]
Sounds good :) We need to keep in mind, that the first part of the workflow (Find PFS, Pay PFS, Pay mediation fees) get's already skipped in several ways, if
1. A PFS is pre-configured
2. A free PFS service is getting used
3. A free route is getting used

**Comment by taleldayekh** [comment]
A first proposal on how this might look like.

When a user finalizes a transfer (image 1) she is redirected to the Transfer view which has an overlay with a dialogue (image 2). The user can close the dialogue and continue using the dApp (image 3). This approach will work whether or not the flow for PFS/Route selection is involved.

This will get rid of stepper as mentioned in my earlier comment. 🥳

The mockups can be accessd here: https://xd.adobe.com/spec/a48683e7-315f-4613-524d-7ea1308c1831-d2b7/

![hide_long_running_transfers](https://user-images.githubusercontent.com/43838780/69967907-a08a3800-1519-11ea-8357-c72345a86b77.jpg)

Some design deceisions:
I decided against a button and choose a good old X instead.

**Comment by christianbrb** [comment]
@taleldayekh Thanks :) Looks nice 👍 

Remarks
1. The success message still needs to be shown
2. Could you try to shorten the text "Sign..." (maybe also using paragraphs) and add a hint, that MetaMask messages are going to continue to pop up until the transfer is complete?

**Comment by nephix** [comment]
@christianbrb 
> The success message still needs to be shown

Acceptance criteria:

> The user does not get notified if a transfer fails or succeeds

I feel like this ticket needs to get cleaned up somehow

**Comment by nephix** [comment]
@taleldayekh the designs look good! Just one thing: You seem to introduce a new type of modal there, currently we are already fighting with having two different types of modals:
![modals](https://user-images.githubusercontent.com/3169205/70030264-21dcdb80-15a9-11ea-8702-91b8ee4905a1.png)
![modal2](https://user-images.githubusercontent.com/3169205/70030268-243f3580-15a9-11ea-9b2d-f697407d7198.png)

Do you think it is worth having a 3rd one? My gut tells me that we should probably match the modals from your design with the **Mint and Deposit** modal

**Comment by christianbrb** [comment]
From @andrevmatos 
> How about 3-4s after last change in transfer in status, so if signatures keep being prompted (there’s activity) it’s delayed a little longer, and if it doesn’t change in 3-4s, may mean the transfer is getting stuck or slow, and then hide it

**Comment by christianbrb** [comment]
@nephix Very good hint :) 
@taleldayekh Could you consider this and update the design?

**Comment by taleldayekh** [comment]
I would say that the modal for depositing is just temporary since neither me or Roy made any design for that.

**Comment by taleldayekh** [comment]
And I think it will be difficult to fit the transfer information in the same modal as minting and depositing. Perhaps the minting and depositing should be the same size as the transfer one.

**Comment by kelsos** [comment]
@taleldayekh Is the design final, can I start working on that?

**Comment by kelsos** [comment]
So there are a few things that came up after I started working on this issue. 

The first thing is how do we handle the error case? 
Currently, the error screen is another component that looks exactly like the stepper screen. Do we still keep it like this or do we integrate it in the new modal dialog?

The second thing is that TransferSteps is another route than the Transfer. When we close the modal we are supposed to see the Transfer screen. To achieve that, an approach would be to modify the TransferSteps so that it becomes part of the Transfer route where it would display as an overlay.

This seems like the proper approach but the easiest would be to redirect either when you close or when the transfer is done/fails.

@christianbrb what is your input on that?

**Comment by taleldayekh** [comment]
@kelsos It would be nice to get rid of the stepper completely, so if possible I think it makes sense to add the error screen as part of the new modal.

Regarding the TransferStepper beign another route is as you mention the proper approach and would provide the nicest experience. However if it is to much we could implementet the other way in this iteration and then create a new issue to make it part of the transfer route.

Both ways will let the user continue using the dApp, which is what we wanted to achive. :)

**Comment by kelsos** [comment]
@taleldayekh I would also prefer to do it the proper way, but these things were not in the initial evaluation of the issue so it would be nice to have Christian's input before expanding the scope of the issue to include these.

**Comment by taleldayekh** [comment]
Agree, let's do so, sounds good!

**Comment by christianbrb** [comment]
@kelsos If it the change would expand the scope and effort, let's keep it the way we have originally discussed it.
