### ISSUE TITLE
 I want to know how much RDN / SVT I own

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#429]
## User Story
I want to know how much RDN / SVT I own so that I know if I can pay the PFS service

## Acceptance criteria
- I see my RDN / SVT balance in the UDC
- The SDK exposes it through observables

## Tasks
![grafik](https://user-images.githubusercontent.com/35398162/67951294-83e1a400-fbeb-11e9-81df-49f8a9334567.png)

**Comment by christianbrb** [comment]
After the refinement:
- This is what André has showed with a nice error message and a link to a guide how to acquire RDN on the testnet and how to deposit it to the UDC

CC @taleldayekh

**Comment by taleldayekh** [comment]
Current screen for reference.

![pfs](https://user-images.githubusercontent.com/43838780/68124310-61af9500-ff0f-11e9-9e1a-aa97a5e23037.png)

**Comment by taleldayekh** [comment]
Current screen for reference.

![route](https://user-images.githubusercontent.com/43838780/68124401-97547e00-ff0f-11e9-97da-e9dcdb9d8030.png)

**Comment by nephix** [comment]
I've removed dapp & design related acceptence criteria, because we have a separate ticket (#402) for this

**Comment by kelsos** [comment]
The SDK part is merged on master, I will do the UI part integration by continuing on top of Thomas' PR.

**Comment by kelsos** [comment]
The amount is now properly integrated with the SDK function and it is displayed to the user. I am closing this issue since all the related PRs have been merged.
