### ISSUE TITLE
Start raiden instance without private key

### ISSUE THREAD

**Issue by eorituz** [raiden-network/light-client#448]
## Description
If we want to allow external signing we would need to come up with an option to start a raiden sdk instance without providing a private key.
@kelsos feel free to add more info

## Acceptance criteria
- Start a raiden instance without revealing anything about the private key

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
This is very tricky. What is the SDK supposed to do without an account? Ok, even if you want to make signing external, we still need the address for almost everything else: detect blockchain events intended for us (who am I?), be present on transport and detect messages to us, etc.
- You may wish for a subset of the functionality which don't depend on an account, in which case I'd need to know what is this subset, and then strip it to a new sdk. It'd not be very useful though, even detecting channels depend on address.
- You could instead still provide the SDK with a `Signer` object, but which would do the signing completely asynchronously, possibly even in a completely remote system. The Signer interface is very simple: `address`, `signTransaction`, `signMessage`; it should be feasible to make a custom one to do what you need, but you would not get much context on what/why some signature is getting requested.
- Another approach could be asynchronous response actions: most actions in the redux engine are in the request/response/error pattern (FSA-like). Currently, most of the signatures happens directly inside the handling of a request action. But it would be possible that signature requests/responses/errors also become lower-level actions, and you could disable the epic which would be responsible for signing, then you intercept/read the request actions, also including context of who/why it was asked, forward it to external signer, get the signature and inject the signed response action directly into the engine. We would still need a dummy Signer anyway, as we need to least know who we are (`address`), but would sideload the signing workflow completely, but this wouldn't disrupt too much the current assumptions.

**Comment by christianbrb** [comment]
Potential solutions:
1. Using the currently implemented signing process (like MetaMask) - see solution 2
2. Going with bullet point 3 (asynchronous response actions) - see solution 3 -> more context is getting provided, which could be used later! to be validated

**Comment by taleldayekh** [comment]
Closing, already possible to do this by exposing an instance that is an interface for the private key.
