### ISSUE TITLE
Remove/hide scrollbar from list

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#482]
## Steps to Reproduce
1. Connect to the dApp

## Expected Result
- Remove or hide slider when the amout of tokens displayed do not require any scrolling.
- Play around with the CSS properties for various browsers and try to make it blend in with the rest of the dApp design.

## Actual Result
- I see the token list with a slider on the right (see screenshot)

    ![grafik](https://user-images.githubusercontent.com/35398162/68115643-230ee000-fef9-11e9-80c5-289e39848d72.png)

## Additional Infos (Optional) 
```

Google Chrome | 77.0.3865.120 (Offizieller Build) (64-Bit) (cohort: Stable)
Überarbeitung | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
Betriebssystem | Windows 10 OS Version 1903 (Build 18362.295)
JavaScript | V8 7.7.299.13


```

**Comment by kelsos** [comment]
@christianbrb The only problem I can see here is that we cannot enforce consistency across browsers. You can customize the scrollbar with CSS for chrome, so we can easily solve this problem for all the WebKit or Chrome-based browsers, but Firefox will still use the default scrollbar since it doesn't support this CSS selectors. On the other hand, the scrollbar on Firefox doesn't look that ugly so it should be fine.

**Comment by nephix** [comment]
Could maybe be fixed via `overflow-y: auto`. Last time I saw this and tried in GC/FF it worked, currently it's `overflow-y: scroll`

**Comment by kelsos** [comment]
@nephix Sure hiding it when you don't have a lot of tokens is a solution, but if you have a few items and the scroll has to show it will still be ugly.

**Comment by nephix** [comment]
I think it only looks confusing when there're not enough items, leading the container to not overflow. When there're a lot of items the scroll bar looks decent enough, better than no scroll bar at all :)

EDIT: Firefox seems to have added basic scroll bar styling support as well https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Scrollbars maybe that's already good enough for a solution

**Comment by taleldayekh** [comment]
**Proposed Solutions**
- Remove or hide slider when the amout of tokens displayed do not require any scrolling.
- Play around with the CSS properties for various browsers and try to make it blend in with the rest of the dApp design.

**Comment by christianbrb** [comment]
Keeping it on the backlog
- Token screen is going to be removed
- Identify all screens where a scroll bar is shown

**Comment by kelsos** [comment]
I tried to change the overflow to `auto` from `scroll` but somehow this triggers my OCD. It seems that this actually makes the scrollbar just invisible but still taking space. So you end up having an empty space at the end. 

This happens both in Firefox and Chrome:

![image](https://user-images.githubusercontent.com/2269732/69549102-eb93d080-0f98-11ea-975f-30deb8804d3f.png)

Based on that I would argue against actually removing them.
