### ISSUE TITLE
Token screen showing a small token amount looks broken

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#483]
## Steps to Reproduce
1. Connect to the dApp
2. Select a token
3. Connect to a hub with a very small token amount (`0.0000000000000001`)
4. Go to the "Transfer" screen

## Expected Result
- The following notation is shown: <0.000001
- Tooltip shows full amount
- Rounded at the last digit (≈0.000001)
- 6 digits
- If the amount is bigger (≈0.032335 - if it is not precise - digits afterward)
- For every number

## Actual Result
- Looks broken

    ![grafik](https://user-images.githubusercontent.com/35398162/68116295-bbf22b00-fefa-11e9-947d-961df20d7093.png)

## Additional Infos (Optional) 
```
Google Chrome | 77.0.3865.120 (Offizieller Build) (64-Bit) (cohort: Stable)
Überarbeitung | 416d6d8013e9adb6dd33b0c12e7614ff403d1a94-refs/branch-heads/3865@{#884}
Betriebssystem | Windows 10 OS Version 1903 (Build 18362.295)
JavaScript | V8 7.7.299.13
```

**Comment by kelsos** [comment]
We could use some kind of truncating/rounding hiding for example we could show this as `<0.000001` and show the real amount in the tooltip. Or we could use some kind of truncation like `0.000...0001`

**Comment by taleldayekh** [comment]
This would be as simple as displaying the number in accordance to `<0.0000001` or `≈0.0000001` that would prevent us from having too long numbers that breaks the layout.
