### ISSUE TITLE
Visualize Redux to gain a better understanding of the flow

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#485]
## Description
It has been shown that Redux is a nice tool to implement Raiden in JS/TS. To make it easier for non-developers to understand the flow, there are tools to visualize Redux

Examples:
- https://www.npmjs.com/package/redux-visualize
- https://github.com/reduxify/seedux
- https://github.com/romseguy/redux-store-visualizer

I am currently trying to test this:
- https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en
- https://livebook.manning.com/book/redux-in-action/chapter-3/30

## Acceptance criteria
-

**Comment by christianbrb** [comment]
@andrevmatos Is there any easy way to do this? If not, we can close the issue.

**Comment by christianbrb** [comment]
@andrevmatos Do you see a possibility for this?

**Comment by andrevmatos** [comment]
Yes, sure, as soon as this gets pulled in an iteration. It's hard to remember about it while there're To do issues already scheduled, but this is easily feasible, just pull it in

**Comment by christianbrb** [comment]
Cool, thanks for your feedback :) I am putting it on the product backlog for one of the next iterations.

**Comment by manuelwedler** [comment]
So after some research I decided to go with the [redux-devtools browser extension](https://github.com/zalmoxisus/redux-devtools-extension) and made the light client work with it:

![Screenshot from 2021-01-13 16-12-25](https://user-images.githubusercontent.com/34456797/104470976-9494f480-55ba-11eb-8323-e3a308da75a5.png)

It not only gives this nice visualization of the store, but also makes it possible to review the data in the store for every action and to modify past actions. A simple function call when creating the redux store enables the devtools.
It might even make sense to enable it for production with the logOnly restriction. See this [post](https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f) for some more thoughts on this.

If the light client is not running in the browser, there is [this tool](https://github.com/zalmoxisus/remote-redux-devtools) for connecting the dev tools, but this needs an additional dependency and configuration.
