### ISSUE TITLE
I want to be able to join a token network transferred as a parameter

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#5]
## User Story
As Chris, I want to be able to join a token network transferred as a parameter so that I can connect to an already existing token network.

**Comment by christianbrb** [comment]
This should be already working @kelsos Please reopen, if I am wrong

**Comment by kelsos** [comment]
It works on development but the parameters get stripped on GitHub pages. There is already an issue about that. I opened it last week when I was preparing for the meetup.
