### ISSUE TITLE
Remove token as start screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#519]
## Description
With the new transfer screen, the usage flow has changed and is not correctly working anymore (eg. back arrow on the connect to hub screen)

Therefore I would propose

- Check the whole flow (eg. back arrow on the connect to hub screen)

Open questions:
- What are we showing, if no token is connected yet?

This should be just a quick fix and focus should be on ease of implementation.

## Acceptance criteria
- The token screen is removed
- The transfer screen is the start screen, if connected to a token network already
- A decision has been made what to do with the back button on the token overlay
- A decision has been made what to do with the back button on the connect to hub screen
- The [new screen](https://github.com/raiden-network/light-client/issues/519#issuecomment-551862673) is shown if no token is connected
- The first token is the list is shown as the first token ;)
- The leave button is removed

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
@christianbrb The proposed solutions in the problem description sounds like the way to go. And the implementation can be broken down in the steps outlined above.

For the empty screen, if the user has no token connected, we could display the plus-button that prompts the user to "Connect new token". 

![connect_new_token](https://user-images.githubusercontent.com/43838780/68486489-765a9880-0241-11ea-95ad-9daf3138ef7b.jpg)

**Comment by christianbrb** [comment]
@taleldayekh Looks good :)
We need to decide which token to preselect within the token transfer screen

**Comment by taleldayekh** [comment]
The preselected token could be the last one used. If I made a transfer with TalelToken before closing the dApp then that would be the one appearing next time I open the dApp, if I then switch and make a transfer with FranziToken then that is the one preselected next time I open the dApp.

I belive this is the most logical way of deciding what token should be displayed on startup. Thoughts?

**Comment by kelsos** [comment]
From a user perspective showing the last used token makes absolute sense, but we have to persist it somewhere (e.g localStorage)

**Comment by christianbrb** [comment]
@taleldayekh @kelsos Thanks for your input :)
Maybe we better iterate on that and define the preselected token as a separate issue. Scope for this issue should be as small as possible as it is supposed to be a fix for the current situation.

**Comment by kelsos** [comment]
@christianbrb the simplest thing is just to change the landing component, which should be fairly easy. I like the idea of scoping the preselected token out as part of a new issue since it would require more effort and though.

**Comment by taleldayekh** [comment]
The design for the updated start screen is finished. Pretty straight forward design. :)

Click [here](https://xd.adobe.com/spec/af1220bd-5e6d-4b25-5320-2eab33331cff-d923/) to access the design file. I'm currently making the mockups in Adobe XD but it shouldn't be any differance for you guys.

I'm happy to try and implement this myself if you have other tasks and if I have time over.

![connect_new_token_start_screen](https://user-images.githubusercontent.com/43838780/69140926-d5cb6a80-0ac3-11ea-898e-116dd73afaac.png)
