### ISSUE TITLE
Token transfer breakdown on confirmation screen (steps)

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#543]
## User Story

As a user I want to have a breakdown of what tokens I have already transferred and will transfer in an easy to understand way, before actually doing the transfer. 

Current confirmation screen for reference:
![confirmation-screen](https://user-images.githubusercontent.com/3169205/68852797-ee5d0e80-06d8-11ea-9eef-6a6b4e37fd43.png)

## Acceptance criteria
- Shows which route will be used
- Shows what kind of transfer you are doing (direct, mediated)
- Shows the number of hops
- Show the dialogue as well for direct transfers
- Shows the route
- Shows the fees
- Shows how much has been paid for the PFS
- The confirmation screen is always shown (currently it is skipped sometimes)

**Comment by christianbrb** [comment]
@taleldayekh to create a low fidelity wireframe

**Comment by taleldayekh** [comment]
How about something like this as a start?
![confirmation-screen](https://user-images.githubusercontent.com/43838780/72529162-fbc77e00-386c-11ea-92ef-c5e517f98e1b.png)

**Comment by christianbrb** [comment]
Route Request

PFS http://.....
Service Fee 0.001 SVT (checkmark)

Mediated Transfer
Direct Transfer (no route request)

Target xxxxx

Transfer Amount  10.000 TTT
Mediation Fee     0.001 TTT
---------------------------
Total Amount     10.001 TTT

**Comment by nephix** [comment]
Design and specs seem to be done, so I will start to work on the implementation
