### ISSUE TITLE
I want to get support to acquire the utility token 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#587]
## User Story
As Chris I want to get support to acquire the utility token so that I can use the Light Client on any net.

This is mainly about the DEX integration.

## Acceptance criteria
- The flow for testnet has been redesigned (see https://github.com/raiden-network/light-client/issues/587#issuecomment-626709953)
- The new functionality for mainnet has been implemented

## Tasks
- [ ] Design (pre-iteration)

## Remarks
- Check the new Raiden Python wizard and have a meeting first to understand their approach and learnings
- Documentation: 
    - https://uniswap.org/docs/v2/SDK/getting-started/

**Comment by christianbrb** [comment]
### Discussion inthe Refinement
- A Wizard like approach
- Could be a document at the start
- Onboarding at the start would be nice
- Transformation of the Mint Dialogue
- Acquiring the tokens (Swapping -> Kyber and Uniswap)
- Maybe just redirecting to Kyber and Uniswap
- Kyber is really easy to use

**Comment by christianbrb** [comment]
First draft (not complete) from @taleldayekh 

Consider mainnet and testnet

eg. on testnet you can mint token and on mainnet you'll have to buy them

![grafik](https://user-images.githubusercontent.com/35398162/81560511-d3224180-9391-11ea-9051-ce399c94a087.png)

**Comment by taleldayekh** [comment]
The complete flow.

The idea is that in order to connect to a hub three requirements need to be fulfilled.
1. The hub needs to be online
2. There needs to be a token balance
3. There needs to be an SVT balance

The three requirements are grayed out and become highlighted and get a green checkmark once fulfilled.
1. The user enters the address of a hub that is online ✅
2. The user mints and deposit tokens and gets a token balance ✅
3. The user mints and deposit SVT tokens and gets a token balance ✅
4. The `Select Hub` button gets enabled.

![wireframe_select_hub](https://user-images.githubusercontent.com/43838780/81567915-4a110780-939d-11ea-8500-a52e56ce86d7.jpg)

@andrevmatos @kelsos @nephix

**Comment by nephix** [comment]
The mint & deposit for test nets is done in #1372 and #1371

**Comment by taleldayekh** [comment]
Yes, I believe this is meant as future improvements. That's why it has a separate issue :)

**Comment by christianbrb** [comment]
@taleldayekh Didn't we move this to a different issue? https://github.com/raiden-network/light-client/issues/587#issuecomment-626709953

**Comment by christianbrb** [comment]
Preview of the mainnet wizard (we should do something similiar, but without the selection of the RDN amount)

![grafik](https://user-images.githubusercontent.com/35398162/81713853-b1e75100-9476-11ea-93ec-39959a8ed325.png)

**Comment by christianbrb** [comment]
We decided to go with the simple dApp integration. 

@taleldayekh to check https://github.com/raiden-network/light-client/issues/587#issuecomment-626709953 (still up to date?)

**Comment by christianbrb** [comment]
@taleldayekh I have marked your https://github.com/raiden-network/light-client/issues/587#issuecomment-626665015 as outdated. I would like to have a simpler approach.

**Comment by kelsos** [comment]
Just to note as we already discussed. It seems that Kyber doesn't have any liquidity, so I am not sure if it makes sense to include.

**Comment by christianbrb** [comment]
Adjusted the description to just go with Uniswap first.

**Comment by christianbrb** [comment]
Discussion with @taleldayekh 

1. On the Select Hub screen

![grafik](https://user-images.githubusercontent.com/35398162/84656533-22204100-af13-11ea-80c9-0eae97564bd4.png)

The mint and deposit button opens a modal with an explanation and link to the uniswap trading interface. 
- Recommend to buy 10 RDN

2. On the Transfer Screen (Select PFS)

![grafik](https://user-images.githubusercontent.com/35398162/84657296-5e07d600-af14-11ea-8538-018290301fb8.png)

The mint and deposit button opens a modal with an explanation and link to the uniswap trading interface.

If we cannot act on behalf of the Raiden Account we would need the following interface:
![grafik](https://user-images.githubusercontent.com/35398162/84658979-0028bd80-af17-11ea-8865-3a18ada7d78c.png)

3. On the UDC Screen

![grafik](https://user-images.githubusercontent.com/35398162/84657868-3cf3b500-af15-11ea-8c1b-02a1caf05bd3.png)

The mint and deposit button opens a modal with an explanation and link to the uniswap trading interface.

Remark
- Align design / aligment of the balance and minting button

Questions:
- Is the RDN amount directly updating after the blockchain transaction has been completed on uniswap?
- Is the RDN/SVT amount which is shown from the main or Raiden account?
- Would I be able to deposit RDN from the main account to the Raiden account?

**Comment by christianbrb** [comment]
@taleldayekh If a users buys RDN at uniswap he still needs to deposit the RDN.
I have adjusted the description:

> The mint and deposit button opens a modal:
> - Recommend to buy 10 RDN
> - Link to https://uniswap.exchange/swap?use=v1
> - Short explanation
> - Entry field for the amount of RDN to be deposited (defaults to 10)
> - Having a deposit button on the screen which is active if the Main Account has got enough RDN

**Comment by kelsos** [comment]
@christianbrb keep in mind that for the link we can actually prefill the token and and swap amounts

See [here](https://uniswap.exchange/swap?outputCurrency=0x255aa6df07540cb5d3d297f0d0d4d84cb52bc8e6&exactAmount=10&exactField=output).

**Comment by christianbrb** [comment]
@kelsos That‘s great 😊👍🏻

@taleldayekh I would also redesign the UDC screen so that it shows the Balance and uses the icon to open the mint and deposit or buy and deposit dialog.

**Comment by taleldayekh** [comment]
I made this proposal:
![wireframe_udc_02](https://user-images.githubusercontent.com/43838780/85117469-34ee8a80-b21f-11ea-921c-62114e416e2b.jpg)

I think it makes sense displaying only the amount once and adding both the deposit and withdrawal button next to the amount. A user would see the amount available and can choose to either deposit more or withdraw. In case the balance is too low we display the `disabled receiving` warning. @christianbrb @kelsos @andrevmatos @weilbith

**Comment by weilbith** [comment]
Where would I enter the amount to deposit? Does not appear on this small modal on the top you have drawn. Would the `Mint and depo...` button open another modal?

I think the warning can even take a higher place. Maybe not a whole paragraph but another obvious indicator at the top of the screen maybe? Do we already have a general warning for the user when he enters the app that his deposit is too low?

**Comment by christianbrb** [comment]
Split mint and deposit into a flow
1. Mint / Buy (showing the RDN/SVT amount within the Main Account)
2. Deposit (showing and changing the amount to be deposited)

**Comment by christianbrb** [comment]
@taleldayekh I have given it another thought and I would propose to make it like this:

If you click on the button next to the UDC balance you first get a deposit modal and afterward a mint or a buy modal.

![grafik](https://user-images.githubusercontent.com/35398162/85127487-cf56ca00-b22f-11ea-88fd-d05d9f453a26.png)

This would also give us the opportunity to use the Mint and Buy screen throughout the dApp (eg. within the Connect to Hub flow).

**Comment by kelsos** [comment]
I don't think we should open a modal on top of a modal. Also, I would argue that minting as a separate action doesn't make sense. The mint and deposit dialog is a more seamless experience. 

For buying, I would prefer to have it integrated into the deposit dialog instead.

The flow could be like that.

I am on the deposit and I enter an amount of 15 RDN but I only have 5 RDN.

The dialog is disabled, warning me that I don't have enough capacity, and provides a suggestion to open `uniswap` to get the other 10 RDN. 

Meanwhile, in every block, I keep checking the available balance and update the deposit dialog status so if the user does the swap the dialog will get updated to the new state enabling them to proceed.

On testnets we don't warn but instead mint the remaining amount automatically.

**Comment by taleldayekh** [comment]
I agree with @kelsos . We risk making something that is already complex more complex without gaining much in the process.

**Comment by taleldayekh** [comment]
This is how I would imagine the flow for mainnet:

![udc_deposit_dialog](https://user-images.githubusercontent.com/43838780/85130543-683c1400-b235-11ea-96a1-54cba495f8ce.jpg)

**Comment by christianbrb** [comment]
Refinement:
- Using a normal token input field (component)
- 10 SVT/RDN should be preselected
- We show a warning if the amount to deposit is bigger than available token amount

Split into issues:
1. Update UDC screen: https://github.com/raiden-network/light-client/issues/587#issuecomment-646534180
2. Deposit modal for testnet
3. Deposit modal for mainnet

**Comment by christianbrb** [comment]
@taleldayekh Thanks for creating the issues :) Looks good :) Let's talk about the details in the planning.

There is one issue missing:
> 4. Showing the SVT/RDN balance
... on the deposit model, I would add

**Comment by taleldayekh** [comment]
> There is one issue missing:

We briefly talked about this last week and @kelsos had a good point in that the user already sees the amount on the main UDC screen.

**Comment by christianbrb** [comment]
Ok closing :)
