### ISSUE TITLE
Understanding code measurement and define refactoring targets

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#588]
## Description
Currently, we are using [CodeClimate ](https://codeclimate.com/github/raiden-network/light-client)in our CI to analyze the code. We need to come to a common understanding of the figures and results.

We need to decide which [CodeClimate Issues](https://codeclimate.com/github/raiden-network/light-client/issues) to ignore or to resolve.

An additional static code analyzer is [CodeScene](https://codescene.io/projects/6071/jobs/17220/results)

## Acceptance criteria
- New issues on what to tackle
- Decide where to split functions
- We see how the tools could help us
- The complaints of the tools are checked
- We can explain the outcome of the tools
- Decide about parameters
- Decide which rules make sense and which once to ignore

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Notes from our first discussions within the Refinement:
- Reactive programming has got a learning curve
    - Functional programming!
    - Observables -> Background, Operators and how they interact
- Epics are complex but relatively easy to use compared to other approaches
- Maybe breaking down the functions within the epics

**Comment by christianbrb** [comment]
See Code Climates explanation of
- [Cognitive Complexity](https://docs.codeclimate.com/docs/cognitive-complexity)
- [Cyclomatic Complexity](https://docs.codeclimate.com/docs/cyclomatic-complexity)
- [Churn](https://docs.codeclimate.com/docs/churn) to define the most effective refactoring targets
- [Duplication](https://docs.codeclimate.com/docs/duplication-concept) - yeah, it's very simple ;)

All thresholds can be [configured](https://docs.codeclimate.com/docs/maintainability#section-checks).

**Comment by kelsos** [comment]
@christianbrb we care more about identical code than similar code when it comes to duplication so we should configure accordingly

**Comment by christianbrb** [comment]
We discussed https://github.com/raiden-network/light-client/issues/588#issuecomment-559700472, took decision on how to move forward and the issues #657 #658 #659 #660 have been created as a follow up. Therefore closing.

**Comment by christianbrb** [comment]
I have found an open question
- How does it applies to functional programming (reactive operators)? (mergemap, merge, filter, etc.)

Some answers:
- https://stackoverflow.com/questions/2187536/do-functional-languages-cope-well-with-complexity
- https://codeclimate.com/github/redux-observable/redux-observable/issues ;)
