### ISSUE TITLE
Make actions serializable

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#591]
## Description

We need serializable actions. Usually, it's not expected actions to need to be serialized, nor go in state, but it's useful for one specific usecase: _pending_ actions that have a **confirmation** counterpart, and we need to be able to recover in case client is closed between both.

The action creator implementation should use `io-ts`, our codec/validation library of choice, and be self-contained (no multiple places of declarations to add a new action). It must also be type-safe and implement the [FSA](https://github.com/redux-utilities/flux-standard-action) pattern (actions being plain objects containg only `type`, `payload`, `meta` & `error` properties).

From this, it'd be interesting if the Acion Creator itself was the codec instance, so members can be accessed directly, but it may not be practical to do it over the callable function needed for the action creator. If this is the case, the codec can be defined as a `codec` property.

It may replace or extend our [typesafe-actions](https://github.com/piotrwitek/typesafe-actions) dependency, may have an interface similar to it (to minimize changes), but ideally replace standalone utilities (ActionType, `getType`, `isActionOf`, etc) with methods/member functions in the action creator object itself.

A generic `Error` serialization codec is needed for the error actions, like [serialize-error](https://github.com/sindresorhus/serialize-error) but typesafe and compatible with `io-ts`. No need for strong guarantees on the types, as they're mostly informative in the SDK.

## Acceptance criteria
- Actions can be serialized
- Actions can be deserialized/validated
- Errors payloads can also be [de]serialized
- Actions are plain objects in the FSA pattern
- Action Creators can be created passing io-ts codecs for `payload` & `meta` members
- The action codec can be accessed, but relevant properties/methods are exposed through utility members.
- An efficient type-guard is exposed as a member arrow function (no `this` unbind) of the AC which checks only `type` literal instead of `codec.is` which validates recursively
- Codec, payload, meta and literal `type` types are exposed as well; a standalone `ActionType` generic can also be exposed to calculate this in a standalone way
- All our current action creators are converted to use this implementation/factory

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@andrevmatos Thanks for pointing this out :)
Some additional information: https://github.com/reduxjs/redux/blob/master/docs/faq/Actions.md#why-should-type-be-a-string-or-at-least-serializable-why-should-my-action-types-be-constants

**Comment by nephix** [comment]
If we're working on the SDK actions it might make sense to investigate whether `typesafe-actions@5.x` would help with our requirements. We recently had a dependency PR https://github.com/raiden-network/light-client/pull/474#issuecomment-549709382 that tried to bump it to 5.x which deprecates the way we currently create our actions. Maybe 5.x make serializing these easier or we can update nontheless if we are going to touch most of our actions anyway. 

Here's the official migration and deprecation guide: https://github.com/piotrwitek/typesafe-actions#v4xx-to-v5xx
