### ISSUE TITLE
SDK PFS fetching: Not handling wrongly returned URLs from ServiceRegistry correctly

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#593]
## Steps to Reproduce
1. Go to https://lightclient.raiden.network
2. Connect
3. Click on Token
4. Click on Transfer
5. Enter an address
6. Enter an amount
7. Click Continue
8. Wait for PFS list fetching to complete

## Expected Result
- I can select a PFS server
- No requests to empty URLs are sent
- At least one working PFS is selectable
- Sanitizing the URLs
    - Nice RegEx for URLs
    - Tests

## Actual Result
- We seem to still query an empty URL returned from service registry:
> fetch.ts?374f:76 GET https://%22%22/api/v1/info net::ERR_NAME_NOT_RESOLVED

It looks like one URL is `url = """"` which seems to pass `if(!url)` as well as `if (url.includes('://') && !url.startsWith('https://'))` in 

> light-client/raiden-ts/src/path/utils.ts

- ~~The working PFS https://pfs-goerli-with-fee.services-test.raiden.network/api/v1/info triggers a warning:~~

> ~~Error trying to fetch PFS info for "0x94DEe8e391410A9ebbA791B187df2d993212c849" - ignoring: Error: Invalid value "0x62436bbadB629498107278486C2A367FfdFEb2f3" supplied to : { message: string, network_info: { chain_id: 5, registry_address: "0x754b1Fa6bcb43F09557Eb5A212513F40A263DAF8" }, operator: string, payment_address: Address, price_info: UInt, version: string }/network_info: { chain_id: 5, registry_address: "0x754b1Fa6bcb43F09557Eb5A212513F40A263DAF8" }/registry_address: "0x754b1Fa6bcb43F09557Eb5A212513F40A263DAF8"
    at Object.report (ThrowReporter.js?896d:12)
    at decode (types.ts?14d6:28)
    at _callee2$ (utils.ts?095b:96)
    at tryCatch (runtime.js?2408:45)
    at Generator.invoke [as _invoke] (runtime.js?2408:271)
    at Generator.prototype.<computed> [as next] (runtime.js?2408:97)
    at fulfilled (utils.js:34)~~

~~And the dApp shows~~

> ~~Could not validate any PFS info. Possibly out-of-sync with PFSs version.~~

~~because there is no working PFS~~

**Comment by andrevmatos** [comment]
@nephix That's very weird. Can you check cache isn't playing a role into your issue?
Your instance seems to be requiring TokenNetworkRegistry address of `0x754b1Fa6bcb43F09557Eb5A212513F40A263DAF8`, but since #550 we are on `0x62436bbadB629498107278486C2A367FfdFEb2f3`. Can you hard-refresh (`Ctrl+Shift+R` or so) and test again?

**Comment by nephix** [comment]
Same issues occur on my end after hard reloading:
1. Fetching from https://%22%22/api/v1/info 
2. Warning from the working PFS with the error message like above

**Comment by andrevmatos** [comment]
The `%22%22` fetching is harmless, although we may sanitize it better, but why the h* would someone set `""` as PFS URL on-chain?
The second one continues to be some caching issue, just checked and deployed instance is on v0.33.3 contracts, which is the `0x62..` one, although your instance is still trying to fetch old `0x75...`, and therefore the error/warning is correct.

**Comment by nephix** [comment]
The 2nd issue is gone after `rm -rf node_modules && npm i`, I have updated the description
