### ISSUE TITLE
Can't use a PFS set in config

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#596]
## Steps to Reproduce
1. Get the `raiden` SDK instance on browser's dev tool
2. Set a config with `raiden.updateConfig({ pfs: 'https://pfs-goerli-with-fee.services-test.raiden.network' })`
3. Try to perform a transfer

## Expected Result
- Skip PFS selection dialog and call `findRoutes` without specifying a `pfs` if `raiden.config.pfs !== undefined`
- Can fetch routes and transfer using this set PFS

## Actual Result
![image](https://user-images.githubusercontent.com/587021/69643659-69f87d00-1042-11ea-9cd4-12643d5df12a.png)

**Comment by nephix** [comment]
How would the RDN/SVT payment be shown to the user in that case?

**Comment by kelsos** [comment]
@nephix That is a good question. So instead of skipping automatically we can show the preselected pfs name instead the list

**Comment by nephix** [comment]
I think that's good. If we skip that step entirely we prevent the user from minting, depositing and paying for the PFS request

**Comment by andrevmatos** [comment]
Oh, yes, you are right, I had forgotten about paying a config set PFS.
But in either case, this needs to consider if a direct route is possible, so we can skip paying PFS and even route selection. I'll provide an interface for this.

**Comment by nephix** [comment]
Removed bug label because this would be a new feature
