### ISSUE TITLE
Caching issues, if a new version of the dApp gets deployed

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#598]
## Steps to Reproduce
1. Connect to https://lightclient.raiden.network/
2. Use the dApp
3. Introduce some visible changes in the dApp code
4. Deploy a new version of the dApp to github pages
5. Connect to https://lightclient.raiden.network/ with the same browser as used in 1.

## Expected Result
- The changes introduced in 3. are visible

## Actual Result
- The changes introduced in 3. are not visible
- They are visible after hitting STRG+F5 (clearing the cache for this page) and a reconnecting

**Comment by nephix** [comment]
This is more of a feature than a bug, because the dApp's service worker caches requests on the client so it doesn't need to reload javascript/css all the time.

We can unregister the service worker to prevent this, we have already done this for the "raiden package" where the light client got installed by the wizard

**Comment by nephix** [comment]
Oh ok I didn't know that

**Comment by christianbrb** [comment]
It even seems persistent. After STRG+F5 while running into this issue, the scrollbar went blue. Today it was grey again and I had to press STRG+F5 again (see https://github.com/raiden-network/light-client/issues/603)

**Comment by kelsos** [comment]
I have seen some web apps somehow check for a new version and force the user to reload/refresh to update but I have never worked on something like that. I am mentioning it because from what I have seen it seems possible.

**Comment by nephix** [comment]
@kelsos I have done this before via [onupdatefound](https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerRegistration/onupdatefound) it's pretty straight forward but would require us to bring back the Service Worker

**Comment by kelsos** [comment]
@nephix I have no issue on bringing back the Service Worker if we actually use it :) if it is straight forward let's go for it.

**Comment by nephix** [comment]
My proposal would be to show an update snackbar that allows the user to refresh the app when a new update is available:
![update](https://user-images.githubusercontent.com/3169205/69790060-06955900-11c2-11ea-93ae-ebbdc9cfed92.png)

**Comment by kelsos** [comment]
@nephix sure let's go with it :)
