### ISSUE TITLE
Logo and Raiden dApp on connect screen on small size not centered

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#602]
## Steps to Reproduce
1. Go to the connect screen

## Expected Result
- Raiden Logo and  Text "Raiden dApp" is centered

## Actual Result
- More on the right, than center
- On mobile I have seen this before, but on Chrome for the first time

![grafik](https://user-images.githubusercontent.com/35398162/69702233-0a0be000-10ef-11ea-9cb6-608db4225fa3.png)

**Comment by kelsos** [comment]
@christianbrb It only happens on smaller window sizes/screens due to how the proportional adjustment works. It should not be overly hard to fix.

**Comment by christianbrb** [comment]
It's on very small sizes, but it is also a problem on 1920 x 1080

If I make the window smaller it is centered, but if I make it very small it is not centered again

**Comment by kelsos** [comment]
closed by #656
