### ISSUE TITLE
Wrong token symbol is displayed on the routes fees

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#610]
## Steps to Reproduce
1. Select a pathfinding service
2. Wait for the route selection to appear

## Expected Result
- The transferred token should be listed as the fee token

## Actual Result
-  The price is listed in SVT instead of the transferred token

![image](https://user-images.githubusercontent.com/2269732/69728944-bd8fc700-1125-11ea-9b7f-016d7165c351.png)

**Comment by nephix** [comment]
> TransferSteps.vue:122
```
:token="udcToken"
```
to
```
:token="token"
```
