### ISSUE TITLE
I want to be able to open a channel to a hub with a transferred parameter

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#62]
## User Story
As Chris, I want to be able to open a channel to a hub with a transferred parameter so that I can make a deposit.

## Acceptance criteria
- Parameters include token address, hub address and deposit amount
- If parameters are transferred the open channel screen is openend and the parameters are filled in the form
- Form is not submitted (user can change the value)

## Tasks
- [ ] Find LN link -> @christianbrb

**Comment by andrevmatos** [comment]
Done in #339
