### ISSUE TITLE
I want to have a link to the basic instructions how to try out the dApp 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#638]
## User Story
As Chris I want to have a [link to the basic instructions how to try out the dApp](https://github.com/raiden-network/light-client#try-out-the-raiden-demo-dapp) so that I don't get frustrated.

**Comment by christianbrb** [comment]
Options:
a) Info button
b) On the bottom of the page
c) Connect screen

**Comment by taleldayekh** [comment]
This is a more all encompassing information and I would argue that it belongs as a link in a paragraph on the connect screen. It will be used mostly by someone trying the dApp for the first couple of times.

In the dApp itself I belive that the context aware info buttons are the way to got to provide guidance for the user.
