### ISSUE TITLE
Explain waiting and signing in UDC minting and deposit dialogue to the user

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#640]
## Description
Tell the user in the UDC minting and deposit dialogue, that he has to
- Describe the action, which is happening while the spinner is turning
- This text should be put on every step to the button
    1. Mint SVT tokens
    2. Allow UDC to access SVT tokens
    3. Deposit SVT tokens to the UDC

![grafik](https://user-images.githubusercontent.com/35398162/69807093-b976ae80-11e4-11ea-8077-d0a19e7f583d.png)

## Acceptance criteria
- Have a message at the bottom explaining what is happening when the spinner is shown.

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb It was certainly confusing despite knowing what happens, to have to information while everything is in progress. We need a better way to communicate it across.
