### ISSUE TITLE
I want to get a route automatically selected and pay mediation fees

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#641]
## User Story
As Chris I want to get a route automatically selected and pay mediation fees so that I do not have to think about it on my own.

**Comment by andrevmatos** [comment]
Same as https://github.com/raiden-network/light-client/issues/639#issuecomment-559593365

**Comment by christianbrb** [comment]
We have estimated 40 for #639 and #641 in combination. I am putting 20 on every individual story.

**Comment by christianbrb** [comment]
Issue housekeeping looking at least recently updated issues.

Nice to have. If the request is going to be raised by a user we'll reopen the issues.
