### ISSUE TITLE
Reduce complexity on raiden-ts/src/channels/epics.ts

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#660]
## Description

According to the code climate reports [raiden-ts/src/channels/epics.ts](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/channels/epics.ts) is one of the often modified classes that has a high maintenance cost due to complexity. 

The purpose of this issue is to identify the possible improvements that can be done on raiden.ts in order to reduce the complexity and improve the maintainability of the class.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
This has got an A rating now: https://codeclimate.com/github/raiden-network/light-client/raiden-ts/src/channels/epics.ts -> Closing
