### ISSUE TITLE
Transfer stuck on "spinner" when a invalid PFS is in the service registry contract

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#663]
## Steps to Reproduce
1. Access the dApp from lightclient.raiden.network (version that is live when this issue was created)
2. Do the necessary steps to send a transfer

## Expected Result
The spinner to be displayed for a while and then for the user to be redirected to the transfer screen

## Actual Result
Spinner goes on indefinitly and console show `GET https://raidentransport.demo-env.raiden.network/api/v1/info net::ERR_FAILED`. Accessing the URL in the browser returns `No Such Resource`

**My understanding of the problem:**
The `demo-env` pfs is for testing and cannot be used. When the Light Client gets the pfs urls from the smart contracts to see if they are active it throws the error mentione above. The transaction still goes through but the user is stuck looking at the spinner unless she refresh the browser.

![pfs-error](https://user-images.githubusercontent.com/43838780/70159897-eed63d00-16b9-11ea-8e11-aba2950bc1e7.png)

**Comment by andrevmatos** [comment]
This has nothing to do with the PFS. The invalid PFS is expected, and handled properly. Even if it hangs request, it'll timeout in default=30s, or if response is invalid, error is handled and best PFS is chosen.
As you can see the signing of the LockedTransfer below, it happens only if PFS phase passed.
My take on it is that Metamask is hidding the signature prompt (which can't be controlled by us). Please, check if there's a small numeric badge on the Metamask icon, and click on it to see if the LockedTransfer signature is pending. If so, it's just a Metamask UX flaw (of hidding the prompt sometimes under the badge), but the workflow went on as expected.

**Comment by christianbrb** [comment]
I have got similiar errors in the console, but the transfer worked

![grafik](https://user-images.githubusercontent.com/35398162/70162598-2e9f2380-16be-11ea-9c3a-671c727a46ba.png)

**Comment by taleldayekh** [comment]
I went through the flow again. MetaMask prompts me to sing once. 20 minutes later I still see the spinner and there has been no additional prompts from MetaMask and I have no badge on the icon.

For Christian it works. I'm using Chrome Canary as browser.

This is the output from my second run:
![pfs-error2](https://user-images.githubusercontent.com/43838780/70162867-be44d200-16be-11ea-85ae-cce0b2b67e4b.png)

**Comment by andrevmatos** [comment]
Without the actions logs, it's hard to say what's happening.
Please, on Chrome Dev Tools at `Connect` screen, go to `Application > Local Storage > https://ligh...`, click on `raiden_goerli_0x6243...` (your account state), double-click on value (right side) to edit the json, then add/set the option at `config.logger` to value `"debug"`. Then, click `Connect` and you should see the action logs. If you got to sign the `LockedTransfer` but there's no other prompts, it most likely means the partner or the target isn't receiving or responding the message, which may trigger either matrix|invite or `Invalid message/state` logs on the Raiden-py side.

**Comment by andrevmatos** [comment]
Notice that even in the unhappy case, this is not going to be stuck forever, but fail after transfer lock expire, which may take like `100` blocks currently

**Comment by christianbrb** [comment]
I was sending transfers to the same node and it worked

**Comment by andrevmatos** [comment]
Different senders can have different states, on the same node. They may have gotten out of sync for some reason, maybe some previously cached instance...
Checking the actions logs & the raiden-py logs for transfer attempts would give better view of the reasons, but doesn't seem to be widespread.

**Comment by kelsos** [comment]
Most probably it was a cached instance of the dApp, we had a few cases of the same exact situation in the Berlin office. 

It should not be a problem from now on probably, due to the update mechanism being in place.

**Comment by christianbrb** [comment]
> It should not be a problem from now on probably, due to the update mechanism being in place.

@kelsos Thanks :)

Closing it :)
