### ISSUE TITLE
Investigate possible integration with WalletConnect

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#68]
## Description
At the Ethereum Wallet UX Demo Night on Friday I learned more about [WalletConnect](https://walletconnect.org/). I would like to investigate if it is possible to also use WalletConnect along with Metamask for the wallet app.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by palango** [comment]
@weilbith Can we close this issue?

**Comment by weilbith** [comment]
Yes. Good catch. 😬
