### ISSUE TITLE
Rework headers in dApp

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#686]
## Description
The headers within the dApp need to be checked and rewritten

## Acceptance criteria
- The right words are capitalized
- The header describes the context of the screen in an understandable way

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
Thought I'd start listing those which needs to be reworked as i discover them.

**Select token -> Select Token**
**Select hub -> Select Hub**
**Open channel -> Open Channel**
**Send -> Transfer**
