### ISSUE TITLE
Align button style in dApp

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#687]
## Description
Currently, different button styles are used in the dApp. They should get aligned.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by nephix** [comment]
Current buttons:
## Action button (primary)

* Sticky: 
<img width="683" alt="Screenshot 2020-04-01 at 09 34 25" src="https://user-images.githubusercontent.com/3169205/78111336-cd355a00-73fc-11ea-8c48-e8dd2fed1ef7.png">

* Not sticky: 
<img width="597" alt="Screenshot 2020-04-01 at 09 34 47" src="https://user-images.githubusercontent.com/3169205/78111356-d45c6800-73fc-11ea-9ead-804bc02dd354.png">

## Secondary buttons

<img width="345" alt="Screenshot 2020-04-01 at 09 34 55" src="https://user-images.githubusercontent.com/3169205/78111383-dde5d000-73fc-11ea-9857-0253f91fc1b7.png">

## Menu buttons

<img width="576" alt="Screenshot 2020-04-01 at 09 41 06" src="https://user-images.githubusercontent.com/3169205/78111429-ef2edc80-73fc-11ea-861d-ebd2127ba6e1.png">

**Comment by kelsos** [comment]
@nephix thank you. 

Do we really need to do further alignment? From what I can see so far these buttons service different purposes.

**Comment by nephix** [comment]
Yes I agree. The only thing that I would change is making all secondary buttons (like **Deposit** on transfer screen) a ghost button, like **Close**) on the channels screen
