### ISSUE TITLE
Back buttons are checked and changed if needed

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#688]
## Description
The back buttons need to be checked and the link needs to be changed, if needed.

## Acceptance criteria
- All back buttons lead to the previous screen

## Tasks
- Check that the current back buttons redirects to the correct screens

**Comment by taleldayekh** [comment]
Transfer Screen -> Transfer ✔️
Transfer Screen (Request Route) -> Transfer ✔️
Channels Screen -> Transfer ✔️
Select Token Screen -> Transfer ✔️
