### ISSUE TITLE
Having errors as modal screens (generalized)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#689]
## Description
Currently we have got different ways to show errors. Errors should get shown as modal screens everywhere.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
**Suggested next steps**
- Collect all error messages that we currently display
- Decide the nature of each error message
  - In most cases they will be displayed within a modal similar to the newly implemented transfer modal in issue https://github.com/raiden-network/light-client/issues/426#issuecomment-560426394
  - Worth concidering are also error messages such as the one show when a user provides invalid input

**Comment by christianbrb** [comment]
Fixed by https://github.com/raiden-network/light-client/pull/909
