### ISSUE TITLE
Address alignment (showed not input addresses)

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#690]
## Description
All addresses should appear in the same format on all screens

## Acceptance criteria (discussed not final)
- The address should be shown in a shortenend format everywhere
- The address should be copied, if I click on it
- A tool tip should be shown, if I hover over the address (`Click to copy`)

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@nephix Great improvement :)

One small issue:
- We now have got two copy functions within the header address. Can you remove the blue one?

![grafik](https://user-images.githubusercontent.com/35398162/72533283-303f3800-3875-11ea-843b-eee776c2dcac.png)

**Comment by nephix** [comment]
I kept this as an optional parameter `icon` of the component, to make it obvious to the user that the address can quickly be copied in the header

**Comment by christianbrb** [comment]
I would naturally navigate with the mouse to the address if I want to copy it.  The interface looks cleaner if there is less information/elements.

**Comment by nephix** [comment]
Ok will remove
