### ISSUE TITLE
I want to easily understand which address I need to enter on the "Select Hub" screen s

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#691]
## User Story
As Chris, I want to easily understand which address I need to enter on the "Select Hub" screen so that I can easily start using the Raiden Network.

## Acceptance criteria
- A Raiden hub is running on Goerli
- An environment is defined
- Variables for the goerli demo/test environment are defined
- On Goerli the hub gets automatically filled in, if the dApp is not connected to a hub

## Tasks
- [ ] Decide on provided hub address and a copy/paste solution or a prefilled hub address.
- [ ] Split issue, move the info overlay to new issue

**Comment by taleldayekh** [comment]
Discussed this briefly with @kelsos and both of us belive it makes most sense to add this in a information overlay as discusse in issue #698 .

**Pros**
* Will be the first step towards introducing the context aware info button
* Builds on overlay functionallity that has already been implemented and should therefore not be too time consuming to realize
* The user will easily find the relevant information when she needs it, link to readme with the hub address and a short discription of what a hub is and what it does
* We won't be adding arbitrary links in i.e. the footer that we would have to remove in the near future. If something need to be changed in can be done easily in the context of that specific info overlay

**Comment by christianbrb** [comment]
@taleldayekh We have been taking a different approach (see description)

**Comment by taleldayekh** [comment]
> @taleldayekh We have been taking a different approach (see description)

Alrighty! 👍

**Comment by taleldayekh** [comment]
I made a separate issue in #1047 for the context-aware information screens that I mentioned in my comment above.

**Comment by taleldayekh** [comment]
I will remove the design label for this an un-assign myself.
