### ISSUE TITLE
Align modal screens

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#692]
## Description
Currently the modal screens have got different styles. They should get aligned.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
## Collection of "modal" screens
without error screens -> covered in #689

### 1. 
![grafik](https://user-images.githubusercontent.com/35398162/72416636-757d4000-3777-11ea-96cc-9b907c3bcf2e.png)

### 2. 
![grafik](https://user-images.githubusercontent.com/35398162/72416817-cc831500-3777-11ea-9d6b-c404bf4250d9.png)

### 3. 
![grafik](https://user-images.githubusercontent.com/35398162/72417439-2c2df000-3779-11ea-9339-495d7a9bd580.png)

### 4. 
![grafik](https://user-images.githubusercontent.com/35398162/72417985-40262180-377a-11ea-822c-0148719c43fc.png)

### 5. 
![grafik](https://user-images.githubusercontent.com/35398162/72418680-96479480-377b-11ea-824f-316c9b83e71d.png)

### 6.
![grafik](https://user-images.githubusercontent.com/35398162/72418783-cbec7d80-377b-11ea-9a36-977c63131bec.png)

**Comment by nephix** [comment]
Looks like it got finished in #977, thanks a lot @taleldayekh 🙏

**Comment by taleldayekh** [comment]
All modals are now aligned 🥳
