### ISSUE TITLE
I want to understand the different PFS error messages

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#693]
## User Story
As Chris I want to understand the different PFS error messages so that I can derive my next actions and feel confident using the Raiden Network.

## Acceptance criteria
Error messages make more sense for the pfs that we choose.

## Additional information
https://github.com/raiden-network/raiden-services/blob/master/src/pathfinding_service/exceptions.py

This issue depends on #1000

**Comment by christianbrb** [comment]
As a first simple step:

| Problem  | Solution | Error Codes|
|:-|:-|:-|
| No route found  | Please try the request again or select a different PFS  | HTTP 404 (Error Code 22xx) |
| PFS Request failed | Please select a different PFS | Error Codes 20xx |
| PFS Payment failed  | Deposit more tokens to the UDC or select a different PFS  | Error Codes 21xx  |

As a hover over or small/hidden we could add the full PFS error message.

**Comment by christianbrb** [comment]
@nephix If you haven't started this yet, we would like to move it to the backlog in favor of other improvements needed for EthCC

**Comment by nephix** [comment]
@christianbrb I'm almost done with it
