### ISSUE TITLE
Finetuning the top of the "Send" screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#696]
## Description
There are some issues on the top of the "Send" screen:
- How to show the "buttons" - Channel and Deposit?
- How to indicate the token drop-down?
- How to align all elements?

Mainly, it needs a redesign

(not up to date)
![grafik](https://user-images.githubusercontent.com/35398162/70313664-5a352180-1816-11ea-9342-3a159d913477.png)

## Acceptance criteria
- Channel and Deposit buttons
- Channel and Deposit is aligned with the token
- Not overdoing it

## Tasks
- [ ]

**Comment by taleldayekh** [comment]
Just a quick thought about how we could go about indicating the token drop-down by making the arrow more prominent and center it underneath the token name.
![token-overlay](https://user-images.githubusercontent.com/43838780/70535176-d607d480-1b5c-11ea-85d3-c166c89bb72d.jpg)

**Comment by taleldayekh** [comment]
Regarding the alignment of the elements, it would take some experimentation within the mockups. It's not a big thing to tackle once the new iteration starts.

**Comment by christianbrb** [comment]
Let's just do it like that as a next simple step to improve it
(would need some finetuning, but the direction should be clear)

![grafik](https://user-images.githubusercontent.com/35398162/72973576-cae7cb80-3dcd-11ea-8a71-2ccae08694ee.png)
