### ISSUE TITLE
Context aware info or help button and page on every screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#698]
## Description
There should be a button which leads to a pop-up/screen which explains the current screen.

@taleldayekh Could you please paste the screen, which you have showed us?

## Acceptance criteria
- There is an information icon on the top
- It is an overlay for the whole screen
- Per screen
     - One illustration
     - One paragraph
- There is one route
- It recognizes on which page it is
- The text is defined in the translation file
- It is individually formatted per screen
- The content for all the screen defined in https://github.com/raiden-network/light-client/issues/698#issuecomment-725418451 is written and implemented

## Tasks
- [ ] Explain limitations to Sahsh @taleldayekh 
- [ ] Design @sashseurat 
- [ ] Illustrations
- [ ] Implement

**Comment by taleldayekh** [comment]
The idea is to provide the user easy access to additional information whenever she is unsure about a certain step in any of the dApp flows.

By clicking the "i" (information) symbol on a screen the user is shown an ovelay with additional information, perhaps together with an illustration. This can be used both to clearify what the user should do on a given screen but also for explaining blockchain/ethereum/dApp concepts that might be unclear for a new user.
![info_overlay](https://user-images.githubusercontent.com/43838780/70424894-69afa700-1a70-11ea-97e5-1aaa7a2e4465.png)

Examples of real world implementations in other apps:

![info](https://user-images.githubusercontent.com/43838780/70424957-8d72ed00-1a70-11ea-9b54-ee1fa04e1504.jpg)

**Comment by christianbrb** [comment]
Maybe should do this instead of #1487 

@sashseurat @MariaNono Do you have got ideas regarding that issue?

**Comment by taleldayekh** [comment]
@christianbrb Here is where I think it makes sense to provide the users with some sort of "documentation" inside the dApp in the info overlay. Have a look and gimme your thoughts.

## Select Hub
<img width="1120" alt="Screenshot 2020-11-11 at 13 53 34" src="https://user-images.githubusercontent.com/43838780/98813977-5269fe00-2425-11eb-9985-0d870cd1a9d0.png">

Not necessarily clear what a hub is.

## Open Channel
<img width="1120" alt="Screenshot 2020-11-11 at 13 55 03" src="https://user-images.githubusercontent.com/43838780/98814112-88a77d80-2425-11eb-939c-a81fcbfd10ff.png">

Short description of the concept of channels.

## Transfer (for mediated transfers)
<img width="1120" alt="Screenshot 2020-11-11 at 14 08 16" src="https://user-images.githubusercontent.com/43838780/98815429-66166400-2427-11eb-8ac7-536b408cd844.png">

Short descriptions about the PFS concept and the purpose of selecting routes (hops).

## Channels
<img width="1120" alt="Screenshot 2020-11-11 at 14 11 30" src="https://user-images.githubusercontent.com/43838780/98815697-d7561700-2427-11eb-8716-fc6dec48fa0b.png">

Describe that the user channels open with the currently selected token and if they cannot see a specific channel it might mean that they have the wrong token selected.

Also describe the close and settle functionality.

## Transfer ETH
<img width="1120" alt="Screenshot 2020-11-11 at 14 13 56" src="https://user-images.githubusercontent.com/43838780/98815925-2bf99200-2428-11eb-8cb5-f33215f5d065.png">

Short description about the main account and Raiden account ETH.

## Withdraw Tokens
<img width="1120" alt="Screenshot 2020-11-11 at 14 15 00" src="https://user-images.githubusercontent.com/43838780/98816029-5b100380-2428-11eb-9513-51759b907971.png">

Describe how the user would get tokens here, i.e. by closing channel.

## UDC
<img width="1120" alt="Screenshot 2020-11-11 at 14 16 04" src="https://user-images.githubusercontent.com/43838780/98816115-7aa72c00-2428-11eb-97ef-475d23e9777f.png">

Move current description of the UDC to info overlay.

## Backup State
<img width="1120" alt="Screenshot 2020-11-11 at 14 17 02" src="https://user-images.githubusercontent.com/43838780/98816225-9f030880-2428-11eb-9660-39d1d100b9b6.png">

Explain to user why backing up state is crucial.

**Comment by sashseurat** [comment]
@taleldayekh & @christianbrb 
Here a designed draft of my suggestion for the Select a Hub screen overlay:
https://www.figma.com/proto/KVi3wU2n28KlozER6tmg4m/LC-Info-Overlays?node-id=1%3A14&viewport=-95%2C292%2C0.5&scaling=min-zoom

It will really nice if the illustration can be done by @MariaNono!

The approach is:

- Giving user an overlay in the appearance of a screen, with a bit of a highlighted background to draw user's attention, and provide better contrast for easier reading of a big paragraph.

- Simple text in large font for a clear and accessible explanation.

- Two exit points (X + Done) for user's hightened sense of control

- Placeholder for illustration depicting a hub - a node which is connected to several other nodes

**Comment by sashseurat** [comment]
Here is draft for Open Channel screen overlay (in same Figma file, under different page):
https://www.figma.com/file/KVi3wU2n28KlozER6tmg4m/LC-Info-Overlays?node-id=10%3A20

**Comment by christianbrb** [comment]
@sashseurat Very nice! @taleldayekh It is improving the dApp a lot, thanks for pushing it :)

Just a workflow and implementation proposal. Is it always the same screen and just the text and icon need to be "configured".

**Comment by taleldayekh** [comment]
> Just a workflow and implementation proposal. Is it always the same screen and just the text and icon need to be "configured".

Yes exactly like that :)

**Comment by MariaNono** [comment]
Hi, @sashseurat I have just finished some first sketches and discussed them with @taleldayekh 
Have a look and let's discuss them soon.
![screen-overlay-illustration-sketches](https://user-images.githubusercontent.com/16062579/99275714-20dda200-282c-11eb-8f3d-84802fb09b94.jpg)

**Comment by MariaNono** [comment]
Second sketch iteration!
@christianbrb , @taleldayekh , @sashseurat , I would proceed with these ideas unless you any changes to suggest.
![sketches](https://user-images.githubusercontent.com/16062579/99692921-1a009a80-2a8b-11eb-997a-5ac37a277222.jpg)

**Comment by christianbrb** [comment]
@MariaNono Looks very nice :)

Open channel:
1. Please also add dots (tokens) on the left side of the channel (it is the deposit)
2. Just make the arrows into one direction (from left to right) as the the user can just pay somebody if the partner hasn't done a counterdeposit.

UDC Funds:
This one is really hard. It should be shown, that it is used to pay a service.
User/Wallet -> Token -> Service (RSB Provider)
