### ISSUE TITLE
I want to be able to set a payment target, which is transferred as a parameter 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#7]
## User Story
As Chris, I want to be able to set a payment target, which is transferred as a parameter so that I know who I am going to pay.

**Comment by christianbrb** [comment]
@kelsos Is this included in #62 ?

**Comment by kelsos** [comment]
@christianbrb This will also be part of #339.

**Comment by christianbrb** [comment]
Closing as it is included in #339
