### ISSUE TITLE
First step towards a mobile design

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#700]
## Description
@nephix @kelsos You had some proposols for first steps towards a mobile friendly design. Could you describe them within this issue? Thanks :)

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
So what I think at least from a code perspective it makes sense to just make the UI adjust to the screen  and remove the card around if the screen is smaller than the card size.

**Comment by nephix** [comment]
I have created #261 in the past for this, most of the mentioned things should still be there

**Comment by christianbrb** [comment]
@nephix Didn't you fix the most obvious issues for EthCC? If yes, please go ahead and close the issue :)

**Comment by nephix** [comment]
Issues have been addressed in #1078
