### ISSUE TITLE
Fetch all contracts address from a single entry point

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#703]
## Description

https://github.com/raiden-network/raiden/pull/5430#issuecomment-562858144 provided a very nice overview of how all contracts in Raiden Network are linked. 
Currently, we require 3 contracts addresses & deployment blocks to be passed as parameter to create in the form of `ContractsInfo` interface: `TokenNetworkRegistry`, `ServiceRegistry` & `UserDeposit`.
We should also implement it in the SDK, to reduce the number of parameters needed (specially in `Raiden.create`) and reduce the surface for errors, and fetch (and validate) the other addresses from the on-chain pointers.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
Part of #657 ?


Image referenced in the comment above 😊
![](https://user-images.githubusercontent.com/310139/70376308-5ffa3800-18e6-11ea-882c-5801a6055f48.png)

**Comment by andrevmatos** [comment]
I'd say it'd not reduce much the code complexity, even because it should actually add code. But will reduce the interface complexity, and number of parameters the user needs to provide, fetching more that's possible, and reducing the chance of a mismatch there.

**Comment by andrevmatos** [comment]
Needed for #1691 (to provide compatible cli options, namely `--user-deposit-contract-address`)
