### ISSUE TITLE
Don't show input validation in red color

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#704]
## Thanks for filing a bug report :-)

Not really a bug ;)

## Steps to Reproduce
1. Connect to the dApp at

## Expected Result
- `Please enter an amount larger than zero` shown in the color it has been shown before
- No red line

...and if you while fixing that, it would be nice if
- The font color and size of the amount and the token name are the same ("white")
- The amount and token name should be aligned(maybe that's already the case)

## Actual Result

- `Please enter an amount larger than zero` shown in red
- Red line

    ![grafik](https://user-images.githubusercontent.com/35398162/70440159-d8e9c300-1a91-11ea-885d-91dd28b01adf.png)

**Comment by kelsos** [comment]
This was one of the unfortunate accidents in the last PR. It is tricky but easy to fix otherwise.

The color/border rules that should be overwritten are in one of the `::before` or `::after` pseudoselectors in the `.v-input` or `v-text-field`

**Comment by christianbrb** [comment]
Is it also related? (grey is nearly unreadable)

![grafik](https://user-images.githubusercontent.com/35398162/70449214-ef981600-1aa1-11ea-8a87-3f1170e5c895.png)

**Comment by kelsos** [comment]
It is related indeed. It seems that somehow the restructuring of the rules broke the component styling overwrittes we had in place.
