### ISSUE TITLE
Channel is closing even if no gas has been paid

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#705]
## Steps to Reproduce
1. Navigate to channels
2. Close channel
3. Sign messages
4. Click on "Deny" if MetaMask requests to pay gas/ETH

## Expected Result
- Channel is still in the status "Open"

## Actual Result
- Channel is "Closing"

![grafik](https://user-images.githubusercontent.com/35398162/70449683-b01df980-1aa2-11ea-9f11-a587655ef790.png)

**Comment by andrevmatos** [comment]
This is expected: there're several events which should trigger a channel to go into the `Closing` state, even if the `ChannelClosed` event didn't or even isn't going to show up on-chain soon. The only thing the user should be able to do then is try to Close again until it's Closed.
One of these events is the user showing the intention of closing the channel, even if rejecting the signature prompt. `Closing` channels are effectively still `Open` on-chain, but not considered suitable anymore for transfers. This prevents the channel from being used again for transfers and some other actions, which could concurr with events that require the channel to be invalidated even though it's still open on-chain (e.g. handling a closing signature to a 3rd-party).
IMO, this works as expected, and it's a safety feature.

**Comment by christianbrb** [comment]
@andrevmatos Ok, cool, thanks :) Closing
