### ISSUE TITLE
Target availability isn't updated while the address doesn't change

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#712]
## Steps to Reproduce
1. Paste the address of an offline node in transfer's `target` input field in dApp
2. Make the node become online/available
3. After some time, turn the target node offline again

## Expected Result
- After #653 
- Identicon color should turn online, `Target is offline` message should be gone
- After target going offline, Identicon border should again turn gray and `Target is offline` error should show up again.

## Actual Result
- Availability status doesn't change. Logs show the update was picked up by SDK but wasn't reflected on the UI. One needs to clear the input field then paste the address again to trigger the status change.

## Additional Infos (Optional) 
Current `master`
CC. @nephix 

# 2nd issue

## Steps

1. Go to https://lightclient.raiden.network
2. Connect
3. Enter a valid amount
4. Enter an address that is online

## Expected
* Continue button gets enabled
* Green circle is shown

## Actual
* Button remains disabled
* Green circle is shown

**Comment by andrevmatos** [comment]
I suppose the cause should be the presences/availability property isn't reactive. The event comes, should update vuex state, and if we bind the status change directly to the reactive property, it should work, instead of evaluating on change, for example.

**Comment by nephix** [comment]
Not a bug, as this behavior was not expected:

> Acceptance criteria
> Check availability as soon as a valid address is inserted

**Comment by andrevmatos** [comment]
Ok, this was the requirement at the time.
I want to use this issue to request this feature, that the behavior matches the one I described, as I think this would be more consistent and actually should be simple to implement with Vue's capabilities.

**Comment by nephix** [comment]
The store state should already know about the updates presence, the difficult part is updating the address input component which is quite complex and has a lot of component level state. But can definitely be done

**Comment by christianbrb** [comment]
@andrevmatos Thanks for testing the feature extensivly :)
It should be an enhancement.

**Comment by nephix** [comment]
Currently there is an issue that should be tackled together with this enhancement because it's quite related. I will add this to the top description and add the bug label again
