### ISSUE TITLE
Disabled button should be green

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#715]
## Steps to Reproduce
1. Go to https://lightclient.raiden.network
2. Click on connect

## Expected Result
- Button gets disabled
- Button is green

## Actual Result
- Button gets disabled
- Button is gray

**Comment by christianbrb** [comment]
@nephix I don't remember the exact color. Was it green?

**Comment by nephix** [comment]
@christianbrb disabled buttons had a grayed-out green. After the SCSS refactoring it became purely gray

**Comment by kelsos** [comment]
Yes for buttons that have a color we usually use a darker shade of the same color when they are disabled.
