### ISSUE TITLE
Split big files

### ISSUE THREAD

**Issue by andrevmatos** [raiden-network/light-client#717]
## Description

This is a discussion issue, to gather input.
As our codebase grows, and due to the nature of functional/reactive architecture, some files start to get too large (1k+ LoC) and should be split. Splitting big functions into local ones are useful to reduce the size/nesting of a single function/class, but doesn't help with the overall size of the file.

At the same time, we don't want to polute our namespace with tons of exported members which are useful only in their own context.

**The proposal is to convert big files into modules, with helper functions split into separate files when relevant, but containing an `index.ts` file to both make it compatible with current imports and also exposing what's relevant for the context of this single module.**

Example: a big epic, like [transfers/epics](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/transfers/epics.ts)
- **shared** utility functions not specific to transfers and not depending on specific SDK data/types/functions/classes could/should go into [utils/](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/utils/)
- **shared** utility functions specific to transfers could/should go into [transfers/utils](https://github.com/raiden-network/light-client/blob/master/raiden-ts/src/transfers/utils.ts)
- helper functions split from big ones but used only **contextually|once** could go into a `transfers/epics/helpers.ts` or even split modules by domain or even a single function per file
- main epics functions could go into `transfers/epics/<name>Epic.ts` or alike, and import helpers from `./...`
- `transfers/epics/index.ts` file exposes **only** the relevant "public" functions (`*Epic` here); helpers are considered context local and not imported anywhere outside this module, possibly only for some specific test that may be needed
- `import ... from './transfers/epics';` still works because of `index.ts` exposes the relevant members; namespace isn't cluttered with local helpers/utility/split functions.

This approach should also work for e.g. `raiden.ts`, splitting away functions like those in #714 

Related: #588 #657 #658 #659 #660 #661 

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
@andrevmatos Very nice issue! 

> split modules by domain 

Which is the most important part from my perspective. It might happen, that we discover new domains/subdomains/entities from a "business" perspective during refactoring. We should not hide them in helper or utility modules, etc.

**Comment by christianbrb** [comment]
@andrevmatos Can we close the issue? If no, could you change the bullet point list into or task list or create individual issues?
