### ISSUE TITLE
I want to find a token where I have got a balance

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#751]
## User Story
As Chris I want to find a token where I have got a balance so that I can connect to a hub.

## Acceptance Criteria
- Less :-< when scrolling through the token list on Goerli

**Comment by andrevmatos** [comment]
Maybe sorting by balance would help? And also a search field to search over address, symbol and name, when present?

**Comment by kelsos** [comment]
Both sorting and search sound like good ideas. Just keep in mind that the search might take a while to properly show the result we want since the tokens and balances are being lazily loaded, so the full data might take a bit of time to be available.

**Comment by christianbrb** [comment]
We have sorted them. By now it is ok to move forward like this
