### ISSUE TITLE
Review the refactoring of raiden-ts/src/transfers/epics.ts

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#761]
## Description
Review and discuss the refactoring of raiden-ts/src/epics.ts 

## Acceptance criteria
- 

## Remarks
- It did not change the [Maintability in CodeClimate](https://codeclimate.com/github/raiden-network/light-client/raiden-ts/src/transfers/epics.ts)
- I think the new thresholds are not working yet
- We should discuss if the perceived readability is better now.

**Comment by kelsos** [comment]
@christianbrb We should at least wait for 24 hours after the configuration PR to make sure that everything is ok. 

Checking at the churn/maintainability graph I can still see that it has not been updated since Monday. Thomas mentioned that it takes time for things to update, this seems to support that.

**Comment by christianbrb** [comment]
@kelsos Makes sense 👍

**Comment by nephix** [comment]
Looks like the churn/maintainability graph is only updated weekly (or bi-weekly?) on Mondays.

The overall [codebase summary](https://codeclimate.com/github/raiden-network/light-client) has already changed to **B** (we started out at D, then to C after the raiden.ts pull request and now to B after the transport epic pull request) 

But I'm not sure whether https://codeclimate.com/github/raiden-network/light-client/raiden-ts/src/transfers/epics.ts is up-to-date or not

**Comment by nephix** [comment]
The **technical debt** graph updates seem to have propagated https://codeclimate.com/github/raiden-network/light-client/trends/technical_debt
