### ISSUE TITLE
Move wiki to documentation and clean up

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#772]
## Description
Moving the [wiki ](https://github.com/raiden-network/light-client/wiki) to the [documentation ](https://lightclient.raiden.network/docs/) and clean up the content.

Related #750 

## Acceptance criteria
- Empty wiki

## Tasks
- [ ] Go through the SDK Development text
- [ ] Move wiki content to repo and have nothing in the wiki

**Comment by kelsos** [comment]
@christianbrb for this we have to evaluate what makes sense to be part of the documentation. I would suggest that the parts that are targeting a developer using the SDK would become part of the docs and the parts that for the developer developing the SDK should probably stay in the wiki
