### ISSUE TITLE
Compatibility with the Raiden protocol

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#786]
## Description
The LC SDK depends upon the Raiden protocol implemented within the
- Raiden Client
- Pathfinding Service
- Matrix
- Raiden contracts

We need to find a way how to stay compatible, deal with breaking changes and align with the core team on how to prepare those changes and minimize their impact.

## Related Issues
- https://github.com/raiden-network/raiden/issues/5396
- https://github.com/raiden-network/light-client/issues/348

## Tasks
- [ ]

**Comment by jomuel** [comment]
There is now a PR for raiden-network/raiden#5396, but it will not help you with this. There will only be encoding/decoding roundtrip tests, no tests that the format does not change. (We don't want this in Raiden at the moment, as backwards compatibility is not ensured yet and thus the formats may change without consequences for development.)

**Comment by christianbrb** [comment]
@jomuel Cool, thanks a lot 👍 

Let's continue the discussion next year ;)

CC @Dominik1999 @hackaugusto

**Comment by taleldayekh** [comment]
We have an issue for discussing on how to align on this #2753.
