### ISSUE TITLE
Can't connect to hub

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#839]
## Steps to Reproduce
1. Go to https://lightclient.raiden.network
2. Clear local storage
3. Refresh
4. Click connect
5. Connect to new token
6. Enter an address that is online

## Expected Result
- I can connect to the hub

## Actual Result
- Button remains disabled, can't connect to hub

![Screenshot 2020-01-08 at 08 40 15](https://user-images.githubusercontent.com/3169205/71959250-8e737780-31f2-11ea-8531-61d7b85fbda1.png)

## Additional Infos (Optional) 
```
- Browser & version: Chrome
- Browser console errors: none
- Device / OS: macOS
```

**Comment by kelsos** [comment]
There is a chance something changed in the latest vuetify update that affects how validation works, this happens in every Address input.

**Comment by christianbrb** [comment]
@nephix This seems to be fixed. Closing. Please reopen, if the issue still happens for you, thanks :)
