### ISSUE TITLE
Have an automatically generated documentation

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#84]
## Description
Evaluate if it makes sense to generate documentation from the source code using [typedoc](https://github.com/TypeStrong/typedoc).

## Acceptance criteria
- All the SDK naming is renamed to raiden-ts (done #281)
- Runs automatically as part of a successful CI flow.
- Gets automatically generated
- Gets automatically deployed to `lightclient.raiden.network/docs` 
- Gets hosted
- Markdown is generated by typedoc
- Markdown is feed to slate

## Tasks
- [x] Add another step in the CI configuration

**Comment by nephix** [comment]
I heard someone only good things to say about https://docsify.js.org which should be pretty straightforward to use as well if typedoc generates markdown

**Comment by kelsos** [comment]
I am going with [vuepress](https://vuepress.vuejs.org/) since it is already supported by [typedoc-plugin-markdown](https://github.com/tgreyuk/typedoc-plugin-markdown).
