### ISSUE TITLE
Activate git.legal

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#840]
## Description
We need to check the compliance of our licenses. Activate the [git.legal](https://docs.codeclimate.com/docs/git-legal) plug-in in the [CodeClimate.yml file](https://github.com/raiden-network/light-client/blob/master/.codeclimate.yml).

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by christianbrb** [comment]
It is getting executed and no issues have been found:

eg. https://codeclimate.com/github/raiden-network/light-client/builds/1424
![grafik](https://user-images.githubusercontent.com/35398162/72429854-27753600-3791-11ea-9d13-1cb06ba83af4.png)

**Comment by kelsos** [comment]
@christianbrb we can try to include a throwaway PR that tries to introduce a GPL dependency just to verify that this will stop us.

**Comment by christianbrb** [comment]
@kelsos That's a nice idea :)

**Comment by christianbrb** [comment]
We could use: https://github.com/zhukov/webogram

Or any other JS library: https://github.com/search?l=JavaScript&q=gpl&type=Repositories

**Comment by kelsos** [comment]
That looks sufficient for the purposes of our test, thank you
