### ISSUE TITLE
Enforce the CodeClimate Check for a PR to pass

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#841]
## Description
Currently, CodeClimate is running a check on every PR and the result is shown, but it is not enforced. We want to change that to require the CodeClimate check to pass for a PR to be merged.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb Enabling the check should be really easy.. If @andrevmatos @nephix agree I can proceed to make it required.

**Comment by nephix** [comment]
It's fine for me 👍

**Comment by andrevmatos** [comment]
I'd rather not push for it yet. Notice codeclimate complais about issues on every file you touch, so even by changing something completely unrelated, if it e.g. detect those dumb duplication issues on the file, it'll fail the PR, and I think this isn't desirable.

**Comment by nephix** [comment]
Isn't code climate only checking the diffs? We used codacy before and it only checked changes, maybe there's a way to set it up this way

**Comment by kelsos** [comment]
As far as I am aware it seems to check only the diff on the touched files so basically if you have previous issues in a touched file it will show them all.

**Comment by nephix** [comment]
I think the [remaining issues](https://codeclimate.com/github/raiden-network/light-client/issues) are quite reasonable besides the 

> Similar blocks of code

Maybe we can get rid of them by adjusting them in the [config](https://github.com/codeclimate/codeclimate-duplication) so these kind of checks aren't overly aggressive?

**Comment by kelsos** [comment]
@nephix We already adjusted the similar code part to be more relaxed. So far the similarities I had to deal with where 80%-90% of similar code with some type differences here and there. @andrevmatos We can evaluate the duplicates/similars after I finish my PR and see if it makes sense to enable. 

I think the reporting is not that clear but if you check the functions mentioned on the similarities check you can actually see it.

**Comment by kelsos** [comment]
@andrevmatos I just remembered that in code climate's interface you can actually convert a failing check to passing by manually approving through the interface. So it shouldn't be a huge issue if we need to ignore a couple of the issues reported.

**Comment by christianbrb** [comment]
@andrevmatos Related to your comment: https://github.com/raiden-network/light-client/issues/841#issuecomment-572022593

CodeClimate is just checking for **new** issues

See
![grafik](https://user-images.githubusercontent.com/35398162/72240101-62d20200-35e3-11ea-8e62-8fbca6d2bf41.png)

and
https://docs.codeclimate.com/docs/github-pull-requests#section-pull-request-statuses
> post a status update in GitHub notifying you of new code quality issues that have been introduced.

and in addition, as @kelsos has pointed out:
> Teams should use their judgment to validate and invalidate issues found by Code Climate. For these cases, Code Climate allows developers to mark any issue with one of 3 different statuses:

**Comment by kelsos** [comment]
I enabled the code climate as a required check for the CI, when we get issues we can go into the code climate interface and evaluate if they need to be fixed or if we want to skip them. We should be able to approve but logging to code climate through GitHub.
