### ISSUE TITLE
Only enforce testnets, if deployed to https://lightclient.raiden.network/

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#842]
## Description
Currently, only testnets are allowed to be used. In future this should just be enforced, if the dApp is deployed to https://lightclient.raiden.network/

## Acceptance criteria
- Mainnet is enabled in the SDK
- Mainnet is disabled if deployed to https://lightclient.raiden.network/
- The environment variable is going to be used

## Tasks
- [ ] Add a flag that throws an error when trying to connect on mainnet using our hosted dApp

**Comment by kelsos** [comment]
Do we really want this to be implemented as part of the SDK? I think it would make more sense as part of the dApp.

**Comment by andrevmatos** [comment]
Yes, I think it should be on the dApp, and not specific to `lightclient.raiden.network`. IMO, the best approach would be to enable mainnet by default, and disable if some `process.env` is set, and we set it in our CI deploy script, so it'll be disabled on our deployment, but available in the codebase.

**Comment by kelsos** [comment]
The environment variable approach sounds good :) let's go with that then.

**Comment by nephix** [comment]
Added SDK label again because at the moment main net is not allowed by the SDK
