### ISSUE TITLE
Review dApp/SDK installation instructions

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#845]
## User Story

As a developer I want to have instructions to start working on the light client or SDK. At the moment, have have some instructions but they are quite old and we haven't tested them in a while.

## Acceptance criteria

- [x] Instructions verified
- [x] Code snippet were cleaned up (e.g. removing python comments in TypeScript code)

**Comment by taleldayekh** [comment]
I followed the instructions to clone the LC repo and install all dependencies in a clean Docker container. @kelsos was correct about that we need to execute both `npm run build` and `npm install --save raiden-ts` else it will not work.

**Comment by christianbrb** [comment]
@taleldayekh Is this issue completed? If yes, please go ahead and close it.

**Comment by taleldayekh** [comment]
Yep! Will do!
