### ISSUE TITLE
Limit the usage of token networks

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#848]
## Description
We need to have the possibility to limit the token networks the user can choose.

## Acceptance criteria
- 

## Tasks
- [ ]

**Comment by kelsos** [comment]
@christianbrb Is that practical? currently you can limit the token networks on the SC level. If you don't limit them in the SC then anyone can register a token and deploy their own tokens. I don't see how we could potentially limit the tokens on the light client or how this would be practical. Do you have any specific scenario/use case/example that would help understand what you mean?

**Comment by andrevmatos** [comment]
I agree with Kelsos. Our source of truth is the blockchain, if somewhere, the limits should be there, the dApp/SDK/light-client is an interface for it and should reflect what's registered there.

**Comment by christianbrb** [comment]
@kelsos @andrevmatos Sounds reasonable. Closing :)
