### ISSUE TITLE
Revise docs content

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#850]
## Description
The docs could benefit from some revision where sections that come of as a bit unclear or to difficult to understand are improved.

## Acceptance criteria
- More "advanced" concepts are clearly explained.
- All content is written in an active voice and follows a similar structure as the Raiden (GitBook) docs.

## Tasks
- [ ]

**Comment by nephix** [comment]
It should also be clarified whether the docs should explain how to develop with the dApp or build a minimal app from scratch. If the dApp is not necessary then we don't need the user to e.g. clone the repo etc

**Comment by kelsos** [comment]
@nephix The existing documentation is about contributing or playing around with everything. 

The documentation for developers using the SDK doesn't exist at the moment. The guide for the developers building on top of the SDK should be a new section in the documentation.

**Comment by nephix** [comment]
> The guide for the developers building on top of the SDK should be a new section in the documentation.

Probably the main section and focus, as that is most likely the main use case for someone who accesses the docs page?

**Comment by christianbrb** [comment]
Outdated
