### ISSUE TITLE
Minting and depositing stuck on spinner with error "Cannot read property 'decimals' of undefined"

### ISSUE THREAD

**Issue by taleldayekh** [raiden-network/light-client#873]
## Steps to Reproduce
1. Start the dApp (hosted or local)
2. Proceed to make a mediated transfer
3. Press the icon for minting and depositing SVT tokens

## Expected Result
- Expecting the minting and depositing to succeed and my SVT balance to increase with 10.

## Actual Result
- The minting dialogue is stuck spinning and in the console an `Cannot read property 'decimals' of undefined` error is thrown.

## Additional Infos (Optional) 
![error](https://user-images.githubusercontent.com/43838780/72158149-dbee1100-33b9-11ea-97f0-a9d770c1968d.png)

**Comment by taleldayekh** [comment]
Proposal to add logger by default to the hosted lc @andrevmatos

**Comment by andrevmatos** [comment]
logs on by default (at `info` level) done as part of #1045

**Comment by taleldayekh** [comment]
Could not reproduce.
