### ISSUE TITLE
New/old token network support

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#874]
## User Story

As a user I want to be able to get money out of my channels from "old" token networks, e.g. if a contract update occurred and then for example two `TTT` tokens under different token addresses exist.

When these kind of updates occur it also seems like the state of the dApp somehow gets corrupted.

Follow up issue for #833 

## Acceptance criteria

* User should get informed whats going on
* User can get his tokens back

**Comment by christianbrb** [comment]
On testnet this shouldn't be an issue with our token minting functionality now. On mainnet this is a bigger issue and we need to handle it differently.
