### ISSUE TITLE
Bundling & Raiden CLI

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#877]
## Description
@andrevmatos Please provide details. Thanks :)

## Acceptance criteria
- Stable  transfers < 5secs
- Max 3 hops

## Tasks
- [ ] Clearify the issue
- [ ] Make sure CLI works with all new changes from last month

**Comment by andrevmatos** [comment]
Is it the bundle for the CLI app? If so, it's like this:
1. Clone repo on `cli` branch: `git clone -b cli https://github.com/raiden-network/light-client.git`
2. Rebase it: `cd light-client ; git rebase master`
3. Install dependencies: `pushd raiden-ts && npm ci && popd && pushd raiden-cli && npm install`
4. Build bundle: `npm run build:bundle`
5. With a JSON key available, open channel, mint, deposit, transfer & exit:
```sh
node build/bundle.js -e https://eth-node -k key.json --token 0x59105441977ecD9d805A4f5b060E34676F50F806 --partner <hub> --mint --deposit 1000 --transfer 5 --target <hub>
```

**Comment by nephix** [comment]
The bundle is built via webpack and does not require outside dependencies. The performance analysis is done in #876
