### ISSUE TITLE
dApp is freezing every few seconds

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#878]
## Steps to Reproduce
1. Open the Light Client
2. Navigate to the transfer screen
3. Paste a targe address (eg. 0x5257964Ef9b81fba7276AF2a97c111AaD7B840D6)
4. Start entering an amount and don't stop typing (add 0 and delete it)

## Expected Result
- I should be able to continue typing flawlessly

## Actual Result
- I am not able to continue to enter a 0 or delete it every few seconds. I am pressing a key and a few moments later it is entered (delay).
- This also appears while navigating the dApp, but typing is the best way to reproduce it

**Comment by kelsos** [comment]
I don't remember having such a problem but I will have to look into it. We have a couple of asynchronous calls getting fired there and I am not sure we are currently doing any debouncing as far as I am aware.

**Comment by nephix** [comment]
Usually these "freezes" happen when a computational heavy operation is running and blocking the main thread for a couple of seconds (e.g. signing a message) I will investigate

**Comment by christianbrb** [comment]
I am under the impression, that one of the latest changes introduced this behavior.

**Comment by christianbrb** [comment]
It is not reproducible at the moment

**Comment by nephix** [comment]
Me neither, I think there is some signing going on in the background (retying to send some previous failed messages?) that blocks the main thread of a couple of milliseconds and in the dApp it appears to freeze.

I had the same issue as well some time ago and in my case there were an unusual high amount of metamask popups

**Comment by nephix** [comment]
@christianbrb got the issue again and observed the **matrix sync request** while having bad connectivity

**Comment by kelsos** [comment]
@nephix I also had some frame rate issues at some point and the profiling actually was showing the matrix sync as the culprit. We need to see if the matrix filtering we help with this or if we need to do something extra.
