### ISSUE TITLE
I want to easily install the dApp on my local system

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#880]
## User Story
As Chris, I want to easily install the dApp on my local system so that I can test it without a hosted environment.

## Acceptance criteria
- Available on Mac, Linux and Windows
- Downloading the latest release
- Mechanism to update to the latest release
- It is hosted on localhost
- The dApp is getting opened
- Extend the CI to build it
- Upload it to GitHub releases

**Comment by nephix** [comment]
> without a hosted environment

does that mean no external dependencies at all or should we will be able to push updates when the user starts the dApp?

**Comment by kelsos** [comment]
We can give it a try if you can use the gh_pages branch sources in the browser without the need for any server. If it works maybe we can pack a version of the dApp in an archive and allow the users to extract and run locally from the browser.

**Comment by nephix** [comment]
In Chrome v73 and later we can already install the Light Client as a Chrome App:

1. Go to https://lightclient.raiden.network
2. Click on Settings (3 dots at top right)
3. Click on Install raiden-dapp

It then installs it as a PWA locally and starts it in a "native window". Still requires a hosted version to fetch updates from though. It can then be started by typing chrome://apps into Chrome and clicking on raiden-dapp.

**Comment by andrevmatos** [comment]
Nice finding @nephix, thanks @kelsos for the the seamless PWA implementation. The local static files from `gh_pages` branch is also a nice option, although we need to check if everything behaves properly when served from local filesystem on Chrome & Firefox. Just let's not go the cursed Electron route on this issue.

**Comment by christianbrb** [comment]
@andrevmatos to check, if PWA works with MetaMask

**Comment by christianbrb** [comment]
@kelsos proposed to do this with Electron

**Comment by kelsos** [comment]
> @kelsos proposed to do this with Electron

I wouldn't say I proposed to do with Electron. Rather I said if they other ways to do it are not acceptable and we have to go the electron way then I can help because I have some prior experience with Electron and Vue :)

**Comment by christianbrb** [comment]
Ok, I hear your excitement 🤣

**Comment by christianbrb** [comment]
We should check 
1. If there is an easy way to host in on the user's machine (like the wizard).
2. If MetaMask can be integrated in Electron

**Comment by christianbrb** [comment]
@andrevmatos @weilbith @kelsos Who has got time to do some pre-iteration research on this?

**Comment by andrevmatos** [comment]
I just checked here, and Metamask is definitely fully available for PWAs on Chromium. Would it be enough to provide it, and point to the `serve_pr` script or full local build/serve if the user needs further control?

**Comment by kelsos** [comment]
> I just checked here, and Metamask is definitely fully available for PWAs on Chromium. Would it be enough to provide it, and point to the `serve_pr` script or full local build/serve if the user needs further control?

The problem with `serve_pr` is that it requires some technical skills, if the local version is targeting non-technical users I don't think it would work that easy.

**Comment by christianbrb** [comment]
The proposal from Kelsos:
- Pack an express app with a node backend which serves the application
- Leave the user to use MetaMask
- Run in the local browser

**Comment by palango** [comment]
> The proposal from Kelsos:
> 
>     * Pack an express app with a node backend which serves the application
> 
>     * Leave the user to use MetaMask
> 
>     * Run in the local browser

The only problem I see with this approach is that the user might not know/understand how to stop the application properly. The same happened with the wizard running as a bundle from a terminal.

**Comment by kelsos** [comment]
> > The proposal from Kelsos:
> > ```
> > * Pack an express app with a node backend which serves the application
> > 
> > * Leave the user to use MetaMask
> > 
> > * Run in the local browser
> > ```
> 
> The only problem I see with this approach is that the user might not know/understand how to stop the application properly. The same happened with the wizard running as a bundle from a terminal.

I don't see how that is a problem. This could be easily solved if you add a terminate endpoint to the "server" and some packaged mode customization so that the user can terminate the server directly from the dApp. I think the WebUI is doing a similar thing with the python client already.

**Comment by kelsos** [comment]
Btw the server doesn't have to be node either, you could easily do a small flask backend packaged with PyInstaller that can produce binaries for Linux/OSX and Windows.

**Comment by christianbrb** [comment]
To check, if it works as a progressive web app:
- Chrome
- Firefox
- Safari
- MetaMask Mobile

**Comment by christianbrb** [comment]
@andrevmatos Could you roughly check the PWA concept.

I have found this articles:
https://almbok.com/kb/progressive_web_application
https://web.dev/progressive-web-apps/

PWA seems to work on MetaMask Mobile:
https://github.com/MetaMask/metamask-mobile/issues/1966

Ok, I think it is not working on a lot of browsers:
https://caniuse.com/web-app-manifest

**Comment by christianbrb** [comment]
It seems to mainly work on mobile.

**Comment by christianbrb** [comment]
Just for completness. There is a PWA plug-in for Vue:
https://axelhodler.medium.com/caching-in-a-vue-js-pwa-845233696072
https://vuepress.vuejs.org/plugin/official/plugin-pwa.html

**Comment by christianbrb** [comment]
@weilbith 
How is our caching currently working? I was under the impression, that in the past we have completely cached the dApp and only refreshed on a new build. I think this would be already sufficient.

If not there is another way of building offline available web pages:
https://vueschool.io/articles/vuejs-tutorials/vue-js-performance-mastering-cache/
https://samvloeberghs.be/posts/lessons-learned-on-offline-capabilities-with-service-workers-using-workbox/

**Comment by weilbith** [comment]
> https://vuepress.vuejs.org/plugin/official/plugin-pwa.html

We use that already if I'm not wrong.

**Comment by christianbrb** [comment]
Closing this one as it has a long discussion and the scope is not clear any more.

First we are going to fix https://github.com/raiden-network/light-client/issues/2382

If need we are going to create a new issue for using the service worker / cache offline capability.
