### ISSUE TITLE
Show when channel becomes settleable/settled

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#881]
## User Story

As a user I would like to know how many blocks are left until I can settle a closed channel. I think the current settle timeout is 500 blocks and we already save `openBlock` and `closeBlock` for each channel in the local state.

## Acceptance criteria
* Progress bar or just a `288/500 blocks` label that indicates how many blocks are left until channel can be settleable/settled

**Comment by kelsos** [comment]
@nephix Also maybe at some point in the future after adding a notification area we could also notify the user about a channel being settleable and let the users settle directly from the notification via an action button.

**Comment by andrevmatos** [comment]
Space/line between `Closed` & `Settleable` in Channel status stepper could/should be said progressbar. Tooltip can include blocks counter and maybe even an ETA based on average block time (we could easily expose that on the SDK).

**Comment by christianbrb** [comment]
Already implemented. Closing :)
