### ISSUE TITLE
Insufficient token balance in "Mint and Deposit"

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#884]
## Steps to Reproduce
1. Make a transfer to a node without a direct channel
2. Click on the symbol to mint and deposit new SVT tokens
3. Click on "Mint and Deposit"

## Expected Result
- Minted 10 SVT

## Actual Result
- Error `Insufficient token balance (0).` is shown

![grafik](https://user-images.githubusercontent.com/35398162/72417036-474c3000-3778-11ea-9c2a-75132cfd47b2.png)

**Comment by kelsos** [comment]
@christianbrb what about the metamask popups, how many did you have? did you confirm every one of them? I tried the mint flow and I got no issues. Any more information that might help to replicate?

**Comment by christianbrb** [comment]
Unfortunately I don't have it. I am going to give it a try another time.
