### ISSUE TITLE
Continue Button stays disabled on transfer screen

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#885]
## Steps to Reproduce
1. Enter a target (eg. 0x2d1bC0F9e6B755155cB379546C1546E0353E6b19)
2. Enter an amount

## Expected Result
- Continue button gets enabled

## Actual Result
- Continue button stays disabled

## Workaround
- Delete the target and paste it again
- The continue button gets enabled
- Afterward it also works if I delete the amount and enter it

**Comment by nephix** [comment]
Same issue as in #839

**Comment by christianbrb** [comment]
Notes from the planning:
- Simplify the validation
- Make it reactive (eg. debouncing)
