### ISSUE TITLE
Create a communication channel with the on-chain channel's partner via Matrix 

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#89]
## Description

Currently, we are just opening a channel on chain. In addition, we need to open the communication channel within the transport protocol (Matrix).

## Acceptance criteria
- The architecture is aligned with the transport team
- Define a common public interface for the transport module
- Implement the retry logic we are using in the Python client
- Not using the state storage and sync of the Matrix SDK
- Having a test coverage of 60% for this module is fine at the start
- Epics are split into modules
- Initialization is split into its own module
- Get matrix servers from github based on response time
- Login and store it in the configuration
- Initial sync

## Tasks
- [x] PR #130 -> Tests
- [x] Pull Request Review via video call

**Comment by andrevmatos** [comment]
Retry is actually part of the messages sending task, which is being done and tracked on #91 . This feature can be considered done as per #130 .
