### ISSUE TITLE
License analysis tool

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#919]
## Description

As git.legal does not work in our set-up (see https://github.com/raiden-network/light-client/pull/917#issuecomment-576255958) we need to find another solution to check if the licenses of all dependencies are compliant with MIT.

Here is a list of the licenses we can use

License | Comment
-- | --
BSD (all versions) | Ok
Apache (all versions) | Ok
MIT | Ok
MPL (Mozilla Public License) | Ok
LGPL-3.0 | Ok
ZPL (Zope Public License) | Ok
ISC | Ok
GPL | Not usable
GPL Affero | Not usable
Do What The Fuck You Want To Public License | Ok

## Acceptance criteria
- PR fails if a dependency with incompatible license is included either in the SDK or the dApp

## Tasks
- [ ] Write CI task that does the license check and fails if needed

**Comment by kelsos** [comment]
One idea would be to configure [license-checker](https://www.npmjs.com/package/license-checker) to check the production modules and pass it a list of the compatible to MIT licenses there. There was an example using it in GitHub actions.

**Comment by christianbrb** [comment]
This one? https://github.com/cds-snc/github-actions/tree/master/node-license-checker

**Comment by kelsos** [comment]
Yes exactly. We need to do a preliminary on what licenses are compatible and add a new job in the CI configuration.

**Comment by kelsos** [comment]
![image](https://user-images.githubusercontent.com/2269732/73847977-89bcd600-4827-11ea-8f1a-34a78d27395e.png)

I did run a test PR to verify that the task helps. As a last part, I am gonna make the license task as required.
