### ISSUE TITLE
I want to add a payment identifier to my transfer

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#921]
## User Story
As Chris, I want to add a payment identifier to my transfer so that the target can identify the payment.

## Acceptance criteria
- Included identifier with each transfer if it is in the parameters

**Comment by andrevmatos** [comment]
SDK already supports receiving the `paymentId` param, which needs to be a 64bit unsigned integer:
https://github.com/raiden-network/light-client/blob/bf4cb4fe8f21649896fc4ba62d8e78975b06ae0d/raiden-ts/src/raiden.ts#L676-L687
So, it's just a matter of adding the dApp bits.

**Comment by kelsos** [comment]
@taleldayekh we need to find a nice way to add this to the payment ui but keep it optional, without talking a lot of space
