### ISSUE TITLE
Spinner in address entry keeps turning after entering an http address

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#922]
## Steps to Reproduce
1. Go to the Transfer screen
2. Enter `https://github.com/raiden-network/light-client/issues/new`
3. Delete `https://github.com/raiden-network/light-client/issues/new`

## Expected Result
- `Enter an address or ENS name` is shown

## Actual Result
- Spinner is still shown
- ![grafik](https://user-images.githubusercontent.com/35398162/72802959-33f40580-3c4d-11ea-8361-1ab5c6459928.png)

## Additional Infos (Optional) 
```
- Firefox 72.0.1 (64-Bit)
```

**Comment by nephix** [comment]
Can't reproduce
