### ISSUE TITLE
Make it clearer to select hub

### ISSUE THREAD

**Issue by czepluch** [raiden-network/light-client#923]
## Description
According to screenshot below, it took me quite some time to realize what I needed to do. It would be nice if the text in the input box would mention that it's the hub address that is being asked for.

![Screenshot from 2020-01-21 14-13-23](https://user-images.githubusercontent.com/1026799/72807817-78d16980-3c58-11ea-9611-557bfdb9c0bd.png)

## Acceptance criteria
- [ ] Make it more clear that the user needs to input the address of the hub to use

**Comment by christianbrb** [comment]
@czepluch Thanks for your feedback :)

@talel is already working on a wireframe to improve this, which is going to be implemented with https://github.com/raiden-network/light-client/issues/691. This should get implemented within the next iteration starting on Thursday.

**Comment by Talel** [comment]
Hello
I don't have any idea about the subject , may be its a tag mistake (same
name Talel :) )
No problem if you need help i'm here ,
;)

*Talel Belwafi*
*CEO Labinet*
*Tél: +216 98 66 08 30*
*Email: talel@labinet.net <talel@labinet.net>*
*Linkedin: https://www.linkedin.com/in/talelbelwafi/
<https://mailtrack.io/trace/link/e753ba2ef6ec4c2569691130859a30c6860d0bba?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ftalelbelwafi%2F&userId=3519119&signature=28b5e85fe9480a77>*
*Site web:* *www.labinet.net*
<https://mailtrack.io/trace/link/b15aa7c308bdf9109aeae568881e94016121fa7f?url=http%3A%2F%2Fwww.labinet.net%2F&userId=3519119&signature=9f9e5b0bc9361dc2>
*WhatsApp: +216 98 66 08 30*
*Skype : talelbelwafi*

[image: image.png]
<https://mailtrack.io/trace/link/cc9284f923f8d0675a0eb87107f41494938dc16b?url=http%3A%2F%2Flabinet.net%2F&userId=3519119&signature=8554376dab221108>


Le mar. 21 janv. 2020 à 14:20, christianbrb <notifications@github.com> a
écrit :

**Comment by christianbrb** [comment]
@Talel Sorry! It was a tag mistake

I wanted to tag @taleldayekh :)

**Comment by Talel** [comment]
No problem :)
Hi @taleldayekh
<https://mailtrack.io/trace/link/2acbce3276cd3df6fa0c6c8cc07f772059fc8afd?url=https%3A%2F%2Fgithub.com%2Ftaleldayekh&userId=3519119&signature=c7ffb3f283b4ae65>

Cordialement
Talel Belwafi
+216 98660830


Le mar. 21 janv. 2020 à 14:35, christianbrb <notifications@github.com> a
écrit :

**Comment by christianbrb** [comment]
@taleldayekh Did you consider this while implementing #691? If yes, please go ahead and close the issue :)

**Comment by nephix** [comment]
@christianbrb I implemented it. At the moment our hub.raiden.eth is automatically filled in on goerli, if the user is not connected to a different hub (read: has no open channel) for the token yet

**Comment by Talel** [comment]
Hello guys :)
Please add and tag talel dayekh
you welcome

*Talel Belwafi*
*CEO Labinet*
*Tél: +216 98 66 08 30*
*Email: talel@labinet.net <talel@labinet.net>*
*Linkedin: https://www.linkedin.com/in/talelbelwafi/
<https://mailtrack.io/trace/link/5277d8853e372916fbcce7ba5fcd52667459199e?url=https%3A%2F%2Fwww.linkedin.com%2Fin%2Ftalelbelwafi%2F&userId=3519119&signature=ab0b68da0a3528ba>*
*Site web:* *www.labinet.net*
<https://mailtrack.io/trace/link/ab31c27d4ba57d0eb8c08e5009c3609cff3c016e?url=http%3A%2F%2Fwww.labinet.net%2F&userId=3519119&signature=3d1d7b1048bed46d>
*WhatsApp: +216 98 66 08 30*
*Skype : talelbelwafi*

[image: image.png]
<https://mailtrack.io/trace/link/48d327724b936b09f666362918af44eac56198e0?url=http%3A%2F%2Flabinet.net%2F&userId=3519119&signature=7e1d52af20e48800>
