### ISSUE TITLE
I want to log into MetaMask at the latest responsible moment

### ISSUE THREAD

**Issue by christianbrb** [raiden-network/light-client#97]
## User Story
As Chris, I want to log into MetaMask at the latest responsible moment, so that I am able to see how the wallet looks like before signing in.

**Comment by kelsos** [comment]
Since this is not feasible for a technical perspective the only thing that can actually be done is not to connect the user automatically as they navigate on the dApp. This is already done in the current iteration of the dApp and thus I am closing the issue.
