### ISSUE TITLE
Split SDK tests between unit and e2e

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#972]
## Description

Split our test suite for the SDK to unit end e2e tests. Have two different commands that can run (maybe also provide one that runs both of them to make it easier during development.

The reasoning behind this is to split and parallelize them. 

## Acceptance criteria
- `npm run test:unit` Runs the unit tests
- `npm run test:e2e` Runs the e2e
- Have separate coverage reports for e2e/unit 
- Run `e2e` and `unit` tests in parallel on CI

## Tasks
- [ ]

**Comment by andrevmatos** [comment]
The separate coverage should be **additional** to the aggregated one, which should still be one reported in README.

**Comment by kelsos** [comment]
Yes instead of having dapp and sdk we will have something like dapp, sdk-unit, sdk-e2e

**Comment by palango** [comment]
This is implemented now
