### ISSUE TITLE
Route Request: Source does not have a channel with sufficient capacity

### ISSUE THREAD

**Issue by nephix** [raiden-network/light-client#982]
## Steps to Reproduce
1. Setup and fund two python clients with latest develop and make them use https://pfs-goerli-with-fee.services-dev.raiden.network
2. Open channel to one of the raiden clients
3. Try to initiate a mediated transfer

## Expected Result
- I receive a route from the PFS

## Actual Result
![Screenshot 2020-02-05 at 11 06 38](https://user-images.githubusercontent.com/3169205/73833135-bf52c680-4809-11ea-8c7e-4dc734aa2b85.png)

```json
{ 
   "errors":"Source does not have a channel with sufficient capacity ([0] < 20000000000)",
   "error_code":2201,
   "error_details":{ 
      "from_":"0x2142194DF04265cF545bC18158347ef36Ba6E35c",
      "to":"0x970e5C8Da0AfDa3159fD9fC9C55F4b2fF2b4568E",
      "value":20000000000
   }
}
```

## Additional Infos (Optional) 

* Channels are properly funded:
![Screenshot 2020-02-05 at 11 21 24](https://user-images.githubusercontent.com/3169205/73833102-b104aa80-4809-11ea-9d9b-22c01601c710.png)
* I made a deposit from every client to their channels to make sure that the PFS Capacity Update is sent again

<details><summary>Application State</summary>
<p>

```json
{ 
   "address":"0x2142194DF04265cF545bC18158347ef36Ba6E35c",
   "chainId":5,
   "registry":"0x9b0c8C8C75904CEf5B7a8dbF59c3459Ea85c6526",
   "blockNumber":2124545,
   "config":{ 
      "pfsSafetyMargin":1.1
   },
   "channels":{ 
      "0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df":{ 
         "0x1a48C928FF31d51543850Ec231e8F1889B3411C7":{ 
            "state":"open",
            "own":{ 
               "deposit":"18873300000000000",
               "locks":[ 

               ],
               "balanceProof":{ 
                  "chainId":"5",
                  "tokenNetworkAddress":"0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df",
                  "channelId":"124",
                  "nonce":"4",
                  "transferredAmount":"3330300000000",
                  "lockedAmount":"0",
                  "locksroot":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
                  "messageHash":"0xe58249175956e7bdd690629a73e70d5d894095ec96962e169d079c0b8443fa30",
                  "signature":"0x554c2e8b8c98f7231ffe4eff9b2dd6ac7fa1513811a27210ec43c84c473978867c90e9d5840c731bdd6933660a6bb6bff8214d00aa0a5a24669b828edb81b1a61b",
                  "sender":"0x2142194DF04265cF545bC18158347ef36Ba6E35c"
               }
            },
            "partner":{ 
               "deposit":"11312300000000000"
            },
            "id":124,
            "settleTimeout":500,
            "openBlock":2124234,
            "isFirstParticipant":true
         }
      }
   },
   "tokens":{ 
      "0x59105441977ecD9d805A4f5b060E34676F50F806":"0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df"
   },
   "transport":{ 
      "matrix":{ 
         "server":"https://transport04.raiden.network",
         "setup":{ 
            "userId":"@0x2142194df04265cf545bc18158347ef36ba6e35c:transport04.raiden.network",
            "accessToken":"MDAyOGxvY2F0aW9uIHRyYW5zcG9ydDA0LnJhaWRlbi5uZXR3b3JrCjAwMTNpZGVudGlmaWVyIGtleQowMDEwY2lkIGdlbiA9IDEKMDA1OWNpZCB1c2VyX2lkID0gQDB4MjE0MjE5NGRmMDQyNjVjZjU0NWJjMTgxNTgzNDdlZjM2YmE2ZTM1Yzp0cmFuc3BvcnQwNC5yYWlkZW4ubmV0d29yawowMDE2Y2lkIHR5cGUgPSBhY2Nlc3MKMDAyMWNpZCBub25jZSA9IEY6OGpZR0U1QFE4aSxHdVEKMDAyZnNpZ25hdHVyZSDEWczgQJuQJw9IWBp-ErYZ7EMlLC2HKeL3bXviOUJDgwo",
            "deviceId":"MRCTLHLKFM",
            "displayName":"0x20b5c63c3166950ab1598b8f6f6051a08d7d776b9ecc382179085ec8346418d24c0fafbdeb107976bbbfeab9e0a41eed6967f9cfda3f692d8deba600da3355a41c"
         },
         "rooms":{ 
            "0x1a48C928FF31d51543850Ec231e8F1889B3411C7":[ 
               "!seQwFylGExaEiwvTvi:transport04.raiden.network"
            ]
         }
      }
   },
   "secrets":{ 
      "0xcf0a0103630c56a53c64ae1b4fd2be796fc9925636adeb96b45272114872db2b":{ 
         "secret":"0x94b93977fcbcd1926317eca9bf1a1f02085d628c5147dfca93041178f0cd089e"
      },
      "0xd82dc4353531fa629f862284a3dbd4d84e5d89973b29150a4f604bc161ba8039":{ 
         "secret":"0xcda9128c7d90cddf6de5d58155473a0534d0570c4a82ff46f8d5f9a54a716938"
      }
   },
   "sent":{ 
      "0xcf0a0103630c56a53c64ae1b4fd2be796fc9925636adeb96b45272114872db2b":{ 
         "transfer":[ 
            1580893953708,
            { 
               "type":"LockedTransfer",
               "message_identifier":"1580893947306",
               "chain_id":"5",
               "token_network_address":"0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df",
               "channel_identifier":"124",
               "nonce":"1",
               "transferred_amount":"0",
               "locked_amount":"300000000",
               "locksroot":"0x9b8f3692fc0bc58d346bba37615d39d21af14be6949a99ef5dbdabfd8cdee9b6",
               "payment_identifier":"11487500240039270647",
               "token":"0x59105441977ecD9d805A4f5b060E34676F50F806",
               "recipient":"0x1a48C928FF31d51543850Ec231e8F1889B3411C7",
               "lock":{ 
                  "amount":"300000000",
                  "expiration":"2124360",
                  "secrethash":"0xcf0a0103630c56a53c64ae1b4fd2be796fc9925636adeb96b45272114872db2b"
               },
               "target":"0x1a48C928FF31d51543850Ec231e8F1889B3411C7",
               "initiator":"0x2142194DF04265cF545bC18158347ef36Ba6E35c",
               "metadata":{ 
                  "routes":[ 
                     { 
                        "route":[ 
                           "0x1a48C928FF31d51543850Ec231e8F1889B3411C7"
                        ]
                     }
                  ]
               },
               "signature":"0x2ca2322fe72a5aa2ba7ad5966a4ffc47828b7391deb4f77ed5f7083326ce5dc32dfd8c9da4807b44463ee15a6459c768ace17fc44b4a915104127d7fc88ff38a1b"
            }
         ],
         "fee":"0",
         "transferProcessed":[ 
            1580893960511,
            { 
               "message_identifier":"1580893947306",
               "signature":"0x47bf3e6cc6e3a96091a785185932b5c80abe242136210dbd89b1e0f05f7c19352ba5896ae2937e6e92f401ad0ce96579e265f0750ba9480760ea7d0f47a403721c",
               "type":"Processed"
            }
         ],
         "secretReveal":[ 
            1580893962603,
            { 
               "type":"RevealSecret",
               "message_identifier":"1580893955534",
               "secret":"0x94b93977fcbcd1926317eca9bf1a1f02085d628c5147dfca93041178f0cd089e",
               "signature":"0x6ae5a5a5b6f1357aac49e56ad03e56ca780ccd2c10ef2f544c0705c1abf472ac40778d9fdd572926376e0b1bf900f635794f4d255546f5e31440f217a33030aa1c"
            }
         ],
         "unlock":[ 
            1580893968907,
            { 
               "type":"Unlock",
               "message_identifier":"1580893963286",
               "chain_id":"5",
               "token_network_address":"0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df",
               "channel_identifier":"124",
               "nonce":"2",
               "transferred_amount":"300000000",
               "locked_amount":"0",
               "locksroot":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
               "payment_identifier":"11487500240039270647",
               "secret":"0x94b93977fcbcd1926317eca9bf1a1f02085d628c5147dfca93041178f0cd089e",
               "signature":"0xb30f8f7901414315d18cd4f4d7df101e55d56878f71f874c03279f316d09b2485b531270464e286dd4463eee1a62e608086eb720b69fabcd556f4576df624a1a1c"
            }
         ],
         "unlockProcessed":[ 
            1580893975949,
            { 
               "message_identifier":"1580893963286",
               "signature":"0x34f62b51fae5ae303e0feae532cf59627e237db26f7048729ebdb57be02087fd6f1bddadf778869dcac3fba66a889e19455a9d0a3241cf8435f063ea46bc75151c",
               "type":"Processed"
            }
         ]
      },
      "0xd82dc4353531fa629f862284a3dbd4d84e5d89973b29150a4f604bc161ba8039":{ 
         "transfer":[ 
            1580896054819,
            { 
               "type":"LockedTransfer",
               "message_identifier":"1580896046303",
               "chain_id":"5",
               "token_network_address":"0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df",
               "channel_identifier":"124",
               "nonce":"3",
               "transferred_amount":"300000000",
               "locked_amount":"3330000000000",
               "locksroot":"0xf09fd0312f3c7dbe0acd5cddc56fed63daf6a46a7dd1305eafd3c07d1732acdc",
               "payment_identifier":"2332864643766854013",
               "token":"0x59105441977ecD9d805A4f5b060E34676F50F806",
               "recipient":"0x1a48C928FF31d51543850Ec231e8F1889B3411C7",
               "lock":{ 
                  "amount":"3330000000000",
                  "expiration":"2124500",
                  "secrethash":"0xd82dc4353531fa629f862284a3dbd4d84e5d89973b29150a4f604bc161ba8039"
               },
               "target":"0x1a48C928FF31d51543850Ec231e8F1889B3411C7",
               "initiator":"0x2142194DF04265cF545bC18158347ef36Ba6E35c",
               "metadata":{ 
                  "routes":[ 
                     { 
                        "route":[ 
                           "0x1a48C928FF31d51543850Ec231e8F1889B3411C7"
                        ]
                     }
                  ]
               },
               "signature":"0x4c90917359d32082b668afc89700e1d1f35030766b9f1c6b8ee0e82b705d6eab61ad6b2be36185bec322626549fa90612ffbf8260d70c88b7c9401686352ea881b"
            }
         ],
         "fee":"0",
         "transferProcessed":[ 
            1580896061112,
            { 
               "message_identifier":"1580896046303",
               "signature":"0xf34d1b2b3363ff33774cf0ccdc53cec90f202543a7182524008c8cfd9b16d8bb4ce072b3cf4d7971a3435aa3c7e7e15e1e851fdc9e01bffe2cbaa142d6166f1f1b",
               "type":"Processed"
            }
         ],
         "secretReveal":[ 
            1580896062184,
            { 
               "type":"RevealSecret",
               "message_identifier":"1580896056038",
               "secret":"0xcda9128c7d90cddf6de5d58155473a0534d0570c4a82ff46f8d5f9a54a716938",
               "signature":"0x65219ed6feecc67fc3f56b54b4627e978f9e68b6e27b4af26bac5beef4b35c99132741d0a7bdc4c3a875f173140ad4fb4aad52aa55b9d27bdcd2a3199dcd43561b"
            }
         ],
         "unlock":[ 
            1580896069448,
            { 
               "type":"Unlock",
               "message_identifier":"1580896062946",
               "chain_id":"5",
               "token_network_address":"0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df",
               "channel_identifier":"124",
               "nonce":"4",
               "transferred_amount":"3330300000000",
               "locked_amount":"0",
               "locksroot":"0xc5d2460186f7233c927e7db2dcc703c0e500b653ca82273b7bfad8045d85a470",
               "payment_identifier":"2332864643766854013",
               "secret":"0xcda9128c7d90cddf6de5d58155473a0534d0570c4a82ff46f8d5f9a54a716938",
               "signature":"0x554c2e8b8c98f7231ffe4eff9b2dd6ac7fa1513811a27210ec43c84c473978867c90e9d5840c731bdd6933660a6bb6bff8214d00aa0a5a24669b828edb81b1a61b"
            }
         ],
         "unlockProcessed":[ 
            1580896076421,
            { 
               "message_identifier":"1580896062946",
               "signature":"0xc066ebef1a894aef803ef37678a25b7ab622df12befb129d69573e3bc482cf590e36d7db336e1775a03ed8feda961f45ea3abf7672ca1c3dcae1d2784838b83f1c",
               "type":"Processed"
            }
         ]
      }
   },
   "path":{ 
      "iou":{ 
         "0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df":{ 
            "0x062C12c01D0f17fC9eAa33940D994594d91a0182":{ 
               "sender":"0x2142194DF04265cF545bC18158347ef36Ba6E35c",
               "receiver":"0x062C12c01D0f17fC9eAa33940D994594d91a0182",
               "chain_id":"5",
               "amount":"700",
               "one_to_n_address":"0xe4C2C47F070152c03a564C2c681C3FbD78234156",
               "expiration_block":"2324331",
               "signature":"0x73bd6cb7bfa8e4f95eec2694ca05b4bcd4fda63c8a8ff04647c631bc6b3c17f063968b4af2f24b5d11668fac25a1681897fefb6db0a08f4957840a49678b80d61c"
            }
         }
      }
   }
}
```
</p>
</details>

<details><summary>Console logs</summary>
<p>
log.js?28c8:24 [HMR] Waiting for update signal from WDS...
inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
If you rely upon this behavior, add a 'networkChanged' event handler to trigger the reload manually: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.on(eventname%2C-callback)
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning: https://metamask.github.io/metamask-docs/API_Reference/Ethereum_Provider#ethereum.autorefreshonnetworkchange'

c.enable @ inpage.js:1
redux-logger.js?0dbf:1  action tokenMonitored @ 10:54:25.175
redux-logger.js?0dbf:1  action channel/monitor @ 10:54:25.177
redux-logger.js?0dbf:1  action matrix/presence/request @ 10:54:25.197
redux-logger.js?0dbf:1  action raidenConfigUpdate @ 10:54:25.198
redux-logger.js?0dbf:1  action newBlock @ 10:54:25.382
redux-logger.js?0dbf:1  action matrixSetup @ 10:54:25.535
redux-logger.js?0dbf:1  action matrix/presence/success @ 10:54:25.862
sync.js?9567:62 Getting saved sync token...
sync.js?9567:62 Getting push rules...
sync.js?9567:62 Got saved sync token
sync.js?9567:62 Getting saved sync...
sync.js?9567:62 Got reply from saved sync, exists? false
sync.js?9567:62 Got push rules
sync.js?9567:62 Checking lazy load status...
sync.js?9567:62 Checking whether lazy loading has changed in store...
sync.js?9567:62 Storing client options...
sync.js?9567:62 Stored client options
sync.js?9567:62 Getting filter...
sync.js?9567:62 Sending first sync request...
sync.js?9567:62 Waiting for saved sync before starting sync processing...
redux-logger.js?0dbf:1  action matrix/presence/request @ 10:54:31.234
redux-logger.js?0dbf:1  action matrix/presence/request @ 10:54:31.249
redux-logger.js?0dbf:1  action matrix/presence/success @ 10:54:31.413
redux-logger.js?0dbf:1  action newBlock @ 10:54:37.512
redux-logger.js?0dbf:1  action pfsListUpdated @ 10:54:38.857
redux-logger.js?0dbf:1  action path/find/request @ 10:54:38.911
redux-logger.js?0dbf:1  action path/find/failure @ 10:54:38.912
redux-logger.js?0dbf:1  action matrix/presence/request @ 10:54:42.159
redux-logger.js?0dbf:1  action matrix/presence/success @ 10:54:42.159
redux-logger.js?0dbf:1  action path/find/request @ 10:54:42.172
pfs-goerli-with-fee.services-dev.raiden.network/api/v1/0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df/paths:1 Failed to load resource: the server responded with a status of 404 ()
redux-logger.js?0dbf:1  action iouPersist @ 10:54:48.510
redux-logger.js?0dbf:1  action path/find/failure @ 10:54:48.516
redux-logger.js?0dbf:1  action newBlock @ 10:54:49.576
redux-logger.js?0dbf:1  action newBlock @ 10:55:09.613
redux-logger.js?0dbf:1  action newBlock @ 10:55:09.616
redux-logger.js?0dbf:1  action newBlock @ 10:55:33.513
redux-logger.js?0dbf:1  action newBlock @ 10:55:57.514
redux-logger.js?0dbf:1  action newBlock @ 10:55:57.518
redux-logger.js?0dbf:1  action newBlock @ 10:56:21.530
redux-logger.js?0dbf:1  action channel/deposit/request @ 10:56:43.032
redux-logger.js?0dbf:1  action newBlock @ 10:56:46.810
redux-logger.js?0dbf:1  action newBlock @ 10:56:46.818
epics.ts?6a11:593 sent approve tx "0xf6e30c0c942381da07ce2b66568e93b3dbc2deeba45eca5b99be275e70a46043" to "0x59105441977ecD9d805A4f5b060E34676F50F806"
redux-logger.js?0dbf:1  action newBlock @ 10:57:05.570
epics.ts?6a11:600 approve tx "0xf6e30c0c942381da07ce2b66568e93b3dbc2deeba45eca5b99be275e70a46043" successfuly mined!
epics.ts?6a11:616 sent setTotalDeposit tx "0x0f28b7e7b6e774f213effabc59fbafab5b98083336b014a42b786c6f674b3ad2" to "0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df"
redux-logger.js?0dbf:1  action newBlock @ 10:57:25.594
redux-logger.js?0dbf:1  action newBlock @ 10:57:25.606
redux-logger.js?0dbf:1  action newBlock @ 10:57:45.591
redux-logger.js?0dbf:1  action newBlock @ 10:58:05.565
epics.ts?6a11:626 setTotalDeposit tx "0x0f28b7e7b6e774f213effabc59fbafab5b98083336b014a42b786c6f674b3ad2" successfuly mined!
redux-logger.js?0dbf:1  action channel/deposit/success @ 10:58:05.807
utils.ts?0c50:327 Signing message "PFSCapacityUpdate" Object
redux-logger.js?0dbf:1  action messageGlobalSend @ 10:58:19.937
redux-logger.js?0dbf:1  action newBlock @ 10:58:21.563
redux-logger.js?0dbf:1  action newBlock @ 10:58:41.617
redux-logger.js?0dbf:1  action newBlock @ 10:58:41.652
redux-logger.js?0dbf:1  action newBlock @ 10:59:05.622
redux-logger.js?0dbf:1  action newBlock @ 10:59:29.527
redux-logger.js?0dbf:1  action newBlock @ 10:59:53.548
redux-logger.js?0dbf:1  action newBlock @ 10:59:53.568
redux-logger.js?0dbf:1  action channel/deposit/success @ 10:59:53.790
redux-logger.js?0dbf:1  action newBlock @ 11:00:17.615
redux-logger.js?0dbf:1  action newBlock @ 11:00:17.633
redux-logger.js?0dbf:1  action newBlock @ 11:00:41.718
redux-logger.js?0dbf:1  action newBlock @ 11:00:41.739
redux-logger.js?0dbf:1  action newBlock @ 11:01:05.537
redux-logger.js?0dbf:1  action newBlock @ 11:01:29.532
redux-logger.js?0dbf:1  action newBlock @ 11:01:29.548
redux-logger.js?0dbf:1  action newBlock @ 11:01:53.688
redux-logger.js?0dbf:1  action newBlock @ 11:02:17.647
redux-logger.js?0dbf:1  action newBlock @ 11:02:17.675
redux-logger.js?0dbf:1  action newBlock @ 11:02:41.535
redux-logger.js?0dbf:1  action newBlock @ 11:03:05.560
redux-logger.js?0dbf:1  action newBlock @ 11:03:05.583
redux-logger.js?0dbf:1  action newBlock @ 11:03:29.539
redux-logger.js?0dbf:1  action newBlock @ 11:03:29.555
redux-logger.js?0dbf:1  action newBlock @ 11:03:53.626
redux-logger.js?0dbf:1  action newBlock @ 11:04:17.542
redux-logger.js?0dbf:1  action newBlock @ 11:04:17.555
redux-logger.js?0dbf:1  action newBlock @ 11:04:41.536
redux-logger.js?0dbf:1  action newBlock @ 11:05:05.543
redux-logger.js?0dbf:1  action newBlock @ 11:05:05.556
redux-logger.js?0dbf:1  action newBlock @ 11:05:29.594
redux-logger.js?0dbf:1  action newBlock @ 11:05:29.657
redux-logger.js?0dbf:1  action newBlock @ 11:05:49.886
redux-logger.js?0dbf:1  action path/find/request @ 11:06:07.038
redux-logger.js?0dbf:1  action path/find/failure @ 11:06:07.041
redux-logger.js?0dbf:1  action matrix/presence/request @ 11:06:09.557
redux-logger.js?0dbf:1  action matrix/presence/success @ 11:06:09.558
redux-logger.js?0dbf:1  action path/find/request @ 11:06:09.586
redux-logger.js?0dbf:1  action newBlock @ 11:06:13.545
redux-logger.js?0dbf:1  action newBlock @ 11:06:13.553
pfs-goerli-with-fee.services-dev.raiden.network/api/v1/0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df/paths:1 Failed to load resource: the server responded with a status of 404 ()
redux-logger.js?0dbf:1  action iouPersist @ 11:06:16.734
redux-logger.js?0dbf:1  action path/find/failure @ 11:06:16.748
redux-logger.js?0dbf:1  action newBlock @ 11:06:37.534
redux-logger.js?0dbf:1  action newBlock @ 11:07:01.592
redux-logger.js?0dbf:1  action newBlock @ 11:07:01.601
redux-logger.js?0dbf:1  action newBlock @ 11:07:25.629
redux-logger.js?0dbf:1  action newBlock @ 11:07:49.537
redux-logger.js?0dbf:1  action newBlock @ 11:07:49.544
redux-logger.js?0dbf:1  action newBlock @ 11:08:13.634
redux-logger.js?0dbf:1  action newBlock @ 11:08:13.643
redux-logger.js?0dbf:1  action newBlock @ 11:08:37.675
toolbarContentscript.js:122 Object
(anonymous) @ toolbarContentscript.js:122
redux-logger.js?0dbf:1  action newBlock @ 11:09:01.553
redux-logger.js?0dbf:1  action newBlock @ 11:09:01.572
redux-logger.js?0dbf:1  action newBlock @ 11:09:25.725
redux-logger.js?0dbf:1  action newBlock @ 11:09:25.735
redux-logger.js?0dbf:1  action newBlock @ 11:09:49.547
redux-logger.js?0dbf:1  action newBlock @ 11:10:13.658
redux-logger.js?0dbf:1  action newBlock @ 11:10:13.664
redux-logger.js?0dbf:1  action newBlock @ 11:10:37.638
redux-logger.js?0dbf:1  action newBlock @ 11:11:01.552
redux-logger.js?0dbf:1  action newBlock @ 11:11:01.561
redux-logger.js?0dbf:1  action newBlock @ 11:11:25.636
redux-logger.js?0dbf:1  action newBlock @ 11:11:49.554
redux-logger.js?0dbf:1  action newBlock @ 11:11:49.561
redux-logger.js?0dbf:1  action newBlock @ 11:12:13.550
redux-logger.js?0dbf:1  action newBlock @ 11:12:37.651
redux-logger.js?0dbf:1  action newBlock @ 11:12:37.657
redux-logger.js?0dbf:1  action newBlock @ 11:13:01.654
redux-logger.js?0dbf:1  action newBlock @ 11:13:01.663
redux-logger.js?0dbf:1  action newBlock @ 11:13:25.730
redux-logger.js?0dbf:1  action newBlock @ 11:13:49.572
redux-logger.js?0dbf:1  action newBlock @ 11:13:49.582
redux-logger.js?0dbf:1  action newBlock @ 11:14:13.561
redux-logger.js?0dbf:1  action newBlock @ 11:14:13.572
redux-logger.js?0dbf:1  action newBlock @ 11:14:37.667
redux-logger.js?0dbf:1  action newBlock @ 11:15:01.700
redux-logger.js?0dbf:1  action newBlock @ 11:15:01.710
redux-logger.js?0dbf:1  action newBlock @ 11:15:25.646
redux-logger.js?0dbf:1  action newBlock @ 11:15:49.564
redux-logger.js?0dbf:1  action newBlock @ 11:15:49.571
redux-logger.js?0dbf:1  action newBlock @ 11:16:13.577
redux-logger.js?0dbf:1  action newBlock @ 11:16:13.589
redux-logger.js?0dbf:1  action newBlock @ 11:16:37.655
redux-logger.js?0dbf:1  action newBlock @ 11:17:01.646
redux-logger.js?0dbf:1  action newBlock @ 11:17:01.653
redux-logger.js?0dbf:1  action newBlock @ 11:17:25.661
redux-logger.js?0dbf:1  action matrix/presence/request @ 11:17:27.236
redux-logger.js?0dbf:1  action matrix/presence/success @ 11:17:27.237
redux-logger.js?0dbf:1  action path/find/request @ 11:17:27.261
redux-logger.js?0dbf:1  action newBlock @ 11:17:34.038
pfs-goerli-with-fee.services-dev.raiden.network/api/v1/0x31fEB78D299EC86d8308c64B711A9eC1Ea5Ae1Df/paths:1 Failed to load resource: the server responded with a status of 404 ()
redux-logger.js?0dbf:1  action iouPersist @ 11:17:34.487
redux-logger.js?0dbf:1  action path/find/failure @ 11:17:34.501
redux-logger.js?0dbf:1  action newBlock @ 11:17:57.558
redux-logger.js?0dbf:1  action newBlock @ 11:17:57.565
redux-logger.js?0dbf:1  action newBlock @ 11:18:21.571
redux-logger.js?0dbf:1  action newBlock @ 11:18:45.660
redux-logger.js?0dbf:1  action newBlock @ 11:18:45.669
redux-logger.js?0dbf:1  action newBlock @ 11:19:09.653
redux-logger.js?0dbf:1  action newBlock @ 11:19:33.664
redux-logger.js?0dbf:1  action newBlock @ 11:19:33.675
redux-logger.js?0dbf:1  action newBlock @ 11:19:57.676
redux-logger.js?0dbf:1  action newBlock @ 11:19:57.685
redux-logger.js?0dbf:1  action newBlock @ 11:20:21.614
redux-logger.js?0dbf:1  action newBlock @ 11:20:45.691
redux-logger.js?0dbf:1  action newBlock @ 11:20:45.697
redux-logger.js?0dbf:1  action newBlock @ 11:21:09.665
redux-logger.js?0dbf:1  action newBlock @ 11:21:33.574
redux-logger.js?0dbf:1  action newBlock @ 11:21:33.595
redux-logger.js?0dbf:1  action newBlock @ 11:21:57.576
redux-logger.js?0dbf:1  action newBlock @ 11:22:21.668
redux-logger.js?0dbf:1  action newBlock @ 11:22:21.682
redux-logger.js?0dbf:1  action newBlock @ 11:22:45.678
redux-logger.js?0dbf:1  action newBlock @ 11:22:45.689
redux-logger.js?0dbf:1  action newBlock @ 11:23:09.668
redux-logger.js?0dbf:1  action newBlock @ 11:23:33.587
redux-logger.js?0dbf:1  action newBlock @ 11:23:33.597
redux-logger.js?0dbf:1  action newBlock @ 11:23:57.603
redux-logger.js?0dbf:1  action newBlock @ 11:23:57.626
redux-logger.js?0dbf:1  action newBlock @ 11:24:21.869
redux-logger.js?0dbf:1  action newBlock @ 11:24:45.588
redux-logger.js?0dbf:1  action newBlock @ 11:24:45.602
redux-logger.js?0dbf:1  action newBlock @ 11:25:09.669
redux-logger.js?0dbf:1  action newBlock @ 11:25:33.607
redux-logger.js?0dbf:1  action newBlock @ 11:25:33.644
</p>
</details>

**Comment by andrevmatos** [comment]
Thank you very much for the detailed report, @nephix 
From what I can see, this was probably caused by a bug introduced in #918 , because we depended on the Room `aliases` to be available to then chose the room to send the `PFSCapacityUpdate` to, and with that change, we don't even have the aliases for those rooms and couldn't identify it, so the client kept waiting for a room with given alias to show up, forever.
But we do have this association at `joinGlobalRooms` time, when we join the rooms by alias. The fix was to populate the rooms list with these global rooms which won't get synced but will be there to be found and then sending the given message to it.
Please, test and let me know if the linked PR fixes the issue. Thank you.
