### ISSUE TITLE
Copied address should be trimmed on the dApp

### ISSUE THREAD

**Issue by kelsos** [raiden-network/light-client#985]
The copied address has leading and trailing whitespace(s) and this makes it invalid. The copied address should be directly pastable to any address expecting inpit without needing any user modification.

## Steps to Reproduce
1. Use the copy functionality
2. Paste the address copied in an address input in the dApp

## Expected Result
- "You cannot use your own address validation error is displayed"

## Actual Result
- "Please enter a valid address or ENS name"

**Comment by nephix** [comment]
Seems to work in Chrome:
<img width="668" alt="Screenshot 2020-02-05 at 17 34 47" src="https://user-images.githubusercontent.com/3169205/73861792-d57a7a00-483d-11ea-8f4b-2db72c5d9f7d.png">

Will check tomorrow where/when this happens. Thanks for spotting!

**Comment by kelsos** [comment]
Firefox
